### ISSUE TITLE
[Issue]: Unable to `nvm install` after manual installation

### ISSUE THREAD

**Issue by loganmzz** [coreybutler/nvm-windows#1001]
### What happened?

Followed instructions from: https://github.com/coreybutler/nvm-windows/wiki#manual-installation

1. Download `nvm-noinstall.zip`
2. Extract content to `<NVM_INSTALLATION_DIR>` (e.g. `D:\Apps\nvm`)
3. Set environment variable `NVM_HOME` to `<NVM_INSTALLATION_DIR>`
4. Set environment variable `NVM_SYMLINK` to `%NVM_HOME%\nodejs`
5. Open new shell
6. Run `nvm install 14.15.1`

```plain
 could not be found or does not exist. Exiting.
Downloading node.js version 14.15.1 (64-bit)... 
Error while creating \v14.15.1\node64.exe - open \v14.15.1\node64.exe: Le chemin d’accès spécifié est introuvable.
Could not download node.js v14.15.1 64-bit executable.
```

### What did you expect to happen?

Node.js to be installed

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
could not be found or does not exist. Exiting.
Downloading node.js version 14.15.1 (64-bit)... 
Error while creating \v14.15.1\node64.exe - open \v14.15.1\node64.exe: Le chemin d’accès spécifié est introuvable.
Could not download node.js v14.15.1 64-bit executable.
```

### Debug Output

```Shell
could not be found or does not exist. Exiting.
lmauza_x is not using admin or elevated rights.
Error getting console handle: L’opération a réussi.
Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.11
NVM4W Path:         D:\Apps\nvm\nvm4win-1.1.11\nvm.exe
NVM4W Settings:     D:\Apps\nvm\nvm4win-1.1.11\settings.txt
NVM_HOME:           D:\Apps\nvm\nvm4win-1.1.11
NVM_SYMLINK:        D:\Apps\nvm\nvm4win-1.1.11\nodejs
Node Installations:

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by loganmzz** [comment]
> First, I do not recommend using a subdirectory within NVM_HOME as the NVM_SYMLINK.

I recommend you adding this to installation instructions 😄 

After using `nvm root <PATH>`, I was able to install. However, I saw nothing mentionning this, neither NVM4W complaining about the missing setup. Just crashing.

But as you said, `nvm use` is failing. As I'm not admin on my workstation, I just remove NVM4W and go for NVS.

**Comment by coreybutler** [comment]
Well, the recommended starting point is to use the installer 😄. The no-install option is primarily for people who want to mass deploy through Active Directory. The regular installer sets everything up correctly by default.

Most users activate developer mode, as described [here](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145). This grants symlink permissions to non-admins. This is how most companies set it up for employees.

I'll close this out since you're moving to a different version manager.
