### ISSUE TITLE
[Feature]: Use junction instead of symbolic links

### ISSUE THREAD

**Issue by loganmzz** [coreybutler/nvm-windows#1002]
### Description of the new feature / enhancement

Windows symbolic links require privileges, but junction ones don't

```
$ cd D:\Apps\nvm-1.1.11

$ mklink /D nodejs v14.15.1
Vous ne disposez pas de privilèges suffisants pour effectuer cette opération.

$ mklink /J nodejs v14.15.1
Jonction créée pour nodejs <<===>> v14.15.1

$ node --version
v14.15.1

```

### Scenario when this would be used?

Always

### Supporting information

https://learn.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions

**Comment by coreybutler** [comment]
This has been addressed numerous times in past issues. Junctions can only be used on a single hard drive. This means any users leveraging a network share (mapped) or different physical disk will lose functionality.

**Comment by loganmzz** [comment]
May be you should have some settings to select which is more appropriate. Admin requirement seems "heavy" for the provided feature.

More cross-drive location between your link and its targets seems:

1. Low-cost workaround (links cost nothing)
2. Unfrequent ("niche") usage

Specially compare to admin right requirements which has no workaround (except not using NVM4W) and just good practice (i.e. "way to go").

**Comment by coreybutler** [comment]
A setting has also been suggested in the past. If someone had sponsored the work or offered to respond to all of the questions that inevitably come, I would have done it. However; at this point, my time is better spent on [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).

**Comment by icharge** [comment]
Please add parameter to let user decide. I need this too.
