### ISSUE TITLE
[Issue]: Fail to install node version

### ISSUE THREAD

**Issue by hornta** [coreybutler/nvm-windows#1006]
### What happened?

When running `nvm install latest` I'm getting an error.

### What did you expect to happen?

I'm expecting this to install the latest version of Node without errors

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
C:\Users\Användaren>nvm install latest
C:\Users\Anv�ndaren\AppData\Roaming\nvm could not be found or does not exist. Exiting.
20.4.0
Downloading node.js version 20.4.0 (64-bit)...
Error while creating C:\Users\Anv�ndaren\AppData\Roaming\nvm\v20.4.0\node.zip - open C:\Users\Anv�ndaren\AppData\Roaming\nvm\v20.4.0\node.zip: The system cannot find the path specified.
Could not download node.js v20.4.0 64-bit executable.
```

### Debug Output

```Shell
C:\Windows\System32>nvm debug
C:\Users\Anv�ndaren\AppData\Roaming\nvm could not be found or does not exist. Exiting.
Running NVM for Windows with administrator privileges.

Administrator: Command Prompt - nvm  debug
NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\Anv�ndaren\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\Användaren\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\Användaren\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\Anv�ndaren\AppData\Roaming\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

I installed nvm using the setup.exe binary. My best guess to this error is because my User folder contains non ASCII letters (åäö)

**Comment by coreybutler** [comment]
These logs don't really make sense to me, but I have a theory. 

`C:\Users\Anv�ndaren\AppData\Roaming\nvm could not be found or does not exist. Exiting.` indicates nvm cannot be found, yet it still attempts to download Node.

I _think_ the problem has to do with character encodings. I would recommend reinstalling NVM4W to a different path (like `C:\nvm4w` or `C:\nvm-windows` or something). I think the umlaut in your username is not being encoded/interpreted correctly by the OS, so using a directory without any special characters would get around this. It's not an ideal solution, but I believe it will work.

There are some known issues with European characters in Go, which I'm trying to work around. In the meantime, this may be your best option.

**Comment by danielart** [comment]
I had the same issue. For me the problem was solved once I installed nvm in a path without whitespaces (program files).

**Comment by 528244053** [comment]
I encountered the same problem,and then I modified the file permissions to solve the problem。
