### ISSUE TITLE
[Feature]: .nvmrc support

### ISSUE THREAD

**Issue by tonycody** [coreybutler/nvm-windows#1010]
### Description of the new feature / enhancement

https://github.com/nvm-sh/nvm#nvmrc
Can you sync and support the linux nvm configuration file standards?

### Scenario when this would be used?

Look up.

**Comment by coreybutler** [comment]
https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported
