### ISSUE TITLE
[Issue]: the nvm on windows only works while installing in C:\ drive

### ISSUE THREAD

**Issue by art2engine** [coreybutler/nvm-windows#1011]
### What happened?

i wanted to install nvm on other drives but without installing the program on C:\...\app\roaming\...
NVM would not work 
and it did install node version such as latest,lts and 16.x but it did not activate anyone of them

after installing in C drive with the default locations on prompted by the installer 
finally it started working

### What did you expect to happen?

I saw a video on giving environment variable paths to the nvm downloaded versions but it still did not work at the end,

as stated before it only works while installed only on C:\

hope this gets fixed in the newer future
and thank you for this amazing software

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt, PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

**Comment by coreybutler** [comment]
NVM4W most definitely works on drives other than `C:`, as long as you have appropriate permissions to install/use those drives.

Once you've installed a version of Node, you have to run `node use <version>`. For example, `nvm use latest`. You can tell if it was successful by running `node -v` (the version number should show up).

Remember, as the README states, this is not the same thing as nvm-sh. That is a separate project with separate leadership. Tutorials for nvm-sh are not necessarily applicable to nvm-windows.
