### ISSUE TITLE
[Feature]: Ability to install a global package to all installed versions of node at once.

### ISSUE THREAD

**Issue by fmotion1** [coreybutler/nvm-windows#1013]
### Description of the new feature / enhancement

It would be nice to have a way to install a global package to every node installation without typing `nvm use...` and then `npm install` over and over again. Is this possible already?

### Scenario when this would be used?

It would make installing packages universally much easier. For instance if I wanted to install Yarn to all my node versions, I have to keep switching (`nvm use`) and then install. This gets tedious.

**Comment by coreybutler** [comment]
This is on the roadmap for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).

**Comment by fmotion1** [comment]
Alright. Looking forward to Runtime... sounds promising.
