### ISSUE TITLE
[Issue]: Path variables do not handle spaces

### ISSUE THREAD

**Issue by RobertGemmaJr** [coreybutler/nvm-windows#1014]
### What happened?

Running `nvm use 18` fails on `exit status 1: 'C:\Users\Robert' is not recognized as an internal or external command,
operable program or batch file.`

My username is "Robert Gemma", and it's not something I can get around because it's a work computer. It appears as though nvm is using an absolute C path that is not in a string so it's seeing two different commands.

### What did you expect to happen?

Running `nvm install lts` installs node 18 (this worked correctly), and `nvm use` picks up that installed version

### Version

1.1.11 or newer (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

### Relevant log/console output

```Shell
PS C:\Users\Robert Gemma> nvm debug
Robert Gemma is not using admin or elevated rights.

Windows PowerShell
Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\Robert Gemma\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\Robert Gemma\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\Robert Gemma\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\Robert Gemma\AppData\Roaming\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
PS C:\Users\Robert Gemma> nvm list

    18.17.0
PS C:\Users\Robert Gemma> nvm use 18
exit status 1: 'C:\Users\Robert' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\Robert Gemma> nvm --version
1.1.11
```

### Debug Output

```Shell
PS C:\Users\Robert Gemma> nvm debug
Robert Gemma is not using admin or elevated rights.

Windows PowerShell
Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\Robert Gemma\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\Robert Gemma\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\Robert Gemma\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\Robert Gemma\AppData\Roaming\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
PS C:\Users\Robert Gemma> nvm list

    18.17.0
PS C:\Users\Robert Gemma> nvm use 18
exit status 1: 'C:\Users\Robert' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\Robert Gemma> nvm --version
1.1.11
```

### Anything else?

![image](https://github.com/coreybutler/nvm-windows/assets/38439940/95c2a87e-f726-4dc1-a8b8-a5f11b837c79)

**Comment by yoshiask** [comment]
I'm also blocked by this issue. Is this a regression?
https://github.com/coreybutler/nvm-windows/blame/c2aba37b1e3c675afa2baaee91a3d43af2510672/src/nvm.go#L666

**Comment by rivalarya** [comment]
Have you tried running "nvm use [version]" in PowerShell (admin)? It works for me

**Comment by Rich-Hopkins** [comment]
> Have you tried running "nvm use [version]" in PowerShell (admin)? It works for me

It works fine if you don't have a space in your user profile path. If you have any spaces, it fails.

**Comment by Mou1z** [comment]
Same issue!!

**Comment by Mou1z** [comment]
Though it works on powershell (not cmd) with Admin.

**Comment by indierodo** [comment]
WORKAROUND: Change the output directory in the installer to C:\nvm to avoid this issue.

**Comment by SylvanasCry** [comment]
Just removed `nvm-windows`. A completely idiotic bug, to which the author does not react in any way. For me, with this project everything is clear.

**Comment by RobertGemmaJr** [comment]
Interestingly the issue seems to have resolved itself? It now prompts for an admin approval (twice, which is a bit annoying but okay given they're working on the successor)  and works correctly. I'll close the issue!

**Comment by coreybutler** [comment]
> Just removed `nvm-windows`. A completely idiotic bug, to which the author does not react in any way. For me, with this project everything is clear.

@SylvanasCry This issue was "resolved" quite some time ago, but it keeps coming back for different reasons. Sometimes these are out of my control. Originally, it was because Go didn't encode values correctly. Some Windows locales don't encode spaces correctly either (need to be UTF-8). Some people simply haven't upgraded to take advantage of the fixes. I've responded to these issues for years, closing the gaps when possible, but I don't have access to every version of Windows. If the bug is so idiotic, maybe you could submit a PR to fix it?

**Comment by DevWand** [comment]
By simply running the program as administrator the problem was resolved, what a strange thing huh?
