### ISSUE TITLE
nvm.exe installer does not respond on windows 10[Issue]: 

### ISSUE THREAD

**Issue by jimmyurl** [coreybutler/nvm-windows#1023]
### What happened?

Fails to install nvm on windows 10 despite deleting previously installed nodejs and npm folder

### What did you expect to happen?

Successful installation of nvm

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

**Comment by coreybutler** [comment]
This is not enough information to troubleshoot. Are you trying to install in a corporate/Active Directory environment? Which directory are you installing to? Which installer are you using?

**Comment by jimmyurl** [comment]
Hey Corey thanks for a quick response, I was trying to install on windows 10 personal computer using the installer nvm-noinstaller.zip

**Comment by coreybutler** [comment]
In this case, use the normal installer. The "noninstall" option is designed for enterprises that need to create their own installer from the app's components. It's completely unnecessary extra work for an individual working on a personal machine. But if you _really_ want to install manually, the intructions are available [here](https://github.com/coreybutler/nvm-windows/wiki#manual-installation).
