### ISSUE TITLE
[Issue]: NVM installation failure inside Azure VM 

### ISSUE THREAD

**Issue by soundd2** [coreybutler/nvm-windows#1028]
### What happened?

I have followed below Github to install the NVM

https://github.com/coreybutler/nvm-windows

and for that I created VM with windows server 2022, both VM and OS are 64 bit but not sure why it is giving following error

Here are the steps I have followed :

1.
I have ran below command as per your instruction

![image](https://github.com/coreybutler/nvm-windows/assets/94822959/11134eec-ebbb-41a1-bb0b-c058ba599808)

2.
however when I navigate to that file and execute giving following error:

![image](https://github.com/coreybutler/nvm-windows/assets/94822959/235ea8d5-3dbe-4805-b334-127a0ca8884f)

and Deleted and downloaded again, it is same error. Please suggest. 

### What did you expect to happen?

I have followed below Github to install the NVM

https://github.com/coreybutler/nvm-windows

and for that I created VM with windows server 2022, both VM and OS are 64 bit but not sure why it is giving following error

Here are the steps I have followed :

1.
I have ran below command as per your instruction

![image](https://github.com/coreybutler/nvm-windows/assets/94822959/11134eec-ebbb-41a1-bb0b-c058ba599808)

2.
however when I navigate to that file and execute giving following error:

![image](https://github.com/coreybutler/nvm-windows/assets/94822959/235ea8d5-3dbe-4805-b334-127a0ca8884f)

and Deleted and downloaded again, it is same error. Please suggest. 

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
Please see above s
```

### Anything else?

Please see above description

**Comment by coreybutler** [comment]
That curl command doesn't look correct. I think you want `curl -O https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe`

Check the size of what was downloaded. If the executable isn't at least 5MB, then you're just not getting the download.

Windows has a habit of blocking `.exe` downloads, so you might want to try with the zip file too.

**Comment by soundd2** [comment]
Hi Core Bulter,

I tried as per your suggestion, seems to be above error is gone, but came up with following error  and when clicked on close I see "access denied" please suggest further


![image](https://github.com/coreybutler/nvm-windows/assets/94822959/34b0a69a-173a-414b-9b7a-dc0a59401470)


![image](https://github.com/coreybutler/nvm-windows/assets/94822959/fe9b10bf-1c2f-46f1-823e-a9c11b958cba)

Please suggest further, thank you.

**Comment by soundd2** [comment]
Hi Core Bulter,

I tried as per your suggestion, seems to be above error is gone, but came up with following error  and when clicked on close I see "access denied" please suggest further


![image](https://github.com/coreybutler/nvm-windows/assets/94822959/34b0a69a-173a-414b-9b7a-dc0a59401470)


![image](https://github.com/coreybutler/nvm-windows/assets/94822959/fe9b10bf-1c2f-46f1-823e-a9c11b958cba)

Please suggest futher, thank you.

**Comment by coreybutler** [comment]
When access is denied, try running it again a few times. Windows may block unknown executables the first time they're downloaded. It's part of Windows' annoyingly intense security. If the app is continually denied, you may need to make sure Windows Defender isn't blocking it.
