### ISSUE TITLE
[Issue]: NVM DOES NOT DETECT NPM

### ISSUE THREAD

**Issue by olallier** [coreybutler/nvm-windows#1029]
### What happened?

- installed properly nvm on windows 10 manually (yes, properly)
- activated lts after install - lts is properly installed as a folder in %NVM_SYMLINK%
- runned npm in powershell with admin rights
- ERROR MESSAGE :  npm not found

### What did you expect to happen?

Instead of adding the full pathfile of node.js to the system (npm being at the root of that folder, with version varying with the one of node), nvm-windows does nothing, hence, npm is not found by the system even after activating the proper version of node. 

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

None

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
unrelevant
```

### Debug Output

```Shell
unrelevant
```

### Anything else?

Please correct, this is the second path issue (first one being nvm_windows uses %NVM_SYMLINK% as folder for nvm root nstead of %NVM_HOME%

**Comment by coreybutler** [comment]
Please post your debug output. It is relevant. It identifies the values of the environment variables. The behavior you're describing suggests the `NVM_SYMLINK` value does not exist in your `PATH` variable.

![image](https://github.com/coreybutler/nvm-windows/assets/770982/9be6fa50-90f1-4b2b-8131-a7fbec589119)

Another possibility is something else is being recognized as the Node root path. The debug tool identifies most of these problems.

**Comment by AliYar-Khan** [comment]
yeah I am facing issue as well 
![image](https://github.com/coreybutler/nvm-windows/assets/37889962/785f4090-2f31-4668-9250-d35cd64ed7ef)

**Comment by AliYar-Khan** [comment]
@coreybutler I did run the nvm use as you can see in my screenshot. list command is runned before the use command

**Comment by coreybutler** [comment]
@AliYar-Khan Yes, I see you did run `nvm use` (apologies for overlooking that). You probably have a permission issue, because the symlink didn't take. Run `nvm debug` to identify the root of the problem. Open a new issue if you can't find the resolution.
