### ISSUE TITLE
I can't install npm latest version

### ISSUE THREAD

**Issue by flpms** [coreybutler/nvm-windows#103]
After run and Install NodeJS a version like 4.2.1 npm version is 2.14.7 and not the latest like  v3.3.8. And many projects depend 3 version of npm.

**Comment by yuricamara** [comment]
Hi @flpms . I have the same problem. Did you solve that?

**Comment by coreybutler** [comment]
NVM4W uses the same versions you would get if you were to download node directly from nodejs.org. That means you get the official version of npm that officially ships with node. It's up to the developer to upgrade npm if they so choose.

`npm upgrade npm` will give you the latest, no matter which version of node you're running.

**Comment by yuricamara** [comment]
Hi @coreybutler. It didn't work. It keeps the same version. Did you run this command on Windows 10? It´s my OS.

**Comment by coreybutler** [comment]
Yeah, it worked for me on Windows 10.

**Comment by yuricamara** [comment]
@coreybutler  Do you remember if you follow others steps after running this command?

**Comment by coreybutler** [comment]
No other steps...install, upgrade, done.

**Comment by yuricamara** [comment]
Ok. Thanks
