### ISSUE TITLE
[Issue]: Unexpected EOF on all Node JS downloads

### ISSUE THREAD

**Issue by brunbimmer** [coreybutler/nvm-windows#1036]
### What happened?

When I am running npm install x.y.z? I encounter the following error:

Downloading node.js version 20.6.1 (64-bit)...
Error while downloading https://nodejs.org/dist/v20.6.1/node-v20.6.1-win-x64.zip - unexpected EOF
Extracting node and npm...
Error extracting from Node archive: zip: not a valid zip file
Could not download node.js v20.6.1 64-bit executable.

### What did you expect to happen?

I expect to see a successful installation. Was able to install 14.18.1 without a problem and then 20.7.0, but then nothing since then. I am geting unexpected EOF errors.

Whichever version I try to install fails and then shows up in the nvm list, but I am neither able to use the said version nor even uninstall it as it says, it is not installed. 

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

### Debug Output

```Shell
PS C:\Users\U1167100> nvm debug
Running NVM for Windows with administrator privileges.

Administrator: Windows PowerShell
NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\U1167100\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\U1167100\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\U1167100\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\U1167100\AppData\Roaming\nvm

Active Node.js Version: v20.7.0

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Do you have fairly strict antivirus settings? I have encountered people whose environments start quarantining/deleting Node zip files as they're being downloaded (ML virus definitions), which would explain EOF's on newer versions of Node. 

Proxies can also impact the download process. So can a mirror server.

You can remove the old versions by deleting their folders from `C:\Users\U1167100\AppData\Roaming\nvm`.

Aside from checking these aspects of your environment, my recommendation would be to just wait and reinstall. It's possible there's a problem with the source server. That's rare, but it has happened in the past.

**Comment by freddi301** [comment]
This keeps happening

**Comment by coreybutler** [comment]
@brunbimmer have you tried again today? Every once in a while, the Node source site becomes unavailable. It's possible you just hit one of these maintenance windows. This also happens for _brand new_ releases. It takes some time for the download site to sync with the actual release. That said, Node 20.6.1 has been released long enough that there shouldn't be a problem with it... unless the Node team replaced the file recently.

**Comment by freddi301** [comment]
It is probably a [heisenbug](https://en.wikipedia.org/wiki/Heisenbug)

**Comment by sanderderks** [comment]
Had the same issue. Excluding `:C/Users/{user}/AppData/Roaming/nvm` from antivirus scanning helped the installation to succeed.

**Comment by jdanl89** [comment]
I was having this issue when running nvm over a VPN. I disabled the VPN and it ran successfully.

**Comment by coreybutler** [comment]
I'm closing this since it doesn't appear to be an issue with NVM4W. @brunbimmer - if you're still struggling with this, let me know and I'll re-open the issue.

**Comment by brunbimmer** [comment]
All good, seemed to be a temporary condition. Apologies for not following
up.

**Comment by Ramdoijad** [comment]
Error while downloading https://nodejs.org/dist/v18.17.0/node-v18.17.0-win-x64.zip - unexpected EOF
Extracting node and npm...
Error extracting from Node archive: zip: not a valid zip file
Could not download node.js v18.17.0 64-bit executable.

**Comment by nthornton2010** [comment]
Not really sure how you can say this isn't a NVM4W bug when it started happening after updating to the latest NVM4W version.

I also find it weird that its trying to go to a user's directory for @coreybutler

```
nvm/web.unzip.func2.1({0xef85e4, 0x1213bbf0})

	C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:306 +0x4c

nvm/web.unzip.func2(0x1206d680)

	C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:333 +0x3c7

nvm/web.unzip({0x12011100, 0x3c}, {0x12278000, 0x33})

	C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:340 +0x111

nvm/web.GetNodeJS({0x1212e241, 0x2a}, {0x12122078, 0x7}, {0xe8fa65, 0x2}, 0x0)

	C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:154 +0x58d

main.install({0x12122078, 0x7}, {0xe8fa65, 0x2})

	C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:341 +0x8d9

main.main()

	C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69
```

**Comment by franmoyano** [comment]
@Ramdoijad did you found a solution? im still getting the same error

**Comment by MarlonX19** [comment]
> @Ramdoijad did you found a solution? im still getting the same error

did you ever found a solution? I'm going through the same now

**Comment by krazykarthik2** [comment]
me too getting the same error
