### ISSUE TITLE
[Issue]: README.md incorrect information

### ISSUE THREAD

**Issue by JorensM** [coreybutler/nvm-windows#1044]
### What happened?

https://github.com/coreybutler/nvm-windows#star-star-uninstall-any-pre-existing-node-installations-star-star

The README states that you should uninstall existing NodeJS folders present on your machine, otherwise there will be conflicts. This doesn't seem to be the case: when I ran the installer, the installer automatically detected my current NodeJS installation and hooked it up to nvm(and also replaced the existing nodejs folder with a symlink).

After running `nvm list` I can see the already-had-been-installed version of NodeJS showing up there as well.

### What did you expect to happen?

I stumbled upon that README section just as I was installing `nvm-windows`, expecting that I'll have to re-do it, but the installation went through smoothly and my existing NodeJS version was hooked to `nvm-windows`

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

None

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
Here you can see my existing NodeJS version successfully showing up after running `nvm list`

C:\WINDOWS\system32>nvm list

  * 18.16.1 (Currently using 64-bit executable)
```

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: Command Prompt - nvm  debug
NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\lucky\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\lucky\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\lucky\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\lucky\AppData\Roaming\nvm

Active Node.js Version: v18.16.1

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

I can make a PR for this

**Comment by coreybutler** [comment]
It's much more nuanced than "it works" or "it doesn't work". Your point is valid though, the README is incomplete. I've updated it. Thanks for bringing this to my attention!
