### ISSUE TITLE
[Issue]: 'go.mod file not found in current directory or any parent directory' when building from source.

### ISSUE THREAD

**Issue by JorensM** [coreybutler/nvm-windows#1045]
### What happened?

I wanted to work on an issue, so I tried building `nvm-windows` from source. When I tried running `go get github.com/blang/semver` I got the following error:

```
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

I'm new to Go and not sure what this error means, but I noticed that the `/src` directory has a `go.mod` file. So I tried to run `go get` from the `/src` directory and everything went fine. I'm not sure if that's the correct way to do this, because the [README states](https://github.com/coreybutler/nvm-windows#build-from-source) that you should `cd` to the project dir, and not the `src` dir. So I'm not sure if the README is wrong or if I'm missing something.

### What did you expect to happen?

I expected for `go get` to run correctly when running it from project root dir.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

None

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: Command Prompt - nvm  debug
NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\lucky\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\lucky\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\lucky\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\lucky\AppData\Roaming\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Run `go mod tidy` in the source directory. For all intents and purposes, this is the Go equivalent of `npm install`.
