### ISSUE TITLE
[Issue]: NVM install latest 21.0.0 is crashing 

### ISSUE THREAD

**Issue by Remzi1993** [coreybutler/nvm-windows#1051]
### What happened?

This is what happens. It stays on this screen for minutes and doesn't complete ever.
![Screenshot 2023-10-19 132241](https://github.com/coreybutler/nvm-windows/assets/980950/14085b7a-9879-4ee8-a078-4d55898430a7)

### What did you expect to happen?

Install latest node version.

![Screenshot 2023-10-19 132526](https://github.com/coreybutler/nvm-windows/assets/980950/e62f37f9-69f8-4a2e-8e8e-747fddccf40f)

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
![Screenshot 2023-10-19 132526](https://github.com/coreybutler/nvm-windows/assets/980950/e62f37f9-69f8-4a2e-8e8e-747fddccf40f)
```

### Debug Output

```Shell
![Screenshot 2023-10-19 132526](https://github.com/coreybutler/nvm-windows/assets/980950/e62f37f9-69f8-4a2e-8e8e-747fddccf40f)
```

**Comment by Remzi1993** [comment]
I tried it a second time, and it worked after 15 minutes. This may be because everyone wants to try it out.

**Comment by coreybutler** [comment]
I'm pretty sure you just ran into the [eager beaver](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#cant-download-latest-nodejs) problem.

**Comment by Remzi1993** [comment]
> I'm pretty sure you just ran into the [eager beaver](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#cant-download-latest-nodejs) problem.

Yeah, I think that's true 😂 Node 21 has other issues, but I need to report that on the Node repo.
