### ISSUE TITLE
[Issue]: The nvm use command does not work

### ISSUE THREAD

**Issue by JasirVoriya** [coreybutler/nvm-windows#1052]
### What happened?

The nvm use command does not create a symlink.

### What did you expect to happen?

Will create a symlink.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
>nvm list

    18.18.2
    16.20.2
>nvm use 18.18.2
Now using node v18.18.2 (64-bit)
>nvm list

    18.18.2
    16.20.2
```

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: PowerShell
NVM4W Version:      1.1.11
NVM4W Path:         E:\DevelopmentTools\nvm\nvm.exe
NVM4W Settings:     E:\DevelopmentTools\nvm\settings.txt
NVM_HOME:           E:\DevelopmentTools\nvm
NVM_SYMLINK:        E:\DevelopmentTools\nvm\nodejs
Node Installations: E:\DevelopmentTools\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)
If you are experiencing npm problems, check the npm mirror (https://npm.taobao.org/mirrors/npm/) to assure it is online and accessible.

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by eantropix** [comment]
I'm having this same problem now. Did you manage to find a solution for it?

**Comment by coreybutler** [comment]
The issue is here:

```
NVM_HOME:           E:\DevelopmentTools\nvm
NVM_SYMLINK:        E:\DevelopmentTools\nvm\nodejs
```

The `NVM_SYMLINK` should not be inside the `NVM_HOME` directory.
