### ISSUE TITLE
[Issue]: erorr using nvm install `panic: runtime error`

### ISSUE THREAD

**Issue by ermish** [coreybutler/nvm-windows#1057]
### What happened?

Using version 1.1.11, I ran the command `nvm install latest` and `nvm install 21.1.0` then received an error

### What did you expect to happen?

it installs the latest version of node!

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt, PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x120100b0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:790 +0x220
main.install({0x120100b0, 0x6}, {0xf9fa65, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:302 +0x35d
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69
```

### Debug Output

```Shell
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x120100b0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:790 +0x220
main.install({0x120100b0, 0x6}, {0xf9fa65, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:302 +0x35d
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69
```

**Comment by coreybutler** [comment]
See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#cant-download-latest-nodejs. This is the "eager beaver" problem.

While it would be nice to add a better error message for this edge case, I just don't have time right now. [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) takes priority over all non-blocking issues.
