### ISSUE TITLE
Invalid after nvm use， nvm -v  1.1.11

### ISSUE THREAD

**Issue by livelyPeng** [coreybutler/nvm-windows#1060]
### What happened?

![image](https://github.com/coreybutler/nvm-windows/assets/32978177/e4c9f055-69ed-4c1a-b5a1-266356d3b754)
![image](https://github.com/coreybutler/nvm-windows/assets/32978177/abbb6184-17ab-4231-bff5-5c77b57944fe)
![image](https://github.com/coreybutler/nvm-windows/assets/32978177/67ca837c-9795-435c-987b-403231387fc6)

### What did you expect to happen?

![image](https://github.com/coreybutler/nvm-windows/assets/32978177/78060523-dfdf-4ac0-8d32-34ddae29f797)
![image](https://github.com/coreybutler/nvm-windows/assets/32978177/8f364815-04dd-4c12-b7ac-3488584c7a46)
![image](https://github.com/coreybutler/nvm-windows/assets/32978177/14614551-bfb0-4ccb-8ba5-1cf93af66bff)

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
Invalid after nvm use
```

**Comment by coreybutler** [comment]
This doesn't make sense. You should be able to run `nvm debug`. If you cannot run that, something is incorrect in the installation.

Navigate to the directory where NVM4W is installed. 

<img width="574" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/b0bf10b7-bcb0-47ca-9807-5ba078e50169">

<img width="377" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/68d6861b-4d65-49f9-ad58-37e89bbdb813">

It should have a `nvm.exe` file in it. Run the command locally, like this:

```sh
.\nvm.exe debug
```

It should generate output like this:

<img width="494" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/c0fff569-2bfa-4a51-bc6b-a9aa089a44c8">

This should give you an idea of what is wrong.

**Comment by LYS-png** [comment]
我也是同样的问题，请问你解决了吗

**Comment by livelyPeng** [comment]
@coreybutler 
![Uploading image.png…]()

**Comment by livelyPeng** [comment]
![image](https://github.com/coreybutler/nvm-windows/assets/32978177/48acfdc3-326e-4c07-82b5-3dcfb54218e7)

**Comment by livelyPeng** [comment]
I don't know why there's such a problem，I had a problem installing node in the custom directory on drive D，If I install node on C drive, it will be fine, but I don't know how to solve it！

**Comment by coreybutler** [comment]
Is your D drive a hard disk? Or is it a mapped drive, network drive, etc? It's quite possible there are permission restrictions on your D drive, which is pretty common in corporate networks.

**Comment by WindBruce** [comment]
same problem,when I type in "nvm use 20.9.0",
it didn't work at all, when I use "nvm debug",I got this result:
![image](https://github.com/coreybutler/nvm-windows/assets/30388825/928e1326-1e24-4393-81a7-a57da82ddd93)

**Comment by coreybutler** [comment]
@WindBruce don't put your `NVM_SYMLINK` directory inside the `NVM_HOME` directory. Also, I have the zame question for you... is the D drive a physical hard disk or a shared/remote/mapped directory?

**Comment by esanking** [comment]
cmd use system administrator try again

**Comment by RSS1102** [comment]
Your node path cannot have Chinese characters or any spaces.

**Comment by WindBruce** [comment]
@

> @WindBruce don't put your `NVM_SYMLINK` directory inside the `NVM_HOME` directory. Also, I have the zame question for you... is the D drive a physical hard disk or a shared/remote/mapped directory?

My D drive is a physical hard disk. And I change the "NVM_SYMLINK" to another path ,and I installed the newest version-1.1.12, but it  still doesn't work,this time got this error: "NVM_SYMLINK (D:\DevPrograms\nodejs) is not a valid symlink",

![image](https://github.com/coreybutler/nvm-windows/assets/30388825/507ffb5f-9663-4b7c-aceb-db0cbfb4ba2d)
As you can see,I use a PowerShell with Administrator permission,I reset the nvm path,and type in "nvm use 20.10.0",It doest not work.  This is my system environment variables setting:

![image](https://github.com/coreybutler/nvm-windows/assets/30388825/2cf0d677-a06a-4ea5-b2dd-61cb9f0f7aba)
I really don't know how to make it work right now.

**Comment by WindBruce** [comment]
> coreybutler

**Comment by RSS1102** [comment]
Perhaps you should consider whether you installed node first and then NVM.

**Comment by coreybutler** [comment]
@WindBruce Glad you got it straightened out.

Since too little information is available about everyone else' situation, I'm closing this issue.

For those coming across this via Google, here are a few pointers.

1. It is critical that you know your user permissions. For example, if `nvm debug` cannot find your username (like @livelyPeng's updated screenshot), then you probably don't have permissions to make many changes on your system. Remember, Windows is particular about what it allows users to install, and this is ultimately an installer that modifies your system.
2. **Make sure `NVM_SYMLINK` does not exist at installation time**. NVM4W automatically creates/manages this for you. For example, if `NVM_SYMLINK` is set to `C:\nvm`, then `C:\nvm` should not already exist as a physical directory. Many people mistakenly assume they need to create this directory ahead of time, which causes a conflict when NVM4W tries to create a symlink here.

For further help, see the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues).
