### ISSUE TITLE
When installing a node version with nvm, the corresponding npm version is not installed

### ISSUE THREAD

**Issue by LakhderAmine99** [coreybutler/nvm-windows#1063]
### What happened?

When installing a node version with nvm, the corresponding npm version is not installed, i can't use multiple npm versions, i can only use one (10.x.x) in my case, does this have something to do with my current installed version of node or what excatly?!

### What did you expect to happen?

for each node version we'll have a corresponding npm version

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

### Debug Output

```Shell
nvm debug
amine is not using admin or elevated rights.

Windows PowerShell
Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\amine\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\amine\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\amine\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\amine\AppData\Roaming\nvm

Active Node.js Version: v20.5.0

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
NVM4W installs whatever version of npm ships with that particular version of _Node_. You can see the manifest at https://nodejs.org/dist/index.json. You cannot have more than one version of _npm_ installed at a time for a specific version of _Node_. That said, each version of Node can have its own independent version of npm.

**Comment by LakhderAmine99** [comment]
i fixed it, you should remove npm cache and node modules from your system (windows) before you install a new (node/npm) version using nvm, thanks!
