### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by arag0re** [coreybutler/nvm-windows#1067]
### Description of the new feature / enhancement

Why did u stop shipping the .exe file in your releases.
Now i need to updated all my scripts, just ship it like u did in your last 38 releases!

### Scenario when this would be used?

Every time

### Supporting information

You did it in the past

**Comment by coreybutler** [comment]
Nothing has changed:
<img width="902" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/820d5c96-e411-4b43-aa89-769311475115">
