### ISSUE TITLE
[Issue]: nvm use <version> doesn't actually switch after UAC is denied

### ISSUE THREAD

**Issue by hiruthicShaSS** [coreybutler/nvm-windows#1073]
### What happened?

I tried to switch to a different version and using `nvm use <version>`. It invokes UAC in Windows 11 x64 and if I deny the operation by clicking "No" in the UAC, the CLI prints `Now using node v20.9.0 (64-bit)` but the operation was not performed at all.

Can verify that listing the versions after the above steps that the version has indeed not changed.

Also, the tool invokes UAC 2 times for some reason.

![image](https://github.com/coreybutler/nvm-windows/assets/56349092/672445d7-cf37-4fd0-b9c5-2226b01219a8)

### What did you expect to happen?

To print something like, `Unable to switch to the specified version`.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Standard Use, Non-Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
C:\Users\user1>nvm list

    20.9.0
    18.13.0
  * 16.20.2 (Currently using 64-bit executable)

C:\Users\user1>nvm use 20.9.0
Now using node v20.9.0 (64-bit)

C:\Users\user1>nvm list

    20.9.0
    18.13.0
  * 16.20.2 (Currently using 64-bit executable)

C:\Users\user1>nvm --version
1.1.12
```

### Debug Output

```Shell
user1 is not using admin or elevated rights.

Command Prompt - nvm  debug
Windows Version: 10.0 (Build 22631)

Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\user1\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\user1\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\user1\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\user1\AppData\Roaming\nvm

Total Node.js Versions: 3
Active Node.js Version: v16.20.2

IPv6 is enabled. This can slow downloads significantly.

No problems detected.
```

**Comment by coreybutler** [comment]
When you deny the operation (canceling UAC), it successfully cancels (as pointed out). Yes, there is a success message even though the version was not changed. Windows doesn't return the results of the UAC prompt to NVM4W, so there's no way to customize the message. It's annoying, I hate it, but I haven't found a workaround. If anyone has a workaround for this, I'd happily accept a PR.

The rest of the behavior is expected. One UAC prompt elevates the user while the other creates the symlink. This is all triggered by the OS based on the requested action.

**Comment by AvremelM** [comment]
Wouldn't the workaround be to check what the current version is after the uac prompt?
