### ISSUE TITLE
[Issue]: The “nvm ls” command displays the node versions available, however, the “nvm use” command fails.

### ISSUE THREAD

**Issue by goodnighteveryone** [coreybutler/nvm-windows#1076]
### What happened?

When I use the command “nvm install version,” everything runs smoothly. However, when I execute “nvm use,” it indicates that the current version does not exist.
![image](https://github.com/coreybutler/nvm-windows/assets/49894559/17cee3af-422d-43ca-8f99-6d6cbae5a864)
![image](https://github.com/coreybutler/nvm-windows/assets/49894559/31550b9b-e1a7-4992-aa2c-edc944664f7f)
It seems that this issue may be related to the extraction of files.
![image](https://github.com/coreybutler/nvm-windows/assets/49894559/e939ac5b-da22-4b2c-bf4c-2746f23b14b3)
![image](https://github.com/coreybutler/nvm-windows/assets/49894559/4f794110-392a-4560-9088-bd27db954e24)

### What did you expect to happen?

Upon executing "nvm install version," I am able to seamlessly utilize "nvm use version."

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

Asian

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
Windows Version: 10.0 (Build 19045)

Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\xxx\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\xxx\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\xxx\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\xxx\AppData\Roaming\nvm

Total Node.js Versions: 4
Active Node.js Version: v16.14.2

IPv6 is enabled. This can slow downloads significantly.
If you are experiencing npm problems, check the npm mirror (https://npmmirror.com/mirrors/npm/) to assure it is online and accessible.

PROBLEMS DETECTED
-----------------
The following Node installations are invalid (missing node.exe): v18.0.0 - consider reinstalling these versions


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Check your antivirus to assure it isn't removing the Node installations.

**Comment by goodnighteveryone** [comment]
> Check your antivirus to assure it isn't removing the Node installations.

I have identified the root of the issue. It appears that the user I am currently employing lacks the necessary permissions within the nvm installation directory. Upon adjusting the permissions, everything functions as intended.

**Comment by coreybutler** [comment]
@goodnighteveryone glad you figured it out!
