### ISSUE TITLE
Respect .nvmrc file

### ISSUE THREAD

**Issue by mvarrieur** [coreybutler/nvm-windows#108]
Should nvm-windows also respect an .nvmrc file to make this more cross platform compatible? Currently running `nvm install` just says "Invalid version" if you don't supply a version rather than checking for an .nvmrc file to supply the version number.

https://github.com/creationix/nvm#usage

**Comment by coreybutler** [comment]
No - this isn't designed to mirror nvm's features since it uses a completely different approach. I have been working on a cross-platform system as time allows... i.e. one version manager for all operating systems. No ETA as I've been swamped.
