### ISSUE TITLE
[Feature]: Do not inform users that -- is unecessary as it hurts cross platform instructions

### ISSUE THREAD

**Issue by elibroftw** [coreybutler/nvm-windows#1081]
### Description of the new feature / enhancement

When I'm writing nvm instructions, it doesn't help that the nvm on windows suggest to instaall the lts without the -- because then I havve to add instructions to use -- for non-windows users. 

### Scenario when this would be used?

Writing software that is developed on all operating systems and not just on Windows.

**Comment by elibroftw** [comment]
Also `nvm use --lts` does not work :(

**Comment by coreybutler** [comment]
nvm-sh and nvm-windows differ in fundamental ways. Neither project follows the other. This has been described in past issues, as well as the [wiki](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported). There is no intention of adding a flag for `--lts`.

Our cross-platform solution is [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime), which will replace this project in 2024.
