### ISSUE TITLE
[Feature]: Allow Windows user do not have administrative rights to install/use Node.js

### ISSUE THREAD

**Issue by doggy8088** [coreybutler/nvm-windows#1083]
### Description of the new feature / enhancement

Some users might not have administrative rights to use their PC especially if they are work for a Enterprise. I hope nvm-windows able to support a way to install/use Node.js without have administrative rights.

### Scenario when this would be used?

Many of the Enterprise devs doesn't have administrative rights due to company policies.

**Comment by coreybutler** [comment]
NVM4W uses dynamic symlinks to modify which version of Node is active. As a result, you only need permission to create/modify symlinks. In older versions of Windows, Microsoft restricted this to administrative accounts. In newer versions of Windows, you can enable Developer Mode to grant these permissions. Corporations can leverage Active Directory Group Policy to grant users appropriate privileges too. 

Regardless, _Windows_ requires these permissions.

For more information on how enterprise developers can use NVM4W now, see [common issues - permissions](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145).

Enterprise users should follow the news about [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). Runtime is the successor to NVM4W and has been designed with enterprise needs as a top priority.
