### ISSUE TITLE
Facing issue in order to convert node version using nvm  

### ISSUE THREAD

**Issue by johnmaju** [coreybutler/nvm-windows#1085]
### What happened?

With help of nvm ,i installed node js version 16.20.2 but when i try to use this as commending like 'nvm use use 16.20.2' ,i got an error like "fork/exec C:\Users\ASUS\AppData\Roaming\nvm\elevate.cmd: The system cannot find the file specified.:".i am using nvm version 1,1.12.

### What did you expect to happen?

i want to convert my node version 14 to 16.

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
C:\Windows\System32>nvm use 16
fork/exec C:\Users\ASUS\AppData\Roaming\nvm\elevate.cmd: The system cannot find the file specified.:
```

### Debug Output

```Shell
Administrator: Command Prompt - nvm  debug
Windows Version: 10.0 (Build 22621)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\ASUS\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\ASUS\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\ASUS\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\ASUS\AppData\Roaming\nvm

Total Node.js Versions: 2
Active Node.js Version: none
(run "nvm use <version>" to activate a version)
NVM_SYMLINK does not exist yet. This is auto-created when "nvm use" is run.

IPv6 is enabled. This can slow downloads significantly.

PROBLEMS DETECTED
-----------------
The following Node installations are invalid (missing node.exe): v14.21.3 - consider reinstalling these versions


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

C:\Windows\System32>nvm use 16
fork/exec C:\Users\ASUS\AppData\Roaming\nvm\elevate.cmd: The system cannot find the file specified.:

**Comment by mar10br0** [comment]
I am facing the same issue with NVM 1.1.7
Win 10 without admin privileges (nvm installed through corporate software distribution)
Switched nvm root to a writeable folder: %USERPROFILE%\nvm
Both when using cmd.exe or MINGW64

**Comment by coreybutler** [comment]
@johnmaju - how did you install NVM4W? Many users of scoop have been reporting this issue (#1069).

@mar10br0 - sounds like the corporate install isn't delivering `elevate.cmd`.
