### ISSUE TITLE
NVM does not work on NanoServer and there is no content output when executing command.

### ISSUE THREAD

**Issue by VAllens** [coreybutler/nvm-windows#1088]
### What happened?

NVM version: `1.1.12`
NVM package: https://github.com/coreybutler/nvm-windows/releases/download/1.1.12/nvm-noinstall.zip
Docker container image version: [mcr.microsoft.com/dotnet/sdk:8.0-nanoserver-ltsc2022](https://mcr.microsoft.com/en-us/product/dotnet/sdk/tags)
Internal version number of the operating system: `10.0.20348.2031`
Run as User: `ContainerAdministrator`

There is no content output when executing the nvm command.
I tested `cmd`, `pwsh` (PowerShell Core 7), and `PowerShell` and obtained the same results.

### What did you expect to happen?

I want it can work on NanoServer ltsc2022

### Version

1.1.11 or newer (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Non-Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
No output
```

### Anything else?

![image](https://github.com/coreybutler/nvm-windows/assets/5094922/52e0e233-ec46-4007-be02-cd3c04e935ec)

**Comment by wsobolewski** [comment]
For this to work you need a 64 bit version of nvm.

**Comment by VAllens** [comment]
> For this to work you need a 64 bit version of nvm.

Where should I get the x64 version from?
If the x64 version is not available, how should I build it from source code?

**Comment by wsobolewski** [comment]
> > For this to work you need a 64 bit version of nvm.
> 
> @wsobolewski Where should I get the x64 version from? If the x64 version is not available, how should I build it from source code?

You can build from source. 
Change line 7 in build.bat from
`SET GOARCH=386 `
to 
`SET GOARCH=amd64`

You can find the information how to build from source [here:](https://github.com/coreybutler/nvm-windows#build-from-source)

**Comment by VAllens** [comment]
> > > For this to work you need a 64 bit version of nvm.
> > 
> > 
> > @wsobolewski Where should I get the x64 version from? If the x64 version is not available, how should I build it from source code?
> 
> You can build from source. Change line 7 in build.bat from `SET GOARCH=386 ` to `SET GOARCH=amd64`
> 
> You can find the information how to build from source [here:](https://github.com/coreybutler/nvm-windows#build-from-source)

Thanks a lot, I will try to build it. @wsobolewski 
I think the x64 version is a general requirement, is the team considering releasing it?

**Comment by wsobolewski** [comment]
> > > > For this to work you need a 64 bit version of nvm.
> > > 
> > > 
> > > @wsobolewski Where should I get the x64 version from? If the x64 version is not available, how should I build it from source code?
> > 
> > 
> > You can build from source. Change line 7 in build.bat from `SET GOARCH=386 ` to `SET GOARCH=amd64`
> > You can find the information how to build from source [here:](https://github.com/coreybutler/nvm-windows#build-from-source)
> 
> Thanks a lot, I will try to build it. @wsobolewski I think the x64 version is a general requirement, is the team considering releasing it?

I'm not a team member, so I can't tell. You may need to ask @coreybutler about it.

**Comment by VAllens** [comment]
Oh, that's okay. Thanks anyway. @wsobolewski

**Comment by wsobolewski** [comment]
> Oh, that's okay. Thanks anyway. @wsobolewski

You're welcome.
