### ISSUE TITLE
It fails to download the node.exe either by proxy or the origin network

### ISSUE THREAD

**Issue by Loyalsoldier** [coreybutler/nvm-windows#109]
It fails to download the node.exe either by proxy nor the original network.

And when using proxy, it fails when node.exe is 99% completion. It's so strange.

And it just can't switch node version.

**Comment by MystK** [comment]
If you could provide some more info like the output, the command you used, how you installed it, it could be more helpful in solving the problem.

**Comment by coreybutler** [comment]
Closing due to age and lack of troubleshooting information.
