### ISSUE TITLE
[Feature]: Can this work on Linux in powershell?

### ISSUE THREAD

**Issue by AceHack** [coreybutler/nvm-windows#1094]
### Description of the new feature / enhancement

NVM.sh does not work in powershell linux, would love to use this instead.

### Scenario when this would be used?

Powershell linux

### Supporting information

Powershell can't run .sh scripts

**Comment by coreybutler** [comment]
I'm not sure what you're asking for. Shell scripts won't work on Windows. If you're referring to nvm-sh, it doesn't have scripts either. If you want this to be a mirror of nvm-sh, you're out of luck. See [why nvm for nix features aren't supported](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported) and what we're doing instead: [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).
