### ISSUE TITLE
No longer works in Windows 10

### ISSUE THREAD

**Issue by vitaly-t** [coreybutler/nvm-windows#110]
It's been working fine under Windows 10, but since the latest updates came, it stopped working.
```
Microsoft Windows [Version 10.0.10586]
```
Now if I issue `use` command, it says - success, but it doesn't do anything, the version never changes, which `nvm list` confirms.

**Comment by coreybutler** [comment]
My machine is slow to update... once I get the latest updates, I'll take a look at this.

**Comment by breck7** [comment]
As a reference point, works great on:

    Microsoft Windows [Version 10.0.10240]

**Comment by vitaly-t** [comment]
As stated in the beginning, it worked great on the initial version of Windows 10, it stopped after the latest update that brought Windows to version 10.0.10586.

**Comment by vitaly-t** [comment]
Ok, I can see that the latest Windows 10 update simply breaks NVM, somehow.

I just have uninstalled, and then reinstalled, and everything works again.
