### ISSUE TITLE
node v5 is not available

### ISSUE THREAD

**Issue by luisrudge** [coreybutler/nvm-windows#111]
```
λ nvm list available

Showing the 15 latest available releases.

      STABLE   |    UNSTABLE
   ---------------------------
       v4.2.1  |    v0.11.16
       v4.2.0  |    v0.11.15
      v0.12.7  |    v0.11.14
      v0.12.6  |    v0.11.13
      v0.12.5  |    v0.11.12
      v0.12.4  |    v0.11.11
      v0.12.3  |    v0.11.10
      v0.12.2  |     v0.11.9
      v0.12.1  |     v0.11.8
      v0.12.0  |     v0.11.7
     v0.10.40  |     v0.11.6
     v0.10.39  |     v0.11.5
     v0.10.38  |     v0.11.4
     v0.10.37  |     v0.11.3
     v0.10.36  |     v0.11.2

For a complete list, visit http://coreybutler.github.io/nodedistro
```

**Comment by luisrudge** [comment]
installing v5 works though..

**Comment by coreybutler** [comment]
NVM for Windows currently shows the old release pattern. I made a snap decision to only list LTS releases in stable, but that doesn't mean the other versions (like v5) are unstable. I'll need to come up with a better way to display this info... maybe an LTS and non-LTS column.

**Comment by luisrudge** [comment]
yeah.. that would be great!

**Comment by luisrudge** [comment]
or maybe.. `nvm list available-lts` and `nvm list available`

**Comment by SteveALee** [comment]
However I find 4.2.2 is not listed as above but it is listed on http://coreybutler.github.io/nodedistro/ which si referenced in the output of nvm list available

**Comment by SteveALee** [comment]
PS the fact the above list prefixes with v is a little confusing. The v  must not be specified when installing  or using

**Comment by MaxArt2501** [comment]
I think in `nvm list available` there should be another column, beside STABLE and UNSTABLE, showing LTS releases.
Specifically, the STABLE column should be renamed to LTS, while the *new* STABLE column should contain 5.x releases.

**Comment by BrainCrumbz** [comment]
Hello all

on a Windows 7 x64 machine, nvm 1.1.0, as of today no node 5.x version is listed as available: 

~~~
Showing the 15 latest available releases.

      STABLE   |    UNSTABLE
   ---------------------------
       v4.3.0  |    v0.11.16
       v4.2.6  |    v0.11.15
       v4.2.5  |    v0.11.14
       v4.2.4  |    v0.11.13
       v4.2.3  |    v0.11.12
       v4.2.2  |    v0.11.11
       v4.2.1  |    v0.11.10
       v4.2.0  |     v0.11.9
     v0.12.10  |     v0.11.8
      v0.12.9  |     v0.11.7
      v0.12.8  |     v0.11.6
      v0.12.7  |     v0.11.5
      v0.12.6  |     v0.11.4
      v0.12.5  |     v0.11.3
      v0.12.4  |     v0.11.2
~~~

but then trying to install 5.0.0 or 5.6.0 works fine. And 5.6.0 is dubbed as stable on nodejs.org. Is this behaviour expected? Thanks!

**Comment by coreybutler** [comment]
@BrainCrumbz - yes. See my comment above. The 5.x series is stable, but not LTS.

**Comment by BrainCrumbz** [comment]
Thanks for feedback, got it. BTW, @MaxArt2501 suggestion seems sensible.

**Comment by MaxArt2501** [comment]
It could have been sensible two months ago, now it sounds a little outdated as there's no more "stable" and "unstable", but rather "LTS" and "stable".
I think a little extra work can be done if le list of the versions is pulled from https://nodejs.org/download/release/index.json instead of [here](https://raw.githubusercontent.com/coreybutler/nodedistro/master/nodeversions.json) (maybe it's a list maintained/generated by Corey himself?). Identifying LTS versions is easy, as they're the ones with the `lts` property not set to `false`.
I don't know enough Go to change the code, compile it and make a pull request after some tests, but that's what I'd do.

**Comment by coreybutler** [comment]
@MaxArt2501 - The node release page is the list I intend to implement in the next version. It didn't exist when I first created the utility (pre node foundation/io.js). The second link you mention (nodedistro) is a list I maintain. I have a script that runs every hour to look for a new release. Not ideal.

I do like your suggestion for naming. The only thing I'm still thinking about is the naming of LTS lines and whether they'll even be a factor (right now I don't think they will, but I'm trying to confirm that). For example, "Argon" is the current LTS line, but the name will change when the next LTS line comes out.

**Comment by BrainCrumbz** [comment]
@MaxArt2501 Yep, I meant: among the various suggestions, I favored the one having separate columns with proper (up to date) headers.

**Comment by RobMoloney** [comment]
We are using node version 5.5.0 in our build environment. I'm using nvm to switch versions.
Today I tried to setup  a new machine and I'm getting this error.

nvm install 5.5.0
Node.js v5.5.0 is not yet released or available.

**Comment by coreybutler** [comment]
@RobMoloney I'm not sure when it happened, but the node distribution list got a little tangled up. I fixed it, so it should work now. For future reference, version issues can be corrected [here](http://github.com/coreybutler/nodedistro).

**Comment by RobMoloney** [comment]
Great. Thanks for the quick reply.

**Comment by pratibhagaund** [comment]
![image](https://user-images.githubusercontent.com/7009178/39577352-c7af1a82-4efe-11e8-88ae-7cf2a2d01ed0.png)

I am trying to install a listed node version. What could be the possible reasons for this behavior?

**Comment by Lyd9607** [comment]
![default](https://user-images.githubusercontent.com/26515666/39745367-a181d80c-52d9-11e8-8b5d-7e35e00016f6.png)
how to resolve it?

**Comment by maganramkrishna** [comment]
You will having old version of "nvm". Update to new version of nvm will solve this issue. Download latest nvm for windows from [here](https://github.com/coreybutler/nvm-windows/releases) and then try again to install node again.

**Comment by Venryx** [comment]
Yep, upgrading nvm worked for me. (the issue of it saying "not yet released or available" for a version listed by the "list available" command)
