### ISSUE TITLE
[Issue]: Symlink seems not working in exFAT filesystem

### ISSUE THREAD

**Issue by MisaLiu** [coreybutler/nvm-windows#1122]
### What happened?

I tried run `nvm install 20.12.1` and nothing wrong happend, but when I tried run `nvm use 20.12.1`, although UAC pop up and nvm promped `Now using node v18.18.2 (64-bit)`, but I still cannot use `node` and there's no `nodejs` symlink created in my node folder.

### What did you expect to happen?

The `nodejs` folder should be created correctly.

### Version

1.1.11 or newer (Default)

### Which locale?

Asian

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Standard Use, Non-Elevated

### Is Developer Mode enabled?

Yes

### Debug Output

```Shell
misaliu is not using admin or elevated rights.

pwsh in misaliu
Windows Version: 10.0 (Build 19045)

Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.12
NVM4W Path:         D:\Develop\nvm\nvm.exe
NVM4W Settings:     D:\Develop\nvm\settings.txt
NVM_HOME:           D:\Develop\nvm
NVM_SYMLINK:        D:\Develop\nodejs
Node Installations: D:\Develop\nvm

Total Node.js Versions: 1
Active Node.js Version: none
(run "nvm use <version>" to activate a version)
NVM_SYMLINK does not exist yet. This is auto-created when "nvm use" is run.

IPv6 is enabled. This can slow downloads significantly.

PROBLEMS DETECTED
-----------------
"pwsh in misaliu" is not an officially supported shell. Some features may not work as expected.



Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by MisaLiu** [comment]
I guess I found the issue:

My `D:` partition, for some reason, is using `exFAT` filesytem, and I found some posts about Windows cannot create symlink on `exFAT` (at least now)[^*] so I reinstall `nvm` to my `C:` partition (which is using `NTFS` filesystem) and everything works fine.

![image](https://github.com/coreybutler/nvm-windows/assets/62408957/0afb8734-4758-4c60-9519-483a249387d1)

[^*]: https://superuser.com/questions/232257/does-or-will-exfat-support-symlinks

**Comment by coreybutler** [comment]
Glad you got it working. I was not aware of the exFAT limitation for symlinks. Thanks for bringing that to my attention. It's something to consider for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).
