### ISSUE TITLE
[Issue]: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by Totati** [coreybutler/nvm-windows#1123]
### What happened?

I can't install a new node version. When I try `nvm install 20.12.1` I get the following error.
```
Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt.


Get "https://nodejs.org/dist/latest/SHASUMS256.txt": read tcp 192.168.0.156:50907->104.20.23.46:443: wsarecv: An existing connection was forcibly closed by the remote host.
```
`nvm debug` says it can't connect to `nodejs.org`.
```
PROBLEMS DETECTED
-----------------
Connection to nodejs.org cannot be established. Check your proxy (none) and your physical internet connection.
```

I've asked around and none of other people in and outside of my work can install new versions. They get the same error.

### What did you expect to happen?

I would like to install a new version :D

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt, PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: Windows PowerShell
Windows Version: 10.0 (Build 19045)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\atoth\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\atoth\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\atoth\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\atoth\AppData\Roaming\nvm

Total Node.js Versions: 8
Active Node.js Version: v20.11.0

IPv6 is enabled. This can slow downloads significantly.

WARNING: The following Node installations are missing npm: v20.8.1
         (Node will still run, but npm will not work on these versions)

PROBLEMS DETECTED
-----------------
Connection to nodejs.org cannot be established. Check your proxy (none) and your physical internet connection.
```

**Comment by 62791755** [comment]
aio plugins:install @adobe/aio-cli-plugin-api-mesh

**Comment by 62791755** [comment]
> aio plugins:install @adobe/aio-cli-plugin-api-mesh
>

**Comment by coreybutler** [comment]
I think you ran into the [eager beaver problem](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#cant-download-latest-nodejs).

**Comment by Totati** [comment]
Thank you the explanation :)

**Comment by fl0wm0ti0n** [comment]
i have exactly the same problem but i get it not solved... it doesn tmatter what version i want to download...
