### ISSUE TITLE
[Issue]: nvm use command does not select certain versions

### ISSUE THREAD

**Issue by jiaohanying** [coreybutler/nvm-windows#1127]
### What happened?

When using use command, versions below nodejs 17 cannot be selected. I tested node versions 20, 18, 17, 16, 15, 14 and 10. 
The response from use command is that given version is now used, however, when checking for current the response is that no version is currently used.

![image](https://github.com/coreybutler/nvm-windows/assets/77376372/c97d3cba-30db-49bd-8849-5402e6c4e152)

Although nvm shows that node 16.20.2 is not selected, the nodejs link points correctly.
My environment variable settings are correct and node 17.9.1 can be used normally.

![image](https://github.com/coreybutler/nvm-windows/assets/77376372/16144ba0-092c-491b-a3ba-6d35cfb8228e)

![image](https://github.com/coreybutler/nvm-windows/assets/77376372/6c6c06d6-a0f5-4b8f-89fe-71e0b0c5ef40)

### What did you expect to happen?

Versions below nodejs 17 should be used.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

Other Non-English

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
PS C:\WINDOWS\system32> nvm ls

  * 17.9.1 (Currently using 64-bit executable)
    16.20.2
PS C:\WINDOWS\system32> nvm use 16.20.2
Now using node v16.20.2 (64-bit)
PS C:\WINDOWS\system32> nvm ls

    17.9.1
    16.20.2
PS C:\WINDOWS\system32> nvm current
No current version. Run 'nvm use x.x.x' to set a version.
```

### Debug Output

```Shell
PS C:\WINDOWS\system32> nvm debug
Running NVM for Windows with administrator privileges.

管理员: Windows PowerShell
Windows Version: 10.0 (Build 22631)

NVM4W Version:      1.1.12
NVM4W Path:         D:\Apps\NVM\nvm.exe
NVM4W Settings:     D:\Apps\NVM\settings.txt
NVM_HOME:           D:\Apps\NVM
NVM_SYMLINK:        D:\Apps\NVM\nodejs
Node Installations: D:\Apps\nvm

Total Node.js Versions: 2
Active Node.js Version: none
(run "nvm use <version>" to activate a version)

IPv6 is enabled. This can slow downloads significantly.

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Please correct me if I'm wrong, but the issue is just in the display, i.e. `nvm ls` is not showing the asterisk next to the version if it is below 17. _Functionally_, everything is working though, correct?

**Comment by jiaohanying** [comment]
No, it doesn't work. What should I do?
![image](https://github.com/coreybutler/nvm-windows/assets/77376372/72d7dd1d-0e59-49d2-885a-934419857565)


> Please correct me if I'm wrong, but the issue is just in the display, i.e. `nvm ls` is not showing the asterisk next to the version if it is below 17. _Functionally_, everything is working though, correct?

**Comment by hanshenrikchr** [comment]
I have a similar problem:
![image](https://github.com/coreybutler/nvm-windows/assets/5486741/802ffbeb-9147-4a5f-a513-cddf013a8116)

i cant go to 16.20.2, even though it says it is using it in the console
