### ISSUE TITLE
[Issue]: Get "https://nodejs.org/dist/latest-v18.x/SHASUMS256.txt": write tcp 10.0.0.10:59499->104.20.22.46:443: wsasend: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by fl0wm0ti0n** [coreybutler/nvm-windows#1133]
### What happened?

I cant install any node,js version (tried 21,20,19,18). I tried also 1.1.11 and 1.1.10 of nvm. See error output beneath.
If i install nvm in the same LAN on my laptop it works... Also with Windows Firewall off, it doesn't work on my Workstation...
and i also have no proxy active or any kind

if i manually open "https://nodejs.org/dist/latest-v18.x/SHASUMS256.txt" in a browser it shows me the list of versions....

```
PS C:\flowGit\crypto-projects\solana-hashlips-candy-nft\4-mint\candy-nft-mint-v3_2> nvm install 18

Could not retrieve https://nodejs.org/dist/latest-v18.x/SHASUMS256.txt.

Get "https://nodejs.org/dist/latest-v18.x/SHASUMS256.txt": write tcp 10.0.0.10:59499->104.20.22.46:443: wsasend: An existing connection was forcibly closed by the remote host.

```
### What did you expect to happen?

installing node.js version

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

Western European

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
PS C:\flowGit\crypto-projects\solana-hashlips-candy-nft\4-mint\candy-nft-mint-v3_2> nvm debug
flow is not using admin or elevated rights.

C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
Windows Version: 10.0 (Build 19045)

Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\flow\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\flow\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\flow\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\flow\AppData\Roaming\nvm

Total Node.js Versions: 1
Active Node.js Version: v22.0.0

IPv6 is enabled. This can slow downloads significantly.

PROBLEMS DETECTED
-----------------
Connection to nodejs.org cannot be established. Check your proxy (none) and your physical internet connection.


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by fl0wm0ti0n** [comment]
> I think the root cause is spelled out in the debug function. The bottom line is your environment cannot connect to nodejs.org. You stated you're using admin/elevated privileges, but the debug console states otherwise.
> 
> This line suggests you're behind a proxy.
> 
> `Get "https://nodejs.org/dist/latest-v18.x/SHASUMS256.txt": write tcp 10.0.0.10:59499->104.20.22.46:443: wsasend: An existing connection was forcibly closed by the remote host. `
> 
> Are you sure there is no proxy? Remember, even though you may not have a proxy setup on your computer, that doesn't mean there isn't a corporate proxy blocking traffic.

thanks for the response.

nodejs.org is reachable via browser. Also "https://nodejs.org/dist/latest-v18.x/SHASUMS256.txt" as mentioned.
im in my private LAN, and i have full control over all my networking. In fact i made it all by self. So i know im not behind a proxy. i checked also windows, there is no proxy no firewall active.

And as said my laptop is in the same network and there it works, but my laptop has windows 11. this computer here has windows 10.

Same problem also with admin powershell:

```
Running NVM for Windows with administrator privileges.

Administrator: Windows PowerShell
Windows Version: 10.0 (Build 19045)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\flow\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\flow\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\flow\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\flow\AppData\Roaming\nvm

Total Node.js Versions: 7
Active Node.js Version: v18.20.2

IPv6 is enabled. This can slow downloads significantly.

PROBLEMS DETECTED
-----------------
Connection to nodejs.org cannot be established. Check your proxy (none) and your physical internet connection.
```

I installed the node.js versions now manually thats why I have now "Total Node.js Versions: 7" ;)

**Comment by coreybutler** [comment]
I'm not sure what to say, because NVM4W doesn't do anything special when it comes to network requests. It issues standard HTTP requests for downloads, and that's it. I'm not aware of anything specific to Win10 vs Win11 that would cause this type of issue... and I know it works on Win10.

I suppose firewalls could play a factor, but you said you didn't have a firewall enabled. I'm not sure why nodejs.org would forcibly close the connection, but it looks like it is indeed nodejs.org (remote host) closing the connection (not NVM4W).

I can't really see anything in the info provided hinting that NVM4W can actually do anything about this... especially if it is working on another machine.

**Comment by fl0wm0ti0n** [comment]
I thought about maybe is the error misleading or wrong, and it happens something different in the background.

look this issue https://github.com/coreybutler/nvm-windows/issues/1123 he had the same error and it was something different than a connection issue.

well i will dive deeper with my opensense and track the connection

**Comment by fl0wm0ti0n** [comment]
ok the connection is perfect there is no issue... so i assume there is no problem going on on the network level..
![image](https://github.com/coreybutler/nvm-windows/assets/24993288/17895a5c-eb0b-4954-818a-da28248f9243)

**Comment by coreybutler** [comment]
The problem is `An existing connection was forcibly **closed by the remote host**.`, meaning nodejs.org is closing the connection. NVM4W doesn't control that.

Can you run `nvm ls available`? This makes a request to a different endpoint on nodejs.org.

**Comment by fl0wm0ti0n** [comment]
> The problem is `An existing connection was forcibly **closed by the remote host**.`, meaning nodejs.org is closing the connection. NVM4W doesn't control that.
> 
> Can you run `nvm ls available`? This makes a request to a different endpoint on nodejs.org.
ah yeah you're right


i tried your hint, same result :(

PS C:\Users\flow> nvm ls available

Could not retrieve https://nodejs.org/dist/index.json.

Get "https://nodejs.org/dist/index.json": write tcp 10.0.0.10:52879->104.20.22.46:443: wsasend: An existing connection was forcibly closed by the remote host.

**Comment by coreybutler** [comment]
Something has to be happening on the network (including the remote end) to cause nodejs.org to close your connection. The code for downloading the index.json file is [here](https://github.com/coreybutler/nvm-windows/blob/master/src/web/web.go#L127C2-L127C46) (`req, err := http.NewRequest("GET", url, nil)`. It's a standard Go HTTP request with absolutely nothing special about it. We can't get any more fundamental than that in Go. Plus, I can't recreate this error and I haven't seen anyone else post anything like this.

Ultimately, I don't think this is NVM4W issue. Since it works on one machine and not the other, I would recommend using something like Wireshark on both machines to compare the successful requests to the failed ones (to nodejs.org).

**Comment by rpw1** [comment]
I had this issue as well. Turns out Windows Defender Firewall has my private network as a Guest or public network. This was blocking the request. Turning off Windows Defender Firewall temporarily solved my issue. I hope this helps!
