### ISSUE TITLE
[Feature]: add `nvm install` to the command line syntax help

### ISSUE THREAD

**Issue by yg-i** [coreybutler/nvm-windows#1136]
### Description of the new feature / enhancement

`nvm install` is conspicuously missing from the command line help. 

![image](https://github.com/coreybutler/nvm-windows/assets/148152939/5c75dbaa-e89e-4fb8-b5f1-fbd22bb06a16)

### Scenario when this would be used?

It helps users discover one of the most used command line parameter without having to google.

### Supporting information

None

**Comment by coreybutler** [comment]
It's the 4th command in the screenshot you provied.
