### ISSUE TITLE
[Feature]: Proper Documentation

### ISSUE THREAD

**Issue by Silentboy7707** [coreybutler/nvm-windows#1138]
### Description of the new feature / enhancement

The code is not properly documented, Its messed up actually So I will help you out with a better documentation for easy Installation for those who just want to Install and use and below that for the developers and issue guide type.

### Scenario when this would be used?

This would be helpful in every case making it more popular and all in one solution in our repository.

**Comment by coreybutler** [comment]
It's pretty hard to not document Go code, given that it is auto-generated. https://pkg.go.dev/github.com/coreybutler/nvm-windows/src. The installation process is "click and follow the wizard".

Anyhow, you're welcome to document whatever you want (I recommend a blog article)... I certainly don't want to discourage that. However; new documentation is not a high priority for the project, and with 10M+ downloads, it seems like most people have figured out how to use it. Before you spend your time on this, remember, NVM4W will be deprecated when we release [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).
