### ISSUE TITLE
NVM on Windows XP

### ISSUE THREAD

**Issue by EdZava** [coreybutler/nvm-windows#114]
Install nvm perfect.
Install node 5.0.0  32 perfect.

Error on:
> nvm use 5.0.0 32

Error msg:
>exit status 1: "C:\Documents" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by coreybutler** [comment]
Technically, XP isn't supported since it reached end of life a while ago. It may still work. I don't speak Spanish, but if Google Translate is correct, I think you're experiencing a problem with escaping. I would suggest installing directly to `:C\` instead of `C:\Program Files`.
