### ISSUE TITLE
[Issue]: unins000.exe not present in installation path (NVM_HOME).

### ISSUE THREAD

**Issue by devatgo** [coreybutler/nvm-windows#1140]
### What happened?

I installed nvm manually (i.e. `nvm-noinstall.zip`, and followed the [manual installation instructions](https://github.com/coreybutler/nvm-windows/wiki#manual-installation)), everything is working great, except that the installation instructions state that in order to uninstall nvm you just run the `unins000.exe` file of which should be present in the installation path (i.e. NVM_HOME), but `unins000.exe` does not exist in the installation path.

Considering that the installation instructions explicitly state that to uninstall nvm you simply need to run `unins000.exe` of which should be present in the installation path, and being that `nvm-noinstall.zip` doesn't contain `unins000.exe`, I originally presumed that this file (i.e. `unins000.exe`) would be generated upon running nvm but that's not the case and it is nowhere to be found. So, being that the manual installation instructions does not contain any instructions as it relates to uninstalling nvm I was just curious about how I would go about uninstalling nvm in the event I need to in the future, along with all nodejs versions installed via nvm, and removing any changes nvm makes to registry.

### What did you expect to happen?

`unins000.exe` present in installation directory (i.e. NVM_HOME) as per the [installation instructions](https://github.com/coreybutler/nvm-windows/wiki#uninstall).

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
C:\Windows\system32>nvm debug
Running NVM for Windows with administrator privileges.

Administrator: Command Prompt - nvm  debug
Windows Version: 10.0 (Build 19045)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\<redacted>\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\<redacted>\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\<redacted>\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Users\<redacted>\nodejs
Node Installations: C:\Users\<redacted>\AppData\Roaming\nvm

Total Node.js Versions: 1
Active Node.js Version: v20.13.1

IPv6 is enabled. This can slow downloads significantly.

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Good point. I've updated the manual installation guide to describe the uninstall process. https://github.com/coreybutler/nvm-windows/wiki#uninstall
