### ISSUE TITLE
[Issue]: C:\Program Files\nodejs not added to the environment variable path

### ISSUE THREAD

**Issue by sawa-ko** [coreybutler/nvm-windows#1141]
### What happened?

Currently when I install nvm, the `C:\Program Files\nodejs` path is not added to the windows path environment variable, so certain programs crash because they try to look for that environment variable to have that path since the nodejs installer for windows does it.

### What did you expect to happen?

Have the path `C:\Program Files\nodejs` added to the windows path environment variable.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

Other Non-English

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrador: Windows PowerShell
Windows Version: 10.0 (Build 22631)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\Kaname\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\Kaname\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\Kaname\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\Kaname\AppData\Roaming\nvm

Total Node.js Versions: 1
Active Node.js Version: v22.2.0

IPv6 is enabled. This can slow downloads significantly.

No problems detected.
```

**Comment by coreybutler** [comment]
How did you install NVM4W? The installer adds `%NVM_SYMLINK%` and `%NVM_HOME%` to the `PATH`. In your case, that resolves to `C:\Program Files\nodejs`

**Comment by sawa-ko** [comment]
Yes, but for example Jetbrains ides does not detect it if it is not the full path instead of an alias.
