### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by chenjidu** [coreybutler/nvm-windows#1142]
### What happened?

![Snipaste_2024-06-04_11-52-30](https://github.com/coreybutler/nvm-windows/assets/25902575/152f0c4e-f19e-4813-a1e4-dd01b50665cb)

### What did you expect to happen?

Running NVM in Gitbash to Display Popups

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
？？？
```

### Anything else?

？？？？

**Comment by somecodingwitch** [comment]
Have you tried to run nvm specifically on a Windows shell as the error message told?
I think the message is pretty clear about it

**Comment by coreybutler** [comment]
Git bash is not officially supported. It uses unix paths that Windows doesn't recognize. See [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#special-terminal-shells).
