### ISSUE TITLE
nvm 

### ISSUE THREAD

**Issue by Rooban21** [coreybutler/nvm-windows#1143]
### What happened?

C:\Users\DELL>node -v
v20.14.0

C:\Users\DELL>nvm install 16.20.2
Downloading node.js version 16.20.2 (64-bit)...
Error while downloading https://nodejs.org/dist/v16.20.2/node-v16.20.2-win-x64.zip - stream error: stream ID 7; INTERNAL_ERROR; received from peer
Extracting node and npm...
Error extracting from Node archive: zip: not a valid zip file
Could not download node.js v16.20.2 64-bit executable.

C:\Users\DELL>
C:\Users\DELL>
C:\Users\DELL>
C:\Users\DELL>nvm install 16
Downloading node.js version 16.20.2 (64-bit)...
Extracting node and npm...
Complete
npm v8.19.4 installed successfully.

Installation complete. If you want to use this version, type

nvm use 16.20.2

C:\Users\DELL>nvm use 16.20.2
Now using node v16.20.2 (64-bit)

C:\Users\DELL>node -v
v20.14.0

### What did you expect to happen?

i want to change the node version of 16.20.2 , but it still showing node -v 20

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
C:\Users\DELL>node -v
v20.14.0

C:\Users\DELL>nvm install 16.20.2
Downloading node.js version 16.20.2 (64-bit)...
Error while downloading https://nodejs.org/dist/v16.20.2/node-v16.20.2-win-x64.zip - stream error: stream ID 7; INTERNAL_ERROR; received from peer
Extracting node and npm...
Error extracting from Node archive: zip: not a valid zip file
Could not download node.js v16.20.2 64-bit executable.

C:\Users\DELL>
C:\Users\DELL>
C:\Users\DELL>
C:\Users\DELL>nvm install 16
Downloading node.js version 16.20.2 (64-bit)...
Extracting node and npm...
Complete
npm v8.19.4 installed successfully.


Installation complete. If you want to use this version, type

nvm use 16.20.2

C:\Users\DELL>nvm use 16.20.2
Now using node v16.20.2 (64-bit)

C:\Users\DELL>node -v
v20.14.0
```

### Debug Output

```Shell
C:\Users\DELL>node -v
v20.14.0

C:\Users\DELL>nvm install 16.20.2
Downloading node.js version 16.20.2 (64-bit)...
Error while downloading https://nodejs.org/dist/v16.20.2/node-v16.20.2-win-x64.zip - stream error: stream ID 7; INTERNAL_ERROR; received from peer
Extracting node and npm...
Error extracting from Node archive: zip: not a valid zip file
Could not download node.js v16.20.2 64-bit executable.

C:\Users\DELL>
C:\Users\DELL>
C:\Users\DELL>
C:\Users\DELL>nvm install 16
Downloading node.js version 16.20.2 (64-bit)...
Extracting node and npm...
Complete
npm v8.19.4 installed successfully.


Installation complete. If you want to use this version, type

nvm use 16.20.2

C:\Users\DELL>nvm use 16.20.2
Now using node v16.20.2 (64-bit)

C:\Users\DELL>node -v
v20.14.0
```

**Comment by somecodingwitch** [comment]
Did you do a retest since the problem occurrence?
The direct link to the ZIP seems fine and returns a valid ZIP with the NodeJS binaries

**Comment by coreybutler** [comment]
The "Debug Output" section of the issue explicitly states you should paste the output of `nvm debug`. Please provide that output.

I suspect a permission issue. If you can successfully install node but not use it, it usually means your user account doesn't have permission to use the underlying mklink utility. The `nvm debug` output helps identify permission issues so they can be resolved.
