### ISSUE TITLE
[Issue]: `nvm use` bug

### ISSUE THREAD

**Issue by CholezYu** [coreybutler/nvm-windows#1144]
### What happened?

I switched versions with nvm use, and then the files in the nodejs folder were emptied, i.e. the association with nvm was gone. However, the files for each nodejs version in the nvm folder still exist.
![1](https://github.com/coreybutler/nvm-windows/assets/88796382/bf4d6644-d4f9-4d54-880e-3bc22e6b7196)
![2](https://github.com/coreybutler/nvm-windows/assets/88796382/2869eee2-ee6e-4858-9250-daf0f8068b4a)
![3](https://github.com/coreybutler/nvm-windows/assets/88796382/a33210e4-d0b1-411f-a3a0-372056d41700)
This is the second time this has happened.

### What did you expect to happen?

Everything works fine.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

None

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
none.
```

**Comment by coreybutler** [comment]
yarn is a global module. When you switch versions, you get a clean/isolated instance of npm global modules. You have to install the global modules in each version.

Some people coming from other version managers are used to having commands that auto-install global modules from one version into another version when they `nvm install` a new version. This functionality will not be added to NVM4W, but it will be in [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).

**Comment by CholezYu** [comment]
I mean, I can make sure I have yarn, npm, etc installed in every node version and that they all work, but I was on a normal version switch and the nodejs folder became empty.
I remember when I installed nvm, the nodejs folder became a shortcut to a version of nvm, but now, it's a normal folder again, and it's empty.

**Comment by coreybutler** [comment]
This sounds like it could be a permissions issue. Run `nvm debug` to confirm NVM4W's privileges. 

NVM4W doesn't create folders for symlinks, so it sounds like you may have a conflicting process doing something to that folder. Once a true folder is created, mklink can no longer create a symlink. This can happen when people choose their installation path as the symlink path. Again, the output of `nvm debug` would help identify if that is the problem.

**Comment by CholezYu** [comment]
I run `nvm debug` and it shows "NVM_SYMLINK (d:\nodejs) is not a valid symlink."
How should I fix this.
![66](https://github.com/coreybutler/nvm-windows/assets/88796382/292d7307-e3d7-4d74-a085-6f82f7ab5eb5)

The environment variables are set up like this, and I'm sure they haven't been manually modified recently.
![77](https://github.com/coreybutler/nvm-windows/assets/88796382/8faf131f-6c82-44f3-945f-315b8813543b)

**Comment by coreybutler** [comment]
Do you have anything else running that manages Node? The only other time I've seen something like this is when another tool is attempting to manage some part of the Node installation (ex: conda). 

NVM4W does not create folders other than the installation root for Node, so it seems like something else is modifying the symlink path. Some other apps assume the path where node.exe exists is the authoritative source (i.e. they don't account for version managers).

Anyhow, to fix this, you just need to remove `d:\nodejs` and re-run `nvm use <whatever_Version_you_want>`. That should put NVM4W back into a working state. However; this could happen again if there is another app that tries to modify the symlink path.
