### ISSUE TITLE
Make `nvm install` automatically use the installed version

### ISSUE THREAD

**Issue by jazelly** [coreybutler/nvm-windows#1148]
### Description of the new feature / enhancement

This will be consistent with the `nvm-sh/nvm`, which automatically uses the installed version. NVM4W does not do this automatically atm but gives a suggestion to `nvm use x.x.x`.

### Scenario when this would be used?

 For developers jumping across platforms, this is a subtle difference to notice/remember. One could do `nvm install` and get going with it, but didn't even realize it was pointing to the old version.

### Supporting information

Output of nvm on WSL
```
Downloading and installing node v20.13.0...
Downloading https://nodejs.org/dist/v20.13.0/node-v20.13.0-linux-x64.tar.xz...
################################################################################################################# 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v20.13.0 (npm v10.5.2)
```

Output of nvm on Windows
```
Downloading node.js version 20.13.0 (64-bit)... 
Extracting node and npm...
Complete
npm v10.5.2 installed successfully.


Installation complete. If you want to use this version, type

nvm use 20.13.0
```

**Comment by saraboosh79** [comment]
I give my permission to make a withdrawal
