### ISSUE TITLE
Unable to install LTS versions of Node

### ISSUE THREAD

**Issue by JamesBewley** [coreybutler/nvm-windows#115]
PS C:\Windows\system32> nvm list available

Showing the 15 latest available releases.

      STABLE   |    UNSTABLE
   ---------------------------
       v4.2.2  |    v0.11.16
       v4.2.1  |    v0.11.15
       v4.2.0  |    v0.11.14
      v0.12.7  |    v0.11.13
      v0.12.6  |    v0.11.12
      v0.12.5  |    v0.11.11
      v0.12.4  |    v0.11.10
      v0.12.3  |     v0.11.9
      v0.12.2  |     v0.11.8
      v0.12.1  |     v0.11.7
      v0.12.0  |     v0.11.6
     v0.10.40  |     v0.11.5
     v0.10.39  |     v0.11.4
     v0.10.38  |     v0.11.3
     v0.10.37  |     v0.11.2

For a complete list, visit http://coreybutler.github.io/nodedistro
PS C:\Windows\system32> nvm install 4.2.2
Node.js v4.2.2 64bit isn't available right now.
Could not download node.js v4.2.2 64-bit executable.

**Comment by JamesBewley** [comment]
It's nothing to do with the proxy.  it just doesn't know the current structure for the LTS version.

latest-argon/

**Comment by coreybutler** [comment]
Pretty sure the recent updates to nodedistro resolved this. If it's still an issue, please reopen.
