### ISSUE TITLE
[Feature]: Manually specifying a custom location of Node.js installation - Visual Studio 2022

### ISSUE THREAD

**Issue by afonsoft** [coreybutler/nvm-windows#1151]
### Description of the new feature / enhancement

[Feature]: Manually specifying a custom location of Node.js installation - Visual Studio 2022

![image](https://github.com/coreybutler/nvm-windows/assets/11299396/06eceb67-d073-4f46-9782-4f45440cdc40)

You can also set the environment variable SONAR_NODEJS_PATH to specify a custom location. The value should be the full file path to the node executable e.g. c:\custom\node.exe. The environment variable takes precedence over the automatic detection. You will need to restart Visual Studio after setting or changing the environment variable.

I Need do set a variable SONAR_NODEJS_PATH  on change a node version.

### Scenario when this would be used?

Error on Visual Studio 2022 for SonarLint becouse not found a node version in variable.

**Comment by coreybutler** [comment]
It seems like you just need to set `SONAR_NODEJS_PATH` to the value of `NVM_SYMLINK`. I don't see how this is an NVM4W feature.

**Comment by afonsoft** [comment]
True, but is there no way to make this setting automatic? Have you already put this option in the system variables?

SET SONAR_NODEJS_PATH=%NVM_SYMLINK% or something like that.

**Comment by coreybutler** [comment]
What you have in your screenshot should work, because `NVM_SYMLINK` is registered when NVM4W is installed. Setting `SONAR_NODEJS_PATH` is the responsibility of Visual Studio or the user.
