### ISSUE TITLE
i have been seeing the nv issue and it was taking too log to resolve and making the package completey rely on the code/project.

### ISSUE THREAD

**Issue by rohitkrishna03** [coreybutler/nvm-windows#1159]
### Description of the new feature / enhancement

just include the node and nvm in the same package while installing the node.js, i have been facing the issue since long back.
sometimes I ned to re-install the older version of the node.js , which is also becoming more load on the actual work.

### Scenario when this would be used?

nvm : The term 'nvm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ nvm install 16

**Comment by coreybutler** [comment]
Please provide the output of `nvm debug`.

**Comment by rohitkrishna03** [comment]
Hey corey, yesterday i have addressed an issue related to nvm and node.js,
but still i have faced the issue till today morning. I dont know what
happened but when i seen it now and used the command nvm -debug  the issue
has been resolved.

May i know what is the reason for that?

Thanks and Regards,
Rohit.

**Comment by rohitkrishna03** [comment]
Ok, thanks for the update.
