### ISSUE TITLE
[Issue]: Error 404 installing 'latest' node version

### ISSUE THREAD

**Issue by jorgelloret** [coreybutler/nvm-windows#1164]
### What happened?

I can't install the latest version of node via `nvm install lastest`

It throws:

```
Error retrieving "https://nodejs.org/dist/latest-lastest/SHASUMS256.txt": HTTP Status 404
```

If I access the URL through a browser, I get a 404 error.

### What did you expect to happen?

Install the latest version

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

Other Non-English

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.
Error getting console handle: La operación se completó correctamente.
Windows Version: 10.0 (Build 20348)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\Administrador\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\Administrador\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\Administrador\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\Administrador\AppData\Roaming\nvm

Total Node.js Versions: 2
Active Node.js Version: v22.6.0

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
I can confirm this is a bug.

Note to self: The `latest` version is being handled literally instead of converting to the latest version or dropping the version. Notice the link is `https://nodejs.org/dist/latest-lastest/SHASUMS256.txt` when it should be `https://nodejs.org/dist/latest/SHASUMS256.txt` or `https://nodejs.org/dist/latest-v22.x/SHASUMS256.txt`.

**Comment by frenchcai** [comment]
yes, i have same problem ，how can i do？

**Comment by jorgelloret** [comment]
> yes, i have same problem ，how can i do？

https://github.com/coreybutler/nvm-windows/issues/1164#issuecomment-2284158568

**Comment by wsobolewski** [comment]
> ### What happened?
> 
> I can't install the latest version of node via `nvm install lastest`
> 
> It throws:
> 
> ```
> Error retrieving "https://nodejs.org/dist/latest-lastest/SHASUMS256.txt": HTTP Status 404
> ```

I think there's a typo, it should be `nvm install latest`

**Comment by Tejas-Sharma-dev** [comment]
Yes, Indeed its typo mistake, the command worked without any error

![image](https://github.com/user-attachments/assets/ed7f1753-e82f-42d3-95af-6bfd0c1a9709)

**Comment by jorgelloret** [comment]
I close the issue.

Thanks, @wsobolewski & @Tejas-Sharma-dev 😅
