### ISSUE TITLE
[Issue]: Using commands such as nvm after installation has no effect and no error is reported

### ISSUE THREAD

**Issue by lzk66688** [coreybutler/nvm-windows#1168]
### What happened?

Using commands such as nvm after installation has no effect and no error is reported，nor is using other versions

### What did you expect to happen?

Using commands such as nvm after installation has no effect and no error is reported，nor is using other versions

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

None

### User Permissions?

I don't know (Default)

### Is Developer Mode enabled?

None

### Debug Output

```Shell
，，
```

**Comment by coreybutler** [comment]
There's not enough info to do anything with this. Can you post the output of `nvm debug`? It's also important to know which installation method you used (official installer, manual, third party like winget, etc).
