### ISSUE TITLE
[Issue]: NVM fails to identify powershell as terminal

### ISSUE THREAD

**Issue by kmartinez5555** [coreybutler/nvm-windows#1169]
### What happened?

I am installing NVM For Windows through Puppet. Importantly the actual package install for NVM goes smoothly including taking over management of current nodejs installation. The issue comes when through Puppet I enact the 'nvm install ${verion}' command. It will pop up with the notification that NVM should be run from a terminal. This is abnormal so far as Puppet is configured to be able to run installers/commands/actions through various command line interfaces. This is the Puppet code that I am running:
```
exec { "Install Node.js v${version}":
      provider => powershell,
      unless   => "if (test-path '${install_path}\\v${version}') {exit 0} else {exit 1}",
      command  => "nvm install ${version}",
      require  => Package['NVM for Windows 1.1.12'],
}
```
To abbreviate the code, the 'unless' is a check/trigger to allow the 'command' to run. This passes as expected with current/not-installed versions of nodejs. In addition the 'unless' is also passed through powershell which will return the data as expected. When the 'command' runs the 'nvm install ${version}' it seems to fail the isTerminal() check in GO. I wrote a test using the code from the source that looks like this:
```
package main

import (
      "fmt"
      "os"
)

func main() {
      if !isTerminal() {
            fmt.Println("Failed isTerminal")
      }

}

func isTerminal() bool {
      fileInfo, err := os.Stdout.Stat()
      if err != nil {
            fmt.Println("false-1", err)
            return false
      }
      fmt.Println("True-1", fileInfo.Mode())
      fmt.Println("True-2", os.ModeCharDevice)
      return true
}
```
To test this to see if it is getting any oddities I still ran it through Puppet like so:
```
 exec { 'go test':
    provider => powershell,
    command  => '$output = go run C://Users//kmartinez1x//Documents//go_test//test.go; $output | Out-File -FilePath "C://Users//kmartinez1x//Documents//output.txt"',
 }
 ```
This test should simulate Puppet running a process through powershell that is calling the GO function. I get the following output:
 ```
True-1 prw-rw-rw-
True-2 c---------
```
So it seems to pass the process through using go on command line but not within the compiled nvm.exe for some reason. I can confirm that when running the `(Get-Host).Name` command (a similar check for confirming in powershell) through the same process it returns `RubyPwshPSHost`. I am uncertain though if there is something here in NVM that is just getting some wires crossed or if Puppet itself is the issue with the abstraction layer.

### What did you expect to happen?

Running the 'nvm install ${version}' through powershell manually does work. It should operate just the same through Puppet as all other functions are performed.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

None

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Debug Output

```Shell
No output available
```

**Comment by coreybutler** [comment]
There is already a plan to revert the change that looks at the terminal (as well as some PRs). In the meantime, use 1.1.11, which doesn't have this.
