### ISSUE TITLE
[Issue]: Using nvm installer is deleting the folder i tell nodejs symlink to download to.

### ISSUE THREAD

**Issue by Brett-Clifford** [coreybutler/nvm-windows#1171]
### What happened?

when running the installer for nvm, where ever i tell nodejs symlink to go, it doesnt go there. It actually deletes the folder it was told to go into.

i tested this on my laptop and it worked fine.

### What did you expect to happen?

to install it properly

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

### Relevant log/console output

```Shell
-
```

### Debug Output

```Shell
-
```

### Anything else?

sorry I'm new to coding so its probably an error on my part. I will say that i did have nvm and nodejs installed on my pc before and it was working fine.

**Comment by NIHANCHU** [comment]
Because you haven't downloaded and used any Node version yet, try downloading a version and then using it.After that, the folder will appear.
For example，enter the following code in cmd
`nvm install 16.14.2`
`nvm use 16.14.2`

**Comment by coreybutler** [comment]
This is expected. Symlink directories cannot exist before they are created. In other words, if you configure NVM4W to use `C:\Program Files\nodejs` as your symlink, but the physical directory already exits, it will fail. The NVM4W symlink should be the target directory where _you want NVM4W to CREATE the symlink_. 

@NIHANCHU is correct. Once you `nvm use` a version, it auto-creates the symlkink.
