### ISSUE TITLE
[Feature]: Replace NVM_SYMBOLINK  if in user env variable

### ISSUE THREAD

**Issue by jeremygblake** [coreybutler/nvm-windows#1173]
### Description of the new feature / enhancement

When setting up the user env you can have the paths added to the user env variables using the supplied vbs scripts. 

Though then when running the 'nvm use' command it seems like we are elevating even though NVM_SYMBOLINK is in the user env path.

### Scenario when this would be used?

Running nvm without administrator privilege

**Comment by coreybutler** [comment]
Simply having the `NVM_SYMLINK` variable in the user `PATH` will not allow you to run without administrative privileges. Admin and/or elevated privileges are required to _change_ the symlink target. That's what happens every time you run `nvm use ....`. This is a core Windows requirement.
