### ISSUE TITLE
[Issue]: nvm use doesn't work

### ISSUE THREAD

**Issue by thany** [coreybutler/nvm-windows#1176]
### What happened?

I had Node.js 20.13 installed prior to this.

1. Install NVM and let it take control of my existing Node.js
2. Went into command prompt and did
    * `nvm install 11.15.0`
    * `nvm use 11.15.0`

After that, any attempt to run npm results in "This app can't run on your PC".

Turns out, `nvm current` shows that no current Node.js version is active.

To clarify:

```
C:\>nvm use 11.15.0
Now using node v11.15.0 (64-bit)

C:\>nvm current
No current version. Run 'nvm use x.x.x' to set a version.
```

So this leads me to believe `nvm use` is broken. Or `nvm install` didn't do its job properly, although it finished without errors or complaints.

### What did you expect to happen?

Either an error that clearly states what the hecko is going on if something got broke, or better yet, just a working Node.js/NPM environment.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Non-Elevated

### Is Developer Mode enabled?

Yes

### Debug Output

```Shell
Windows Version: 10.0 (Build 19045)

NVM4W Version:      1.1.12
NVM4W Path:         C:\Users\marty\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\marty\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\marty\AppData\Roaming\nvm
NVM_SYMLINK:        C:\Program Files\nodejs
Node Installations: C:\Users\marty\AppData\Roaming\nvm

Total Node.js Versions: 2
Active Node.js Version: none
(run "nvm use <version>" to activate a version)

PROBLEMS DETECTED
-----------------
"Administrator: C:\WINDOWS\system32\cmd.exe - nvm  debug" is not an officially supported shell. Some features may not work as expected.



Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

What's that about an unsupported shell? It comes by default with Windows - there's not an awful lot I can change there...

**Comment by thany** [comment]
```
nvm uninstall 11.15.0
nvm install 11.15.0
nvm use 11.15.0
```

This "fixed" it. But why?

Do I have to install-uninstall-install every Node.js version I might need in the future? I wonder if this is the intended workflow. If it is, please consider fixing this so that people don't have to install a version twice.

**Comment by thany** [comment]
Okay, fair enough. Thanks for your explanation.

I forgot to mention that in a non-admin cmd, it requests access through UAC twice in quick succession. Perhaps that has something to do with it, maybe it's a built-in retry mechanism or something.

**Comment by coreybutler** [comment]
@thany - NVM4W will initiate the UAC prompts whenever possible (the alternative is silent failure). If developer mode is enabled _and_ the user account has permission to create symlinks in the directory, the prompts won't usually show up. However; if the `NVM_SYMLINK` points to a protected directory (like `C:\Program Files`), the prompts will return for non-admin accounts... once to allow the action on the directory and the other to physically create the link.

This is annoying, but it's part of Windows built-in security. In a nutshell, NVM4W attempts to run your command, but if it fails for permission reasons, it attempts to run with elevated rights, triggering the UAC prompts.

The challenge I face in developing this program is finding an appropriate balance between ease of use and not circumventing native protections that exist for valid reasons. Some users have made workarounds with scripts to bypass the UAC prompts entirely, so there are ways if you really want to do this now. The aforementioned Runtime app has a new approach that I believe offers the best of both worlds without resorting to workaround scripts.
