### ISSUE TITLE
[Issue]: The nvm use command cannot be used

### ISSUE THREAD

**Issue by xfeng-github** [coreybutler/nvm-windows#1185]
### What happened?

The nvm use command cannot be used
![image](https://github.com/user-attachments/assets/2f767eee-2049-4fbc-a642-aee8276483c0)

### What did you expect to happen?

- [ ] 

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

None

### User Permissions?

I don't know (Default)

### Is Developer Mode enabled?

None

### Debug Output

```Shell
Windows Version: 10.0 (Build 19045)

Windows Developer Mode: UNKNOWN (user cannot read registry)

NVM4W Version:      1.1.12
NVM4W Path:         D:\Program Files\nvm\nvm.exe
NVM4W Settings:     \settings.txt
NVM_HOME:
NVM_SYMLINK:        .
Node Installations: .

Total Node.js Versions: 1
Active Node.js Version: none
(run "nvm use <version>" to activate a version)

IPv6 is enabled. This can slow downloads significantly.
If you are experiencing npm problems, check the npm mirror (https://npmmirror.com/mirrors/npm/) to assure it is online and accessible.

PROBLEMS DETECTED
-----------------
"C:\Windows\System32\cmd.exe - nvm  debug" is not an officially supported shell. Some features may not work as expected.


The NVM4W symlink (.) was not found in the PATH environment variable.

NVM_SYMLINK (.) is not a valid symlink.

The following Node installations are invalid (missing node.exe): v18.3.0 - consider reinstalling these versions


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Something is very wrong with your installation. `NVM4W Settings`, `NVM_HOME`, `NVM_SYMLINK`, and `Node Installations` should all have absolute paths. Your debug output should look similar to this:

![image](https://github.com/user-attachments/assets/fb5ec0fe-04ee-46d5-bed1-4e61c748297d)

The error you're seeing is because NVM4W doesn't know where to find your Node installations.

I recommend reinstalling NVM4W.

**Comment by xfeng-github** [comment]
Thank you very much. The problem was solved after reinstallation
