### ISSUE TITLE
[Feature]: Combine install and use

### ISSUE THREAD

**Issue by zdm** [coreybutler/nvm-windows#1197]
### Description of the new feature / enhancement

Why install and use commands exists, and exists separately?
Nobody needs to install node without use it.
You force users to type and perform extra commands.
Main usage should be the following:
```
# download (if not cached) and use lts version
nvm lts
```
Also it would be nice to have `prune` command - it will delete all downloaded nodes, except currently installed version.

What do you think?

### Scenario when this would be used?

See above

**Comment by coreybutler** [comment]
Combining `install` and `use` will be part of [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). In other words, `nvm use lts` would install (if needed) before switching to the lts version. There will also be a pruning feature, though it's more nuanced than nuking all versions other than the current one.

Bottom line, both of these are already on the roadmap for the successor tool.
