### ISSUE TITLE
npm corrupt after nvm usage

### ISSUE THREAD

**Issue by 1000i100** [coreybutler/nvm-windows#121]
When i try to use npm, from git-bash or classic cmd.exe, i get this : 

```
module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\Users\myUserName\AppData\Roaming\npm\node_modules\npm
\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by coreybutler** [comment]
Did you run `nvm use x.x.x`?

**Comment by xfh** [comment]
I can confirm this bug with nvm install 0.12.8 and nvm install 0.12.9. Both installs create an empty node_modules folder in the nodejs folder, which results in above error message. 
nvm install 0.12.1 worked fine.

**Comment by shairez** [comment]
Check if you have a c:\program files\nodejs folder already exists, if so, delete it, reinstall nvm and try again

This solved my problems with npm and nvm

**Comment by micha-LEAP** [comment]
I am having the same problem as described here. A fresh install of nvm on Windows 10, followed by a restart. Then using git-bash, `nvm install 4.3.0` runs perfectly. `nvm user 4.3.0` results in a UAC prompt requesting permission for the symlink command to run. I allow it, and the console shows `Now using node v4.3.0 (64-bit)`

I then try npm and get this:
```
$ npm install -g serverless
module.js:328
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

When I look in C:\Program Files\nodejs\node_modules, it is empty. If I go to the AppData\Roaming\nvm folder, I see the folder v.4.3.0 and inside there, the node_modules folder is empty. It looks like npm was not installed correctly.

**Comment by micha-LEAP** [comment]
OK I have got it to work. I watched the disk processes and saw the npm folder is downloaded to `nvm\temp\` then moved. I tried a different version (4.4.2) and saw that npm was moved correctly. So I uninstalled 4.3.0, removed the version folder as instructed, and reinstalled the version. This time it worked correctly. And now npm commands work properly.

**Comment by coreybutler** [comment]
@micha-LEAP Thank you for following up and detailing the process. It's strange that it worked once.

Everything is downloaded to the temp folder to account for cancelled downloads, timeouts, etc... the point being an incomplete download would not be moved and therefore not available. It sounds like that is working for node, but not necessarily for npm. This is on my to-do list now, but I don't know when I'll get to it.

**Comment by drownbes** [comment]
Seems that nvm returned before job is done. For example:
`nvm use 5.3.0 && npm` - not working.
while:
`nvm use 5.3.0 && sleep 5 && npm` - works

**Comment by techiemmk** [comment]
I got this error while installing node v8.15.0. Fixed it by downloading the zip file for the nodejs sit, unzipped it and replace the content in nvm\v8.15.0. It is working fine now.

**Comment by jg572h** [comment]
Has there been any movement on this issue?  I'm having this problem, too.  Was careful to run nvm-windows in an Administrator window.  Still, node_modules is empty.  Using version 1.1.17.  Thanks.

**Comment by Cubelaster** [comment]
Also experiencing the same issue.

**Comment by coreybutler** [comment]
A new download process exists in v 1.1.8+. This should resolve some issues.

For those using `nvm use x.x.x && ....`, please see [the last point in ](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#delayed-changes)
