### ISSUE TITLE
node-gyp 3 can be switched to without requirements

### ISSUE THREAD

**Issue by fresheneesz** [coreybutler/nvm-windows#122]
[node-gyp](https://github.com/nodejs/node-gyp) is packaged alongside `npm` and `node`, but it installs without error or warning when the requirements of node-gyp 3 aren't met. `node-gyp` v3 requires MS Visual Studio 2013, but when I install and/or switch to node v5.1.0 which uses node-gyp v3.0.3, I see no warnings or errors, but doing things like installing `fs-ext` fails with lots of compilation errors.

Can nvm-windows check to make sure dependencies are met when versions are switched between or installed? At very least, a warning would save a lot of people a lot of trouble.

**Comment by coreybutler** [comment]
Module dependency management/checking doesn't really fit in the scope of NVM. The experience would be the same whether or not you use NVM. NVM is just a means of managing which version of Node is installed. Application support is a completely different animal.
