### ISSUE TITLE
Unable to install Adapt CLI on Windows

### ISSUE THREAD

**Issue by AmitGolhar** [coreybutler/nvm-windows#125]
C:\Users\amitg>node -v
v0.10.33

C:\Users\amitg>npm install -g grunt-cli
C:\Users\amitg\AppData\Roaming\npm\grunt -> C:\Users\amitg\AppData\Roaming\npm\n
ode_modules\grunt-cli\bin\grunt
grunt-cli@0.1.13 C:\Users\amitg\AppData\Roaming\npm\node_modules\grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)

C:\Users\amitg>npm install -g adapt-cli
npm ERR! git clone git://github.com/adaptlearning/download.git Cloning into bare
 repository 'C:\Users\amitg\AppData\Roaming\npm-cache\_git-remotes\git-github-co
m-adaptlearning-download-git-2681a17e'...
npm ERR! git clone git://github.com/adaptlearning/download.git fatal: unable to
connect to github.com:
npm ERR! git clone git://github.com/adaptlearning/download.git github.com[0: 192
.30.252.129]: errno=Invalid argument
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\amitg\App
Data\Roaming\npm-cache\_git-remotes\git-github-com-adaptlearning-download-git-26
81a17e'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Invalid argument
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "adapt-cli"
npm ERR! cwd C:\Users\amitg
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

**Comment by coreybutler** [comment]
This isn't a problem with NVM. NVM merely exposes the node and npm commands... it has nothing to do with how they function. Looks like a problem with github, the repo, the network, potentially a proxy, or maybe the version of npm you're using. Keep in mind you can always upgrade npm if that is the culprit, ie. `npm install npm`.

This is what stands out:

```sh
npm ERR! git clone git://github.com/adaptlearning/download.git fatal: unable to
connect to github.com:
npm ERR! git clone git://github.com/adaptlearning/download.git github.com[0: 192
.30.252.129]: errno=Invalid argument
```
