### ISSUE TITLE
Node.js Install (v4.2.4) does not properly install npm on Windows 10

### ISSUE THREAD

**Issue by jennykwan** [coreybutler/nvm-windows#126]
As the title says.

I've tried changing the default `%NVM_HOME%` to `C:\nvm\`. I've also tried running `nvm install 4.2.4 64` as Administrator. No dice.

Seems related to #62.

FWIW, `node_modules/` is empty after Node.js installation. `npm` and `npm.cmd` are there, and both throw the missing `npm_cli.js` error.

**Comment by alyssackwan** [comment]
Oh, this is not #75 because download is fine.

**Comment by coreybutler** [comment]
Which version are you running? Does `nvm list` show 4.2.4?

**Comment by tongzou** [comment]
I have the same problem. I installed node 5.4.1 and 0.12.9, both had empty node_modules. nvm list shows the correct version.

**Comment by alyssackwan** [comment]
Yes, `nvm list` shows the correct version.

**Comment by sullivanpt** [comment]
Probably need a little more information to accurately diagnose the problem you are encountering. For reference, I am running nvm 1.1.0 on Windows 10 and am using it successfully to switch between node 5.4.0, 4.2.4, 4.1.0, 0.12.7, 0.10.4.  

However, I have encountered at least one npm "segmentation fault" on 4.2.4 while running "npm install". In my case deleting the existing node_modules folder and running "npm cache clean; npm install" made the issue go away, but the unexplained seg. fault leaves a troubling bad taste.

My other suggestion from a previous anomaly (I weirdly triggered by reinstalling my git bash shell) is to completely uninstall all traces of nvm, then reinstall it using the installer's default options.

**Comment by alyssackwan** [comment]
I'm using 1.10. `node_modules/` is empty for the handful of Node.js versions I've tried. I can't even invoke `npm` from the command line without it raising the "can't find `npm-cli.js`" error. I've tried uninstalling cleanly and reinstalling several times.

I suspect an error being swallowed by the `nvm install`. Is there a debug flag? I'll try digging into the source code.

**Comment by coreybutler** [comment]
There is no debug flag, but there is a guide for [hacking on NVM](https://github.com/coreybutler/nvm-windows/wiki/Hacking) that might offer some value.

**Comment by santriseus** [comment]
I had similar issue, I was able to fix it when completely uninstall nvm, then choose the root directory paths like C:/nvm and C:/node during the installation.

**Comment by SebastianMetzger** [comment]
I use Windows 10 Pro and also stumbled on this empty "node_modules" folder issue where npm won't work.

The latest version that seems to work and correctly install npm is node v4.2.4
Maybe something changed after this release?

**Comment by deedaralam** [comment]
Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "gulp"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! path /lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/lib'
npm ERR!     at Error (native)
npm ERR!  { Error: EACCES: permission denied, access '/lib'
npm ERR!     at Error (native) errno: -13, code: 'EACCES', syscall: 'access', path: '/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/deedaralam/npm-debug.log

Please slove thiss issue kindly

**Comment by coreybutler** [comment]
@deedaralam - `Darwin 16.0.0` indicates you're running this on a Mac. This is NVM for _Windows_. 

Also, I think the solution is pretty straightforward where it says `Please try running this command again as root/Administrator.`

**Comment by rcollette** [comment]
I'm not able to get NPM to work  after installing either.  I tried setting the directories to c:\nvm and c:\nodejs like others above and I still can't run npm.

I've tried running in an admin window as well thinking that maybe creating symlinks was the issue but that didn't help.

```
C:\Users\rcoll>nvm install v6.3.1
Downloading node.js version 6.3.1 (64-bit)...
Complete
Creating C:\nvm\temp

Downloading npm version 3.10.3... Complete
Installing npm v3.10.3...

Installation complete. If you want to use this version, type

nvm use 6.3.1

C:\Users\rcoll>nvm use 6.3.1
Now using node v6.3.1 (64-bit)

C:\Users\rcoll>npm
module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
 module.js:442
    throw err;
    ^

Error: Cannot find module 'C:\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

C:\Users\rcoll>
```

**Comment by coreybutler** [comment]
closing due to age (cleanup)
