### ISSUE TITLE
Where is the install path?

### ISSUE THREAD

**Issue by justsayno** [coreybutler/nvm-windows#127]
I am having nvm not recoginzed error. I presume its not in my path. What path should I use? I cant find it anywhere...

**Comment by jamesmanning** [comment]
When I last installed it, the install went into %APPDATA%\nvm

If it isn't there, you could use the 'manual install' - it has you tell it where you extracted it to and then sets the 2 env vars and adds it to your path.

https://github.com/coreybutler/nvm-windows/blob/a0ce187f6e21f9c8a69f0f65c5c54668c016b42f/bin/install.cmd#L3-L5

**Comment by coreybutler** [comment]
The install path is determined by the installer. If you used the default, then @jamesmanning is correct... the default is `%APPDATA%\nvm`.

**Comment by justsayno** [comment]
Thanks guys, sorry I should have closed this.
