### ISSUE TITLE
No new line after uninstalling Node (minor issue).

### ISSUE THREAD

**Issue by toomastahves** [coreybutler/nvm-windows#135]
After running 'nvm uninstall v5.3.1' and uninstalling old Node, then there is no new line in console.

In source: https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L272
Currently:

```
fmt.Printf(" done")
```

Looks slightly better, when there is new line after successful uninstalling:

```
fmt.Println(" done")
```

**Comment by coreybutler** [comment]
Closing due to age.
