### ISSUE TITLE
possibility to add target directory for automatic setup

### ISSUE THREAD

**Issue by miira** [coreybutler/nvm-windows#137]
Hello,

is there any possibility to setup target directories for the automatic installation?

I tried to set settings.txt in the current directory of nvm-setup.exe.
I also tried to setup NVM_HOME and NVM_SYMLINK (even NODE_PATH). Through .bat file, for user and for machine (SETX /M ..), I validated that the environment variables are set, but still the setup is not using them.

And in the wizard, I see the default values.

Please let me know, thank you

**Comment by coreybutler** [comment]
This isn't possible in the current installer. The current installer defines these variables, so it will temporarily overwrite anything you set.

**Comment by miira** [comment]
Ok, I see. Would it be possible to add some configuration/command line parameters for the installer, so that we could redefine those values, please? 
What we are trying to achieve is to create semi-automatic installer of our project, that will put everything (nvm win, nodejs, our sw) in one parent folder, so it is easier for later introspections/suport/uninstallation. For that we need to redefine the default values in the installer, so the people, who will be installing it, won't need to change the folders manually (browse) (potential source of mistakes :))
Please, let me know, or if you can point me to the proper direction/source file/lines, I can add it on my own. 
Thank you

**Comment by espoelstra** [comment]
@miira There will be a Chocolatey package wrapping the nvm-nosetup.zip coming soon that will allow you to modify these things in the next version or two of it's life.

I may also see about trying to make a more generic PowerShell script if you can't/won't use Chocolatey to install the zip file and set the various pieces up, but really Chocolatey is an awesome way to go.

**Comment by coreybutler** [comment]
Closing due to age and alternative options (chocolatey).
