### ISSUE TITLE
Not able to install node verisons

### ISSUE THREAD

**Issue by samirprakash** [coreybutler/nvm-windows#144]
Hi, 

Running the below command does not install the required version of node. I am using a 64 bit windows 10 setup.

Proxy configurations are in place using nvm proxy command.

nvm install 0.10.40 64
**_Node.js v0.10.40 is not yet released or available._**

Please let me know if any changes are required.

**Comment by coreybutler** [comment]
This works for me... is your proxy blocking access? Perhaps try it without a proxy? If nvm doesn't get a successful response from the web server, it will display this message.

**Comment by coreybutler** [comment]
Closing due to non-response. If this is still an issue, please let me know so I can re-open it.
