### ISSUE TITLE
After install every command fails with message "C:\Users\%username%\AppData\Roaming\nvm could not be found or does not exist. Exiting."

### ISSUE THREAD

**Issue by bevalorous** [coreybutler/nvm-windows#145]
If `%username%` in path `C:\Users\%username%\AppData\Roaming\nvm contains` some non-latin symbols (in my case username is written with cyrillic characters), every `nvm` command displays this error message, for example:

```
C:\Windows\system32>nvm arch
C:\Users\�����\AppData\Roaming\nvm could not be found or does not exist. Exiting.
System Default: 64-bit.
Currently Configured: 64-bit.
```

Possible solution is to write settings.txt with encoding UTF-8 instead of ANSI. After manual correction of file encoding with Notepad++ error message disappears and now everything works fine:

```
C:\Windows\system32>nvm arch
System Default: 64-bit.
Currently Configured: 64-bit.
```

**Comment by gorillatron** [comment]
The encoding fixed it for me as my name contains "ø".

**Comment by TheZeroNine** [comment]
fixed the issue for me! Thanks! (name contains "ß")

**Comment by Fip3** [comment]
Great! (my name contains " í ") Thanks a lot

**Comment by janjon** [comment]
I changed to UTF-8 after,
```
C:\WINDOWS\system32>nvm arch
**There's a space.﻿ C:\Users\中文\nvm could not be found or does not exist. Exiting.
System Default: 64-bit.
Currently Configured: -bit.
```

**Comment by lnaie** [comment]
this fails: C:\Users\Lucian Naie\AppData\Roaming\nvm

**Comment by espoelstra** [comment]
@lnaie I think there is another issue regarding spaces or whitespace in the user name, please add your voice there.
@janjon Do your NVM_* environment variables have the correct values in them if you do a `gci env:` in a PowerShell window?

**Comment by firrae** [comment]
I think I have the same issue as my account has a period between my first and last names.

**Comment by LizanLycan** [comment]
Problem is maintained with blanks

**Comment by jose-vasquez-mantum** [comment]
Please, solve the problem with blanks in the account name, thanks

**Comment by coreybutler** [comment]
@jose-vasquez-mantum - I would accept a Pull Request if someone fixes it.

**Comment by urbgimtam** [comment]
If anyone is suffering from this, they can:

- type "nvm root" to know where is the nvm current path 
- In windows explorer, copy the contents of the previous path to a simple path like "c:\nvm".
- Then type "nvm root [new path]" (like "nvm root c:\nvm").

Everything should work without problems.

On a side note, I would like to help, but I don't know Go, so...

**Comment by klreeher** [comment]
I also have a space in my Windows User folder, and @urbgimtam's work around worked for me.

**Comment by Bekhx** [comment]
> If `%username%` in path `C:\Users\%username%\AppData\Roaming\nvm contains` some non-latin symbols (in my case username is written with cyrillic characters), every `nvm` command displays this error message, for example:
> 
> ```
> C:\Windows\system32>nvm arch
> C:\Users\�����\AppData\Roaming\nvm could not be found or does not exist. Exiting.
> System Default: 64-bit.
> Currently Configured: 64-bit.
> ```
> 
> Possible solution is to write settings.txt with encoding UTF-8 instead of ANSI. After manual correction of file encoding with Notepad++ error message disappears and now everything works fine:
> 
> ```
> C:\Windows\system32>nvm arch
> System Default: 64-bit.
> Currently Configured: 64-bit.
> ```

Thanks a lot, this solution helped me!

**Comment by juliavaz** [comment]
This [https://github.com/coreybutler/nvm-windows/issues/334](https://github.com/coreybutler/nvm-windows/issues/334) was very useful to me, where does it say to run on terminal `nvm root C:\Users\username\AppData\Roaming\nvm`

**Comment by coreybutler** [comment]
encodings and white space are now supported in path names as of v1.1.8.

**Comment by JoaoVitorLima242** [comment]
> If anyone is suffering from this, here's a suggestion:
> 
> * type "nvm root" to know where is the nvm current path
> * In windows explorer, copy the contents of the previous path to a simpler path like "c:\nvm".
> * In system variables, search for NVM_HOME and update its value to the new path.
> * Then type "nvm root [new path]" (like "nvm root c:\nvm").
>   (don't forget to close cmd, and open a new one.)
> 
> Everything should work without problems.
> 
> On a side note, I would like to help, but I don't know Go, so...

Thanks man! This really help me!

**Comment by LesyaSvk** [comment]
Nothing works( 
At instuction to nvm is line - "If NVM4W doesn't appear to work immediately after installation, restart the terminal/powershell (not the whole computer)." BUT computer restar really help me. Everything works without any problem

**Comment by AlibekMussin** [comment]
Why the heck this it trouble till this day already? UTF-8 sooooo long existing.

**Comment by maxbond2** [comment]
2023! Encoding bug still don't fixed!... 
@bevalorous Thank you very much for solution!!!

**Comment by wcaroman** [comment]
Thank you very much, you are my savior! Hate russian win versions, always make a lot of issues
