### ISSUE TITLE
nvm-windows v1.1.0 doesn't change between node.js versions

### ISSUE THREAD

**Issue by arberpolis** [coreybutler/nvm-windows#147]
Hi,
I would like to report a problem related to nvm use <version> <arch> on windows 10 64-bit. It goes like this:

nvm list > I get the list of all node.js versions installed on my machine where the version in use is let's say 5.5.0
nvm use 4.2.6 64 > Gives me the following message: Now using node v4.2.6 (64-bit)

however when i do:
nvm list > I still get version 5.5.0 marked as currently in use with bullet point.

Also node --version gives me 5.5.0

Any idea where the bug is?
Thanks for you support.

**Comment by arberpolis** [comment]
Never mind. I resolved the issue by completely uninstalling the nodejs distribution for windows. I then recreated a nodejs directory in the Programs Folder and the symlink works fine.

Thanks for the good job.

**Comment by fultonm** [comment]
Same problem. I get 
PS G:\w> nvm use 5.6.0
exit status 1: 'G:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by coreybutler** [comment]
@fultonm - Did you also have a version of node previously installed? If so, which version of node, which version of Windows?

**Comment by fultonm** [comment]
@coreybutler No versions of Node installed at the time I ran the installer. Installing nvm to G:\nvm and Node to G:\Program Files\Node.js worked.
This could be due to Admin permissions as I had seen on previous answers, but it also feels like it's because there is a space between Program and Files, due to PowerShell trying to run some command and not returning anything after the space.

**Comment by coreybutler** [comment]
I'm not sure why Powershell isn't recognizing the spaces on your system, but I have taken a lot of precautions for escaping paths in the new version I'm working one. So, I'll close this since it seems like everybody on this thread got it working.
