### ISSUE TITLE
got trouble in windows 10 after installation 

### ISSUE THREAD

**Issue by vasuvanka** [coreybutler/nvm-windows#150]
ERROR open \settings.txt: The system cannot find the file specified.

got an error like this..help me out ..

**Comment by ishigami** [comment]
Hi vasuvanka,

At the first time, execute your prompt as Administrator and run 

`nvm .`

Then, you can use nvm (even if you aren't using prompt as Administrator).

**Comment by vasuvanka** [comment]
thank you..issue solved..

**Comment by raztus** [comment]
No go for me here from cmd.exe as Admin :(

```
C:\apps\nvm-noinstall>nvm.exe .

ERROR open \settings.txt: The system cannot find the file specified.
```
