### ISSUE TITLE
nvm install path with spaces throws error

### ISSUE THREAD

**Issue by ractoon** [coreybutler/nvm-windows#154]
### My Environment

Windows 10

### Steps to reproduce the problem:

If the install path includes spaces such as:

`C:\Program Files\nodejs`

It throws an error when setting the npm version to use that the file could not be found and outputs the path up to the space, in this case it would output the error with a reference to:

`C:\Program`

**Comment by dmillerme7** [comment]
See the last comment in issue #84. Uninstall nvm and reinstall in a directory with any spaces in the name. Something like C:\otherPrograms or C:\nvm

**Comment by coreybutler** [comment]
See #41

**Comment by IMTanuki** [comment]
With all due respect - if nvm doesn't work in a dir with spaces, the install should catch that. If I'm correct, the nvm uninstall will also uninstall nodejs and all -g packages.
