### ISSUE TITLE
npm version isn't latest available for given node version

### ISSUE THREAD

**Issue by djsylvester** [coreybutler/nvm-windows#157]
### My Environment

- [x ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

nvm install 4.4.0 64 - should install npm v2.14.22 (latest release)
nvm install 5.8.0 64 - should install npm v3.8.1 (latest release)

### Actual Behavior

For node v4.4.0, npm v2.14.20 is installed
For node v5.8.0, npm v3.7.3 is installed

### Steps to reproduce the problem:

See expected behavior
I checked the nodeversion.json file https://raw.githubusercontent.com/coreybutler/nodedistro/master/nodeversions.json
and it seems to be out of date, installing versions listed under "actual behavior".

**Comment by coreybutler** [comment]
Thanks for reporting. It should be fixed now. 

For future reference, issues with the nodeversions.json file should be filed in the [nodedistro](https://github.com/coreybutler/nodedistro) repo.... at least until I get around to using the new sources straight from the node release API.
