### ISSUE TITLE
Current? What happened to Stable? (v6.0.0)

### ISSUE THREAD

**Issue by vellotis** [coreybutler/nvm-windows#164]
Node has changed its version labeling. v6.0.0 is in https://raw.githubusercontent.com/coreybutler/nodedistro/master/nodeversions.json but only under `all` json key. It is not under `stable` or `unstable` json keys. This means it is installable, but it is not showed as an available version.

Referenced from https://nodejs.org/en/blog/release/v6.0.0/

> ### Current? What happened to Stable?
> You may have noticed that the v6 release uses the label `Current` instead of Stable. This name change has been made in order to better differentiate the Long Term Support releases from the `current` active development branches. We will be using the `Current` label from here-on instead of Stable.

### Expected Behavior

Following is just a suggestion. As `nodeversions.json` is handled by you, @coreybutler, maybe you want to list it as stable instead of putting it in `all`?

```bash
> nvm list available

Showing the 15 latest available releases.

   CURRENT: v6.0.0

      STABLE   |    UNSTABLE
   ---------------------------
      v5.10.1  |     v5.11.0
      v5.10.0  |      v5.9.1
       v5.8.0  |      v5.9.0
       v4.4.3  |      v5.7.1
       v4.4.2  |      v5.7.0
       v4.4.1  |    v0.11.16
       v4.4.0  |    v0.11.15
       v4.3.2  |    v0.11.14
       v4.3.1  |    v0.11.13
       v4.3.0  |    v0.11.12
       v4.2.6  |    v0.11.11
       v4.2.5  |    v0.11.10
       v4.2.4  |     v0.11.9
       v4.2.3  |     v0.11.8
       v4.2.2  |     v0.11.7
```

### Actual Behavior

```bash
> nvm list available

Showing the 15 latest available releases.

      STABLE   |    UNSTABLE
   ---------------------------
      v5.10.1  |     v5.11.0
      v5.10.0  |      v5.9.1
       v5.8.0  |      v5.9.0
       v4.4.3  |      v5.7.1
       v4.4.2  |      v5.7.0
       v4.4.1  |    v0.11.16
       v4.4.0  |    v0.11.15
       v4.3.2  |    v0.11.14
       v4.3.1  |    v0.11.13
       v4.3.0  |    v0.11.12
       v4.2.6  |    v0.11.11
       v4.2.5  |    v0.11.10
       v4.2.4  |     v0.11.9
       v4.2.3  |     v0.11.8
       v4.2.2  |     v0.11.7
```

**Comment by coreybutler** [comment]
Moved to https://github.com/coreybutler/nodedistro/issues/24.

**Comment by fritx** [comment]
![image](https://cloud.githubusercontent.com/assets/6647633/15316736/e7e5b7b2-1c50-11e6-8ebe-2b341cb2d433.png)

**Comment by coreybutler** [comment]
@fritx One of the PR's on [nodedistro](https://github.com/coreybutler/nodedistro) removed v6 and I didn't catch it in time. I just added it back, so this should go away.
