### ISSUE TITLE
Download URL incorrect for 4.4.x

### ISSUE THREAD

**Issue by tohagan** [coreybutler/nvm-windows#178]
### My Environment

- [X] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

When performing nvm install 4.4.3, it should down and create a new `node.exe` executable and associated files under `c:\nvm\4.4.2`

### Actual Behavior for Node 4.4.x

Creates a single node.exe file containing HTML :) that reports 404 file not found. So I'm assuming that (1) download path is invalid and (2) that 404 error testing logic is incorrect when the download takes place.  

Reports the following during download  ...

The `node.exe` file contains the following:

```
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### Steps to reproduce the problem:

```
> nvm install 4.4.3 32
Downloading node.js version 4.4.3 (32-bit)... Download failed. Rolling Back.
Rollback failed. remove C:\nvm\v4.4.3\node32.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v4.4.3 32-bit executable.
```

settings.txt file contains:

```
root: C:\nvm
path: C:\nodejs
```

Installs of earlier versions (tested 0.10.2) works fine.

**Comment by coreybutler** [comment]
I've just released version 1.1.1. Can you try that and see if you still have this issue?

**Comment by coreybutler** [comment]
I just noticed something..... you mentioned the following:

"When performing nvm install **4.4.3**, it should down and create a new node.exe executable and associated files under c:\nvm\\**4.4.2**"

I assume that was a typo?

**Comment by tohagan** [comment]
**down** should be **download**.   Was that the typo?

**Comment by coreybutler** [comment]
@tohagan - Any luck with the new release?

**Comment by tohagan** [comment]
Yes!  Download and install now works fine!  It also upgraded `npm` smoothly.

However I did find one additional issue (should probably be tracked as a new issue).
`nvm install 4.4.3 32`  told me at the end that I should run `nvm use 4.4.3` which is incorrect. 
It should say `nvm use 4.4.3 32`.

Here's the log ...

```
$ nvm install 4.4.3 32
Downloading node.js version 4.4.3 (32-bit)... Complete
Creating C:\nvm\temp

Downloading npm version 2.15.1... Complete
Installing npm v2.15.1...

Installation complete. If you want to use this version, type

nvm use 4.4.3

$ nvm use 4.4.3
node v4.4.3 (64-bit) is not installed.

$ node -v
v4.3.2

$ nvm use 4.4.3 32
Now using node v4.4.3 (32-bit)

$ node -v
v4.4.3
```

**Comment by coreybutler** [comment]
@tohagan - I'm glad the download worked for you this time. I'm closing this in favor of the new issue regarding the bit operator.
