### ISSUE TITLE
Node version 6 not listed

### ISSUE THREAD

**Issue by SteveALee** [coreybutler/nvm-windows#179]
I thought that someone recently fixed the script to better get versions but i find ```nvm list available``` does not show 6.x.x. at all

**Comment by coreybutler** [comment]
Strange - it did exist. There were several PR's recently on nodedistro, but I thought we were current. In looking at the list, 6.x.x was listed in "all", but not in "stable". I added it there, so it should show up now. Let me know if it doesn't.

**Comment by SteveALee** [comment]
all good. Thanks!

**Comment by uharbachou01** [comment]
Hi,
just have the same issue
i have installed fresh env and the latest version of the nvm
`
nvm list available
`
write me next
`
|   CURRENT    |     LTS      |  OLD STABLE  | OLD UNSTABLE |
|--------------|--------------|--------------|--------------|
|    6.8.1     |    6.9.1     |   0.12.17    |   0.11.16    |
|    6.8.0     |    6.9.0     |   0.12.16    |   0.11.15    |
|    6.7.0     |    4.6.2     |   0.12.15    |   0.11.14    |
|    6.6.0     |    4.6.1     |   0.12.14    |   0.11.13    |
|    6.5.0     |    4.6.0     |   0.12.13    |   0.11.12    |
|    6.4.0     |    4.5.0     |   0.12.12    |   0.11.11    |
|    6.3.1     |    4.4.7     |   0.12.11    |   0.11.10    |
|    6.3.0     |    4.4.6     |   0.12.10    |    0.11.9    |
|    6.2.2     |    4.4.5     |    0.12.9    |    0.11.8    |
|    6.2.1     |    4.4.4     |    0.12.8    |    0.11.7    |
|    6.2.0     |    4.4.3     |    0.12.7    |    0.11.6    |
|    6.1.0     |    4.4.2     |    0.12.6    |    0.11.5    |
|    6.0.0     |    4.4.1     |    0.12.5    |    0.11.4    |
|    4.1.2     |    4.4.0     |    0.12.4    |    0.11.3    |
|    4.1.1     |    4.3.2     |    0.12.3    |    0.11.2    |
|    4.1.0     |    4.3.1     |    0.12.2    |    0.11.1    |
|    4.0.0     |    4.3.0     |    0.12.1    |    0.11.0    |
|              |    4.2.6     |    0.12.0    |    0.9.12    |
|              |    4.2.5     |   0.10.48    |    0.9.11    |
|              |    4.2.4     |   0.10.47    |    0.9.10    |

`
right now 7.2.0 is latest node version BUT 
`
nvm install 7.2.0 
`
installed me this version successfully.
Thank you.

**Comment by coreybutler** [comment]
This looks to be a bug in how stable versions are determined.

Note to self: See https://github.com/coreybutler/nvm-windows/blob/master/src/nvm/node/node.go#L145
