### ISSUE TITLE
node is not available win32 application!

### ISSUE THREAD

**Issue by mrdulin** [coreybutler/nvm-windows#181]
![image](https://cloud.githubusercontent.com/assets/17866683/16545792/0a6103b4-4168-11e6-943a-508d30377cd7.png)

![image](https://cloud.githubusercontent.com/assets/17866683/16545793/15d892fc-4168-11e6-8e19-aa0ac7e93106.png)

![image](https://cloud.githubusercontent.com/assets/17866683/16545795/1f453458-4168-11e6-867d-32621a753c47.png)

![image](https://cloud.githubusercontent.com/assets/17866683/16545803/63296fb8-4168-11e6-9fc2-240a99260a94.png)

And, the `npm` was not installed~

Thanks~

**Comment by coreybutler** [comment]
You have to install the 32 bit version explicitly on 64-bit operating systems.

![image](https://cloud.githubusercontent.com/assets/770982/16546238/8661cd9a-4109-11e6-97f8-a0f9121ba787.png)

If npm was not installed, there was probably a network problem. I suggest using a mirror.

**Comment by mrdulin** [comment]
@coreybutler 

You said I had installed 32-bit version.
But why the bash give me this message?
```bash
Now using node v4.4.4 (64-bit)
```

the `64-bit`?
