### ISSUE TITLE
Trojan.Win32.Ebowla.il

### ISSUE THREAD

**Issue by osher** [coreybutler/nvm-windows#182]
Day after installing nvm using the msi installer - I got the attached virus alert, which I though you might want to know about:
![Trojan.Win32.Ebowla.il](https://cloud.githubusercontent.com/assets/803101/16615159/50bf8652-437d-11e6-9ce2-48331208bc03.jpg)

### My Environment
- [X] Windows 10

### I have already...
- [ X] read the README to be aware of npm gotchas & antivirus issues.
- [ X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):
- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior
After installing - I expect no viruses with any reference to nvm

### Actual Behavior

See photo:
![Trojan.Win32.Ebowla.il](https://cloud.githubusercontent.com/assets/803101/16615159/50bf8652-437d-11e6-9ce2-48331208bc03.jpg)

### Steps to reproduce the problem:

Just FYI

**Comment by coreybutler** [comment]
Thanks for reporting this, though I'm kind of stumped on what in nvm4w could trigger this. Was this with the latest v1.1.1?

**Comment by coreybutler** [comment]
This appears to be a false positive. See https://github.com/golang/go/issues/16292 for detail. There isn't much I can do about this since it appears Kaspersky is specifically looking for Go signatures. I suspect many other Go apps will have this same false positive. 

For anyone coming across this issue with Symantec products, please see issue #133.

Closing, since there is nothing I can do about this until Go fixes it.

**Comment by szarouski** [comment]
Hi, I also get an alert from Malwarebytes for version 1.1.1. I didn't have that issue with 1.0.6.

![image](https://cloud.githubusercontent.com/assets/911388/17057718/e33ced12-4fe9-11e6-958a-47aa96bfa6d1.png)

**Comment by Offirmo** [comment]
Windows Defender as well

![screen_20160724-23h25_24001](https://cloud.githubusercontent.com/assets/603503/17086568/30eb7f52-51f6-11e6-8360-1321ba7b84cf.png)

**Comment by sawilde** [comment]
Some multi-scan analysis

nvm-setup.exe

https://www.virustotal.com/en/file/04f1488a7074b12a7809834798e6d726e1c72d982f8277f4650744780fa5fe3c/analysis/1469399604/

nvm.exe

https://www.virustotal.com/en/file/b194e2ebb14b5694dbabb88d9beb3a366aa4e1b3767586ae7a6cbae994160978/analysis/1469399770/

To deal with this you'll need to submit it to each vendor as to why you think it is a false positive.

**Comment by coreybutler** [comment]
@sawilde - very helpful, thanks for your comments.

**Comment by coreybutler** [comment]
To all: @sawilde is correct, each vendor needs to be contacted in regards to the false positive. The folks behind Go (i.e. Google) are in the process of doing this, but there is no ETA. I've looked into doing it specifically for NVM4W. There are alot of requirements around having a registered company, a website, and a bunch of other validation processes (depending on the vendor). I have a company, and I'll be obtaining signing certificates for my other project ([Fenix](https://github.com/coreybutler/fenix)) that I believe can be used in this scenario. It's something of an ordeal though, so I cannot promise anything at the moment.

Depending on how complex this ultimately ends up being, I may consider switching to Java. I'd like to wait a little bit because I really don't want to switch to Java. I also have to believe the entire Go community will be pushing for this, since the entire programming language has been flagged.

**Comment by coreybutler** [comment]
This was posted in Gitter, but for anyone viewing this, there is a video showing [how to exclude files in Windows Defender](https://www.youtube.com/watch?v=0nNVvczCJPw).

**Comment by georgeedwards** [comment]
Urgh, this is really biting me with Kaspersky Total Security v16. Which deletes nvm.exer whenever it is used... Even if I add it to my trusted applications, it still gets deleted.

**Comment by MartinKolarik** [comment]
Had the same problem with avast! a few days ago. Sent them a false-positive report and it seems they already fixed it. Either way, having a signed executable would be great, and would most likely help with AV false-positives as well.

**Comment by sawilde** [comment]
Updated windows defender

````
Analysis of the file(s) in Submission ID MMPC16080237329614 is now complete.	
	
This is the final email that you will receive regarding this submission.	
	
The Microsoft Malware Protection Center (MMPC) has investigated the following file(s) which we received on 8/2/2016 6:14:01 AM Pacific Time.	
Below is the determination for your submission.	
	
========	
Submission ID MMPC16080237329614	
	
  Submitted Files	
  =============================================	
  nvm-setup.zip [Not Malware]	
  +---nvm-setup.exe [Not Malware]	
	
	
	
	
Your submission was scanned using antimalware definition version 1.225.2971.0.	
========	
````

The latest definitions work.

**Comment by coreybutler** [comment]
@sawilde - awesome!!!

**Comment by coreybutler** [comment]
@MartinKolarik - also awesome! that avast has already fixed it!!

**Comment by coreybutler** [comment]
@szarouski - I've got an awesome friend at Malwarebytes who looked into this and got it whitelisted. So, it should be "safe" in the latest definitions.

**Comment by AlexWalker222** [comment]
> Day after installing nvm using the msi installer - I got the attached virus alert, which I though you might want to know about: ![Trojan.Win32.Ebowla.il](https://cloud.githubusercontent.com/assets/803101/16615159/50bf8652-437d-11e6-9ce2-48331208bc03.jpg)
> 
> ### My Environment
> * [x]  Windows 10
> 
> ### I have already...
> * [ X] read the README to be aware of npm gotchas & antivirus issues.
> * [ X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
> * [ ]  verified I'm using an account with administrative privileges.
> * [ X] searched the issues (open and closed) to make sure this isn't a duplicate.
> * [ ]  made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.
> 
> ### My issue is related to (check only those which apply):
> * [ ]  settings.txt
> * [ ]  proxy support
> * [ ]  32 or 64 bit support
> 
> ### Expected Behavior
> After installing - I expect no viruses with any reference to nvm
> 
> ### Actual Behavior
> See photo: ![Trojan.Win32.Ebowla.il](https://cloud.githubusercontent.com/assets/803101/16615159/50bf8652-437d-11e6-9ce2-48331208bc03.jpg)
> 
> ### Steps to reproduce the problem:
> Just FYI 
I also have received this same message and now I have been searching for others who had this same problem now I know I am not alone.
