### ISSUE TITLE
node vlatest (64-bit) is not installed.

### ISSUE THREAD

**Issue by lewismoten** [coreybutler/nvm-windows#185]
```
$ nvm install latest 64
Version 6.3.0 is already installed.
$ nvm use latest
node vlatest (64-bit) is not installed.
```

**Comment by coreybutler** [comment]
`nvm use latest` is not a valid command. You must specify a proper semantic version for the `use` operator.

**Comment by errorx666** [comment]
@corebutler Can this please be a thing?  [You yourself said](/coreybutler/nvm-windows/issues/156#issuecomment-235276927) that `nvm use` syntax should be the same as `nvm install`.

I'm currently trying to write a script that parses `nvm list` output to find the latest version and pass it to `nvm use`, and it seems like it shouldn't be necessary.

**Comment by coreybutler** [comment]
@errorx666 - It can & will be a thing... I'm just not sure when. I'm in the middle of several product release sprints, contracts, and talks. It should be reasonably simple to implement if someone wants to take a crack at it before I get a chance to do it. I would accept a PR.

For your immediate purposes, perhaps it's worth pulling the release feed from node. This is how NVM4W does it.
