### ISSUE TITLE
Windows Defender recognizes installer as malware

### ISSUE THREAD

**Issue by arieljannai** [coreybutler/nvm-windows#188]
### My Environment
- [X] Windows 10

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):
- [x] windows installer

### NVM Version
- [x] 1.1.1

### Expected Behavior
nvm-setup.exe will pass the anti virus check

### Actual Behavior
Windows defender recognizes the nvm-setup.exe as a threat and removing it.

### Extra

I saw the issue about the nvm.exe that Kaspersky security identified (#182), but this time it's about the installer itself and not directly the nvm.exe. Maybe it detects nvm.exe inside the installer and it's the same issue?
Anyways, just to let you know, cause I'm not sure it's the same problem.

**Comment by coreybutler** [comment]
Yes, unfortunately this is the same issue. The anti-virus systems use a generic pattern to scan for the Golang signature. It is an issue I hope the Go team can address soon.

**Comment by Brian1111** [comment]
I have also the same problem.  When I run nvm-setup.exe, or when I try to unzip it, Windows 10 says that it is removing malware from my computer.   Also, your installation instruction says that I have to delete all globally installed npm's and reinstall them again.  This will take a lot of time.  As it is I cannot use this software.

**Comment by coreybutler** [comment]
@Brian1111 - See the gitter channel about migrating global npm modules... there was a conversation about it today. 

You should also be aware that if you were to manually perform what NVM4W does by hand, you would have to do the same thing. Node itself does not migrate npm modules. NPM has the capability to set a global node_modules directory via `.npmrc`, so I recommend looking into that.
