### ISSUE TITLE
Space in Windows username

### ISSUE THREAD

**Issue by AntiCZ** [coreybutler/nvm-windows#195]
### My Environment

- [x] Windows 7 or below (not truly supported due to EOL)

I have found little error when someone has a space in username and so has path to default dir like `C:\Users\firstname second\AppData\Roaming`

Everything seems to be ok until you type `nvm use 4.4.7` -> error exit 1 C:\Users\firstname is not command etc..

Solution install nvm eg. C:\nvm. Just dont use space

**Comment by coreybutler** [comment]
Duplicate of #41.
