### ISSUE TITLE
Easier No-Install instructions

### ISSUE THREAD

**Issue by heri16** [coreybutler/nvm-windows#20]
We should be using powershell/CLI in the wiki/scripts to assist the user.
Create an "install.cmd" file with these lines:

setx /m NVM_HOME "C:\nvm"
setx /m NVM_SYMLINK "C:\Program Files\nodejs"
setx /m PATH "%PATH%;%NVM_HOME%;%NVM_SYMLINK%"
(echo root: C:\nvm && echo path: C:\Program Files\nodejs && echo arch: 64 && echo proxy: none) > C:\nvm\settings.txt
notepad C:\nvm\settings.txt

**Comment by dgreene1** [comment]
Can a section on this be added to the readme? I'm still a bit lost on how to accomplish this.

**Comment by swap2ag** [comment]
@dgreene1 You need to run the script `install.cmd`. If you don't have admin permissions, then you need to remove `/M` from the `install.cmd` script and then run it.
Also, `C:\Program Files\" might not be available for users not having admin permissions. @coreybutler Can you please fix it?
