### ISSUE TITLE
How to migrating global-packages while installing?

### ISSUE THREAD

**Issue by yeehone** [coreybutler/nvm-windows#202]
### Feature Request
I have a question. How to install a new version of Node.js and migrate npm packages from a previous version? Or I should reinstall packages one by one manually...
see [https://github.com/creationix/nvm#migrating-global-packages-while-installing](https://github.com/creationix/nvm#migrating-global-packages-while-installing)

**Comment by coreybutler** [comment]
You'll need to reinstall global modules one-by-one or use a shared directory. You can setup a common/shared global node_modules directory using `.npmrc` (notice `p`, not `v`). Please have a look at the other issues, as this has been asked before. The Gitter channel also has a number of user suggestions for handling this.

**Comment by coreybutler** [comment]
Also, you may want to subscribe to #190. I don't know when I'll get it implemented, but this is the longer term solution for this.
