### ISSUE TITLE
Missing NPM information makes installation failed

### ISSUE THREAD

**Issue by sarunint** [coreybutler/nvm-windows#211]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

This is partial content of http://nodejs.org/dist/index.json of version 6.8.1

    {
    "version": "v6.8.1",
    "date": "2016-10-14",
    "files": [
    "aix-ppc64",
    "headers",
    "linux-arm64",
    "linux-armv6l",
    "linux-armv7l",
    "linux-ppc64le",
    "linux-x64",
    "linux-x86",
    "osx-x64-pkg",
    "osx-x64-tar",
    "src",
    "sunos-x64",
    "sunos-x86",
    "win-x64-exe",
    "win-x64-msi",
    "win-x86-exe",
    "win-x86-msi"
    ],
    "v8": "5.1.281.84",
    "uv": "",
    "zlib": null,
    "openssl": "1.0.2j",
    "modules": null,
    "lts": false
    }

Notice that no npm version information is available, thus making installation of NodeJS 6.8.1 failed

**Comment by coreybutler** [comment]
Please file this issue with the Node foundation, who is responsible for that list. I've moved this to #212.
