### ISSUE TITLE
npm fallback

### ISSUE THREAD

**Issue by coreybutler** [coreybutler/nvm-windows#212]
The node.js JSON feed sometimes has bad data (see issue #211). NVM4W should provide a fallback to download the latest available version of npm if no other version is specified.

**Comment by coreybutler** [comment]
Related to issue https://github.com/nodejs/nodejs.org/issues/969

**Comment by sidneys** [comment]
Should be fixed now, as documented in:
https://github.com/nodejs/build/issues/519

**Comment by coreybutler** [comment]
@sidneys - thanks for the update, and I'm glad to see it working.

I'm still going to leave this issue open because I think NVM4W needs to handle this scenario in case it happens again.

**Comment by nbarnwell** [comment]
Yeah so this is happening again with node 10.8.0. I'm going to have to ditch nvm and install node the old-fashioned way, since it doesn't look like this workaround is going to be implemented. Probably best to just close this issue if not.

**Comment by coreybutler** [comment]
@nbarnwell - cannot recreate.

![image](https://user-images.githubusercontent.com/770982/43932548-61288786-9c0a-11e8-9141-b51d27466f0e.png)

**Comment by nZeus** [comment]
Cannot install 10.8.0.

```
Downloading npm version 6.2.0... Download failed. Rolling Back.                                                                                                      
Rollback failed. remove C:\Users\i.tsvetkov\AppData\Roaming\nvm\temp\npm-v6.2.0.zip: The process cannot access the file because it is being used by another process. 
Could not download npm for node v10.8.0.                                                                                                                             
Please visit https://github.com/npm/npm/releases/tag/v6.2.0 to download npm.                                                                                         
It should be extracted to C:\Users\i.tsvetkov\AppData\Roaming\nvm\v10.8.0                                                                                            
```

If you go to https://github.com/npm/npm/releases/ there is no 6.2.0 available:
![image](https://user-images.githubusercontent.com/2727326/43955149-372abe82-9c9f-11e8-9411-6dc842f5d4ed.png)

**Comment by nZeus** [comment]
Apparently `nvm` is trying to reach the wrong repo. It should use `https://github.com/npm/cli/releases`

**Comment by coreybutler** [comment]
Check your version of nvm. 1.1.7 fixed this.

**Comment by javlc** [comment]
Is there a command to upgrade nvm v1.17, or just re run the new installer?

**Comment by coreybutler** [comment]
@javlc https://github.com/coreybutler/nvm-windows#installation--upgrades

**Comment by nagthgr8** [comment]
the issue still there with the latest 11.1.0

**Comment by coreybutler** [comment]
New repos and download URLs have been available for quite awhile and are integrated in newer versions of NVM4W. Closing (because I forgot to years ago).
