### ISSUE TITLE
Suggestion: wildcard major version to latest X.y..z

### ISSUE THREAD

**Issue by tomByrer** [coreybutler/nvm-windows#214]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.
### My Environment
- [ ] Windows 10
### I have already...
- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
### Expected Behavior

`nvm install 6` uses the latest 6._._ version, in this case v6.9.1
Typical behavior of [nvm Bash script](https://github.com/creationix/nvm#nvmrc)
### Actual Behavior

nvm installed 6.0.0 (assumed null = 0)

Would be handy to when having to install the latest versions in a specific major version without having to visit the NodeJS website.  Changing this behavior does have a slight potential of confusing current users, but is currently confusing of Mac devs using this on Windows.  I'd say the added benefit latest security updates & bug fixes trumps.
Same suggestion goes for `nvm use`, etc.

If 'no, won't add', I'd like to document the current behavior.

**Comment by coreybutler** [comment]
This has been requested before and I do think it makes sense to have the absolute latest version downloaded/used. I'm still pretty pressed for time at the moment, but consider this on my to-do list..... I would gladly accept a PR if someone wants this before I get around to it.

**Comment by kylewuolle** [comment]
I submitted a PR for this https://github.com/coreybutler/nvm-windows/pull/222

**Comment by navossoc** [comment]
@kylewuolle That is great, but I think you should go further and implement the same behavior on semver.

nvm install 6 = **6**.10.2
nvm install 6.9 = **6.9**.5
nvm install 6.9.2 = **6.9.2**

For reference:
https://nodejs.org/en/download/releases/

**Comment by Sieabah** [comment]
I've made a PR finishing the steps so install and use both have sane versions. [#311](https://github.com/coreybutler/nvm-windows/pull/311)

@navossoc
@coreybutler

**Comment by coreybutler** [comment]
Closing. This was added in v1.1.8.
