### ISSUE TITLE
`nvm node_mirror [url]` not work

### ISSUE THREAD

**Issue by gera2ld** [coreybutler/nvm-windows#216]
### My Environment
- Windows 10
- My Windows installation is non-English.

While typing `nvm` in `cmd`, I got help message saying `nvm node_mirror [url]` can set the node mirror to a different URL. But it seems not to work and is not mentioned in README. Is it deprecated or do I miss anything? Thanks.

**Comment by Jaykin** [comment]
+1

**Comment by coreybutler** [comment]
This functionality exists and should work as of version 1.1.1. Which mirror are you trying to use? Do you get an error or some other feedback from the console?

**Comment by WalterZou** [comment]
@coreybutler 
your source code 
```
var env = &Environment{
  settings: os.Getenv("NVM_HOME")+"\\settings.txt",
  root: "",
  symlink: os.Getenv("NVM_SYMLINK"),
  arch: os.Getenv("PROCESSOR_ARCHITECTURE"),
  node_mirror: "",
  npm_mirror: "",
  proxy: "none",
  originalpath: "",
  originalversion: "",
}
```
should modified as
```
var env = &Environment{
  settings: os.Getenv("NVM_HOME")+"\\settings.txt",
  root: "",
  symlink: os.Getenv("NVM_SYMLINK"),
  arch: os.Getenv("PROCESSOR_ARCHITECTURE"),
  node_mirror: os.Getenv("NODE_MIRROR"),
  npm_mirror: os.Getenv("NPM_MIRROR"),
  proxy: "none",
  originalpath: "",
  originalversion: "",
}
```

**Comment by jackxu2011** [comment]
@coreybutler
console out  the nvm's usage

**Comment by phtwo** [comment]
+1
console out the nvm's usage when use  `nvm node_mirror [url]`

**Comment by ldzhu** [comment]
modify `..\AppData\Roaming\nvm\settings.txt` by yourself .

```
node_mirror: http://npm.taobao.org/mirrors/node/
npm_mirror: http://npm.taobao.org/mirrors/npm/
```

**Comment by xhlwill** [comment]
@ldzhu taobao had changed http -> https

**Comment by Dengjiansheng** [comment]
http also work

**Comment by clarkttfu** [comment]
I guess the problem here is taobao does not respond version urls that does not end with '/':
https://github.com/coreybutler/nvm-windows/issues/285#issuecomment-472324274

**Comment by coreybutler** [comment]
taobao has moved to npmmirror.com. The inline help now references this.
