### ISSUE TITLE
Settings file needs to be in ASCII format to be properly read

### ISSUE THREAD

**Issue by espoelstra** [coreybutler/nvm-windows#219]
### My Environment

PowerShell/Chocolatey install

### My issue is related to (check only those which apply):

- [X] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

Settings file simply needs to exist and Go handles reading/decoding the YAML syntax from whatever encoding it has.

Possibly related: I noticed in the code there are two instances of the file existence check in the code, this could probably be consolidated to a function and two calls to it, this would avoid the split brain where it finds one but not the other and only fails if the settings file itself is missing and not if the nodejs folder doesn't exist.

### Actual Behavior

If I write the file using PowerShell and Out-File, the default encoding is UTF-8 or UTF-16, and it throws a blank "doesn't exist warning" but nvm still runs, but none of the functions actually work correctly. It reports I can install a version, but then it can never find it. It appears that the file exists but is in the wrong format for reading it avoids the hard exit.If I add -Encoding ascii then nvm works properly.

### Steps to reproduce the problem:

This is an excerpt of the chocolateyInstall.ps1 that creates settings.txt file in the install directory using two different methods.

```
$nvmPath = Join-Path $toolsDir $packageName
$NvmSettings = Join-Path $nvmPath "settings.txt"

# This works without specifying an encoding somehow (line endings?)
#New-Item "$NvmSettings" -type file -force -value `
# $("root: $nvmPath `r`npath: $nodePath `r`narch: $OsBits`r`nproxy: none");

# This uses a dict for a more OO approach
$NvmSettingsDict = [ordered]@{}
$NvmSettingsDict['root'] = $nvmPath
$NvmSettingsDict['path'] = $nodePath
$NvmSettingsDict['arch'] = $OsBits
$NvmSettingsDict['proxy'] = "none"

# The ASCII type is required for NVM to read the file properly
$NvmSettingsDict.GetEnumerator() | % { "$($_.Name): $($_.Value)" } | Write-Verbose
$NvmSettingsDict.GetEnumerator() | % { "$($_.Name): $($_.Value)" } | Out-File "$NvmSettings" -Force -Encoding ascii

# Without the encoding the file appears identical in Notepad,
# in WinMerge only the line endings differed
$NvmSettingsDict.GetEnumerator() | % { "$($_.Name): $($_.Value)" } | Out-File "$NvmSettings" -Force
```

**Comment by bmcminn** [comment]
Took a look at the `settings.txt` file, and it's getting garbled up... Apparently, after attempting to set the default architecture using `nvm arch ##`, NVM takes it upon itself to inject the empty config variables into the `settings.txt` file, but subsequent calls to `nvm arch ##` cause multiple copies of `npm_mirror:` and `node_mirror` to be appended to the `settings.txt` file as shown below:

```
root: C:\.bin\nvm
arch: 64
proxy: none
originalpath: 
originalversion: node_mirror: npm_mirror:node_mirror: npm_mirror: 
```

**Comment by coreybutler** [comment]
Closing due to age. A new settings management module is used in v1.1.8+.
