### ISSUE TITLE
nvm show commands instead of unistall node specified version

### ISSUE THREAD

**Issue by VitorLuizC** [coreybutler/nvm-windows#220]
### My Environment

- [x] Windows 10

- [x] My Windows installation is non-English.

### Expected Behavior

NVM Unistall the version.

### Actual Behavior

NVM just show me the command list, like if I write it wrong or doesnt exists.

### Steps to reproduce the problem:

1. Install some versions.

```sh
nvm install 6.9.1
nvm install 7.0.0
```
2. Try to unistall a version

```sh
nvm unistall 6.9.1
```
![Screenshot GIF](https://gyazo.com/8593394cede979215ef12179f6255d90.gif)

**Comment by espoelstra** [comment]
It looks like you have a typo, `unistall` instead of `uninstall` (two n's).
