### ISSUE TITLE
Feature: chocolatey package

### ISSUE THREAD

**Issue by pmizel** [coreybutler/nvm-windows#223]
Hi,

it is possable to distrebute nvm in chocolatey?
(https://chocolatey.org/packages?q=nvm)

thx
 Paul

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- My Windows installation is non-English.

**Comment by coreybutler** [comment]
I believe someone is working on this. See #17.

**Comment by dragon788** [comment]
@pmizel You can try the "preview" version of nvm from Chocolatey by installing the version here. https://chocolatey.org/packages/nvm.portable/1.1.1 Use `choco install nvm.portable --version 1.1.1` and let the maintainers know if you have any issues on their [GitHub repository](https://github.com/arieljannai/chocolatey-nvm-windows). Once it actually gets approved you can upgrade to the final version by adding --force to the install arguments.
