### ISSUE TITLE
After modifing the settings.txt, It doesn't work.I can't use proxy and mirror url

### ISSUE THREAD

**Issue by martinko2009** [coreybutler/nvm-windows#227]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [x] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [x] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

make the config of 'proxy','npm_mirror','node_mirror' in settings.txt effect.

### Actual Behavior

In settings.txt, I write some configs like below:
proxy:http://172.168.2.24:8080
originalpath: 
originalversion: 
node_mirror:npm.taobao.org/mirrors/node
npm_mirror:npm.taobao.org/mirrors/npm 

but it doesn't effect.

### Steps to reproduce the problem:

It doesn't access via the proxy,  node_mirror url and npm_mirror url

I think whether I should do sth after modifing settings.txt.

**Comment by ldzhu** [comment]
```
root: C:\Users\webas\AppData\Roaming\nvm
path: C:\Program Files\nodejs
node_mirror: http://npm.taobao.org/mirrors/node/
npm_mirror: http://npm.taobao.org/mirrors/npm/
```

**Comment by coreybutler** [comment]
@ldzhu is correct. Closing.
