### ISSUE TITLE
Gulp not being intalled with: nvm use [LTS_VER] 64 npm install gulp-cli -g

### ISSUE THREAD

**Issue by westerdaled** [coreybutler/nvm-windows#238]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x ] verified I'm using an account with administrative privileges. ( I think this the default in Cmder)
- [ x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ x] 32 or 64 bit support

### Expected Behavior
gulp to install via the command

λ `nvm use 6.9.5 64 npm install gulp-cli -g`
Now using node v6.9.5 (64-bit)
C:\Program Files\nodejs\gulp -> C:\Program Files\nodejs\node_modules\gulp-cli\bin\gulp.js   
C:\Program Files\nodejs                                                                     
`-- gulp-cli@1.2.2                                                                          
  +-- archy@1.0.0                                                                           
  +-- chalk@1.1.3      
..........
                                                                     
### Actual Behavior

Gulp doesn't appear to install in the way you suggest in the install instructions .  Instead  to run a **separate** command after running the use command shown above. Confused me for a minute or two ;-)

`npm install gulp-cli -g`

C:\Program Files\nodejs\gulp -> C:\Program Files\nodejs\node_modules\gulp-cli\bin\gulp.js
C:\Program Files\nodejs
`-- gulp-cli@1.2.2
  +-- archy@1.0.0
  +-- chalk@1.1.3
.......
### Steps to reproduce the problem:

open up cmder and run

```
nvm install 6.9.5 64
nvm use 6.9.5 64 npm install gulp-cli -g
```

**Comment by coreybutler** [comment]
`nvm use 6.9.5 64 npm install gulp-cli -g` is invalid syntax. It needs to be broken up. In other words, first run `nvm use 6.9.5`, then run `npm install gulp-cli -g`.
