### ISSUE TITLE
Incorrect version number displayed when installing

### ISSUE THREAD

**Issue by Efreak** [coreybutler/nvm-windows#239]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [x] Windows 10

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

NVM should say 'installing version X.Y.X' when installing X.Y.Z, no matter what version it is.

### Actual Behavior

NVM incorrectly identifies the version number when installing. This may be related to installing a version that isn't in the list (ls available only lists up to 6.9.5, but I'm installing 7.5.0).

Note: NVM installs properly, and `node --version` checks out correctly--the only issue here is that nvm states that it's installing the incorrect version.

### Steps to reproduce the problem:

`nvm install 7.5.0`

### Screenshot

[![screenshot](http://i.imgur.com/aivsjxC.png)](http://i.imgur.com/aivsjxC.png)

**Comment by coreybutler** [comment]
```sh
nvm install 7.5.0
Downloading node.js version 7.5.0 (64-bit)... Complete
```

Where is it displaying the wrong version?

(Remember `4.1.2` is the latest version of **npm**)

**Comment by coreybutler** [comment]
Closing since I don't see an issue.

**Comment by Efreak** [comment]
I seem to have been looking at the NPM version. Apparently I'm dumb...

**Comment by coreybutler** [comment]
It's easy enough to miss. If I had time, I'd add color coding or reformat in some way to make this clearer.
