### ISSUE TITLE
CygWin is an unspecified prerequisite

### ISSUE THREAD

**Issue by bobbycircle** [coreybutler/nvm-windows#24]
It might help newbies like me save some time if it is stated that something like CygWin tools are needed in order to run npm, which I discovered is a shell script which cannot be run from cmd.exe as far as I can tell.

**Comment by Kilbourne** [comment]
I have the same issue.  Node works well but npm seems to not install properly. 
Cannot find module 'C:\Apps\nodejs\node_modules\npm\bin\npm-cli.js'.
Already tried to reinstall node version and also nvm...every node version give the same npm problem...
npm and npm.bat are there...OS Windows7

**Comment by vkbansal** [comment]
Have you tried it in this order ?
 - Remove all `node` versions
 - Remove `nvm`
 - Install `nvm`
 - Install `node` versions

**Comment by Kilbourne** [comment]
Alsa nvm uninstall version doesn't work...

C:\Users\Luca>nvm list
 * 0.10.6 (Currently using ?-bit executable)

C:\Users\Luca>nvm uninstall 0.10.6
node v0.10.6 is not installed. Type "nvm list" to see what is installed.

C:\Users\Luca>node -v
v0.10.6

C:\Users\Luca>nvm root
Current Root: E:\Roaming\nvm

C:\Users\Luca>echo %NVM_HOME%
E:\Roaming\nvm

C:\Users\Luca>echo %NVM_SYMLINK%
C:\App\nodejs

C:\Users\Luca>cd %NVM_SYMLINK%
C:\App\nodejs>dir
 Il volume nell'unità C non ha etichetta.
 Numero di serie del volume: D424-80BB

 Directory di C:\App\nodejs

27/02/2015  10:57    <DIR>          .
27/02/2015  10:57    <DIR>          ..
27/02/2015  10:56         6,508,392 node.exe
27/02/2015  10:56    <DIR>          node_modules
27/02/2015  10:56               274 npm
27/02/2015  10:56               209 npm.cmd
               3 File      6,508,875 byte
               3 Directory  38,833,328,128 byte disponibili
C:\App\nodejs>cd node_modules

C:\App\nodejs\node_modules>dir
 Il volume nell'unità C non ha etichetta.
 Numero di serie del volume: D424-80BB

 Directory di C:\App\nodejs\node_modules

27/02/2015  10:56    <DIR>          .
27/02/2015  10:56    <DIR>          ..
               0 File              0 byte
               2 Directory  38,833,324,032 byte disponibili

**Comment by Kilbourne** [comment]
i have also installed nvm to C:\Users\Luca\AppData\Roaming\nvm ( which is on my settings a symlink to E:\Roaming\nvm) and uninstall command works but npm continues to not..

**Comment by Kilbourne** [comment]
Ok i resolve...
1 I have installed nvm to C:\nvm
Npm on 0.12.0 works but on 0.10.6 not, so
2 with 0.10.6 in use, i've needed to update npm, so npm install -g 2.6.1 and it works( maybe you have to put the need for npm update on older version in the docs)

**Comment by antogerva** [comment]
I have the same issue, I really don't understand why I get this message:
`C:\<path>\emptyFolder>nvm list
  * 0.12.0 (Currently using ?-bit executable)
    0.10.30`
The ?-bit seem a bit weird...

**Comment by coreybutler** [comment]
The `?-bit` is do to a missing command that apparently isn't shipping in all versions of Windows (or at least isn't installed by default in a few use cases). See issue #23 for a temporary fix.

Go had limited support for checking the bitness of a file, thus the need for the `file.exe`. However; Go v1.4 has much better support for this. In the next version, the `file.exe` won't be necessary at all. Until I can release the next version (which is a 2.0 release), try the the `file.exe` mentioned in issue #23.
