### ISSUE TITLE
Quickheal antivirus finds Trojan.Ebowla while running nvmsetup

### ISSUE THREAD

**Issue by aino-gautam** [coreybutler/nvm-windows#240]
If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ Yes] Windows 10

- [No ] My Windows installation is non-English.

### I have already...

- [yes ] read the README to be aware of npm gotchas & antivirus issues.
- [ yes] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ yes] verified I'm using an account with administrative privileges.
- [ yes] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ yes] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior
shouldn't be there and shouldn't occur

### Actual Behavior
Report for - Internet Security Virus Protection
Thursday, 16 February, 2017, Time 14:14:17
Internet Security Version - 17.00
Virus database - 15 February 2017

Detected: Trojan.Ebowla in
C:\Users\admin\AppData\Roaming\nvm\is-V2QRA.tmp
Action taken: Repaired

Operating system and version:
Windows 10

Fill me in...

### Steps to reproduce the problem:
install quickheal and run the nvm_setup.exe
Fill me in...

**Comment by coreybutler** [comment]
I submitted a ticket (#UFR-225-80000) with Quickheal.

**Comment by aino-gautam** [comment]
Can anyone test it with a different antivirus to see if the trojan is specific to Quickheal ?

**Comment by Chilace** [comment]
@aino-gautam Why? It's false positive.

**Comment by coreybutler** [comment]
The trojan isn't specific to Quickheal, which you can see in the [virus analysis](https://www.virustotal.com/en/file/b194e2ebb14b5694dbabb88d9beb3a366aa4e1b3767586ae7a6cbae994160978/analysis/), nor is it specific to NVM for Windows. The antivirus vendors were marking ALL applications written in Go as a virus. Most of the vendors have worked around this, but Quickheal is one of the few that hasn't yet.

**Comment by aino-gautam** [comment]
Every day new things to learn :)

**Comment by coreybutler** [comment]
The Quickheal team got back to me. They whitelisted NVM4W and it should no longer throw a false positive after their next virus definition update.
