### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by errorx666** [coreybutler/nvm-windows#244]
I'm receiving the following error:
```
> nvm install latest

Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt.

Get https://nodejs.org/dist/latest/SHASUMS256.txt: x509: certificate signed by unknown authority
```

I'm behind a proxy server which may be responsible for the certificate error; is there a flag or config option to ignore certificate trust issues?
If not, could one please be added?

**Comment by coreybutler** [comment]
I'm guessing it's your proxy. The SSL certificate on nodejs.org is from Comodo, a generally recognized CA, but it is a wildcard certificate. It's unusual to block something from a generally trusted CA, but I suppose it could happen.

![image](https://cloud.githubusercontent.com/assets/770982/23220233/e29f0bfa-f8e6-11e6-903d-0917b00654fc.png)

Are you able to try this outside of your proxy?

**Comment by errorx666** [comment]
That's the certificate I see but it's not trusted on my machine.  Is there no way to disable certificate validation?  I'd like to use nvm for automated CI builds and it's not feasible to fix this for every machine that may run it.

I'm not very concerned by the possibility of MITM attacks.

**Comment by coreybutler** [comment]
At present moment, there is no way to disable the certificate validation. However; I've already mocked up a potential way to bypass this with a CLI flag. I still need to test it, but if I have enough time this afternoon, I'll build a new release.

**Comment by coreybutler** [comment]
OK, this was a pretty straightforward fix. I managed to find time to run the build, so there is now a `--insecure` flag you can set when installing node that should skip the SSL validation check.

New release: [v1.1.2](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.2)

**Comment by coreybutler** [comment]
I got a little slap-happy and uploaded an incorrect installer. It's fixed, but if you unsuccessfully tried installing the new version before this comment, you may have encountered issues that are now fixed.

**Comment by errorx666** [comment]
The new flag works great, but I was able to resolve my underlying issue by installing the Comodo intermediate certificate from https://support.comodo.com/index.php?/Default/Knowledgebase/Article/View/929/75/intermediate-comodo-high-assurance-secure-server-ca

**Comment by psiddharth709** [comment]
![error](https://user-images.githubusercontent.com/25383528/30782788-4c43ded8-a156-11e7-8301-cb8b014b65b3.png)

how to solve error ? please share your ans..

**Comment by coreybutler** [comment]
@psiddharth709 - this is a different issue... it looks like a problem with your network. If it is the same issue noted above, just run `nvm install latest --insecure`.

**Comment by psiddharth709** [comment]
nvm install latest --insecure
 i run this command .
before image error show..

**Comment by enihar** [comment]
> Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt.
> 
> Get https://nodejs.org/dist/latest/SHASUMS256.txt: dial tcp 104.20.22.46:443: connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

How to get around this error?

**Comment by webia1** [comment]
You may have to set http/https-proxy before:

```js
npm config set proxy http://---myproxy---:PORT
npm config set https-proxy http(s)://---myproxy---:PORT
```

**Comment by deepthireddy1789** [comment]
I have got the same issue when I am on my VPN network. Log off from your VPN and try out. It worked!!! Run CMD as admin
![image](https://user-images.githubusercontent.com/60017071/107097131-e43d9900-67d1-11eb-8295-c411554a2f6b.png)
