### ISSUE TITLE
nvm list available fails to show 7* versions

### ISSUE THREAD

**Issue by ujaroe** [coreybutler/nvm-windows#246]
While "nvm list available" shows the latest LTS version (6.10.0), no 7.* version is listed - 6.8.1 is latest "current".

**Comment by coreybutler** [comment]
There is a bug processing the JSON for v7. I've fixed it and will release in the next update.

**Comment by coreybutler** [comment]
OK, this is fixed and shippied in [v1.1.2](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.2).
