### ISSUE TITLE
Download server not responding, downloads from nvm-windows releases page currently not available

### ISSUE THREAD

**Issue by 18steps** [coreybutler/nvm-windows#250]
Links to downloads on [the nvm-windows releases page](https://github.com/coreybutler/nvm-windows/releases) are currently not working. 

github-cloud.s3.amazonaws.com took too long to respond.

I'm in EMEA.

It attempts e.g.
https://github-cloud.s3.amazonaws.com/releases/24268127/273c7acc-f91e-11e6-8db5-91c9aa04aa02.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=abc&X-Amz-Date=20170228T202229Z&X-Amz-Expires=300&X-Amz-Signature=xyz-SignedHeaders=host&actor_id=pqr&response-content-disposition=attachment%3B%20filename%3Dnvm-setup.zip&response-content-type=application%2Foctet-stream

**Comment by coreybutler** [comment]
This is because Github is using Amazon S3 in the US-East-1 region to host releases. Amazon is currently down.... so there's nothing I can do about this. There's not even anything Github can do about this. We just have to wait for S3 to come back online.
