### ISSUE TITLE
Provide "nvm use auto" command that determines version using package.json

### ISSUE THREAD

**Issue by zrisher** [coreybutler/nvm-windows#255]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016
- [ ] My Windows installation is non-English.

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

Given a working directory containing a `package.json` file that specifies a node version, e.g.:
```
{
  "name": "some_project",
  "dependencies" : {},
  "engines": {
    "node": ">=7.0.0"
  }
}
```
And some versions of node installed via nvm:

```
> nvm list
  * 7.7.3
  * 7.7.2
```

I'd like to be able to run the command `nvm use auto` and have it select the highest available version that fits the provided version range, in this case `7.7.3`.

```
>nvm use auto
Now using node v7.7.3 (64-bit)
```

### Actual Behavior

No such command exists.

**Comment by byronmejia** [comment]
I'll have a look at this, @zrisher 🛩

**Comment by byronmejia** [comment]
Hecking lol, was trying to look at how [creationix/nvm](https://github.com/creationix/nvm/issues/651) implemented it, but it seems like a mess there. Any suggestions on the path to go down, @zrisher, @coreybutler ?

My current thought process is:
  1. Check package.json for type
  2. Check operator (i.e. >= )
  3. Check if version matches operator when compared to `node.GetInstalled(env.root)`

**Comment by byronmejia** [comment]
So far I've achieved a somewhat working solution to this, using [blang/semver](https://github.com/blang/semver)

Still need to implement wildcard, in case someone chooses that.

I am now going to sort the version array, so it chooses the highest version. Sound good? 😸

**Comment by coreybutler** [comment]
I'm sorry, but this feature will not be implemented directly in version managers. Please see the version management working group [discussion on package.json](https://github.com/nodejs/version-management/issues/12).

As I mentioned to @byronmejia in the comments of PR #258, a more appropriate solution is a scripting engine, similar to `npm run`. For example, something like `npm run auto` where `auto` is a reference to a shell/.bat script that switches the version. I know this seems more verbose, and it is, but it's also the only way to provide a truly customizable environment that doesn't force a dependency on npm.

**Comment by zrisher** [comment]
@coreybutler Understood, thanks for taking a look. 
@byronmejia Thanks for working on a solution!
