### ISSUE TITLE
Can't uninstall phantom version

### ISSUE THREAD

**Issue by SteveALee** [coreybutler/nvm-windows#267]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

can uninstall version 4.3.2

### Actual Behavior

told it is not installed
### Steps to reproduce the problem:

Just installed latest release 
`npm list` - prints `4.3.2`
`npm uninstall 4.3.2` says `node v4.3.2 is not installed. Type "nvm list" to see what is installed.`

I had previously uninstalled NVM as it clashed with nvm installation in Bash on Unbuntu On Windows.

Is there somewhere I should empty?

**Comment by coreybutler** [comment]
Go to your physical installation root (type `nvm root` to see where this is). There is most likely a directory in there for v4.3.2 with a file that wasn't removed completely. You should be able to just delete whichever versions you don't want.

**Comment by SteveALee** [comment]
Thanks @coreybutler that was indeed the case. It seems that uninstalling nvm using Windows "Add Remove" leaves these around. I see it's no so clear cut if they should be removed with nvm. Perhaps make it an option?

**Comment by coreybutler** [comment]
With the current uninstaller (which is autogenerated by the installer), it only recognizes files created by the installer, not what's created by the tool. If I can make a custom uninstaller for the next version, it totally makes sense to heed your suggestion and provide some sort of cleanup option. I really have no idea if time will allow for that, but consider it in my mental backlog.
