### ISSUE TITLE
Node.js vx.y.z is not released or avaliable, official list returns 503

### ISSUE THREAD

**Issue by Graren** [coreybutler/nvm-windows#268]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [x] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.
Have one english and one spanish

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

`nvm install x.y.z`

should install node version x.y.z and related npm

### Actual Behavior
`Node.js vx.y.z is not released or avaliable`

And nothing installs

### Steps to reproduce the problem:

`nvm install 7.8.0`
In fact failed even with LTS so try any

Tried to do it both in w 8.1 and w10, I have before used nvm on these machines, I got other installed versions in the list and also completely usable, but can't install anymore, also I can't reach your list
 [nvm4wList](http://coreybutler.github.io/nodedistro/), returns 503, is the service down?

**Comment by coreybutler** [comment]
The old node distro list was deprecated in v1.1.1 and stopped being updated late last year. You can type `nvm -v` to see which version you're using, but I suspect it's 1.1.0 or below. Make sure you're using the latest version from the [releases](https://github.com/coreybutler/nvm-windows/releases).

**Comment by Graren** [comment]
I was not aware, That just came from a little google search and not much reading, I apologize for that, but I'm running 1.1.3, so... what else could it be?
```
C:\>nvm v
1.1.3
```

**Comment by bonesoul** [comment]
same here, can install 7.10.0 but not 7.9.0

**Comment by coreybutler** [comment]
I'm pretty sure https://github.com/coreybutler/nvm-windows/blob/5a235cad46689972325807152bb6a1610dad8dcb/src/nvm.go#L140 is the offender. I've got OSCON to deal with this week and launching a new site next week... so it may take me a little while to get to this. I'd accept a PR.

**Comment by Graren** [comment]
Submitted a PR I believe It's solved
