### ISSUE TITLE
Cannot install node v7.4.0, but can install other versions.

### ISSUE THREAD

**Issue by JayyWalker** [coreybutler/nvm-windows#273]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support
- [ ] 32 or 64 bit support

### Expected Behavior

Install v7.4.0 of node.

### Actual Behavior

`Node.js v7.4.0 is not yet released or available.`

### Steps to reproduce the problem:

I only ran `nvm install 7.4.0`

I also attempted to install 7.10.0 which was successful, but I require 7.4.0 as that is the latest version Electron can run on.

**Comment by coreybutler** [comment]
Which version are you running? This issue should have been fixed in the latest release.

**Comment by JayyWalker** [comment]
@coreybutler I'm using 1.1.3. I see that there is a new version out, I'll download that and if anything I'll get back to you.

**Comment by vunb** [comment]
I got the same issue. After install new version v1.1.5 then it works for me!
Thanks.
