### ISSUE TITLE
Problem finding Path

### ISSUE THREAD

**Issue by DenisPolicastro** [coreybutler/nvm-windows#275]
### My Environment

- [X ] Windows 10

### My issue is related to (check only those which apply):

- [X] settings.txt

### Expected Behavior

Change node version

### Actual Behavior

Cannot find the path correctly

### Steps to reproduce the problem:

use the command nvm use 6.10.3

C:\Users\Denis Policastro>nvm use 6.10.3
exit status 1: 'C:\Users\Denis' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

I think there is a problem in the settings.txt, when the nvm doesn't recognize my path cause it have a space in my \<USER\>

**Comment by benoneal** [comment]
I also have this issue. 

`exit status 1: 'C:\Users\Ben' is not recognized as an internal or external command, operable program or batch file.`

**Comment by jonathanlinat** [comment]
I'm currently facing the same issue using `nvm use 8.0.0` command line after having installed Node v8.0.0 with Cmder (cmd.exe with admin privileges) in Microsoft Windows 10.

![nvm_windows10_issue_exit1](https://image.ibb.co/cdwaDF/nvm_windows10_issue_exit1.png)

**Comment by coreybutler** [comment]
Duplicate #41 - also see https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#spaces-in-pathnamesinstallation-root
