### ISSUE TITLE
Failed on use command

### ISSUE THREAD

**Issue by matheusrufca** [coreybutler/nvm-windows#278]
`nvm use 6.10.3`
I'm getting this error:

> exit status 1: 'E:\Program' is not recognized as an internal or external command,
> operable program or batch file.

**Node** is installed on `E:\Program Files\nodejs`
**NVM** is installed on `E:\Program Files (x86)\nvm`

**Comment by ysk2014** [comment]
I have the same problem, do you have a solution?

**Comment by coreybutler** [comment]
See #41 and the [FAQ](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#spaces-in-pathnamesinstallation-root).
