### ISSUE TITLE
Installation for user with space in the name fails

### ISSUE THREAD

**Issue by jbergens** [coreybutler/nvm-windows#279]
### My Environment

- [X ] Windows 10

### Expected Behavior

Installing nvm for a user with a space in the name should work including "nvm use <version>" afterwards.

### Actual Behavior

when running "nvm use 8.1.0" I get
`C:\src>nvm use 8.1.0`
`exit status 1: 'C:\Users\Johan' is not recognized as an internal or external command, operable program or batch file.`

### Steps to reproduce the problem:

Use an account with a space in the name. 
Install nvm in the default location (below AppData\Roaming).
choose a node version with "nvm use <version>"

**Comment by coreybutler** [comment]
Closing because this is already mentioned in several other issues.
