### ISSUE TITLE
nvm fails to install npm@5.0.3 alongside Node 8.1.3

### ISSUE THREAD

**Issue by Nicholaiii** [coreybutler/nvm-windows#283]
However, it works with Node 8.1.2

### My Environment
- [x] Windows 10
### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows

### My issue is related to (check only those which apply):

- [x] none of these

### Expected Behavior

NVM installs NVM 5.0.3 succesfully along Node 8.1.3

### Actual Behavior

NVM fails with a runtime error during TLS handshake.

### Steps to reproduce the problem:

`nvm install 8.1.3`

**Comment by coreybutler** [comment]
Cannot recreate.

![image](https://user-images.githubusercontent.com/770982/27814391-a2dbd238-6041-11e7-8ccd-9e7978bc75fc.png)

**Comment by coreybutler** [comment]
FYI - make sure you're running the latest [release](https://github.com/coreybutler/nvm-windows/releases).

**Comment by Nicholaiii** [comment]
I tried replicating again and it doesn't happen. I will assume it was an issue with wherever npm was hosted.
