### ISSUE TITLE
Installing without admin permissions results in uninstallable version

### ISSUE THREAD

**Issue by rfgamaral** [coreybutler/nvm-windows#284]
When I invoke `nvm install` within a non-admin command prompt, I get this:

```
$ nvm install 6.11.0
Downloading node.js version 6.11.0 (64-bit)...
Error while creating C:\Progra~1\NVM\v6.11.0\node64.exe - open C:\Progra~1\NVM\v6.11.0\node64.exe: Access is denied.
Error while downloading https://nodejs.org/dist/v6.11.0/win-x64//node.exe - invalid argument
Complete
Creating C:\Progra~1\NVM\temp

Downloading npm version 3.10.10... Complete
Installing npm v3.10.10...

Installation complete. If you want to use this version, type

nvm use 6.11.0
```

But version `6.11.0` was not installed successfully:

```
$ nvm use 6.11.0
node v6.11.0 (64-bit) is not installed.
```

But the version is listed as installed:

```
$ nvm list

  * 8.1.3 (Currently using 64-bit executable)
    6.11.0
```
But I can't even uninstall it:

```
$ nvm uninstall 6.11.0
node v6.11.0 is not installed. Type "nvm list" to see what is installed.
```

I have no idea where `nvm list` is getting the `6.11.0` version, there's no such folder on my NVM folder. Uninstall NVM and reinstalling, clears this information.

**Comment by rfgamaral** [comment]
Because of the failed installs under non-admin command prompt, the versions were being "installed" under `AppData\Local\VirtualStore`, just deleted those and everything is back to normal.

Maybe check for admin privileges before running commands like `install` and `uninstall`? Or even better, use the elevate command bundled with NVM for Windows to install/uninstall correctly.

**Comment by coreybutler** [comment]
Actually, it does attempt to do this. Which version of Windows are you running? Filepaths like `C:\Progra~1` haven't been around for a very long time.

**Comment by rfgamaral** [comment]
I'm using Windows 10.

That filepath is required because of the space in "Program Files", where I have NVM installed. I followed the suggestion on issue #41 and changed `settings.txt` like this.

**Comment by mikeyc1030** [comment]
I get the same error even if I am running the command prompt as admin (Windows 7).

`c:\>nvm install 0.12.18
Downloading node.js version 0.12.18 (64-bit)...
Error while creating C:\Users\mikec\AppData\Roaming\nvm\v0.12.18\node64.exe - open C:\Users\mikec\AppData\Roaming\nvm\v0.12.18\node64.exe: Access is denied.
Error while downloading https://nodejs.org/dist/v0.12.18/x64//node.exe - invalid argument
Complete
Creating C:\Users\mikec\AppData\Roaming\nvm\temp

Downloading npm version 2.15.11... Error while creating C:\Users\mikec\AppData\Roaming\nvm\temp\npm-v2.15.11.zip - open C:\Users\mikec\AppData\Roaming\nvm\temp\npm-v2.15.11.zip: Access is denied.
Error while downloading https://github.com/npm/npm/archive/v2.15.11.zip - invalid argument
Complete
Installing npm v2.15.11...

Installation complete. If you want to use this version, type

nvm use 0.12.18`

The key message in this error is "Access is denied" but I have full read/write permissions on all directories involved!
NVM looks like a very useful tool, just need to get it working on my system if anyone can help.

**Comment by LeeXTZ** [comment]
I got the same error as you...

**Comment by LeeXTZ** [comment]
> 
> 
> I got the same error as you...

I have solved this by uninstall node and nvm mannully, then reinstall nvm with every setting being default. Hope this will help you

**Comment by maguilar93** [comment]
right click on the Command Prompt app and choose "Run as administrator"

**Comment by gian1200** [comment]
In my case, I solved the "uninstallable" problem by manually removing the folder from `AppData\Roaming\nvm`

**Comment by coreybutler** [comment]
The issue with whitespace in paths is resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8. There is also rollback support, so if a download fails, it will attempt to remove the old files. From node 16.9.0 and up, a different distribution is used (which bundles node and npm). If this comes up again in v1.1.8+, please open a new issue.
