### ISSUE TITLE
Npx not created in the base directory next to npm

### ISSUE THREAD

**Issue by B3zo0** [coreybutler/nvm-windows#290]
### My Environment

- [x] Windows 10

### I'm using NVM4W version:

- [x] 1.1.5

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### Expected Behavior

Using nvm install latest which now ships with npm 5.3 also adds the npx.cmd not just the npm.cmd to the basedir.
Like this: https://www.screencast.com/t/6pLKLuRGf

### Actual Behavior

It only adds npm.cmd to the basedir so I can't run npx command from a command line tool.
https://www.screencast.com/t/6ISwwKeO

### Steps to reproduce the problem:

nvm install latest

**Comment by coreybutler** [comment]
See #288.
