### ISSUE TITLE
Add 'current' option to mimic nvm cli

### ISSUE THREAD

**Issue by DDuTCH** [coreybutler/nvm-windows#291]
### My Environment
- [ x] Windows 10

### I'm using NVM4W version:
- [x ] 1.1.5

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

nvm current to print the version currently in use. (like nvm native)

This is breaks default prompt enhancements that show current node version, like zsh bullet-train.
Work around is to modify the prompt on windows systems.

### Actual Behavior

prints help section

### Steps to reproduce the problem:

type `nvm current`

**Comment by coreybutler** [comment]
zsh is mac/Linux only. `nvm version` outputs the current version of NVM4W. `nvm ls` or `nvm list` shows the list of installed versions of Node & highlights the current version. `node -v` will always display the active version of Node.

This is not a clone of nvm, so I'm not inclined to add this if it's merely for the sake of parity with nvm. I am also unaware of any windows shells where this behavior is required.
