### ISSUE TITLE
nvm v1.1.6 ls-remote not work

### ISSUE THREAD

**Issue by comeriven** [coreybutler/nvm-windows#292]
### My Environment
- [x] Windows 10
- [x] My Windows installation is non-English.

### I'm using NVM4W version:
- [x] 1.1.6
![qq 20170730014138](https://user-images.githubusercontent.com/19868056/28747021-7f550820-74c8-11e7-8ac9-b8ccffcd2f68.png)

I try use 'nvm ls-remote', but it not work.

**Comment by coreybutler** [comment]
That's never been a valid command.You may be thinking of nvm, which is a different project.

**Comment by comeriven** [comment]
How to view the remote version of node?  I remember nvm can do it.

**Comment by coreybutler** [comment]
It's `nvm ls available`.

You can always just type `nvm` to see the help menu.

**Comment by comeriven** [comment]
Thank you!
