### ISSUE TITLE
Do not demand elevation on Windows 10 Creators Update and forward

### ISSUE THREAD

**Issue by giggio** [coreybutler/nvm-windows#295]
### My Environment

- Windows 10 Version 1703 (OS Build 15063.540)

### I'm using NVM4W version:

- 1.1.6

### Expected Behavior

On a Windows 10 Creators Update and forward, if Developer Mode is enabled, you do not need to be elevated to create or edit a symlink. See [this blog post from Microsoft](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10) for more info.
The expected behavior for such a system is that elevation is not requested.

### Actual Behavior

Elevation is requested even on Windows 10 Creators Update (or later).

### Steps to reproduce the problem:

Run a `nvm use` command on Windows 10 Creators Update (or later) on a non elevated cmd or powershell window.

### Other info

I have just tried a `mklink` command on a non elevated cmd window and it worked perfectly. I can confirm that the behavior is already implemented and working on Windows 10 Creators Update.

**Comment by coreybutler** [comment]
I haven't updated to this build yet. While symlinks may be supported, I didn't see any mention of accessing protected directories, specifically `C:\Program Files`. That's the other reason UAC is leveraged. My assumption is developer mode should allow this, but if you can (or did) test creation of a symlink within `C:\Program Files`, it would help assess the effort. 

I'm not opposed to adding this, but it will require a secondary set of commands for... well everything. I'll mark it as an enhancement request for now and add it to the 2.0 milestone for discovery.

**Comment by giggio** [comment]
I get `Access is denied.` when I try to create a symlink on `C:\Program Files`.
I guess that for it to work we would need to use a different directory, one that does not sit on the default `C:\Program Files\nodejs\`. I don't really see a problem in that if I get to not need administrative privilege to change node versions (and the nagging prompt as well). At the end, Node only demands that the `PATH` is right.
For example, it would be fine for me to have the default symlink sitting under `APPDATA\nvm\nodejs` instead of the default on Program Files.

**Comment by coreybutler** [comment]
That's what I was afraid of. There are alot of users who want to keep it under `C:\Program Files`, which is still the Windows standard installation path... so this seems like quite an edge case. Don't get me wrong, I too would like to see the UAC go away, but I'll have to do some testing to make sure the code base doesn't spiral into an unmanageable slew of if/else statements (next version is cross-platform). Bottom line, I'll put it in if I can, but I'm not sure when that will be.

**Comment by TomeOkin** [comment]
nvm root path does not support uppercase letters

**Comment by giggio** [comment]
@coreybutler You could make it an option. If the user demands the use of `Program Files`, then they will have to elevate. If you don't want to elevate on every nvm call, then you have to let go of the `Program Files` path.

**Comment by andregs** [comment]
May I suggest another option? Why don't you just rename the folder name of the current node version? I was able to install and use nvm-windows without admin rights by doing the following steps:
1. Add %NVM_HOME% and %NVM_HOME%\current to my user path env var (no admin needed);
1. Download and extract nvm-noinstall.zip into %appdata%\nvm;
1. Create settings.txt
1. Create a script like my silly nodeset.cmd into %appdata%\nvm:
```cmd
@echo off
node -v > currver 2>nul
set /P CURR_VER=<currver 2>nul
del currver 2>nul
set /P NEW_VER="Which version, sir? "
rename current %CURR_VER% 2>nul
rename %NEW_VER% current 2>nul
rename current\node64.exe node.exe 2>nul
@echo on
```
5. Now I can use `nvm` to download and install node versions, and `nodeset` to select the current one

**Comment by kasajian** [comment]
There's no mention of nvm-noinstall other than here.   The instructions here create settings.txt.  the .cmd file just pops it up in a notepad file.  There's no explanation of what should be inside settings.txt in the install, in this issue, or the readme.

My suggestion is for someone to post a sample settings.txt file here so that we can get this to work.

**Comment by sebthom** [comment]
I am using the following portable approach that does not require admin permissions:

1. unzip nvm into a directory of choice, e.g. **C:\dev\nvm**
1. create an **nvm-init.cmd** script in the nvm installation directory containing:
    ```batch
    @echo off
    set "thisDir=%~dp0"
    set "NVM_HOME=%thisDir:~0,-1%"
    set "NVM_SYMLINK=%NVM_HOME%\current"

    (
        echo root: %NVM_HOME%
        echo path: %NVM_SYMLINK%
        if "%PROCESSOR_ARCHITEW6432%" == "AMD64" (
            echo arch: 64
        ) else (
            echo arch: 32
        )
        echo proxy: none
    ) > %NVM_HOME%\settings.txt

    setx NVM_HOME "%NVM_HOME%"
    setx NVM_SYMLINK "%NVM_SYMLINK%"
    setx PATH "%PATH%;%NVM_HOME%;%NVM_SYMLINK%"
    ```
1. replace **elevate.cmd** in the nvm installation directory with:
    ```batch
    @echo off
    if "%3" == "mklink" (
        if exist %NVM_SYMLINK% (
            del /F %NVM_SYMLINK%
        )
        mklink /J %NVM_SYMLINK% "%6"
    )
    ```
1. Execute **nvm-init.cmd** once either in command line or by double clicking in Windows Explorer.
1. Now you can use nvm/nodejs in any command prompt as usual.
1. When you move the nvm installation directory to another place simply execute **nvm-init.cmd** again once.

**Comment by leonard84** [comment]
IMHO we don't need a symlink in `C:\Program Files\nodejs\` it could also live in the %APPDATA%, so there would be no need for UAC if the developer mode is active. You could check if the mode is active via the registry https://stackoverflow.com/questions/40033608/enable-windows-10-developer-mode-programmatically

This enhancement would make using nvm a much smoother experience.

**Comment by jensotto** [comment]
@leonard84  You might be right, but enabling Developer mode would require elevation. Therefore it might not be an option if the user has insufficient permissions. Developer mode could also not be allowed due to company policy.
Your suggestion could possibly be implemented if developer mode is available.

**Comment by leonard84** [comment]
@jensotto I meant it should check if dev mode is active and then continue without elevation, and fall back to elevation if it is not active.

**Comment by leonard84** [comment]
@jensotto our company has switched to a rather painful admin access setup, you have to request admin access with a two-factor authentication, then log-off and on again. The admin rights are removed at the next login. So to have a solution that does not require continuous admin access to work would really help.

**Comment by TimoP** [comment]
Any news on that front? We have a lot of small projects with different node versions and working students without admin rights.

**Comment by coreybutler** [comment]
This is the default in v1.1.9. It requires developer mode to be enabled to suppress prompts.

If NVM4W is installed in a protected directory (such as `C:\Program Files`), Windows will required admin privileges. The workaround is to install in a non-protected directory, such as `C:\nvm`.
