### ISSUE TITLE
How to install and use yarn along with nvm-windows

### ISSUE THREAD

**Issue by Deilan** [coreybutler/nvm-windows#297]
How to install and use `yarn` along with `nvm-windows`? `yarn` depends on Node.js and brings it if it's not installed in a regular way.

**Comment by coreybutler** [comment]
`npm install -g yarn` should work.

**Comment by Deilan** [comment]
@coreybutler Thanks! I wonder it's not on the [official list of theirs' install options](https://yarnpkg.com/en/docs/install), although the npm package is the official one.

**Comment by coreybutler** [comment]
The yarn team has a funky approach. It's a great tool, but they enforce several practices the Node Foundation wishes would just go away. One frustration is lack of consideration for version managers, even though there is an official working group for it within the Node Foundation and there have been several conversations around whether the node installer should actually install a version manager (an ongoing discussion). However; at the end of the day, yarn is still just an npm package. I'll update the README/wiki to make a note of this.

**Comment by nanmu42** [comment]
Actually it is on the list, see [Alternatives Tab](https://yarnpkg.com/en/docs/install#alternatives-tab).

Although the `security risk` they mentioned seems to be a little pale...

@Deilan

**Comment by justoverclockl** [comment]
why if i run npm install -g yarn, he create node_modules folder into desktop??
