### ISSUE TITLE
nvm ls available don't show the latest version of node

### ISSUE THREAD

**Issue by DanielWLam** [coreybutler/nvm-windows#298]
![image](https://user-images.githubusercontent.com/8369212/29992782-b7f1aebc-8fd6-11e7-8174-436eb89e3b8f.png)

 AS you can see, nvm show the lastest version is 7.10.1, however, the latest current version of nodejs is v8.4.0. Is this a bug?

**Comment by coreybutler** [comment]
You're running an old version. Upgrade to 1.1.5 or higher.
