### ISSUE TITLE
Error while install

### ISSUE THREAD

**Issue by vkbansal** [coreybutler/nvm-windows#3]
I get the following error while installing and it just goes into loop
install screen <-> error
![01](https://cloud.githubusercontent.com/assets/5930351/4399406/eedef052-446a-11e4-8f40-31ba80950448.JPG)

**Comment by grofit** [comment]
I get a similar error here but my error is `ShellExecuteEx` with the message `A referral was returned from the server`

I think this may be down to group policies applied to this laptop I am working on but not entirely sure if anyone else has had this before?
