### ISSUE TITLE
Misleading installer instruction

### ISSUE THREAD

**Issue by mlindsten** [coreybutler/nvm-windows#31]
I just learned about nvm-windows when googling for a convenient way to update node (on Windows) and it seems to be just what I need!

However, it wouldn't play at first and it took me a while to figure out why. In the installer I changed the default paths to my liking (which I almost always do), but I misunderstood the instruction that says _"Select the folder in which Setup should create the symlink"_ (see screenshot below) and I chose an existing folder.

The installation completed without problems and (after changing some permissions) I could run `nvm install latest` to install version 0.10.35. Then I tried to run `nvm use 0.10.35`. It gave me an UAC prompt (like it's supposed to?) and then failed silently - no symlink created!

It wasn't obvious (at least to me) that the reason was that I had entered a path to an existing directory (since I thought that was what the installer asked for). You should really rephrase that instruction in the installer and perhaps also output a descriptive error message if there is a folder in the way when creating the symlink.

![screen](https://cloud.githubusercontent.com/assets/7278260/5660821/ceb385b0-9724-11e4-819e-825a192a89d0.png)

**Comment by coreybutler** [comment]
Noted, thanks for the suggestion!

**Comment by coreybutler** [comment]
Closing due to age. An entirely new installer will be built for "rt" (successor effort).
