### ISSUE TITLE
NVM breaks when installed in a folder which name contain a space

### ISSUE THREAD

**Issue by danidemi** [coreybutler/nvm-windows#310]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [ ] 1.1.6
- [x] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

I downloaded the zipped installer, installed it changing the destination folder to `C:\Program Files\nvm\`.

Then, I install from an admin console like that
```
$ nvm install 6.11.4
Downloading node.js version 6.11.4 (64-bit)...
Complete
Creating C:\Program Files\nvm\temp

Downloading npm version 3.10.10... Complete
Installing npm v3.10.10...

Installation complete. If you want to use this version, type

nvm use 6.11.4
```

Then, I choose the version that has been just installed.
```
esche@DESKTOP-IR6RUPA C:\Users\esche
$ nvm use 6.11.4
exit status 1: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

As you can see, the path described in the error is the installation path I choose, truncated at the first space.

### Actual Behavior

It should work regardless of the installation path containing a space or not.

### Steps to reproduce the problem:

1. Start with no nvm installed.
1. Download the installer.
2. During installation change installation directory to a folder containing a space, like `c:\program files\`
3. `nvm install 6.11.4`
3. `nvm use 6.11.4`

The last operation fails as explained above.

**Comment by coreybutler** [comment]
See #41.
