### ISSUE TITLE
Why is nvm 1.1.6 just a pre-release?

### ISSUE THREAD

**Issue by mriehema** [coreybutler/nvm-windows#316]
### My Environment

- [X] Windows 10

### I'm using NVM4W version:

- [ ] 1.1.6
- [X] 1.1.5

I'm using [scoop](https://github.com/lukesampson/scoop) for nvm. 
I just wanted to update my nodejs to the latest LTS (8.9.1) version but I got the "filename is too long" error. I checked the issues and found, that 1.1.6 fixed this. But this is just a pre-release, so it it not avaialbe through scoop yet. :(

See https://github.com/lukesampson/scoop/issues/1825 and #300 and #289 

Could you mark 1.1.6 as a stable release? Thank you.

**Comment by coreybutler** [comment]
Because it hasn't fully addressed some issues with spaces and special characters in path names that are affecting non-English users. Most issues are resolved, but there are still some edge cases I need to work through... just haven't had enough time to wrap it up yet.

**Comment by mriehema** [comment]
Thanks for your quick response. Since more and more people start to migrate to node8/npm5, couldn't you release the fix as 1.1.6 to help them and keep the missing issues for 1.1.7?
