### ISSUE TITLE
"nvm use" (without params) returns a bizarre message

### ISSUE THREAD

**Issue by peternann** [coreybutler/nvm-windows#318]
Please consider this suggestion:

### My Environment
- [*] Windows 7 or below (not truly supported due to EOL - see wiki for details)
(Wow, didn't know Win7 was not supported...)

### I'm using NVM4W version:
- [* ] 1.1.6

### Expected Behavior

I actually expected "nvm use" (without parameters) to tell me what Node was in in use.
In fact, I mistook the current output of this command to indicate that nvm was knotted and broken in some way, and did a complete re-install of nvm (Silly me).

I accept that my expectations was incorrect on both counts, so take this as a suggestion:

It seems like a good idea to me that "npm use" (without parameters) should probably just behave precisely like "nvm list", Thusly:

```
> nvm use
  * 6.11.4 (Currently using 64-bit executable)
```

So that the user is informed of BOTH the Node in use, and other options available (if any - I have none).

### Actual Behavior

```
> nvm use
.0.0
node v.0.0 (64-bit) is not installed.
```

Which isn't really helpful in any way, and looks quite bizarre.

### Steps to reproduce the problem:

Install nvm and a node as usual, then type "nvm use" and hit enter.

**Comment by coreybutler** [comment]
Well that's a first. Was node previously installed before NVM4W?

Re: `(Wow, didn't know Win7 was not supported...)`, see https://github.com/coreybutler/nvm-windows/wiki/Support-for-Windows-7-and-Earlier

**Comment by alanionita** [comment]
Still having this issue today. Is there any idea what's causing it?

**Comment by coreybutler** [comment]
I never got a chance to really dive in and fix this properly, but it's trying to fall back to a default value.... which doesn't exist. Only the minor and patch versions default to 0... there is nothing for the major version. That's _why_, but it's not a fix. 

It needs to provide a help message when no argument is provided. Happy to accept a PR if someone has time, otherwise it will be on my to-do list.

**Comment by coreybutler** [comment]
Closing due to cleanup. In newer versions, a message stating "Invalid version" is returned.
