### ISSUE TITLE
NPM does not work with Node 9.x.x

### ISSUE THREAD

**Issue by SeanSobey** [coreybutler/nvm-windows#319]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Using node 9.x.x and npm with nvm should work fine the same as older versions.

### Actual Behavior

```
npm WARN npm npm does not support Node.js v9.2.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN npm npm does not support Node.js v9.2.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
npm WARN npm You can find the latest version at https://nodejs.org/
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.C:\Program Files\nodejs\node.exe: src\node_zlib.cc:437: Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
```

After installing node and trying to run any command with npm I get a fail and the above message. I have replicated this accross 3 seperate machines running similar setups. There are a few open issues on npm (like [this one](https://github.com/npm/npm/issues/19193)) with what looks to be the same issue, but the workarounds do not work with nvm.

I also tried uninstalling nvm and all node versions, and clearing all caches etc, and installing node 9.2.0 directly. NPM then works fine. Uninstall node 9.2.0 then install nvm again, and same issue.

### Steps to reproduce the problem:

`nvm install 9.1.0`
or
`nvm install 9.2.0`

`npm install` on a project.

**Comment by coreybutler** [comment]
This is an upstream issue (https://github.com/nodejs/node/issues/16649). Npm has gradually been forcing more of their own opinions into the install process, causing sporadic failures throughout different versions. This will, unfortunately, require a fix from npm or rearchitecting version managers. This is something I've been planning to do (and have accomplished a little), but time hasn't been available to do it yet.

For anyone else reading this, the only way to expedite my effort on this is through a sponsorship. I'm at max capacity and would have to take time away from paid work. PM me if you're interested.

**Comment by SeanSobey** [comment]
Thanks for the quick reply.

I have been reading around and it seems like a [fairly prevalent](https://github.com/npm/npm/issues/19019) issue in npm (looks like 2 issues actually, one with supported node versions and another with node_zlib.cc). It looks like a fix has gone in npm (for the node version bug at least), so hoping npm 5.5.2 will resolve this issue.

**Comment by inventti-silvio** [comment]
# Path to long

**Latest**
```
λ nvm install latest
Downloading node.js version 9.2.0 (64-bit)... Complete
Creating C:\Users\silvio.greuel\AppData\Roaming\nvm\temp

Downloading npm version 5.5.1... Complete
Installing npm v5.5.1...2017/11/24 14:31:46 mkdir C:\Users\silvio.greuel\AppData\Roaming\nvm\temp\nvm-npm\npm-5.5.1\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish: The filename or extension is too long.
```
**8.9.1**
```
C:\Program Files\nodejs
λ nvm install 8.9.1
Downloading node.js version 8.9.1 (64-bit)... Complete
Downloading npm version 5.5.1... Complete
Installing npm v5.5.1...2017/11/24 14:24:21 mkdir C:\Users\silvio.greuel\AppData\Roaming\nvm\temp\nvm-npm\npm-5.5.1\node_modules\libnpx\node_modules\yargs\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\parse-json\node_modules\error-ex\node_modules\is-arrayish: The filename or extension is too long.
```

**Comment by WORMSS** [comment]
Can NVM install node without npm ?

**Comment by coreybutler** [comment]
@WORMSS - at the moment, no.... but it should be possible to make that an option. If you're interested, open a new issue (otherwise I'll forget).

**Comment by SeanSobey** [comment]
[NPM 5.6.0](https://github.com/npm/npm/releases/tag/v5.6.0) has fixed the issues I experienced here, but I did have to manually install (download the [zip](https://github.com/npm/npm/archive/v5.6.0.zip) and extract to replace `%NVM_HOME%\v9.2.1\node_modules\npm`), since `nvm install latest` still installed NPM v5.5.1.

**Comment by laukstein** [comment]
@SeanSobey npm v6.5.0 currently released as **Pre-release** and not as stable **Latest release**, probably because of it `nvm install latest` wouldn't upgrade to v6.5.0.

**Comment by larrybahr** [comment]
Thanks @SeanSobey! Your work around fixed the issue for me. [NPM 5.6.0](https://github.com/npm/npm/releases/tag/v5.6.0) is working fine for me on Windows 10.

**Comment by nduc** [comment]
My work around is to install an older version 8.x.x and update npm to the latest version.  Since I'm using nvm, I copy the npm folder from version 8.x.x to version 9.x.x and I have version 5.6.0 working with node 9.x.x.

**Comment by likeabossTM** [comment]
while trying to any regular deploy on firebase.

BooM.!



WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
/usr/local/bin/node[9040]: ../src/node_zlib.cc:437:static void node::{anonymous}::ZCtx::Init(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort() [node]

**Comment by ranbuch** [comment]
I've uninstalled ```nodejs``` 9.x.x and installed 8.x.x from here:
https://nodejs.org/en/download/

**Comment by likeabossTM** [comment]
about my case it's already working right now what was happening was that the firebase cli was updating it ...

but I had to do what the ranbuch friend did here to uninstall node and npm from the / bin
and then install again it worked perfectly.
