### ISSUE TITLE
npm ls -g lists npm

### ISSUE THREAD

**Issue by mlindsten** [coreybutler/nvm-windows#32]
I noticed that `npm ls -g` lists npm itself (with all its dependencies) now that I've installed Node via nvm. When I had Node installed the "normal" way it didn't (which I've just verified with a colleague). It seems to work fine otherwise (though I haven't tested it that much yet), but the fact that it behaves differently is a bit disturbing.

Do you know why and are there any other differences?

**Comment by coreybutler** [comment]
There should be no functional differences.

I haven't tested this myself, but I suspect your experience partially depends on the version of node installed. The way npm was packaged changed right around v0.10.26, and it is often different in the unstable branches. Npm is a global node module of it's own right, so it really should be showing up in the list of global modules. I suspect that if you run `npm install npm` or `npm update npm`, you will see the same list.

Remember that NVM for Windows is not changing the behavior or structure of node or npm. It merely changes symlinks and environment variables for you so it doesn't have to be done manually.

**Comment by mlindsten** [comment]
Yes, that's why I was surprised by this. As I mentioned I verified with a colleague and we both used the same version of Node and npm. I still think this is strange ...

**Comment by coreybutler** [comment]
Have you tried installing Node.js by hand instead of using the Windows installer? I suspect you'll see the same results you're seeing with NVM.

**Comment by mlindsten** [comment]
No, I've only installed it using the installer. Perhaps you're right...
