### ISSUE TITLE
Installer default nvm path uses username different from logged-in user

### ISSUE THREAD

**Issue by nbkhope** [coreybutler/nvm-windows#320]
### My Environment
- [X] Windows 10

### I'm using NVM4W version:

- [X] 1.1.5

### Expected Behavior

`nvm-setup` installer uses the logged in user's username for the default path `C:\Users\<username>\AppData\Roaming\nvm`

### Actual Behavior

If nvm-windows was first installed using a different Windows user and you try to install it using a new user, the default path in the installer uses that former user instead of the current logged-in user's username.

### Steps to reproduce the problem:

1) Log in using UserA. Download `nvm-setup` and install it (first time install).
2) Log out. Then login UserB. Download `nvm-setup` and execute installer.
3) Default path will be `C:\Users\UserA\AppData\Roaming\nvm`, but should use `UserB` by default

### Comments

I kept getting nvm not a recognized command and realized it was never installing the symlink in the right place. So I failed to note at first that the installer was using the username of another user for the installation path. Perhaps that default path should be set to the current user's username instead of the first user who installed nvm-windows?

**Comment by coreybutler** [comment]
The installer cannot install NVM for two separate users sharing the same symlink directory. The installer is recognizing the existing installation and assuming it is an update.

NVM4W is designed to be used at the system level, i.e. one installation per computer.
