### ISSUE TITLE
nvm toggle

### ISSUE THREAD

**Issue by fracz** [coreybutler/nvm-windows#323]
It would be nice to have an ability to toggle the version you use with `nvm toggle`. It should turn the other version one have installed (or the next one on the list if there is more than 2).

In my work it's common use case to have 2 major versions installed and now in order to switch them you must see what you have with `nvm list` and then `nvm use X` :-)

**Comment by kakkarott** [comment]
Me too felt this small feature as good enhancement: submitted pull request: https://github.com/coreybutler/nvm-windows/pull/328

**Comment by erikleo** [comment]
I think this feature could be more generally implemented  with an expansion of "nvm use".  For example the described feature could be implemented as:

nvm use next

I think also doing a left string match would be very useful.  I have a version of 8.x.x installed and 6.x.x installed but i can never remember the specific version so it would be nice if it could check for matching major version number using the following:

nvm use 6
nvm use 8

if you had multiple matches then you could return a message with the matches that are installed.

**Comment by coreybutler** [comment]
Closing. This feature may be added to rt (successor project) though.

**Comment by erandakarachchi** [comment]
@coreybutler any update on this?
