### ISSUE TITLE
New install looks for settings.txt in old install location

### ISSUE THREAD

**Issue by webtechnologyinc** [coreybutler/nvm-windows#327]
### My Environment

- [X] Windows 7 and Widnows Server 2008 R2

### I'm using NVM4W version:

- [X] 1.1.6

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.  **[Found similar issue with no replies.]**
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [X] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

I installed nvm4w in the default location of C:\Users\myname\AppData\Roaming\nvm. I then uninstalled and installed to C:\nvm.

The install worked fine.  I typed the simple command "nvm list" to test the install.

I expect to see nvm text that there were no installations.

### Actual Behavior

ERROR open C:\Users\myname\AppData\Roaming\nvm\settings.txt: The system cannot find the path specified.

### Steps to reproduce the problem:

Install nvm4w in the default location of C:\Users\myname\AppData\Roaming\nvm.
Uninstall nvm4w
Install nvm4w to a different location.  e.g. C:\nvm.
Type "nvm list"

-->>The nvm command tries to find the settings.txt file at the old install location.

**Comment by cheng-github** [comment]
try to run nvm under administrator

**Comment by coreybutler** [comment]
Closing due to age.
