### ISSUE TITLE
exit status 1

### ISSUE THREAD

**Issue by hsali** [coreybutler/nvm-windows#333]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ x ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x ] read the README to be aware of npm gotchas & antivirus issues.
- [ x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Fill me in...

### Actual Behavior

exit status 1: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce the problem:

- I install the noinstall-setup.exe 
- set settings.txt at C:\. 
- nvm install 8.9.4
- nvm use 8.9.4 ( error occured )

**Comment by Andries-Smit** [comment]
Windows files systems allows spaces... in paths.. seems to be the issue.
Did you try to install on a different location?

**Comment by createdbyjurand** [comment]
Edit file
```
C:\Users\User Name\AppData\Roaming\nvm\settings.txt
```
Change
```
root: C:\Users\User Name\AppData\Roaming\nvm
path: C:\Program Files\nodejs
```
To
```
root: C:\Users\UserNa~1\AppData\Roaming\nvm
path: C:\Progra~1\nodejs
```
The idea is to remove spaces from "User Name" to "UserName" and delete last letters so that with "~1" at the end there was 8 letters.
So
"UserName~1" - 10 letters
"UserNa~1" - 8 letters

**Comment by ozanmuyes** [comment]
Also [this](https://superuser.com/a/179450) superuser answer is valuable as work-around supplementary.

**Comment by mikelee516** [comment]
I ran into this with the latest version and the only way I could get it to work was install to C:\nvm and symlink at C:\nodejs

**Comment by coreybutler** [comment]
Closing due to age. Several new versions have been released, which address most of the concerns raised in this issue. See the https://github.com/coreybutler/nvm-windows/wiki/Common-Issues if you're finding this via Google.
