### ISSUE TITLE
io.js

### ISSUE THREAD

**Issue by xgrommx** [coreybutler/nvm-windows#34]
Hello @coreybutler 

Do you plan add support for https://iojs.org? It's will be very useful.

**Comment by coreybutler** [comment]
It's not on my immediate priority list _yet_. I haven't had much time to play with it yet. At first glance, it looks like the integration process may be a bit more restricted (there is only an `msi` available). For the moment, I do not have plans to add support, but I will certainly consider adding it as more people start using io.js.

**Comment by alubbe** [comment]
+1 for iojs

**Comment by tracker1** [comment]
`nvm install 0.11.14` default node.js
`nvm install node@0.11.14` explicit node.js
`nvm install io@1.0.2` explicit iojs

**Comment by tracker1** [comment]
Should coordinate with https://github.com/creationix/nvm/issues/590 so that the engine syntax is implemented the same...

**Comment by midknight41** [comment]
+1 for io.js

**Comment by MrHyde** [comment]
Just letting you know that nvm implemented and merged support for io.js creationix/nvm/pull/616
and io.js now have standalone builds for win-x86 and x64
https://iojs.org/download/release/v1.0.4/win-x64/

**Comment by coreybutler** [comment]
Thanks for the heads up @MrHyde - the standalone installations definitely make this much more feasible within this project.

I'm currently doing a refactor of the project, mostly just cleanup/organization and a new installer. However; I'll at least implement experimental io.js support when I get through this.

**Comment by jaylinski** [comment]
+1

**Comment by tracker1** [comment]
Thanks @coreybutler support for this would be much appreciated...

**Comment by christoth** [comment]
+1, thanks

**Comment by takueof** [comment]
:+1:

**Comment by iamvdo** [comment]
+1

**Comment by dshook** [comment]
+1.  Thanks for the project

**Comment by gitjhn** [comment]
+1

**Comment by vkbansal** [comment]
An update from @coreybutler from gitter
> Just as an update, I have started work on a 2.x version of this now, but I may release it under a different name since it will be much more robust than the current program. I have not established a release timeline yet, but I am fairly happy with the progress so far, having made many bug fixes for Windows and initial Linux support (OSX is on my mind too). I am committing a lot of time to exploring distribution across all operating systems using tools like yum, apt-get, homebrew, chocolatey, and of course a proper Windows installer.
I will also say that my current plan is still to add iojs support, but I am having hesitations. I've waited, in part, because political issues usually settle given a little bit of time. Since the iojs project is already talking about merging back in with node, it may be a short-lived effort.

**Comment by zxqfox** [comment]
:+1:

**Comment by MetaMemoryT** [comment]
:+1:

**Comment by t-esch** [comment]
:+1: Thanks

**Comment by ryedog** [comment]
:+1:

**Comment by coreybutler** [comment]
Since io.js is [merging back into node](http://blog.nodejs.org/2015/05/15/node-leaders-are-building-an-open-foundation/), there is no longer a need to add special support for it.

**Comment by tracker1** [comment]
@coreybutler sure, wait for a situation to resolve itself... some people are just so lazy... ;-)

**Comment by coreybutler** [comment]
@tracker1 - haha! 

Honestly, I sort of anticipated this... this is the natural pattern. This took about twice as long as I thought it would though!

**Comment by alubbe** [comment]
meh :(
The merge will still take several months, so it's too bad you won't include it.
How is 2.0 generally coming along?

**Comment by coreybutler** [comment]
@alubbe - I posted a quick update on the gitter channel regarding progress.

**Comment by mickae1** [comment]
+1

**Comment by pyhedgehog** [comment]
nvm needed to switch between **different** versions. Changing state of **current** version doesn't removes requirement to support old versions of io.js. Am I wrong?

**Comment by coreybutler** [comment]
@pyhedgehog - NVM needed to switch between different versions of **node**, meaning a distinctly different code base from io.js. Since io.js merged the code base with node, _current versions of node have all of the io.js features in them_.

Basically, you can use old versions of node, but not old versions of io.js.

Does that answer your question?

**Comment by pyhedgehog** [comment]
@coreybutler Yes.
