### ISSUE TITLE
How to uninstall nvm in window？

### ISSUE THREAD

**Issue by z649319834** [coreybutler/nvm-windows#351]
window如何卸载nvm

**Comment by b-dur** [comment]
Yes, that is correct.
When you install a node version with NVM, the node files will be saved into the NVM folder. When you uninstall NVM all of its files and subdirectories will be deleted. Included any node versions you may have installed.

**Comment by z649319834** [comment]
我是使用.exe软件包安装的，使用npm uninstall nvm无法卸载

**Comment by b-dur** [comment]
Hi @z649319834. Sorry I do not understand Chinese - Google Translate translated your message into: 

> I installed using the .exe package, using npm uninstall nvm can not uninstall

Did you run `npm uninstall nvm`? Cause that will not work. NVM is not a node package, but a windows program. So uninstall NVM as you would do with any other windows programs (see @coreybutler answer above).

**Comment by kwzm** [comment]
@b-dur @coreybutler 
Hi, i have the same question, but i didn`t find nvm in my Control Panel, should i remove the nvm folder to uninstall?

**Comment by z649319834** [comment]
@kwzm 
The direct deletion of the NVM folder does not address the underlying problem, and there are records in the registry. If you want to install NVM again later, you may not be able to install it unless you find NVM in the registry completely.

**Comment by b-dur** [comment]
@z649319834 Maybe you never installed nvm. Only used the noinstall zip file.

What you can do to remove any potential values in the windows registry, is to install NVM again and then uninstall it.

**Comment by shearichard** [comment]
In case anyone else finds this useful I came across this SO answer which first suggests using the `Control Panel -> Programs -> Programs and Features`

**Comment by zitanlin** [comment]
Just execute command `nvm unload`. This solve my problem.

**Comment by coreybutler** [comment]
If you're struggling with this, there are a few points to consider:

1. Make sure you've actually installed _this project_. `nvm unload` is **not part of this project**, it is part of https://github.com/nvm-sh/nvm.
2. NVM4W does not install Node the same way the installer from nodejs.org does. See https://github.com/coreybutler/nvm-windows/wiki#uninstall for specific details about removing it.
3. To install a specific version of Node, run `nvm uninstall x.x.x` where `x.x.x` is the version you want to uninstall.
4. Uninstalling the entire NVM4W application using the uninstaller will uninstall _all_ versions of Node that have been installed using the NVM4W utility.

**Comment by mokolotron** [comment]
Also if you cant find nvm in `Programs and Features` you can go to directory where nvm is instaled and run `unins000.exe`

**Comment by jlma81** [comment]
I installed it once via Powershell by Chocolatey, I found the way to uninstall it was by running Powershell as Adminstrator, then checking which version I had by running _nvm list_ , once I got the version I ran _nvm uninstall <version>_ where version is the specific version
I hope this helps.
