### ISSUE TITLE
npm for node v8.11.1 LTS not working in nvm 1.1.6

### ISSUE THREAD

**Issue by devt3000** [coreybutler/nvm-windows#353]
Everytime i run npm, npm -v or npm i <package>, nothing happens, please help?

**Comment by cristianofromagio** [comment]
Windows 10 and nvm v1.1.6, working after a fresh installation. Have you run `nvm use 8.11.1` after the installation? And `nvm on` before `nvm user 8.11.1` if you disabled node.js version management before with `nvm off`.

```bash
PS C:\Users\froma> nvm install 8.11.1
Downloading node.js version 8.11.1 (64-bit)...
Complete
Creating C:\nvm\temp

Downloading npm version 5.6.0... Complete
Installing npm v5.6.0...

Installation complete. If you want to use this version, type

nvm use 8.11.1
PS C:\Users\froma> nvm use 8.11.1
Now using node v8.11.1 (64-bit)
PS C:\Users\froma> node -v
v8.11.1
PS C:\Users\froma> npm -v
5.6.0
PS C:\Users\froma> npm i -g @angular/cli eslint firebase-tools http-server
C:\Program Files\nodejs\ng -> C:\Program Files\nodejs\node_modules\@angular\cli\bin\ng
C:\Program Files\nodejs\eslint -> C:\Program Files\nodejs\node_modules\eslint\bin\eslint.js
C:\Program Files\nodejs\firebase -> C:\Program Files\nodejs\node_modules\firebase-tools\bin\firebase
C:\Program Files\nodejs\hs -> C:\Program Files\nodejs\node_modules\http-server\bin\http-server
C:\Program Files\nodejs\http-server -> C:\Program Files\nodejs\node_modules\http-server\bin\http-server

(...)

+ firebase-tools@3.18.4
+ http-server@0.11.1
+ eslint@4.19.1
+ @angular/cli@6.0.1
added 951 packages in 226.796s
```

**Comment by b-dur** [comment]
@devt3000 Can you provide a bit more details on how you installed NVM and where you are trying to run nvm?
E.g. if you had a command prompt open while installing NVM you need to close it and the command prompt again before the nvm command is accessible

**Comment by devt3000** [comment]
I just installed it normally, the command prompt wasn't open. By the way i can rum nvm on, off and all that but not npm.

**Comment by Kochiya-Yoru** [comment]
My system is Windows7, and nvm version is 1.1.6.
When I install version to start with 8. I get this like below.
```
$ nvm install 8.11.2
Node.js v8.11.2 is not yet released or available.

neohuang@20140417-3880 C:\Users\neohuang
$ nvm install 8
8.0.0
Node.js v8.0.0 is not yet released or available.
```

**Comment by evperedadiaz** [comment]
@devt3000 I recommend uninstalling the version of node 8.11.1 and if you get an error you delete the folder manually, then reinstall the version of node 8.11.1 and test.

If it does not work for you, you may have problems with the nvm root directory.

**Comment by EMCP** [comment]
I am having the same issue, yet my folder has no spaces in it.  I uninstalled `v8.11.1` and tried to upgrade to `v8.11.3` .. same issue occurred as before where i do not get NPM .. the `node_modules/` is empty.

seems something it just fundamentally broken with the install process when it goes to copy the contents of the npm zip file.. but it doesn't show up in the console.

**Comment by devt3000** [comment]
I fixed the problem by deleting the nodes_modules folder in the users directory.

**Comment by coreybutler** [comment]
Per @devt3000's last comment, this seems to be resolved. Reopen if necessary.

Please see https://github.com/coreybutler/nvm-windows/issues/300#issuecomment-332030011 for issues with Node 8.x.x and issue #373 if you're having issues with Node 10.x.x+.
