### ISSUE TITLE
Bug on Windows 10 - after install 

### ISSUE THREAD

**Issue by eliavmaman** [coreybutler/nvm-windows#357]
After install i get : "This is not the package you are looking for: please go to http://nvm.sh"

**Comment by eliavmaman** [comment]
?

**Comment by coreybutler** [comment]
You tried to install nvm for unix. This is NVM for Windows.

**Comment by dark-swordsman** [comment]
Same here, I have a friend trying to install on Windows 10 with the latest 1.17 `nvm-setup.zip` and it gives him this error.

**Comment by AlexSench** [comment]
The reboot of PC helped for me ( windows 10 ).

**Comment by dark-swordsman** [comment]
Sorry if this is irrelevant and it depends on your situation, but I swapped over to WSL with Ubuntu 18.04.2 LTS and it's a breeze. Everything just works as if I was developing directly on Ubuntu.

Should solve a lot of your NVM and Node problems.

**Comment by yotech1324** [comment]
i am getting this error in windows 11
what should i do please tell me

**Comment by nd-roy** [comment]
> You tried to install nvm for unix. This is NVM for Windows.

**Comment by Dreier14** [comment]
I am facing the same and opened a issue, I AM NOT USING THE LINUX OR MAC version of NVM
