### ISSUE TITLE
Tested with proxies?

### ISSUE THREAD

**Issue by jefff888** [coreybutler/nvm-windows#36]
I am having trouble getting nvm-windows to work with my proxy.

From the nvm settings.txt file, I see that it has set everything in the proxy URL to lower case. That trashed my password and ID.
Second, when I manually edit the settings file (and then verify the proxy URL from the command line), it still fails with a message stating that proxy authentication is required.

I am using a proxy URL of the form http://userid:password@host.name:port#

This same string works in npm and git. Does your implementation expect something different?

**Comment by coreybutler** [comment]
This format should work... NVM just delegates the proxy request to the operating system, so I'm not sure what the issue is off the top of my head. I'll look into this as soon as I can.

**Comment by jefff888** [comment]
Cory,

Thanks, I will look into is on my system and try to find out why it fails. What I would ask is that the case of the proxy statement should be be left as the user defined it.


Jeff

-------- Original message --------

**Comment by coreybutler** [comment]
@jefff888 - I've tried, but I cannot recreate an error with this format. Have you found anything new? Which version of Windows are you running this on?

**Comment by jefff888** [comment]
Cory,

Sorry for the delayed reply. I have started having problems with proxies 
all over the place (NPM, Ruby Gems, github, etc.), so I think it has 
more to do with my office's security than anything else. The only 
problem I really see at this point was the case change issue I mentioned.

Jeff

**Comment by coreybutler** [comment]
@jefff888 - Thanks for reminding me about the case issue, I forgot about that. I'll leave this open until that's fixed.

**Comment by coreybutler** [comment]
Better (extremely) late than never.... case sensitivity for proxies was removed in the master branch.
