### ISSUE TITLE
Error while downloading nodejs 8.11.2

### ISSUE THREAD

**Issue by fishwjy** [coreybutler/nvm-windows#361]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [v] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [v] My Windows installation is non-English.

### I'm using NVM4W version:

- [ ] 1.1.6
- [v] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [v] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [v] verified I'm using an account with administrative privileges.
- [v] searched the issues (open and closed) to make sure this isn't a duplicate.
- [v] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [v] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Download and install nodejs/npm successfully

### Actual Behavior

GitBash give this error:

**$ nvm install 8.11.2
Downloading node.js version 8.11.2 (64-bit)...
Error while downloading https://nodejs.org/dist/v8.11.2/win-x64//node.exe - stream error: stream ID 7; INTERNAL_ERROR
Complete
Creating C:\Users\admin\AppData\Roaming\nvm\temp
Downloading npm version 5.6.0...**

### Steps to reproduce the problem:

Just input this command line:
**$ nvm install 8.11.2**

**Comment by fishwjy** [comment]
Oh, I have solved this problem. I must use mirror url of node and npm because I'm in China. ^_^

**Comment by ocramot** [comment]
Hello, how did you solve this problem? What mirror url did you use? how did you put it and where? Any detail useful for other people with the same problem?
