### ISSUE TITLE
Feature request: Migrating packages

### ISSUE THREAD

**Issue by hoegge** [coreybutler/nvm-windows#362]
Thanks for NVM for Windows. Would it be possible to implement the same feature as NVM has, that migrates global packages too?

[https://github.com/creationix/nvm#migrating-global-packages-while-installing](url)

**Comment by hoegge** [comment]
Actually just changed from Node 8.8.1 to 8.10 and the installed global packages are the same. That should not be the case, or?

**Comment by petervangennip** [comment]
Which command did you run?

**Comment by hoegge** [comment]
Two years ago? :-D I'd guess install and then use. Are there other ways?

**Comment by 46511dedi** [comment]
Referensi kepada saya agar dapat menjalankan perintah? 
Saya belum memahaminya..
,😉😉

**Comment by 46511dedi** [comment]
Reference to me to be able to run the command?
I do not understand it ..
, 😉😉

**Comment by petervangennip** [comment]
> Two years ago? :-D I'd guess install and then use. Are there other ways?

Haha, yeah was just wondering how this was possible since the whole issue list is full of people screaming for this feature

**Comment by hoegge** [comment]
Well, as I remember it the packages for some reason was still there after changing which should normally not be the case. Hence the question.

**Comment by 46511dedi** [comment]
### _****_
``
@petervangennip 
Jika mendapati masalah sekalipun kecil, ada baiknya bertanya, seperti mrminta fitur untuk di migrasi? agar semua menjadi baik.

**Comment by 46511dedi** [comment]
### _****_
``
@petervangennip 
Jika mendapati masalah sekalipun kecil, ada baiknya bertanya, seperti meminta fitur untuk di migrasi? agar semua menjadi baik.

**Comment by petervangennip** [comment]
I really don't understand this man

**Comment by coreybutler** [comment]
Migrating packages is non-trivial, and conceptually it is far more about the npm ecosystem than it is about Node.

The biggest problems are native modules, some of which only work on specific architectures (32 vs 64 bit). It is also possible to specify a minimum and even maximum version number for a module. This means diving into the package.json file to determine when something can or cannot be migrated.

The other problem is the footprint size. If you migrate modules onto a SAN or network drive, you can be moving/adding many GB of data at a time. This can be exceptionally slow on some networks.

I know nvm for *nix has this, but the nature of the most common Windows environments are significantly different. I don't really see this being added to this tool, but I have been experimenting with some migration concepts in the successor project (code named "rt", not public at the moment). I can't guarantee migrations will make it in, but it's certainly on the table.
