### ISSUE TITLE
[Feature Request] Portable version

### ISSUE THREAD

**Issue by thereisnotime** [coreybutler/nvm-windows#363]
It would be great if there was a portable version, just like:
https://github.com/garethflowers/nodejs-portable
or
https://github.com/crazy-max/nodejs-portable

**Comment by coreybutler** [comment]
Interesting idea... but I'm not sure this would really be practical. Portability requires precompilation of the Node executables, so they'd all have to be packaged ahead of time.

**Comment by yougotwill** [comment]
I have a hacky solution for this for those who need it. I used portable Cmder but I imagine any terminal program where you can add to the `PATH` is fine.

1. Install Cmder in your desired location.
2. Download `nvm-noinstall.zip` from the [latest release](https://github.com/coreybutler/nvm-windows/releases/latest).
3. Extract the contents of  `nvm-noinstall.zip` into the `bin` folder inside of the portable Cmder folder.
4. Navigate to the *bin* folder in Cmder and run `install.md`
5. When asked enter the absolute path to your Cmder `bin` folder. (In my case, for some reason the `settings.txt`  isn't created in the `bin` folder but instead is made at top level of my usb i.e. `E:/` ).
6. Install the version of node you want i.e. `nvm install latest` (Make sure to still be inside of the `bin` folder).
7. Wait until node and npm have been installed.
8. Inside the `bin` folder there should be a folder containing the latest node version e.g. `v13.8.0`.
9. Copy the absolute path to the node folder. e.g. `E:\PortableApps\CmderPortable\bin\v13.8.0`.
10. Add this to your existing path in Cmder's environment settings. e.g. `set "PATH=E:\PortableApps\CmderPortable\bin\v13.8.0;%PATH%"`
11. Close and open Cmder and you should have access to `node`, `npm` and `npx` 😄

**Comment by hagbid** [comment]
Hi @yougotwill ,
Do you know how to change the strange behavior of creating the settings.txt in the root? On my corporate computer it tries it in C:\ but that is blocked by rights.

**Comment by yougotwill** [comment]
Hey @hagbid, I installed everything on a USB drive so my root was E:\ not C:\. You probably need to install Cmder on the drive you want to use and not run your commands from C:\. 

Alternatively looking at the source code you could change the NVM_HOME environment variable? Haven't confirmed if that works.
