### ISSUE TITLE
Node v#.##.## not installed

### ISSUE THREAD

**Issue by fpatros** [coreybutler/nvm-windows#37]
I am a newbie on this so bare with me.

Trying to switch between node installations does not work. When using `nvm list` it shows all the installed versions.
![image](https://cloud.githubusercontent.com/assets/1079247/5794628/9fe098b8-9f44-11e4-8748-8fc642359b07.png)

But when trying to switch to another version, it says it is not installed.
![image](https://cloud.githubusercontent.com/assets/1079247/5794638/f7efeffe-9f44-11e4-8955-2633cafbbb07.png)

I figured I was doing something wrong so I tried to specify an architecture. Still nothing.
![image](https://cloud.githubusercontent.com/assets/1079247/5794641/1806ef7c-9f45-11e4-8ce0-e0d7959f9344.png)

But if I keep re-installing then switching, then it works.

Running Windows 8.1
nvm installed on c:\
root set to c:\nvm

Issue #30 maybe related.

And thanks btw for this. Really great piece of software @coreybutler .

**Comment by fpatros** [comment]
Well, after trying several times by re-installing each time, now it seems to work.

I have no idea what happened here....

**Comment by coreybutler** [comment]
@fpatros - I actually think this specific issue is related to issue #23. I have not yet had a chance to add the `file.exe` to the distribution (the resolution for that issue), but it might resolve your problems. The key indicator here is the `?-bit`... it should read `32-bit` or `64-bit`.

If you install to the `default` user directory, it should theoretically work for all users.

**Comment by fpatros** [comment]
Thanks for the prompt reply @coreybutler 

I always thought when you install in the `roaming` folder of a user, that user is the only one able to access them, save, an administrator can access everything.

The way I set up my computer is to have an admin account which I do all my installations through, but work through a user account.

Even when I installed aptana studio I installed it on the `c:\` drive for that reason.

Installed `nvm` on the `c:\` drive and logged in with the normal user account to use it. The only issue that I can find at the moment is that when I use `nvm use 0.10.35` the windows UAC pops up asking me to authenticate. If I authenticate with user account, it shows that it makes the switch but it actually doesn't. I test this by typing `node -v` which spits out `'node' is not recognized...`. If I redo it but authenticate with the admin account, then no problems. Doing other things such as `nvm install 0.11.14` under the normal user account seems to work no problem because I see the folder with all the files being created. I don't know whether or not going in as admin and allowing `Full Control` access under `Security` will do anything considering I am able to `Write' to this folder without that being the case.

![image](https://cloud.githubusercontent.com/assets/1079247/5795856/d97b9582-9f67-11e4-8e3d-03eb618d6f71.png)

`System Variables` for both accounts show `nvm` and `symlink`. But only the admin shows those same variables for the `Environment Variables`. Adding these `variables` to the `Environment Variables` for the user account does not solve the above problem either.

**Comment by romualdr** [comment]
I'm also on Win 8.1 64bits and i ave the same issue. I'll try to reinstall and get some logs for you guys

**Comment by romualdr** [comment]
So after a while trying to play with the code and Go (which is a good language i must say), i found that actually the bug is in /src/arch/arch.go -> arch.Bit. exec.Path say that the file is not not found.

"file" exec doesn't seems to exist in Windows 8.1 or well, go doesn't handle it (more info here: https://github.com/skratchdot/open-golang/issues/4) so this is a Windows 8.1 issue only. Also GNUFile for Windows crashes on Windows 8.1 (and that's probably the issue here).

The workaround the folks found on the issue above is good, but here we only want to know which arch the file is, so i created a workaround who simply read the first bytes until he found a correct architecture.

PR in a minute

**Comment by coreybutler** [comment]
I've already fixed this in the next version.

**Comment by g0t4** [comment]
FYI, if you had node installed before, delete C:\Program Files\nodejs and nvm windows will create the symlink

**Comment by Adam13531** [comment]
I just ran into this issue too. Corey did indeed fix it two weeks ago, but the release listed on the GitHub is from 5 months ago, so here are instructions on how to build nvm-windows yourself:

1. Download this GitHub repo, e.g. as a zip from [here](https://github.com/coreybutler/nvm-windows/archive/master.zip).
2. Download [Go](https://golang.org/dl/) if you don't already have it.
3. Navigate to the root of the nvm-windows-master directory. This is the project root.
4. Open nvm.iss and set ProjectRoot to the directory from above.
5. Open CMD and navigate to the project root.
6. Type "build".
7. Run the installer in <project root>\dist\<version>\nvm-setup.exe

@coreybutler - thanks for the project! I suggest adding build instructions to the README and perhaps updating your latest release with a new installer.

**Comment by coreybutler** [comment]
@Adam13531 - The latest code in master has not been tested as a release, and I have no plans to do so... mostly because I am working on a much improved version of this project. See the Gitter feed for more information.

I'll add these instructions to the wiki along with the other installer instructions in the interim.

**Comment by JeffHerb** [comment]
Not sure if this is the best place, but the `nvm use latest` also appears to be broken in the latest release. Whenever I try the command it always returns the following error:

**Comment by coreybutler** [comment]
`nvm use latest` is not a supported command.... only "npm **install** latest". The use command expects a specific version. The "latest" keyword refers to the latest release, which may or may not be installed on your system. It is not context aware, though that's an interesting idea.

**Comment by JeffHerb** [comment]
Ah. My apologizes. I miss understood its usage. Though it would be an
amazing feature if it could work. In the mean time I will update our
internal scripts to a support release version. Thanks again.

**Comment by coreybutler** [comment]
@JeffHerb - No need to apologize. I think this could be a useful context to expand into for the next version. It's not something I thought about, but it's on my radar now.

**Comment by romualdr** [comment]
The latest version looks like helping a lot of persons.

Maybe you could update the README to prevent recurring issues like this ? Like putting a link to this thread with a message : "If you have trouble, get the lateste repo version and try" ?

**Comment by giggio** [comment]
I am also having the `node v0.12.5 (64-bit) is not installed.` problem. I am using NVM 1.0.6, which is the latest.
Only when I reinstall a version is that I am able to `use` it.
@coreybutler This bug has been open for very long. Do you need help on fixing it? Do you need any logs or help on checking something? Let us know.

**Comment by coreybutler** [comment]
@giggio - See the gitter feed, announcement on July 11.

**Comment by giggio** [comment]
@coreybutler Got it.

**Comment by coreybutler** [comment]
Not sure why this is still open. It was fixed a long time ago.
