### ISSUE TITLE
NPM github repo is moving from npm/npm to npm/cli and it causes NVM to fail to install it

### ISSUE THREAD

**Issue by PlanetVaster** [coreybutler/nvm-windows#373]
NPM is moving from https://github.com/npm/npm to https://github.com/npm/cli and it causes nvm installing node 10.8.0 and higher (which uses npm 6.2.0) to fail to install npm (because npm 6.2.0+ are only on the new repo).

**Comment by coreybutler** [comment]
Fixed in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.7

**Comment by Doehl** [comment]
I have just downloaded and installed the setup file from tag 1.1.7. But it have installed the 1.1.5 version.
I had not nvm-windows installed before.

**Comment by 7sDream** [comment]
same here, install use [nvm-setup.zip](https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.zip) in 1.1.7 release page, but I got a 1.1.5 version nvm and it's modify time is "2017.5.31".

**Comment by coreybutler** [comment]
@Doehl, @PlanetVaster, @7sDream - A new binary was uploaded... you should see 1.1.7 now. Sorry for the late notice (it's been up for awhile).

**Comment by Zhou-Bill** [comment]
i have the same issues and i have use nvm for 1.1.7,but  i not for me 

![Uploading image.png…]()

**Comment by yashdabi** [comment]
**Fixed**
`nvm install 10.16.3`
will show error - **Could not download npm for node v10.16.3.**
download npm version what you want  - https://github.com/npm/cli/releases
I had downloaded 6.9.0 npm version - https://github.com/npm/cli/archive/v6.9.0.zip
It should be extracted to `C:\Users\xxx\AppData\Roaming\nvm\v10.16.3\node_modules\npm`

then go to  `C:\Users\xxx\AppData\Roaming\nvm\v10.16.3\node_modules\npm\bin` and copy two npm files. first (npm  .cmd file), second (npm file)
then paste both files in `C:\Users\xxx\AppData\Roaming\nvm\v10.16.3`

open cmd and run command `node -v` and `npm -v`

**Comment by EmiyaYang** [comment]
> **Fixed**
> `nvm install 10.16.3`
> will show error - **Could not download npm for node v10.16.3.**
> download npm version what you want - https://github.com/npm/cli/releases
> I had downloaded 6.9.0 npm version - https://github.com/npm/cli/archive/v6.9.0.zip
> It should be extracted to `C:\Users\xxx\AppData\Roaming\nvm\v10.16.3\node_modules\npm`
> 
> then go to `C:\Users\xxx\AppData\Roaming\nvm\v10.16.3\node_modules\npm\bin` and copy two npm files. first (npm .cmd file), second (npm file)
> then paste both files in `C:\Users\xxx\AppData\Roaming\nvm\v10.16.3`
> 
> open cmd and run command `node -v` and `npm -v`

That's it.

**Comment by AhammadAliPK** [comment]
@yashdabi sorry to say that it is not working for me . The below folder is empty 
`
C:\Users\xxxxx\AppData\Roaming\nvm\v10.13.0\node_modules `

**Comment by yashdabi** [comment]
> @yashdabi sorry to say that it is not working for me . The below folder is empty
> `C:\Users\xxxxx\AppData\Roaming\nvm\v10.13.0\node_modules`

@AhammadAliPK download the npm from https://github.com/npm/cli/releases and then the downloaded file extract into` C:\Users\xxxxx\AppData\Roaming\nvm\v10.13.0\node_modules\npm`

then see my above answer

**Comment by ZiuChen** [comment]
@yashdabi 

Execllent work! It helps me alot. Thank you!!! 💖

**Comment by loyanhakan** [comment]
Firstly uninstall current nvm datas from pc(if required include user\AppData\Roam\nvm folder and C:\programfiles\nvm folder too). 

After just downloaded the https://github.com/coreybutler/nvm-windows/releases/tag/1.1.12 

It fixed on my pc hope it will help
