### ISSUE TITLE
Node.js vgulp-cli.0.0 is only available in 32-bit

### ISSUE THREAD

**Issue by westerdaled** [coreybutler/nvm-windows#376]
Hi

Just installing NVM 1.1.7 on a client supplied dev machine ( had to set the proxy for this to work)

```

PS C:\windows\system32> nvm install 8.11.3
Version 8.11.3 is already installed.

PS C:\windows\system32> nvm use 8.11.3
Now using node v8.11.3 (64-bit)

PS C:\windows\system32> nvm install gulp-cli -g
gulp-cli.0.0
Node.js vgulp-cli.0.0 is only available in 32-bit.
```

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [x] OTHER (Please Specify) 1.1.7

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior
I shouldn't get an error ( this works fine on my personal dev laptop with 1.1.6)

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

See above error

**Comment by coreybutler** [comment]
You're running `nvm install gulp-cli`. I think you meant `npm install -g gulp-cli`. However; nvm4w should probably have a better error message. I'm leaving this open so a better error message will be part of the task list for 1.1.8.

**Comment by westerdaled** [comment]
Thanks for your reply. I found out npm wasn't installed correctly so resinstalled this and then ran the correct commandline 

```
C:\Program Files\nodejs\gulp -> C:\Program Files\nodejs\node_modules\gulp-cli\bin\gulp.js
+ gulp-cli@2.0.1
added 235 packages in 17.142s
```

**Comment by ganesansnkr-philips** [comment]
Still I was facing the issue in 1.1.7 also, any ideas or other workaround

**Comment by coreybutler** [comment]
@ganesansnkr-philips this isn't an nvm4w issue. NVM doesn't install packages, that's a job for n**p**m.
