### ISSUE TITLE
1.1.7 nvm-noinstall.zip?

### ISSUE THREAD

**Issue by barik** [coreybutler/nvm-windows#379]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.
### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

The Wiki indicates that there is a `nvm-noinstall.zip` for releases.

### Actual Behavior

However, for 1.1.7 this asset does not seem to be published.

### Steps to reproduce the problem:

See: https://github.com/coreybutler/nvm-windows/releases

**Comment by coreybutler** [comment]
Good catch. Apparently I mistakenly removed it. I'll publish the no-install version as soon as I can.

**Comment by kasajian** [comment]
Here's some code that I use from PowerShell to update the system environment variable:

    $syspath = [System.Environment]::GetEnvironmentVariable("path", "machine")
    $syspath = $syspath + ";C:\Program Files (x86)\WinMerge\;C:\Program Files\KDiff3\;C:\ProgramData\chocolatey\tools\;C:\Program Files\Git\bin;C:\Program Files\Notepad++"
    [System.Environment]::SetEnvironmentVariable("path", $syspath, "machine")
