### ISSUE TITLE
Number pad detection of version

### ISSUE THREAD

**Issue by eyes2design** [coreybutler/nvm-windows#38]
Ok, so I'm installing 0.10.35 64 but when I click enter in the Console it just outputs:
C:\Users\Mairuzu>nvm install v0.10.35 64
Node.js vv0.10.35 is only available in 32-bit. 

but if you hit the numbers in the top row I get:
C:\Users\Mairuzu>nvm install 0.10.35 64
Downloading node.js version 0.10.35 (64-bit)... Complete

This is a bug with the keyboard or my console, or something just weird.

**Comment by vkbansal** [comment]
You don't need to prefix `v` before version.

So `nvm install v0.10.35 64` is wrong

`nvm install 0.10.35 64` is correct

**Comment by coreybutler** [comment]
@vkbansal is correct.
