### ISSUE TITLE
When switching root, commands aren't moved over from AppData. 

### ISSUE THREAD

**Issue by rageycomma** [coreybutler/nvm-windows#381]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [X] A standard shell environment (terminal/powershell) - Powershell
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

When `nvm root` is set to another directory (i.e. `nvm root C:\NVM`), the commands for NVM should be moved over to that directory.

### Actual Behavior

When `nvm root` is run, the other directory is set, and new downloads for Node.js distributions go into that other directory, however, once you run "nvm use", the console command errors saying that the .cmd file is not found in the new directory for root. 

### Steps to reproduce the problem:
1. `nvm root C:\NVM\`
2. `nvm install <version> <arch>`
3. `nvm use <version>`

**Comment by coreybutler** [comment]
This fix will be in 1.1.8 release, but it is available in master right now.
