### ISSUE TITLE
NodeJS release index for 10.8.0 and 10.9.0 is fubar so NVM appears to be broken

### ISSUE THREAD

**Issue by markarnott** [coreybutler/nvm-windows#384]
### Expected Behavior

> nvm install 10.9.0

should install NodeJS version 10.9.0 and its associated NPM

### Actual Behavior

NPM install fails with:
> Downloading npm version 6.2.0... Download failed. Rolling Back.
> Rollback failed. remove C:\Users\Marnott\AppData\Roaming\nvm\temp\npm-v6.2.0.zip: The process cannot access the file because it is being used by another process.

### Steps to reproduce the problem:
The problem comes from the node release index file found here:
https://nodejs.org/download/release/index.json 

That index specifies NPM version 6.2.0, for both NodeJS 10.9.0 and 10.8.0 but no such NPM version exists
https://github.com/npm/npm/releases 

### Work Around ###
>nvm install 10.7.0

and wait for Node 10.10.0 which hopefully will be fixed

**Comment by coreybutler** [comment]
Upgrade to 1.1.7. npm changed their repo.
