### ISSUE TITLE
Are there any plans to support nvm current & nvm run for NVM4W?

### ISSUE THREAD

**Issue by ryan-haksi** [coreybutler/nvm-windows#390]
Are there any plans to support the full command set for NVM?

In our automation the lack of:
nvm run --silent <VERSION> some.js
nvm current

causes compatibility issues.

The non-windows version of nvm has a much larger command set. Including below just for convenience, but much doesnt apply to windows.

```
Node Version Manager

Note: <version> refers to any version-like string nvm understands. This includes:
  - full or partial version numbers, starting with an optional "v" (0.10, v0.1.2, v1)
  - default (built-in) aliases: node, stable, unstable, iojs, system
  - custom aliases you define with `nvm alias foo`

 Any options that produce colorized output should respect the `--no-colors` option.

Usage:
  nvm --help                                Show this message
  nvm --version                             Print out the installed version of nvm
  nvm install [-s] <version>                Download and install a <version>, [-s] from source. Uses .nvmrc if available
    --reinstall-packages-from=<version>     When installing, reinstall packages installed in <node|iojs|node version number>
    --lts                                   When installing, only select from LTS (long-term support) versions
    --lts=<LTS name>                        When installing, only select from versions for a specific LTS line
    --skip-default-packages                 When installing, skip the default-packages file if it exists
    --latest-npm                            After installing, attempt to upgrade to the latest working npm on the given node version
  nvm uninstall <version>                   Uninstall a version
  nvm uninstall --lts                       Uninstall using automatic LTS (long-term support) alias `lts/*`, if available.
  nvm uninstall --lts=<LTS name>            Uninstall using automatic alias for provided LTS line, if available.
  nvm use [--silent] <version>              Modify PATH to use <version>. Uses .nvmrc if available
    --lts                                   Uses automatic LTS (long-term support) alias `lts/*`, if available.
    --lts=<LTS name>                        Uses automatic alias for provided LTS line, if available.
  nvm exec [--silent] <version> [<command>] Run <command> on <version>. Uses .nvmrc if available
    --lts                                   Uses automatic LTS (long-term support) alias `lts/*`, if available.
    --lts=<LTS name>                        Uses automatic alias for provided LTS line, if available.
  nvm run [--silent] <version> [<args>]     Run `node` on <version> with <args> as arguments. Uses .nvmrc if available
    --lts                                   Uses automatic LTS (long-term support) alias `lts/*`, if available.
    --lts=<LTS name>                        Uses automatic alias for provided LTS line, if available.
  nvm current                               Display currently activated version
  nvm ls                                    List installed versions
  nvm ls <version>                          List versions matching a given <version>
  nvm ls-remote                             List remote versions available for install
    --lts                                   When listing, only show LTS (long-term support) versions
  nvm ls-remote <version>                   List remote versions available for install, matching a given <version>
    --lts                                   When listing, only show LTS (long-term support) versions
    --lts=<LTS name>                        When listing, only show versions for a specific LTS line
  nvm version <version>                     Resolve the given description to a single local version
  nvm version-remote <version>              Resolve the given description to a single remote version
    --lts                                   When listing, only select from LTS (long-term support) versions
    --lts=<LTS name>                        When listing, only select from versions for a specific LTS line
  nvm deactivate                            Undo effects of `nvm` on current shell
  nvm alias [<pattern>]                     Show all aliases beginning with <pattern>
  nvm alias <name> <version>                Set an alias named <name> pointing to <version>
  nvm unalias <name>                        Deletes the alias named <name>
  nvm install-latest-npm                    Attempt to upgrade to the latest working `npm` on the current node version
  nvm reinstall-packages <version>          Reinstall global `npm` packages contained in <version> to current version
  nvm unload                                Unload `nvm` from shell
  nvm which [current | <version>]           Display path to installed node version. Uses .nvmrc if available
  nvm cache dir                             Display path to the cache directory for nvm
  nvm cache clear                           Empty cache directory for nvm

Example:
  nvm install 8.0.0                     Install a specific version number
  nvm use 8.0                           Use the latest available 8.0.x release
  nvm run 6.10.3 app.js                 Run app.js using node 6.10.3
  nvm exec 4.8.3 node app.js            Run `node app.js` with the PATH pointing to node 4.8.3
  nvm alias default 8.1.0               Set default node version on a shell
  nvm alias default node                Always default to the latest available node version on a shell
```

**Comment by coreybutler** [comment]
No. This project has never intended to be a clone of nvm.

I'm planning to rename the project to avoid confusion (in 2.0.0). This project has a different philosophy from nvm... it's more akin to n than it is nvm. You can see the discussions around the different philosophies in the issues at https://github.com/nodejs/version-management.

**Comment by slikts** [comment]
I don't understand the rationale for not supporting `nvm-exec`; it would allow using multiple node versions in parallel, which is an essential use case for nvm that's not currently supported by this tool.

**Comment by coreybutler** [comment]
This is spelled out in the README, see https://github.com/coreybutler/nvm-windows#why-another-version-manager.

I disagree that this is an essential use case, but it is clearly a popular one. Node itself was never designed for per-shell, per-execution, or other virtualized operations. Node is designed as a runtime to be installed on an operating system as a system-wide executable. Currently, containerization is a more appropriate technology for virtualizing environments.

The Windows environment is significantly different with far more edge cases to support, especially when it comes to permissions. That said, I'm not unsympathetic towards the use case & value proposition people see. I just don't feel version management is the appropriate place to address this issue, and it's certainly not proving to be sustainable (translation: lack of money/time).

That said, the demand has inspired me to work on this from a different angle. I have a small team of cofounders working on a commercial environment virtualization tool, alongside a handful of individuals and companies who have expressed interest. It's well beyond just Node, so I have no ETA yet. I'm hopeful we'll have something to release late spring or early summer of 2020. With funding and resources, these types of use cases (and _many_ more) can be properly supported and even enhanced.

**Comment by slikts** [comment]
node is agnostic towards being installed system-wide or locally, and nvm is the precedent for node working fine installed locally and in parallel. This tool reuses nvm's name without supporting a core use case. Running parallel versions, not just installing them, should be straightforwardly within the scope of version management.

Using Docker just for parallel node versions is like shooting flies with a canon; it's overkill. For example, Docker can't just be installed on Windows because it also requires Hyper-V, which in turn requires hardware virtualization being enabled in the BIOS, and Hyper-V turns Windows itself into a guest OS and adds non-insignificant overhead to all applications, and Hyper-V also isn't compatible with certain other virtualization software.

The reason running parallel node versions is a common use case is because major node versions are not ABI compatible, and a lot of functionality is available only as native modules.

I'd recommend renaming this to something other than nvm.

**Comment by coreybutler** [comment]
The stock Node installer always installs system-wide or per user profile. It is not installed per-shell or per command.

I've spoken with both Tim (original nvm creator) and Jordan (current maintainer of nvm-sh) about the naming... right from the beginning, several years ago. There is a reason it is called NVM _for Windows_ and not just nvm. Regardless, you can read plenty of old issues or the roadmaps where I've clearly spelled out my intent to rename the project in the next major release. The distinction is made right at the top of the README.

nvm-sh is not the only precedent. n was released in the same timeframe as nvm. Point: There has been precedence for the different philosophies since the early days of Node.

Docker isn't the only containerization game in town. It's merely an example.

**Comment by slikts** [comment]
node installers being system-wide isn't a function of node's design but just OS conventions, and those installers are for more basic use cases. nvm is a precedent for node not needing to be system-wide. Other tools that precede node like pyenv and rbenv also are user level. Containerization as a whole is overkill just for managing parallel versions, so it's not specifically about Docker.

It'd be understandable if it were about technical limitations preventing an important core use case, but not if it's about "philosophy".

**Comment by coreybutler** [comment]
Obviously you're entitled to your opinion and I my own. 

I'm closing this issue from comments because this is not the appropriate forum for these kinds of conversations.
