### ISSUE TITLE
npx -v returns incorrect version

### ISSUE THREAD

**Issue by epikhighs** [coreybutler/nvm-windows#395]
### My Environment

- [ x] Windows 10

### I'm using NVM4W version:

- [ x] 1.1.7

### My issue is related to (check only those which apply):

- [x ] A standard shell environment (terminal/powershell)

### Expected Behavior

Using nvm 1.1.7, i installed node 8.12.0.  I expected executing `npx -v` to return `10.2.0` as found in (C:/nvm/v8.12.0/node_modules/npm/node_modules/libnpx/package.json:1). 

### Actual Behavior

But instead `npx -v` returns `6.4.1`, which is the same version as `npm -v`. Note that there is no v 6.4.1 of npx.  6.2.0 was the latest 6.x release for npx (https://github.com/zkat/npx/blob/latest/CHANGELOG.md#620-2017-06-23)

### Steps to reproduce the problem:

1. install nvm 1.1.7
2. install node 8.12.0
3. run `npx -v`

**Comment by coreybutler** [comment]
This would appear to be an issue with npx reading the package.json file. _Executing_ npm/npx doesn't touch NVM4W code _at all_. NVM4W [copies the the original npx.cmd file to the npm directory](https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L281) during the install proess, then it's completely hands off/up to npx.
