### ISSUE TITLE
help function not working properly: doesn't open help page

### ISSUE THREAD

**Issue by chmerk** [coreybutler/nvm-windows#397]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior
First of all: thank you very much for making and supporting this! Really great! :-)

The "standard" npm help functionality is that, when typing in `npm help <command>` it opens the related help page of the npm docs in the browser.
For example https://docs.npmjs.com/cli/update for `npm help update`

### Actual Behavior

Since installing nvm, it doesn't open the webpage but instead shows a list of possible topics with "hits" of the keyword. 
```
$ npm help update
Top hits for "update"
————————————————————————————————————————————————————————————————————————————————
npm help update                                                     update:16
npm help config                                                       update:8
npm help package-locks                                          update:7
npm help outdated                                                  update:5
npm help install                                                       update:4
npm help hook                                                        update:4
npm help semver                                                     update:4
```

This is the functionality of `npm help-search <text>` function (which does work and produces the exact same output)!

### Steps to reproduce the problem:

1. Open Terminal (e.g. cmd, git-bash,...)
2. Check if npm is installed/activated...: npm -v
3. Search help for function e.g. `npm help update` or `npm help install`

### Further info
I tested this in different shells, with / w/o admin rights and with node versions 8.12.0 or 10.11.0 activated.

More than the actual solution of this bug, I would be interested in an explanation of the behavior as I wouldn't have expected a different behaviour of npm "natively" installed and through nvm  :-)

**Comment by coreybutler** [comment]
This has nothing to do with NVM4W. `npm help` is run under the node process, which NVM4W doesn't touch _at all_.

Just to make sure, you're actually using NVM4W, right? It's not possible to have more than one version activated at the same time (though I read that as "I tested them separately", so I assume you meant this project). 

npm v5.2-6ish is pretty broken with some of these commands, but the truth is I don't know why this is occurring. NVM4W literally only leaves a symlink... npm runs under the node.exe context, not the nvm.exe context.... so running `npm help` doesn't touch NVM4W at all.

**Comment by Dudeonyx** [comment]
I have the same issue.

I swear it worked before I installed nvm yesterday.

**Comment by chmerk** [comment]
Hey, sorry for my late reaction.
@coreybutler: Thanks for your reply. Yes, sure I'm using NVM4W ;-)
Ok, that's really weird... :-/

Thanks @Dudeonyx! That means 1. I'm not crazy and 2. it's probably not a "super rare special case" for my system :-)

I'm pretty busy right now, but maybe I can investigate it a little further next month or so.
So long!

**Comment by chmerk** [comment]
i just discovered (by chance) that when using e.g. node version 9.4.0 the behaviour is correct again: When typing e.g. "npm help install" it opens the help page for npm-install in my web browser.
When doing the same thing with node v8.12.0 it (wrongly) lists the help search results for "install" in the console.
(Both running with npm v6.4.1).

So, I guess the ticket can be closed as it's probably obsolete.

Curious observation: I'm 85% sure, before installing nvm the command opened the online help page, e.g. https://docs.npmjs.com/cli/install.html), now it opens a local version somewhere in the nvm directory (file:///C:/Users/.../AppData/Roaming/nvm/v9.4.0/node_modules/npm/html/doc/cli/npm-install.html)

Thanks anyway! :-)

**Comment by coreybutler** [comment]
Node 8.x uses the npm 5.x branch, which has alot of nuances. One nuance which causes alot of headaches, is the fact they hard-coded a few paths into that version of npm. They also _explicitly_ ignored symlinks in some cases, which caused issues with `npm update` (deleting files on a symlink path). That has since been removed, but it would explain why it works without a version manager but not with one... and also why newer/older versions would work, but not the 8.x branch.

**Comment by james-world** [comment]
FYI: After clearing node of my Windows 10 machine and installing nvm4w and ndoe 10.16.0, I am experiencing this issue, so perhaps it's been reintroduced.
