### ISSUE TITLE
Fix exec paths to work with Windows

### ISSUE THREAD

**Issue by JamesJansson** [coreybutler/nvm-windows#399]
If you have a space in your path (e.g. a space in your user name, a common occurrence in Windows) 
e.g.
C:\Users\James Jansson\Documents\GitKraken\project-name>nvm use 10.12.0
exit status 1: 'C:\Users\James' is not recognized as an internal or external command,
operable program or batch file.

You will have a failure. Suggest quote marks to be added around path in exec command.

https://github.com/coreybutler/nvm-windows/blob/0a258f810d13eb20c56f6bebe575cd7451348d03/src/nvm/node/node.go#L24

**Comment by coreybutler** [comment]
This issue is already resolved in the master branch, which is tentatively v1.1.8 (i.e. the next release). See #355.

**Comment by nealoke** [comment]
@coreybutler is it possible to already use the latest version where this is fixed? Because now I can't use it 😢
