### ISSUE TITLE
Unable to Install v.12.0 in windows 32 bit machine 

### ISSUE THREAD

**Issue by byteshiva** [coreybutler/nvm-windows#40]
I'm unable to install v.12.0 in windows 32 bit machine.

![image](https://cloud.githubusercontent.com/assets/10637299/6133250/a5dd3888-b17e-11e4-97d4-a70c3110dfd1.png)

Also note that v.12.0 was released on feb 6

![image](https://cloud.githubusercontent.com/assets/10637299/6133316/101fed9e-b17f-11e4-98e9-a90695d7a061.png)

**Comment by coreybutler** [comment]
That's because your syntax is incorrect. 

It should be `nvm install 0.12.0 32`... not nvm install **v**0.12.0 32

**Comment by byteshiva** [comment]
Thanks for the correction it worked.
My bad, I just followed the nvm *nix way of installation, there it expect string "v" prior the version number.

**Comment by vkbansal** [comment]
@coreybutler this a common mistake. I feel that this should be tackled. what do you say?
