### ISSUE TITLE
wrong version installed by Scoop

### ISSUE THREAD

**Issue by DanielRuf** [coreybutler/nvm-windows#400]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [x] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Latest release should be 1.1.7

### Actual Behavior

Latest release seems to be 1.1.6

### Steps to reproduce the problem:

```
Daniel@Daniel-MSI MINGW64 ~
$ scoop install nvm
Installing 'nvm' (1.1.7) [64bit]
Loading nvm-noinstall.zip from cache
Checking hash of nvm-noinstall.zip ... ok.
Extracting nvm-noinstall.zip ... done.
Running pre-install script...
Linking ~\scoop\apps\nvm\current => ~\scoop\apps\nvm\1.1.7
Creating shim for 'nvm'.
Persisting nodejs
Persisting elevate.cmd
Persisting elevate.vbs
Persisting settings.txt
'nvm' (1.1.7) was installed successfully!
Notes
-----
You'll need to restart powershell/cmd to have it reload Environment Variables
so nvm will work correctly

Daniel@Daniel-MSI MINGW64 ~
$ nvm version
1.1.6
```

**Comment by coreybutler** [comment]
This should be taken up with the scoop team. It looks like they picked up on a pre-release.

**Comment by DanielRuf** [comment]
Sorry forgot to close this one. It seems there was already an old release of nvm installed (with the installer) and the new one which came last in $PATH was not used. Removed both, reinstalled the new one and now it is the latest release.

`which nvm` lead me to the path of the version by the nvm installer (different than the noinstall one).

**Comment by DanielRuf** [comment]
Imo nvm should warn in this case and provide an option to upgrade / migrate existing installs, cancel the install or suggest the reoval of the old / duplicate installs.

**Comment by DanielRuf** [comment]
See https://github.com/lukesampson/scoop/issues/2670
