### ISSUE TITLE
Alias for latest lts/non-lts/major

### ISSUE THREAD

**Issue by thany** [coreybutler/nvm-windows#402]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

I tried to install with `nvm install`, `nvm install node` and `nvm install latest`. I would expect one of these to install the latest version of Node.js. I would also expect `nvm install 10` to install the latest 10.x.

Fixing `nvm install node` would be in line with [nvm](https://github.com/creationix/nvm) even though it is a different thing - it *is* what mac/linux people use in place of nvm4w and having (mostly) identical commands will reduce confusion.

### Actual Behavior

When I run `nvm install node`, it says:
```
node.0.0
Node.js vnode.0.0 is only available in 32-bit.
```

When I run `nvm install 10` it installs 10.0.0, which might not what one woud expect.

### Steps to reproduce the problem:

Try the commands mentioned.

**Comment by vinils** [comment]
nvm use $(nvm ls) works in powershell

**Comment by tats-u** [comment]
I have already created the following PRs:
- https://github.com/coreybutler/nvm-windows/pull/469 (support for  installation of LTS)
- https://github.com/coreybutler/nvm-windows/pull/468 (fix of bug X.0.0 are installed)

However, they seem not to be merged.

**Comment by thany** [comment]
> nvm use $(nvm ls) works in powershell

Maybe so, but it's important to keep the syntax identical to the original nvm, when working together in one project with folks on a Mac or Linux. That way, there can be no confusion as to what commands to use on nvm.
