### ISSUE TITLE
nodejs for windows and wsl using nvm-windows

### ISSUE THREAD

**Issue by rweller59** [coreybutler/nvm-windows#408]
- [x] Windows 10

- [x] 1.1.7

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ ] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

I need to be able to use nodejs for windows alongside of nodejs for wsl (linux). Was hoping to use nvm-windows to manage this but I cannot figure out how to have nvm-windows install linux version. Is this possible?

**Comment by coreybutler** [comment]
This is not currently possible. NVM for Windows will only manage Node.js on Windows. For now, I recommend using n for Linux, which follows the same principles as NVM4W (though the syntax are a little different).

I built a cross-platform version of this almost two years ago, and I still intend to release it. However; I am currently the only one working on it, most of which is spent answering questions or fixing issues (some additional maintainers are also helping with questions). I get very little time to do new development, so there is no planned release date other than "when I get to it" :-( That said, my current contract ends in mid-January and we're wrapping up my other major project [Fenix 3](https://preview.fenixwebserver.com) very soon, so hopefully I'll have more time for this starting next quarter.
