### ISSUE TITLE
NPM is not installed with Node in NVM v1.1.6

### ISSUE THREAD

**Issue by samriddhi** [coreybutler/nvm-windows#409]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [ ] 1.1.7
- [X] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Typing in `nvm install 10.14.1` installs both node and npm at the same time.

### Actual Behavior

Typing in `nvm install 10.14.1` installs both node but throws an error on the npm install hence not working.

![screenshot_3](https://user-images.githubusercontent.com/5325345/49711476-629f5000-fbf4-11e8-9018-622a92a3ffa5.png)

### Steps to reproduce the problem:

1. Installed v 1.1.6 of nvm on my machine 
2. Checked to make sure nvm is installed with admin rights
3. Install node using nvm install 10.14.1 and nvm install latest
4. The message saying it cannot install npm
5. Install npm as the message says in the screenshot, however, it still does not work

**Comment by LeeRayno** [comment]
I also encountered the same problem.

**Comment by coreybutler** [comment]
npm changed the address of their repo. Upgrade to NVM 1.1.7.
