### ISSUE TITLE
Windows 1809 symlink issues

### ISSUE THREAD

**Issue by cp-fabian-pittroff** [coreybutler/nvm-windows#412]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Actual Behavior 

With Windows 1809 the symlinks seems to have a little delay until they are fully there. Our Build Servers are running the following commands 
```
nvm install x.x.x
nvm use x.x.x
npm install
```
After the nvm use, the symlink resets and npm is not a known command. After some time the symlink is present in the filesystem and the npm commands works again.

### Expected Behavior

After using nvm use x.x.x the command should wait until the symlink is present in the filesystem, to avoid issues with not finding npm and node. 

### Steps to reproduce the problem:

With Windows 1809 you can open a cmd with these commands
```
nvm install 10.11.0 && nvm use 10.11.0 && dir

Output: 10.01.2019  10:30    <SYMLINKD>     nodejs [..]
```
Sometimes the symlink is completely gone. With an delay inbetween the directory symlink appears
```
nvm install 10.11.0 && nvm use 10.11.0 && timeout 1 > NUL && dir

Output: 10.01.2019  10:35    <SYMLINKD>     nodejs [C:\develop\nvm\v10.11.0]
```
You can also add npm --version instead of dir to get "the system can not find the path" error

With virtualization the timeout of 1 second is sometimes not enough to get the symlink working.

**Comment by coreybutler** [comment]
Closing due to age.

Unfortunately, this is not something the app can detect without adding significant overhead in non-CI cases. The only possibility is to keep the application open in a loop until the symlink is detected.

In CI environments, use a larger timeout or execute the command sequentially (instead of chaining them together with the `&&` notation.

A note has been added to the wiki regarding this issue and workarounds: https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#delayed-changes
