### ISSUE TITLE
Symlink not created when path includes underscore

### ISSUE THREAD

**Issue by BCurrell** [coreybutler/nvm-windows#420]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [x] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [x] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

During setup, I set the symlink directory to `D:\_languages\nvm\current`, which should symlink node version to that directory.

### Actual Behavior

No symlink is created. Changing settings and environment variables to default `C:\Program Files\nodejs` works as expected.

### Steps to reproduce the problem:

See expected behaviour.

**Comment by BCurrell** [comment]
It just occurred to me that this might not be the introduction of another disk. I just tried it by setting NVM_SYMLINK to `D:\nodejs` and it worked. Looks like it could be the introduction of an underscore in my directory. I've updated the issue title.

**Comment by coreybutler** [comment]
I know this issue is stale (I've been absent for awhile now). Did you figure it out? Underscores should be supported. Is there a chance your version was non-English?

**Comment by BCurrell** [comment]
My version is English UK, and I never figured it out. I changed the path instead. I'm not sure specifically what was causing it, but with the different paths I tested, it failed to create the symlink when there was an underscore 100% of the time.

**Comment by coreybutler** [comment]
Spaces and special character support are included in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
