### ISSUE TITLE
.github/ISSUE_TEMPLATE refers to non-existant StackOverflow tag

### ISSUE THREAD

**Issue by ptandler** [coreybutler/nvm-windows#423]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

The ISSUE_TEMPLATE https://github.com/coreybutler/nvm-windows/blob/master/.github/ISSUE_TEMPLATE refers for questions about usage to http://stackoverflow.com/questions/tagged/nvm-windows

However, this tag does not exist (yet) on StackOverflow and you need 1500 credits to create it (which I don't have). Can anyone else create it - or I think the template should be updated.

**Comment by coreybutler** [comment]
Looks like it was automatically culled (https://stackoverflow.com/help/privileges/create-tags). I've added it again and submitted a tag wiki entry (requires review).
