### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mailbala** [coreybutler/nvm-windows#426]
I tried to install nvm-windows  1.1.7 in windows 10. I got the below error.

**PS C:\> nvm install latest
Downloading node.js version 11.11.0 (64-bit)...
Complete
Downloading npm version 6.7.0... Error while downloading https://github.com/npm/cli/archive/v6.7.0.zip - Get https://codeload.github.com/npm/cli/zip/v6.7.0: dial tcp 192.30.255.120:443: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5c6eb0]

goroutine 1 [running]:
_/C_/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.Download(0x1138a2d0, 0x2d, 0x1147a000, 0x3e, 0x116d0140, 0x5, 0x0)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:68 +0x240
_/C_/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.GetNpm(0x1138a4e1, 0x2a, 0x116d0140, 0x5, 0x44)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:163 +0x21b
main.install(0x113888b8, 0x7, 0x660283, 0x2)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:268 +0x626
main.main()
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:78 +0x8cd**

Please look into the issue.

**Comment by coreybutler** [comment]
I believe this was due to an outage. Please re-open if it is still an issue.

**Comment by navisayslisten** [comment]
I'm also getting this issue. 
![image](https://user-images.githubusercontent.com/27226232/58366057-f787c400-7e89-11e9-8762-3bedb69e121d.png)
