### ISSUE TITLE
nvm install command errors on installing npm

### ISSUE THREAD

**Issue by skynetit** [coreybutler/nvm-windows#430]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [x] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

When I give nvm install latest or nvm install {latest} it should install node & corresponsing npm

### Actual Behavior
Failed with this error
PS C:> nvm install latest
Downloading node.js version 11.11.0 (64-bit)...
Complete
Downloading npm version 6.7.0... Error while downloading https://github.com/npm/cli/archive/v6.7.0.zip - Get https://codeload.github.com/npm/cli/zip/v6.7.0: dial tcp 192.30.255.120:443: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5c6eb0]

goroutine 1 [running]:
/C/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.Download(0x1138a2d0, 0x2d, 0x1147a000, 0x3e, 0x116d0140, 0x5, 0x0)
C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:68 +0x240
/C/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.GetNpm(0x1138a4e1, 0x2a, 0x116d0140, 0x5, 0x44)
C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:163 +0x21b
main.install(0x113888b8, 0x7, 0x660283, 0x2)
C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:268 +0x626
main.main()
C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:78 +0x8cd**

### Steps to reproduce the problem:

1. Download nvm-windows.
2. Install.
3. run the command nvm install latest

**Comment by aravindvnair99** [comment]
@mailbala Have a look at #300

**Comment by aravindvnair99** [comment]
> @mailbala Have a look at #300

@mailbala This is what worked for me: https://github.com/coreybutler/nvm-windows/issues/300#issuecomment-474860882

**Comment by coreybutler** [comment]
https://codeload.github.com/npm/cli/zip/v6.7.0 is not a standard source for npm. Are you running a proxy or a customize version of NVM4W?

**Comment by skynetit** [comment]
I am not running a proxy or nvm. 

When I run this comand - **nvm install 12.18.1** 

Downloading npm version 6.14.5... Error while downloading https://github.com/npm/cli/archive/v6.14.5.zip - Get https://codeload.github.com/npm/cli/zip/v6.14.5: dial tcp 192.30.253.121:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x5c6eb0]

goroutine 1 [running]:
_/C_/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.Download(0x11452090, 0x2e, 0x11728000, 0x3f, 0x1162a4d0, 0x6, 0x0)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:68 +0x240
_/C_/Users/corey/Documents/workspace/nvm-windows/src/nvm/web.GetNpm(0x11394211, 0x2a, 0x1162a4d0, 0x6, 0x44)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm/web/web.go:163 +0x21b
main.install(0x11384080, 0x7, 0x660283, 0x2)
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:268 +0x626
main.main()
        C:/Users/corey/Documents/workspace/nvm-windows/src/nvm.go:78 +0x8cd

**Comment by WJY-JY** [comment]
I had the same problem.

The problem went away when I changed the npm_mirror.

You can try to fix the problem by modifying the npm_mirror.
```bash
 nvm npm_mirror https://npm.taobao.org/mirrors/npm/
```

**Comment by tanrui8765** [comment]
I faced the same problem, and this solution works out. Thanks 👍  @WJY-JY 



> I had the same problem.
> 
> The problem went away when I changed the npm_mirror.
> 
> You can try to fix the problem by modifying the npm_mirror.
> 
> ```shell
>  nvm npm_mirror https://npm.taobao.org/mirrors/npm/
> ```

**Comment by coreybutler** [comment]
Closing due to age and new releases (which have an updated npm download link).

**Comment by frankgo81** [comment]
nvm npm_mirror https://npm.taobao.org/mirrors/npm/
this works great!!

**Comment by Leuconoe** [comment]
I had a download fail when cloudflare warp was running.
I turned off warp and it worked fine.
