### ISSUE TITLE
 安装后运行npm遇到这个报错:Cannot find module

### ISSUE THREAD

**Issue by MoonCheung** [coreybutler/nvm-windows#432]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [X] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [X] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

1.原来nvm版本1.1.6将node版本10.x.x安装完成后发现npm模块不见了，无法运行
2.这个nvm软件更新1.1.7来进行安装node版本10.15.3 LTS，发现里面有存在npm模块的，打算运行npm模块报错：Cannot find module ，求解！！！

### Actual Behavior

![UC截图20190323224420](https://user-images.githubusercontent.com/19801190/54868114-eb1cb780-4dc3-11e9-81e8-4185c34bcbd2.png)

还有nvm文件夹里面setting.txt和在C盘目录setting.txt都一样配置的如下：
root: D:\NodeFiles\nvm 
path: D:\NodeFiles\nodejs 
arch: 64 
proxy: none
node_mirror: https://npm.taobao.org/mirrors/node/ 
npm_mirror: https://npm.taobao.org/mirrors/npm/

### Steps to reproduce the problem:

nvm install 10.15.3
nvm use 10.15.3
node -v //10.15.3出来了
npm -v //报错了，是上面截图提示的

**Comment by MoonCheung** [comment]
将Git Bash输入10.15.3安装后，然后use 10.15.3运行出来发现有node，npm版本显示的，已经自行解决了的

**Comment by shingz96** [comment]
> 将Git Bash输入10.15.3安装后，然后use 10.15.3运行出来发现有node，npm版本显示的，已经自行解决
你好，请问你是怎么解决的？
