### ISSUE TITLE
Vue is not recognized after npm -g install

### ISSUE THREAD

**Issue by Avasse** [coreybutler/nvm-windows#433]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [X] My Windows installation is non-English.

### I'm using NVM4W version:

- [X] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [X] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

vue create and/or vue ui running.

### Actual Behavior

vue is not recognized as an internal or external command.

### Steps to reproduce the problem:

nvm install latest
nvm use 11.12.0
npm install -g @vue/cli-service-global
vue

**Comment by Cooboob** [comment]
i met the same issue, how to do ?

**Comment by coreybutler** [comment]
This is not an NVM4W issue.

There appears to be a bug in that package. There is no `bin` attribute in the `package.json` file. The package will be installed globally, but no link is created.

Notice the `@vue` namespace is available in `node_modules`
![image](https://user-images.githubusercontent.com/770982/78944577-d7ea9180-7a83-11ea-8243-0d8ccdc7ae52.png)

However; there is no link created for it in the root of the Node directory:

![image](https://user-images.githubusercontent.com/770982/78944635-f486c980-7a83-11ea-981c-22f58063f88e.png)

I suspect you may actually want `@vue/cli`. If you run `npm install -g @vue/cli`, the `vue` command will work and you will see it in the node root, like this:

![image](https://user-images.githubusercontent.com/770982/78944730-2ac44900-7a84-11ea-9a4c-c983a32a45a2.png)
