### ISSUE TITLE
The symlink create command didn't work

### ISSUE THREAD

**Issue by KeisukeeLee** [coreybutler/nvm-windows#434]
I install the nvm and it fails when i try to type 'node' in the command line with
'npm' is not recognized as an internal or external command
Then I check the source and found that the 'mklink' command didn't work, but I can create the same directory symlink in command line by manual, so what cause this problem?
![image](https://user-images.githubusercontent.com/46807188/55283422-68809300-5395-11e9-8b0a-93eb15467b04.png)
My english is poor, hope you can understand！

**Comment by demetrioalvesnl** [comment]
try uninstalling nvm, removing all the folders(and installations) related to node(if you have any), install it again and it should work.

The issue that I was facing was due to have node installed already and then nvm failed in oprder to create the symlink.

Hope it helps

**Comment by coreybutler** [comment]
Did you run `nvm use ____`? You have to `nvm install ____`, then `nvm use ___` before `node` will work.

**Comment by StephenMcConnel** [comment]
I'm having trouble with the mklink apparently failing silently.  This has happened both on my local developer machine (where it then started working for no apparent reason) and on a TeamCity build machine.  Older versions worked fine for me.  I'm not sure what is happening.

**Comment by axelstudios** [comment]
I ran into this as well, what worked for me was to change the symlink location from `C:\Program Files\nodejs` to a directory that doesn't need admin rights like `C:\Users\<user>\nodejs`

**Comment by bitbay** [comment]
> I ran into this as well, what worked for me was to change the symlink location from `C:\Program Files\nodejs` to a directory that doesn't need admin rights like `C:\Users\<user>\nodejs`

@axelstudios while what You are saying is definitely needed, it doesn't solve the issue. I already have it mapped to a folder with enough privileges, but the symlink is still created at random (and use a command line with elevated privileges).

**Comment by coreybutler** [comment]
The original issue suggested npm was not found. The mklink command works, but if the username or path contained a space, the npm executable could not be found. The space issue has been resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8.

**Comment by VladimirRybalko** [comment]
> I ran into this as well, what worked for me was to change the symlink location from `C:\Program Files\nodejs` to a directory that doesn't need admin rights like `C:\Users\<user>\nodejs`

It was an exactly issue in my case. 
Thank you, @axelstudios
