### ISSUE TITLE
版本切换不过去

### ISSUE THREAD

**Issue by xiechunhao** [coreybutler/nvm-windows#435]
下面是我的问题：我这里简述一下

我已经安装了两个 node 版本，但是切换的时候切换不过去，不知道为什么。
详情情况看图片可能更直接点：
希望大佬帮我解决下。

![image](https://user-images.githubusercontent.com/30240638/55928446-3e5b8a80-5c4b-11e9-89bf-909a84aedd42.png)

**Comment by momocow** [comment]
會不會是 Windows UAC 授權問題？可以確認看看 NVM 是否得到授權。
理論上 `nvm use` 之後會有兩次彈窗授權請求，第一次是為了 node，第二次是為了 npm。

**Comment by demonskp** [comment]
nvm list 显示只有8.12.0。
是否原来的版本并没有被nvm管理。
建议先删除原来的node再安装nvm

**Comment by coreybutler** [comment]
Closing... because I can't read this. Hopefully the comments from others have resolved the issue.
