### ISSUE TITLE
npm -g outdated npm ERR! Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by createdbyjurand** [coreybutler/nvm-windows#437]
### My Environment

Windows 10

### I'm using NVM4W version:

1.1.7

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### Expected Behavior

list of outdated components installed globaly or nothing (if nothing is outdated)
using node install without nvm works fine

### Actual Behavior

npm ERR! Cannot read property 'length' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\***\AppData\Roaming\npm-cache\_logs\2019-04-18T22_33_51_466Z-debug.log

### Steps to reproduce the problem:

- install nvm
- nvm install 10.15.3
- nvm use 10.15.3
- update npm to 6.9.0
- npm -g outdated

**Comment by alexdevero** [comment]
This is a bug in npm (https://stackoverflow.com/questions/55172700/npm-outdated-g-error-cannot-read-property-length-of-undefined). It was already fixed - https://github.com/npm/cli/commit/d07547154eb8a88aa4fde8a37e128e1e3272adc1#diff-3d20499d58f14c6f1edfe93d8ba8a8a2.
