### ISSUE TITLE
It Fails with  nvm use <installed_node_version>

### ISSUE THREAD

**Issue by coyhom** [coreybutler/nvm-windows#438]
### Issue
Hello? Does anyone know it?
I met problem when I installed nvm successful , nvm -v: Running version 1.1.7.
then I use command : nvm use <installed_node_version>
It fails with: 
fork/exec C:\Users\<user_name>\AppData\Roaming\nvm\elevate.cmd: The system cannot find the file specified.

### My Environment

- [ ] Windows 7 (x64)

### I have already re-install nvm many times, but it stay the same.......
1.nodejs is completely uninstall from windows 
2.there is no spaces in pathname

**Comment by jacobq** [comment]
* Are you running as Administrator?
* What shell/CLI are you using?

**Comment by coyhom** [comment]
> * Are you running as Administrator?
> * What shell/CLI are you using?

1. yes，there is only one Administrator in my Windows.
2. windows/system32/cmd.exe

have tried many times, but……
Does anyone meet the same problem?

**Comment by jacobq** [comment]
> Does anyone meet the same problem?

:( Sorry, I haven't seen the problem you described. Sometimes I have had to manually remove and reinstall a particular version of nodejs though (as if `nvm` didn't install it properly or something)

**Comment by coyhom** [comment]
> > Does anyone meet the same problem?
> 
> :( Sorry, I haven't seen the problem you described. Sometimes I have had to manually remove and reinstall a particular version of nodejs though (as if `nvm` didn't install it properly or something)

Ok, maybe I have to give up nvm. Thanks for your replay! :)

**Comment by hussnainsheikh** [comment]
I am facing almost the same issue: 
![image](https://user-images.githubusercontent.com/20900683/58357461-5b16ef00-7e94-11e9-9e76-d1060bb8c640.png)

**Comment by prsadh** [comment]
@hussnainsheikh What OS and build version are you using?

**Comment by jacobq** [comment]
Looks like you are using Git Bash (mingw32). I have had problems with "nvm
use" not being able to make the symlink in that shell, but it always works
with elevated cmd.exe for me.

**Comment by cpmoore** [comment]
It's caused by the space in the path.  I have the same issue.

**Comment by hussnainsheikh** [comment]
I have also tried with cmd but it is not working:

![image](https://user-images.githubusercontent.com/20900683/58442482-13e36500-8105-11e9-9496-e500721064d6.png)

**Comment by hussnainsheikh** [comment]
> It's caused by the space in the path (the one in your user account name). I have the same issue.
> 
> Edit: Actually it looks like the source has already been fixed. An actual release just hasn't been created.
> 
> Release 1.1.7
> 
> ```go
> cmd := exec.Command(filepath.Join(env.root, "elevate.cmd"), "cmd", "/C", "rmdir", filepath.Clean(env.symlink))
> ```
> 
> Master branch
> 
> ```go
> // Create new symlink
>   if !runElevated(fmt.Sprintf(`"%s" cmd /C mklink /D "%s" "%s"`,
>     filepath.Join(env.root, "elevate.cmd"),
>     filepath.Clean(env.symlink),
>     filepath.Join(env.root, "v"+version))) {
>     return
>   }
> ```
> 
> In the 1.1.7 version the path to the elevate.cmd file isn't being quoted. Thus creating the space issue.

Could you please help to fix it?

**Comment by marlag** [comment]
Same if node installed in "Program files", need to manually set target by symlink properties - would love the fix released :)

**Comment by UziTech** [comment]
@coreybutler could you release a new version since this is already fixed in master?

**Comment by LeonBlade** [comment]
There hasn't been a new release in over a year despite this still being an active project.  Could we please get a new release.  Thanks!

**Comment by coyhom** [comment]
It is fixed in the new version

**Comment by fbalhawan** [comment]
I'm having the same issue, my OS username is Fouad's HP, so the error I'm getting is
`C:\Users\Fouad's HP>nvm use 10.16.3`
`exit status 1: 'C:\Users\Fouad's' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by auravOO7** [comment]
> > * Are you running as Administrator?
> > * What shell/CLI are you using?
> 
> 1. yes，there is only one Administrator in my Windows.
> 2. windows/system32/cmd.exe
> 
> have tried many times, but……
> Does anyone meet the same problem?

I'm too facing the same problem

**Comment by michaelgwelch** [comment]
> It is fixed in the new version

Which new version? The original issue was report in 1.1.7 which appears to still be the latest (and it still has the issue) as I just encountered it.

**Comment by dev-makanju** [comment]
This is 2024 and i still have the same issue
