### ISSUE TITLE
Consider adding the executable directly to releases

### ISSUE THREAD

**Issue by TomasHubelbauer** [coreybutler/nvm-windows#439]
Hey there, I see you only offer a zipped installer to download in releases. I am not sure why this is, it doesn't seem like the ZIP saves that much space, at any rate, though, I'd like to suggest that the executable itself replaces the archive or is made available alongside the archive. What do you think?

I want this because I see this quite often when downloading stuff and it's always annoying to have to unpack first and then run the executable. I know there must be a good reason for this, because so many sites do it (antivirus? corporate proxies not allowing direct downloads? just guessing), so maybe adding it alongside the archive is better than replacing the archive with the executable.

One downside of this would be potential confusion - people wondering what to download, the executable, the archive - both says *installer* so, like, which is it? That's a legit reason not to do this so I'll leave it up to you to determine where the balance lies.

This is a request for new releases only of course, already unzipped and installed the latest on a new computer just now - truly an indispensable piece of software! Thank you for all your work on this project :-)

**Comment by coreybutler** [comment]
Most browsers/antivirus/proxies explicitly prevent downloads of `.exe` files, and as you mentioned, it gets confusing when there are too many versions.

Keep in mind there are other files beyond just the executable. There are also command/vbs files and settings files. The installer bundles these, so the zip file is really just for transport (i.e. bypassing the issue above). However; it can't just be a "download and run" experience, it must be a "download, install, then run" experience.

The goal for the next version is to do automatic self-updates. Unzipping would only occur on the initial installation.
