### ISSUE TITLE
Failed to extract npm. Could not find C:\Users\my_user_name\AppData\Roaming\nvm\temp\nvm-npm\npm-3.10.10\bin

### ISSUE THREAD

**Issue by timothy** [coreybutler/nvm-windows#441]
### My Environment
- [X] Windows 10

### I'm using NVM4W version:

- [X] 1.1.7

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [X] A standard shell environment (terminal/powershell)

### Expected Behavior

npm installs 3.10.10 along with node 6.11.2

### Actual Behavior

When I do `nvm install 6.11.2` in the cmd it install node.js correctly but gives the following error for npm:
```
C:\windows\System32>nvm install 6.11.2
Downloading node.js version 6.11.2 (64-bit)...
Complete
Downloading npm version 3.10.10... Complete
Installing npm v3.10.10...2019/06/03 11:58:49 Failed to extract npm. Could not find C:\Users\my_user_name\AppData\Roaming\nvm\temp\nvm-npm\npm-3.10.10\bin
```
npm does not install
node.js 6.11.2 does install

When I look inside of `C:\Users\my_user_name\AppData\Roaming\nvm\temp\` There is only one file named `npm-v3.10.10.zip` there are no other folders or files. This is where the path stops.

### Steps to reproduce the problem:

1. `nvm install 6.11.2`
2. `nvm list`
3. `nvm use 6.11.2`
4. `node -v` results in `v6.11.2`
5. `npm -v` results in `'npm' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by han-xiaowei** [comment]
I had the same problem.

**Comment by okzhu** [comment]
+1

**Comment by 95erlong** [comment]
+1

**Comment by piercezzs** [comment]
me too, how to solve it,please

**Comment by coreybutler** [comment]
Closing due to age. There were some initial release problems with npm 3.x.x and the node 6.x.x branch. If this issue occurs with newer versions of NVM4W, please open a new issue.
