### ISSUE TITLE
Error Execution of the Windows Script Host failed when nvm use version

### ISSUE THREAD

**Issue by ddieppa** [coreybutler/nvm-windows#445]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [X] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [X] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [X] read the README to be aware of npm gotchas & antivirus issues.
- [X] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [X] verified I'm using an account with administrative privileges.
- [X] searched the issues (open and closed) to make sure this isn't a duplicate.
- [X] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [X] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

1. `nvm install 10.16.0`
2. `nvm use 10.16.0`
3. `node -v` should say node 10.16.0

### Actual Behavior

when execute `nvm use 10.16.0` got this error:

> Execution of Windows Script Host failed. (Access is denied.)

**Comment by thomasjmwb** [comment]
@ddieppa were you able to find a solution to this?

**Comment by Skylertodd** [comment]
Same issue, anyone figure this out?

**Comment by coreybutler** [comment]
Closing due to age and several version releases (which address access/permissions).

**Comment by alexcrowdpharm** [comment]
I'm still experiencing this issue with 1.1.7 on Windows 10 Pro
