### ISSUE TITLE
Installer improvements

### ISSUE THREAD

**Issue by noelhibbard** [coreybutler/nvm-windows#457]
My windows account does not have admin rights so when I run the nvm installer it prompts for creds. When I type creds for an admin account the installer defaults to my correct user profile folder (not the admin's) but when it creates the %NVM_HOME% and %NVM_SYMLINK% vars and adds them to the %PATH% it's creating them in the admin's profile rather than my non-admin profile.

Inno Setup has an ExecAsOriginalUser function which will execute a program in the non-elevated environment which could be used to add the registry values to the correct HKCU.

For example:
```
ExecAsOriginalUser('REG', 'ADD HKCU\Environment /F /V NVM_HOME /D "' + ExpandConstant('{app}') + '"', '', SW_SHOWNORMAL, ewWaitUntilTerminated, ResultCode)
ExecAsOriginalUser('REG', 'ADD HKCU\Environment /F /V NVM_SYMLINK /D "' + SymlinkPage.Values[0] + '"', '', SW_SHOWNORMAL, ewWaitUntilTerminated, ResultCode)
```

Manipulating the path would require you to do REG QUERY and then parse the stdout. I just don't have time to mess with this right now. It would be great if these changes could be made to the installer though.

**Comment by coreybutler** [comment]
Thanks for this. I am pressed for time too, but if someone wants to take a shot at this, I'd accept a PR.

**Comment by noelhibbard** [comment]
I will try to get to over the weekend sometime.

**Comment by noelhibbard** [comment]
I created a pull request here: https://github.com/coreybutler/nvm-windows/pull/459

**Comment by mcgwiz** [comment]
#459 was merged. Should this be closed?

**Comment by coreybutler** [comment]
@mcgwiz yes. Thanks for pointing that out.

**Comment by nabarun-olea** [comment]
Thanks for this @noelhibbard.
Is this mentioned somewhere in the docs @coreybutler ?
I will try to add it if not done already.

**Comment by coreybutler** [comment]
@nabarun-olea no need... I'm launching v2 this month (or maybe July 1). Brand new installers.
