### ISSUE TITLE
when install in another partition npm is not working

### ISSUE THREAD

**Issue by cckowin** [coreybutler/nvm-windows#46]
when i install the nvm in `d:\nvm`
and use `nvm install latest 32` to install node
it seems npm is not installed properly
the `node_modules` under the latest installed node is empty
i view the code, and the problem seem to be
this line in `nvm.go`:
```
os.Rename(os.TempDir()+"\\nvm-npm\\npm-"+npmv,env.root+"\\v"+version+"\\node_modules\\npm")
```
it seems using os.Rename to rename directories between different partitions is not working properly
issue #24 may be related

**Comment by coreybutler** [comment]
I assume your `d` drive is another physical disk in the computer, as opposed to a mapped network drive?

**Comment by cckowin** [comment]
no, my computer has only one physical disk
i download the go and try the code my self
the test code is below:
```
package main
import "os"

func main() {
    os.Rename("e:\\test\\test\\test_a", "e:\\test\\test\\test_b");
    os.Rename("e:\\test\\test\\test_b", "d:\\test_b"); //not working
    os.Rename("e:\\test\\test\\test_file_a", "d:\\test_file_a");
}
```
`test_a` is a directory, `test_file_a` is a file
and the result is os.Rename works when rename files between two partiton, and
not work when rename directories between two partion

**Comment by coreybutler** [comment]
Which version of Go did you use to run your test?

**Comment by cckowin** [comment]
```
e:\test\test> go version
go version go1.4.2 windows/amd64
```

**Comment by inoc603** [comment]
ran into the same issue on windows8.1, with go 1.4.2. I tried to catch the err with:
```go
err := os.Rename(os.TempDir()+"\\nvm-npm\\npm-"+npmv,env.root+"\\v"+version+"\\node_modules\\npm")
 if err != nil {
    fmt.Println(err)
    os.Exit(1)
}
```
And it turned out there is one:
`Installing npm v2.5.1...rename C:\Users\MY_USERNAME\AppData\Local\Temp\nvm-npm\n
pm-2.5.1 E:\nvm\v0.12.0\node_modules\npm: Access is denied.`

**Comment by inoc603** [comment]
Update

I made some change to fix the problem. Instead of using system temp dir, I created a new directory `temp` under the nvm root and do all the work there. 

I changed `func GetNpm(v string)` to `func GetNpm(root string, v string)`, pass the nvm root path like in `func GetNodeJS(root string, v string, a string)`.

Works fine.

I'll make a pull request soon. In fact this is the first time I write sth in Go, never touch it before trying to solve this problem. Hopefully I'm coding in the right manner, really know little about Go.

**Comment by atroo** [comment]
Hello to all of you, First of all thx for this great tool. Second: Nice seeing that this fix is already incooperated into the codebase because it hit me today as well. Are there any plans (especially a date) when a new release of the node-nvm will land?
