### ISSUE TITLE
nvm list available displays wrong URL

### ISSUE THREAD

**Issue by alexvkcr** [coreybutler/nvm-windows#460]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

When you execute 
`nvm list available`
and it fails, the displayed URL should be contactable

### Actual Behavior

You get nothing, because the URL being displayed for contact is
[https://nodejs.org/dist/index.json.](url)
(there's a dot at the end) instead of 
[https://nodejs.org/dist/index.json](url)

### Steps to reproduce the problem:

Download a new nvm, you open a powershell with admin privileges and execute 
`nvm list available` with no internet for example
You can see the URL for display and if you follow it, you see it on the browser yourself

**Comment by coreybutler** [comment]
Cannot recreate. Do you have a screenshot of this? 

The code specifies the correct URL at https://github.com/coreybutler/nvm-windows/blob/256d69427b501b673057d11f59aeca073934ba87/src/nvm/web/web.go#L20

**Comment by alexvkcr** [comment]
I screwed my nvm when deleting the proxies to take the screenshot lol

How come you can't reproduce it?

You just need to execute nvm list available and qhat you get is https://nodejs.org/dist/index.json.

With the dot at the end

**Comment by xianghongai** [comment]
`nvm list available` = `nvm list -a`,

provide an option to retrieve the remotely available version?

**Comment by coreybutler** [comment]
The dot at the end was a period. It has been removed in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8 to prevent confusion.
