### ISSUE TITLE
Add run/exec options

### ISSUE THREAD

**Issue by Arcanorum** [coreybutler/nvm-windows#463]
A way to run a command with a particular version would be nice, without it affecting every other terminal, such as `nvm run [VERSION] [COMMAND]`.

Useful in the case I want to have different processes running on different node versions at the same time.

**Comment by coreybutler** [comment]
This has been asked for **many** times in the past, and it has been addressed in the version management working group with conflicting opnions. Ultimately, it runs contrary to the philosophy of this project (most notably that shims are required to support this).

This issue prompted me to write a clarifying piece on a) why this won't be natively supported in NVM4W and b) my solution/approach for resolving the challenge. Available in the wiki at https://github.com/coreybutler/nvm-windows/wiki/Per-Script-Shell-Versions.
