### ISSUE TITLE
Nodejs Shortcut Folder Target with Settings.txt

### ISSUE THREAD

**Issue by seansyao** [coreybutler/nvm-windows#464]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [ ] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [x] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior
Correction for expect behavior in the settings.txt would still be "root: ." instead of "root: nvm"
<img width="551" alt="Capture0001" src="https://user-images.githubusercontent.com/45821822/61969363-5c55bc80-afa8-11e9-8732-890696e04556.PNG">

### Actual Behavior
<img width="548" alt="Capture0002" src="https://user-images.githubusercontent.com/45821822/61969369-611a7080-afa8-11e9-93f9-facc4c5d3f54.PNG">

### Steps to reproduce the problem:
<img width="776" alt="Capture0000" src="https://user-images.githubusercontent.com/45821822/61969097-b1dd9980-afa7-11e9-817d-8eb2368c76e8.PNG">

### Problem:
root in settings.txt is not pointing to ~/nvm but somehow ~/"Program Files"

### Temp solution:
Had to go a level above and do nvm root ./nvm to fix the target in the shortcut nodejs folder.
<img width="266" alt="Capture0003" src="https://user-images.githubusercontent.com/45821822/61969531-c2424400-afa8-11e9-9953-dc96f8f8566c.PNG">

**Comment by coreybutler** [comment]
I realize this issue is pretty old and is likely resolved. Bottom line: `nvm root ...` requires an absolute path.

I'm not sure how the settings file would have gotten into that state to begin with. If the process truly is using *~*/nvm, then it is most likely a shell issue. NVM4W is not designed to run in the Linux subsystem.

I'm closing due to age and lack of steps for recreating the issue. If anyone continues to experiences this problem, please let me know and I'll reopen the issue.
