### ISSUE TITLE
Node Version is Not Changing on Windows 10

### ISSUE THREAD

**Issue by CodeBradley** [coreybutler/nvm-windows#474]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x ] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x ] read the README to be aware of npm gotchas & antivirus issues.
- [x ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x ] verified I'm using an account with administrative privileges.
- [x ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### Expected Behavior

Expected NVM to switch to version 11.4.0

### Actual Behavior

Didn't switch to Node 11.4.0, kept same version

### Steps to reproduce the problem:

```
C:\Users>node -v
v10.16.3

C:\Users>nvm use 11.4.0
Now using node v11.4.0 (64-bit)

C:\Users>node -v
v10.16.3

```

**Comment by coreybutler** [comment]
Did you install Node 11.4.0? If not, you need to before you can use it (and that is a false positive message).

**Comment by GrolarDan** [comment]
I have the same problem. I installed the 12.10.0 node version. I can see it in the list using nvm list but I'm not able to use it. After nvm use

**Comment by isaacdre** [comment]
Running into this issue as well.

Running in admin mode:

successfully installed (according to the readout from nvm install)  v10.16.3

nvm list shows:
```
* 12.8.1 (Currently using 64-bit executable)
  10.16.3
```
When I run `nvm use 10.16.3` it says "Now using node v10.16.3 (64-bit)"

However when I run nvm list again (even after opening up a new terminal) it shows that it is still stuck on the previous version of node.

**Comment by PhantomHost** [comment]
Same problem here too.   

I've been doing a lot of windows updates the last 2 weeks.  Do you think it has something to do with that?  The timeline of this issue would match the timeline of this thread.

**Comment by arlandisflorent** [comment]
I ran into this problem and found a solution: you to manually unistall you global node version. Then nvm install and nvm use the version you want.

**Comment by snerte** [comment]
Seems to be the same issue I had:

#472

**Comment by Barsonax** [comment]
Also broken for me:
![image](https://user-images.githubusercontent.com/19387223/68874766-05fcbd00-0702-11ea-9b2c-bb381c6531c3.png)

On top of that as you can see in the screenshot `list` is not working properly either.

**Comment by Xtrazyx** [comment]
SAME

**Comment by coreybutler** [comment]
This almost always occurs when the [installation instructions](https://github.com/coreybutler/nvm-windows#installation--upgrades) aren't followed. 

![image](https://user-images.githubusercontent.com/770982/69776502-2432d600-1162-11ea-87ff-b5d006dd294e.png)


[The root cause/resolution is here](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#uninstall-existing-node-installation-before-installing-nvm4w). Bottom line: make sure you don't have any other copies of Node installed.

**Comment by coreybutler** [comment]
Additionally, I have logged issue #494, related to providing better messaging when this type of scenario occurs.

**Comment by navkor** [comment]
Not sure if anyone figured out the fix, but I was able to get it working. Using Powershell as admin, here's what I did:
`Remove-Item 'C:\Program Files\nodejs' -Recurse
nvm use _VERSION#_
node -version`
