### ISSUE TITLE
The node and npm commands not available after install.

### ISSUE THREAD

**Issue by vgjenks** [coreybutler/nvm-windows#475]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x ] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x ] read the README to be aware of npm gotchas & antivirus issues.
- [x ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x ] verified I'm using an account with administrative privileges.
- [ x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Once installed and set the node version I want to use, it (and nvm) become available in a new admin shell (Powershell) using `node` command.

### Actual Behavior

The `node` command is not found, nor is `npm`. All files are there, env vars are there, but I can't use node at all.

### Steps to reproduce the problem:

Download latest and install using `nvm-setup.exe`. Run `nvm install 12.10.0` and `nvm use 12.10.0`. Launch new Powershell window as Administrator, type `node` or `node -v` and hit enter.

**Comment by qBaebs** [comment]
@vgjenks I found that I had a similar problem. 

After installing, use the "nvm on" command, then try node -v and npm -v to see if they are working.

This worked for me.

I do think that the README is a little vague with this detail if this is the requirement to make nvm-windows working.

@coreybutler I recommend updating your README to clarify this detail if this is expected to get node working properly after installation.

**Comment by vgjenks** [comment]
I appreciate the help all, but none of these steps works for me. I even tried the nvm manual install process. When I go that route, the `nvm` command doesn't work for me at all, I have to navigate to the directory...but that's another bug report for another time.

Regardless - I just can't get this thing to work.

**Comment by Jessica-Koch** [comment]
@qBaebs thank you that fixed it for me! :)

**Comment by qBaebs** [comment]
@Jessica-Koch no problem! Happy to help :)

**Comment by vgjenks** [comment]
@qBaebs That was very helpful, thanks! It's all working now.

**Comment by qBaebs** [comment]
@vgjenks Awesome, no problem!

**Comment by gopalkrish23** [comment]
i deleted empty nodejs folder from program files and did nvm off and nvm use <node version>

**Comment by AmazingTang** [comment]
I encountered the same problem and tried the two methods mentioned above, but neither of them worked
