### ISSUE TITLE
nvm broken after you set proxy to ''

### ISSUE THREAD

**Issue by ryanouyang** [coreybutler/nvm-windows#479]
### My Environment

- [x] Windows 10

### I'm using NVM4W version:

- [x] 1.1.7

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.

### My issue is related to (check only those which apply):

- [x] settings.txt
- [x] proxy support (Have you tried version 1.1.0+?)

### Expected Behavior

unset the proxy env, proxy should be none

### Actual Behavior

proxy is set to '' in `settings.txt`, and nvm never work again (even type `nvm ls` or just `nvm`), runtime error `panic: runtime error: slice bounds out of range`

### Steps to reproduce the problem:

type `nvm proxy ''`

**Comment by coreybutler** [comment]
Per the instructions (note the second line):

![image](https://user-images.githubusercontent.com/770982/67153740-42c8c600-f2b4-11e9-87c6-bf4c0c75f1df.png)

In other words, use `nvm proxy none`.
