### ISSUE TITLE
nvm install fails with stream error: stream ID 7; INTERNAL_ERROR - yet reports complete.

### ISSUE THREAD

**Issue by MuTLY** [coreybutler/nvm-windows#481]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

To install nodejs and npm without issues.

### Actual Behavior

nvm fails to download nodejs then proceeds to install npm.

### Steps to reproduce the problem:

```
C:\WINDOWS\system32>nvm install 12.13.0 --insecure

WARNING: The remote SSL certificate will not be validated during the download process.

Downloading node.js version 12.13.0 (64-bit)...
Error while downloading https://nodejs.org/dist/v12.13.0/win-x64//node.exe - stream error: stream ID 7; INTERNAL_ERROR
Complete
Creating C:\Users\MuTLY\AppData\Roaming\nvm\temp

Downloading npm version 6.12.0... Complete
Installing npm v6.12.0...

Installation complete. If you want to use this version, type

nvm use 12.13.0

C:\WINDOWS\system32>nvm uninstall 12.13.0
Uninstalling node v12.13.0... done
C:\WINDOWS\system32>
```

**Comment by nielsmaerten** [comment]
Same exact issue here.
I wonder if this is not a problem with nvm, but with nodejs.org?
Downloads seem very slow (<50kb/s) and fail after a few minutes.

Still, there should probably be a way for nvm to detect the download has failed (checksum or similar)

**Comment by MuTLY** [comment]
@nielsmaerten I think you're right. Manual downloads are failing as well on nodejs.org.

Some sort of download verification on nvm would be a very good idea.

**Comment by coreybutler** [comment]
I'm closing this in favor of #495. This was definitely a remote host issue, but NVM could provide clearer messaging.
