### ISSUE TITLE
cannot load file `C:\Program Files\nodejs\shx.ps1`

### ISSUE THREAD

**Issue by zhaoyao91** [coreybutler/nvm-windows#483]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [x] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

After switching to nvm-installed node v12.13 and installing some global packages, such as `shx`, I can't execute `shx` in the powershell directly, it errors that

```
shx : 无法加载文件 C:\Program Files\nodejs\shx.ps1。未对文件 C:\Program Files\nodejs\shx.ps1 进行数字签名。无法在当前系
统上运行该脚本。有关运行脚本和设置执行策略的详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=135170 中的 about_E xecution_Policies。
所在位置 行:1 字符: 1
+ shx
+ ~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

open the `C:\Program Files\nodejs`, dir, I found a `shx.ps1` file, which does not exist when using 12.10.

**Comment by coreybutler** [comment]
This doesn't seem like it's an NVM4W issue. It sounds like it is potentially a Windows user account problem (permissions) or an issue with that module. I installed it using NVM4W 1.1.7, Node 12.13.0 and npm 6.12.0 on a system with administrative privileges - no problems.

![image](https://user-images.githubusercontent.com/770982/69015380-e27f7f80-0958-11ea-870a-f281c1848cbf.png)

I'd recommend posting this on the module's issues.
