### ISSUE TITLE
Unable to update npm  Refusing to delete C:\Program Files\nodejs\npm.cmd: is outside C:\Program Files\nodejs\node_modules\npm and not a link

### ISSUE THREAD

**Issue by casufi** [coreybutler/nvm-windows#484]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [*] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

- [*] 1.1.7
- [ ] 1.1.6
- [ ] 1.1.5
- [ ] 1.1.4
- [ ] 1.1.3
- [ ] 1.1.2
- [ ] 1.1.1
- [ ] Older
- [ ] OTHER (Please Specify)

### I have already...

- [*] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [*] verified I'm using an account with administrative privileges.
- [*] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior
the new version of npm installed after
npm install -g npm 

### Actual Behavior
```
PS C:\WINDOWS\system32> npm install -g npm
npm ERR! code EEXIST
npm ERR! path C:\Program Files\nodejs\npm.cmd
npm ERR! Refusing to delete C:\Program Files\nodejs\npm.cmd: is outside C:\Program Files\nodejs\node_modules\npm and not a link
npm ERR! File exists: C:\Program Files\nodejs\npm.cmd
npm ERR! Move it away, and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\casufi\AppData\Roaming\npm-cache\_logs\2019-11-07T14_10_37_445Z-debug.log
PS C:\WINDOWS\system32>
```

### Steps to reproduce the problem:

Install nvm
run npm install -g npm as Administrator in PowerShell

**Comment by jmartsch** [comment]
Same problem here. Win 10 Pro 64

**Comment by coreybutler** [comment]
My guess is this occurred when installing node 8.x.x. Unfortunately, this is a problem with npm, where they hard coded permissions into a version of npm, making it impossible to remove the old file. See https://github.com/coreybutler/nvm-windows/issues/300#issuecomment-332523342.

**Comment by casufi** [comment]
> 
> 
> My guess is this occurred when installing node 8.x.x. Unfortunately, this is a problem with npm, where they hard coded permissions into a version of npm, making it impossible to remove the old file. See [#300 (comment)](https://github.com/coreybutler/nvm-windows/issues/300#issuecomment-332523342).

I've tried to install node 10
