### ISSUE TITLE
nvm root path issue due to blank/space in directory name

### ISSUE THREAD

**Issue by dev4y0u** [coreybutler/nvm-windows#485]
There is a problem with a root path set during the setup installation where the path contains a space/blank.
For example I am used to have my nvm installation under %APPDATA% which is 
C:\Users\Lenovo E470\AppData\Roaming
Now you can see there is the Users folder: "Lenovo E470" which contains a blank.

If I try to enable nvm with "nvm on" for example, I get "nvm enabled" followed by "exit status 1" ... Cannot find "C:\Users\Lenovo" ...
First my attempt was to change the system environment variable NVM_HOME.
This doesn't changed anything so I searched in the nvm folder and found "settings.txt"
First line: root: C:\Users\Lenovo E470\AppData\Roaming\nvm
So I created a Hardlink via mklink /J "C:\Users\Lenovo E470" C:\Users\Lenovo and changed the root path in the settings file to C:\Users\Lenovo\AppData\Roaming\nvm

This solved the problem. I am now able to use nvm as expected.

So please check if it is possible to interpret directories like mine in the right (windows) way.

**Comment by coreybutler** [comment]
This is resolved in https://github.com/coreybutler/nvm-windows/pull/355 - I just haven't had a machine to build the new release on. I'm working on a Github action to build new releases, but it's been a slow process. New release likely near the end of the month.
