### ISSUE TITLE
oversized record error

### ISSUE THREAD

**Issue by mnaughto** [coreybutler/nvm-windows#49]
When I run a command like `nvm list available` or `nvm install 0.10.32`, I get an error:

> Could not retrieve https://raw.githubusercontent.com/coreybutler/nodedistro/master/nodeversions.json
> 
> Get https://raw.githubusercontent.com/coreybutler/nodedistro/master/nodeversions.json: tls: oversized record received with length 20527

Any ideas? Running windows server 2008 R2, not sure what other information you might need.

**Comment by coreybutler** [comment]
Sorry for the delayed response.

I can't tell if this is a network issue or a checksum problem. Have you tried this again since it occurred? I think Github recently updated their SSL certificates as well, so there's a slight chance it was just a temporary glitch.

**Comment by mnaughto** [comment]
Apologies for *my* delay. It appears that the problem has resolved itself, so it must have been a temporary issue. 

-- Mike Naughton

**Comment by coreybutler** [comment]
If it crops up again, please let me know!

**Comment by mnaughto** [comment]
Mike Naughton has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=366668462857-3qkidqn8oseh9v3fhm3085kpb747bgm7.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.download%2Fg.php&customparam=customparam>

**Comment by coreybutler** [comment]
@mnaughto - Hit by this? http://gizmodo.com/a-huge-and-dangerously-convincing-google-docs-phishin-1794888973

**Comment by dengxiaozhen** [comment]
When I ran this command, I reported the error, and the network was normal. It has been going on for a day
![err](https://user-images.githubusercontent.com/8529528/29495752-d881c114-85f7-11e7-9ea4-5af9b0853163.jpg)

**Comment by coreybutler** [comment]
@dengxiaozhen - cannot replicate your issue (i.e. works for me). If you suspect a problem, it would be with the node site, not NVM4W. Remember to check your proxy to assure you are reaching the site.

**Comment by dengxiaozhen** [comment]
@coreybutler 
Problem solved, is network problem, thanks
