### ISSUE TITLE
Consider adding a link to "Common Issues" in the README

### ISSUE THREAD

**Issue by adamjohnson** [coreybutler/nvm-windows#492]
Hey Corey,

New to this project today and ran into the same issue as everyone else (spaces in user name, eg: `C:\Users\My User Name With Spaces\nvm`...).

Have you considered adding a highly visible link to the [Common Issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) page in the Wiki? That might redirect people and help them solve some of the repeat issues you see here.

I'm happy to help do this if you think it's worthy. Thanks for creating nvm-windows!

### My Environment

- [x] Windows 10

### I'm using NVM4W version:

- [x] 1.1.7

### I have already...

- [x] Done all these things

### My issue is related to (check only those which apply):

- [x] Add "Common Issues" link to README.
- [x] Spaces in computer's user name when trying to `nvm use`.

**Comment by coreybutler** [comment]
Good idea!
