### ISSUE TITLE
can't install certain versions of nodejs

### ISSUE THREAD

**Issue by inoc603** [coreybutler/nvm-windows#50]
I'm on windows 8.1. When I tried to install a fairly old version of node, I ran into this:
![image](https://cloud.githubusercontent.com/assets/11290006/6725200/f1deb61c-ce48-11e4-8844-ed807babca9e.png)
As I checked, 0.8.28 is in the [list](http://coreybutler.github.io/nodedistro). And it seems that version 0.9.x and older ones are all unavailable now. But 0.12.0 and 0.10.x are installed properly.

**Comment by coreybutler** [comment]
Hmmm.... maybe there was a server issue? Are you behind a proxy?

I just ran this successfully on 3/24/15 at 11:40am CST on Windows 8.1.

![image](https://cloud.githubusercontent.com/assets/770982/6807107/8bc6ba66-d21a-11e4-9c49-a14496881a01.png)

**Comment by inoc603** [comment]
Oh, didn't mention that I used the newest code forked from the repository, not the latest released version. I looked into the code again, and I think it's a problem with the `CheckVersionExceedsLatest()` function added by @rahulroy9202 . 

I did some test, inside `CheckVersionExceedsLatest()`. 

```
func CheckVersionExceedsLatest(version string) bool{
  content := web.GetRemoteTextFile("http://nodejs.org/dist/latest/SHASUMS.txt")
  re := regexp.MustCompile("node-v(.+)+msi")
  reg := regexp.MustCompile("node-v|-x.+")
  latest := reg.ReplaceAllString(re.FindString(content),"")
  
  if version <= latest {
    return false
  } else {
    //  print version to be installed and latest version
    fmt.Println("\n"+version+" exceeds "+latest)
    return true
  }
}
```

And the output shows:
```
...>nvm install 0.8.23

0.8.23 exceeds 0.12.1
Node.js v0.8.23 is not yet released or available.
```

Then it's rather clear, that comparing the version against the latest one using `<=` as string is to naive. This will not work for versions older than 0.10.0. You should use a stronger method.

**Comment by coreybutler** [comment]
Yes, it does look as though the patched version detection is string based as opposed to semver-based, which would indeed cause this. There are semver Go packages that could be used for a temporary fix if someone wants to put the effort into it.

In the next edition, I will not be using the SHASUMS file. NVM for Windows already utilizes a separate [project/service](https://github.com/coreybutler/nodedistro) that tracks node versions and supports semver for determining the proper release pattern. This is ultimately a more appropriate way of determining whether a version of node exists and is available. I'll likely be updating this service with some additional JSON convenience files like `latest.json` as progress on the next edition continues.

**Comment by inoc603** [comment]
Great, for personal and temporary use I guess I'll just skip the version check. Since you have planned for the semver approach, I guess I'll just be lazy here and wait for the new edition :)

Keep up the good work. Oh and another thing, I made some update on #46, and did a PR (It's marked *build failed* by AppVeyor for missing some project file, I think that doesn't matter...right? I did build and test it on my local machine).  Would you take some time and check on that? THX.

And don't forget to close this one, issues are really piling up here :)

**Comment by coreybutler** [comment]
If you can hang tight until the new version is released, I'd definitely recommend that.

**Comment by Lyd9607** [comment]
which way did you resolve it?
