### ISSUE TITLE
feature request: multi copy of special version coexit

### ISSUE THREAD

**Issue by wjx0912** [coreybutler/nvm-windows#501]
nvm install  my_env1   12.14.0   32
nvm install  my_env2   12.14.0   32
nvm install  my_env3   12.14.0   64
nvm use  my_env1   
nvm use  my_env2   

i need do some works on my_env1,  sometimes need change another enviroment  my_env2.

it's important. wish your reply, thanks.

**Comment by coreybutler** [comment]
Environment management is significantly more complex than simple version management. It will not be included in NVM4W (it requires full time effort). 

The good new is I am working on an environment management application that will do this (among many other things). I have put together a small team to work on it in 2020. The bad news is it will likely take us until early summer to release our first beta, and it will be a paid product (reasonably priced, of course).
