### ISSUE TITLE
About how  to alias  a nodejs version

### ISSUE THREAD

**Issue by 2467811213** [coreybutler/nvm-windows#503]
ask for a help,friends,I'm a beginner of NVM.there is a touble bothering me,which is about how to create a name for any nodejs version.I have read some articles,it is said it can use the command "nvm alias <name> <version>".I have tried it,while,it is not effective.doesn't the latest version of NVM support it？or,I uesd a wrong command,need a help sincerely！ 

### My Environment
Windows 7 

### I'm using NVM4W version:
latest 1.1.7

###my code
nvm alias LTS 12.14.1

**Comment by coreybutler** [comment]
NVM4W doesn't currently support aliases. That's a feature of nvm for Linux.

**Comment by melMass** [comment]
> NVM4W doesn't currently support aliases. That's a feature of [nvm for Linux](https://github.com/nvm-sh/nvm).

Is there a plan to add it?

**Comment by coreybutler** [comment]
For anyone arriving via search, please note that generic aliases are supported (such as `nvm install latest`), but they aren't necessarily the same as those in nvm-sh. NVM4W does _not_ support _custom aliases_. There is no plan to add it to NVM4W, but they are already on the roadmap for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) (the successor tool we're building).

**Comment by melMass** [comment]
> NVM4W does _not_ support _custom aliases_. There is no plan to add it to NVM4W, but they are already on the roadmap for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) (the successor tool we're building).


Nice I did not know about that project! 

Yes I meant to add another answer but actually forgot sorry.
My need was for IDEs to pick it up and most guides I've seen mention using `nvm alias default <version>`, I somehow assumed it was needed from this, but it's not and "use" is enough in the windows version.

Thanks
