### ISSUE TITLE
nvm-setup.exe An error occurred while trying to rename a file in the destination directory

### ISSUE THREAD

**Issue by ktm4ck** [coreybutler/nvm-windows#506]
During run of nvm-setup.exe (version for Windows 1.1.7), I get the error 

> C:\Users\username\Roaming\nvm\unins000.exe
> An error occurred while trying to rename a file in the destination directory:
> MoveFile failed; code 5.
> Access is denied
> 
> Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation

Note: I ran as administrator and still get this error.

### My Environment
- [ ] Windows 10
### I'm using NVM4W version:
1.1.7 (Same error occurs with 1.1.6)

### Expected Behavior
No error
### Actual Behavior
Error

### Steps to reproduce the problem:
go to https://github.com/coreybutler/nvm/releases
Choose  nvm-setup.exe (Same error occurrs for 1.1.7 and 1.1.6)
Download the zip file
unzip
run nvm-setup.exe

**Comment by ktm4ck** [comment]
I notice that they say to run with an administrative account on Windows.  While I did the install file with admin privileges, I am on my work PC and do not have access to upgrade any user privileges.  I'm not clear if this is the issue.  

I chose 'skip' and let it install, and now have another issue.
I have tried to use 'Uninstall' button in Apps on Windows, but now the unins000.exe file is missing.  it is not present in nvm directory.   I woudl like to just delete the nvm directory, but I am concerned other config changes will not be undone.

Perhaps do not allow the user to skip these files if it creates this situation.

**Comment by ktm4ck** [comment]
To fix, I changed the install directory.  It installed without issue after not using the roaming directory.  
I manually removed the reg entry from programs.

**Comment by ktm4ck** [comment]
Feel free to close if you are satisfied with this resolution (It would probably be better to instead change the default install directory of the program)

**Comment by coreybutler** [comment]
Users are free to choose the install location - that's why there is a prompt. I do not plan to change this right now, but I may consider a different default directory in rt (see [discussion](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112)).
