### ISSUE TITLE
Progress Bar when downloading

### ISSUE THREAD

**Issue by woaibiancheng01214** [coreybutler/nvm-windows#516]
### My Environment

-  Windows 10

### My issue is related to (check only those which apply):
new feature

### Expected Behavior

downloading with progress bar for those who have low speed connection to github/node.org server

**Comment by qiulaidongfeng** [comment]
@coreybutler #980 A progress bar for downloading is provided

**Comment by uiolee** [comment]
same issue. https://github.com/nvm-sh/nvm/issues/3227#issuecomment-1789291331

**Comment by coreybutler** [comment]
See https://github.com/coreybutler/nvm-windows/wiki/Runtime#nvm4w-feature-freeze
