### ISSUE TITLE
Feature Request: .msi Installer for nvm

### ISSUE THREAD

**Issue by Jan-Kruse** [coreybutler/nvm-windows#518]
### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

1.1.7

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

.msi installer is available for distribution

### Actual Behavior

No .msi installer found. Deployment via Intune is not possible.

**Comment by thiagodp** [comment]
@Jan-Kruse Do you actually need a `.msi` installer? You may find `nvm-setup.zip` at the [releases page](https://github.com/coreybutler/nvm-windows/releases). It contains an executable installer, `nvm-setup.exe`.

**Comment by coreybutler** [comment]
After exploring this concept, it's become apparent the msi installation will not work. The msi installer only allows one version to be installed at a time.
