### ISSUE TITLE
directories with blank spaces in name  are not supported

### ISSUE THREAD

**Issue by bruceauyeung** [coreybutler/nvm-windows#519]
### My Environment

- [x] Windows 7
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [x] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

my settings.txt
~~~
root: D:\Program Files\nvm
path: d:\Program Files\nodejs
~~~

nvm itself can be installed correctly
`nvm install 10.14.2 32` also runs as expected.
now i expect  `nvm use 10.14.2 32` can set current node.js version to `10.14.2`

### Actual Behavior
when i try to run `nvm use 10.14.2 32` , error occurred:
>exit status 1: 'D:\Program'

**Comment by RealFlachmann** [comment]
Same problem just occurred for me:
```
C:\>nvm root
Current Root: C:\Program Files\nvm
```
```
C:\>nvm version
1.1.7
```
```
C:\>nvm list
    13.11.0
    12.12.0
    10.19.0
```

When activating:
```
C:\>nvm use 10.19.0
exit status 1: Der Befehl "C:\Program" ist entweder falsch geschrieben oder konnte nicht gefunden werden.
```
Which translates: **The command "C: \ Program" is either misspelled or could not be found.**
I guess this is linked to the fact, that Windows uses 'Program Files' and 'Program Files (x86)'.

**Comment by decherneyge** [comment]
See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues

**Comment by bruceauyeung** [comment]
@decherneyge thanks , i will try to reproduce this issue with 1.1.8 version when it's released

**Comment by FMauroy** [comment]
Additionally, diacritic characters are not handled properly as well, as you can see below:

`C:\Users\Frédéric>nvm install latest`
`C:\Users\Fr�d�ric\AppData\Roaming\nvm could not be found or does not exist. Exiting.`

After I set the root to use the "old" 8.3 file name (found it using dir /X), it works:

`nvm root C:\Users\FRDRIC~1\AppData\Roaming\nvm`

HTH

**Comment by aaroncalderon** [comment]
## Suggestion

When installing, install to a directory that does not have spaces.

```
C:\dev\nvm\
```

That worked for me.

**Comment by coreybutler** [comment]
Resolved with https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
