### ISSUE TITLE
README lacks information about upgrading npm

### ISSUE THREAD

**Issue by jakobrosenberg** [coreybutler/nvm-windows#522]
There's a section about **Uninstall existing npm**, but the recommendations for upgrading are scattered in the issues.

The relationship between ``node``, ``npm`` and ``nvm`` is not clear and it's not obvious if upgrading ``npm`` should be done through ``nvm`` or at least in a way that doesn't break ``nvm``.

**Comment by coreybutler** [comment]
This is more of a "how Node works" type of thing, but your point is well taken. I do think clarifying language around this concept would be a valuable addition.

**Comment by pastelmind** [comment]
[npm-windows-upgrade] does not work for me, but a variation of the technique mentioned in https://github.com/coreybutler/nvm-windows/issues/500#issuecomment-571619789 did work.

1. Go to Node.js install directory
2. Rename the following files:
    * `npm` → `npm-old`
    * `npm.cmd` → `npm-old.cmd`
    * `npx` → `npx-old`
    * `npx.cmd` → `npx-old.cmd`
3. Run `npm-old install -g npm@latest`
4. Delete the files I renamed in step 2. (Step 3 should have created new files named `npm`, `npm.cmd`, etc.)

[npm-windows-upgrade]: https://github.com/felixrieseberg/npm-windows-upgrade

**Comment by coreybutler** [comment]
This is documented in the wiki at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#upgrading-npm
