### ISSUE TITLE
Installer doesn't work?

### ISSUE THREAD

**Issue by JimLynchCodes** [coreybutler/nvm-windows#523]
Hi, I'm using cmder on windows 10. I downloaded the installer (both the "noinstaller version and `nvm-setup`. After I go through the installer and create a new cmder shell, I still don't have nvm installed...

```
λ nvm
'nvm' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by JimLynchCodes** [comment]
"you need to uninstall any existing versions of node.js before installing NVM for Windows"

what's the correct way to do this?

**Comment by coreybutler** [comment]
If you already had a version of Node installed, it needs to be uninstalled first (as the README states). Shells like cmder often change components of the environment. The best way to get started is to make sure any prior version of Node is uninstalled, then install NVM for Windows using the installer. Then _test in a standard shell_, such as the normal terminal or powershell. Depending on which version of Windows you're running, you may need to reopen it once before NVM is recognized. Some slightly older versions of Windows have a timing issue where the PATH is set after the installer relaunches the terminal the first time. 

Once you have NVM4W running in a standard shell, you can look into making it work with your custom shell. Search the old issues, as there are users who have made it work in almost every environment. Also review https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#special-terminal-shells, which states the position the project takes on supporting custom shells like cmder.

**Comment by JimLynchCodes** [comment]
Thanks, it would be nice if you didn't have to uninstall node first. seems like an unnecessary step to me.

**Comment by coreybutler** [comment]
@JimLynchCodes - I agree. The NVM4W installer attempts to do this when it can, but the Node installer (from nodejs.org) leaves artifacts that cannot be removed by a separate process. It's one of the quirks of Windows (and some other operating systems). Bottom line: it's not something we've got any control over.
