### ISSUE TITLE
weird 32-bit error

### ISSUE THREAD

**Issue by JimLynchCodes** [coreybutler/nvm-windows#525]
λ `nvm install v12`:
```
v12.0.0
Node.js vv12.0.0 is only available in 32-bit.
```

**Comment by JimLynchCodes** [comment]
Please make it install the latest like real nvm. thanks!

**Comment by coreybutler** [comment]
As the README states, this is not the same as NVM for *nix. Having command line parity is not a goal of this project. Yes, the name "nvm" is confusing, something I've mentioned regretting for years (it's well documented). The next version of this project will have a new name (and most likely support all platforms, not just Windows).

**Comment by JimLynchCodes** [comment]
@coreybutler but installing the latest version is the better functionality... idk why you are so resistant to improvement
