### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by lane-holcombe** [coreybutler/nvm-windows#527]
I found the secret hidden executable nvm-setup.exe in nvm-setup.zip and I ran it.  Then I ran
```
nvm list
```
and saw there were none.

Next I type:
```
nvm install 12.16.1
nvm use 12.16.1
```
But before nvm use completes, I get a popup:
"This file does not have an app associated with it for performing this action.  Please install an app or, if one is already installed, create an association in the Default Apps Settings page."

I am a linux user for two decades and a nodejs developer for at least a decade.  I have avoided windows since XP was a thing.  Even since W98, IIRC.  But now I have to use Windows.  How do I get my Windows 10 laptop configured to use node?

BTW: 
```
nvm list

    12.16.1
```

**Comment by coreybutler** [comment]
Need to know more about your environment.... which version of Windows 10, whether you're running with elevated permissions (think sudo), which shell you're using (terminal, powershell, something else).

**Comment by lane-holcombe** [comment]
Hi, corey.  I know it is of no help to you, but I switched over to nodist.
I will try to get back to this when I have some bandwidth, but I just started this new job and I have to get things working fast.

**Comment by Jack-Barry** [comment]
Running into similar issues for Node `12.16.1`.

Able to successfully run 

```powershell
nvm install 12.16.1
nvm use 12.16.1
```

in an elevated PowerShell. However, when running `node` after setting NVM to use `12.16.1`, get the following:

```powershell
Program 'node.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
+ node
+ ~~~~.
At line:1 char:1
+ node
+ ~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

Doing the same as above with Node `12.16.0` yields no error.

Windows specs
| Spec Name | Value |
|-------------|--------|
| Edition | Windows 10 Home Insider Preview |
| Version | 2004 |
| Installed on | 3/26/2020 |
| OS Build | 19592.1001 |
| Serial Number | R90T6TZQ |
| Experience | Windows Feature Experience Pack 120.7001.0.0 |

**Comment by joshmakar** [comment]
I was having the same issue when using Git Bash. Using Windows PowerShell (as admin) bypassed the issue for me and I was able to switch node versions.

**Comment by Jack-Barry** [comment]
I don't remember what I did or what changed but just to clarify this hasn't been an issue for me for several months

**Comment by coreybutler** [comment]
@joshmakar - shells aren't guaranteed to be supported. See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#special-terminal-shells
