### ISSUE TITLE
nvm use issue -- 'C:\Program' is not recognized as

### ISSUE THREAD

**Issue by dwkrueger2** [coreybutler/nvm-windows#532]
### Expected Behavior
I expected to be able to change to the node version installed
### Actual Behavior
The changing of version fails to execute the change.
### Steps to reproduce the problem:
I'm using version 1.1.7 which is the current maintenance release.  I saw some issue posts that marked this as resolved before.  It appears to be related to the fact that "C:\Program Files" has a space in it.
I've been able to determine that in the Program Files\nvm directory there is a file settings.text that contains the following settings
```
root: C:\Program Files\nvm
path: C:\Program Files\nodejs
```
This appears to be the starting point of the error.   I tried manually changing the paths to the following.
```
root: "C:\Program Files\nvm"
path: "C:\Program Files\nodejs"
```
and several other combinations (i.e with %20 encoding)

I tried looking through the source code to find the point of the error but I couldn't quite get there.

**Comment by dwkrueger2** [comment]
I see that you already know about this issue in your common issues and are planning on fixing this in the 1.8 update.  -- Sorry --

**Comment by chrisparton1991** [comment]
My workaround for this was to install NVM into `C:\tools\nvm` and use `C:\tools\nodejs` as the symlink folder.

**Comment by ht450** [comment]
Until this is fixed, you can also work around it by changing the root and path in settings.txt to the short name version. 
e.g.
`C:\Program Files\` --> `C:\Progra~1\` 
or 
`C:\Program Files (x86)\` --> `C:\Progra~2\`

**Comment by coreybutler** [comment]
Spaces in paths are supported in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8

**Comment by Damperen** [comment]
> Until this is fixed, you can also work around it by changing the root and path in settings.txt to the short name version. e.g. `C:\Program Files\` --> `C:\Progra~1\` or `C:\Program Files (x86)\` --> `C:\Progra~2\`

Suddenly i ran into this problem, even though it used to work. Your comment fixed the issue for me, thanks. <3
