### ISSUE TITLE
"ERROR open \settings.txt: The system cannot find the file specified."

### ISSUE THREAD

**Issue by gartha1** [coreybutler/nvm-windows#533]
I know my way around windows, and command line, and my path is fine.

I uninstalled node through win7 "programs and features", and I deleted c:\program files\nodejs
I also uninstalled npm in programs and features, (I think it was listed there, it's not now)
And I removed the directory C:\Users\user\AppData\Roaming\npm"

iC:\javascript2020>nvm version
1.1.7

iC:\javascript2020>

I tried first from a regular command prompt,  and then from an administrative one, and I include output from each here.

From the regular one, it did not prompt me with a UAC prompt so no doubt it wouldn't have been able to install Node

```
iC:\javascript2020>nvm install 10
10.0.0
Downloading node.js version 10.0.0 (64-bit)...
Complete
Creating C:\Users\harvey\AppData\Roaming\nvm\temp

Downloading npm version 5.6.0... Complete
Installing npm v5.6.0...

Installation complete. If you want to use this version, type

nvm use 10.0.0

iC:\javascript2020>node --version
'node' is not recognized as an internal or external command,
operable program or batch file.

iC:\javascript2020>

iC:\javascript2020>dir "c:\Program Files\nod*"
 Volume in drive C has no label.
 Volume Serial Number is B411-D580

 Directory of c:\Program Files

File Not Found

```

I tried from an administrative command prompt

```
C:\Users\harvey>cd \javascript2020

C:\javascript2020>dir "C:\Program Files\nodejs"
 Volume in drive C has no label.
 Volume Serial Number is B411-D580

 Directory of C:\Program Files

File Not Found

C:\javascript2020>npm install 10
'npm' is not recognized as an internal or external command,
operable program or batch file.

C:\javascript2020>nvm install 10

ERROR open \settings.txt: The system cannot find the file specified.

C:\javascript2020>

```
I don't know what "ERROR open \settings.txt:"  means.  It must be a mistaken error message since of course there is of course no \settings.txt 

There is a C:\Users\user\AppData\Roaming\nvm\settings.txt

So I tried the following from an administrative command prompt
```
C:\Users\user\AppData\Roaming\nvm>nvm install 10

ERROR open \settings.txt: The system cannot find the file specified.

C:\Users\user\AppData\Roaming\nvm>dir settings.txt
 Volume in drive C has no label.
 Volume Serial Number is B411-D580

 Directory of C:\Users\user\AppData\Roaming\nvm

24/04/2020  11:00 PM                74 settings.txt
               1 File(s)             74 bytes
               0 Dir(s)  206,252,060,672 bytes free

C:\Users\user\AppData\Roaming\nvm>

```

Well,  .\settings.txt is there.  Not \settings.txt of course, but .\settings.txt

**Comment by coreybutler** [comment]
Closing due to age an inability to recreate this issue.

**Comment by hershkoy** [comment]
I had the same issue. 
I was using "nvm-noinstall.zip" from the release page when it happened. The issue was fixed when I used "nvm-setup.zip"

**Comment by UraniumDonut** [comment]
Hello, used nvm-setup.zip Issue persists. Windows 11 64 bit.

**Comment by hershkoy** [comment]
update: I tried now on a new machine (windows 10).

Latest release ([1.1.10](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.10)) fails with the error
```
ERROR open \settings.txt: The system cannot find the file specified.
```

I downgraded to 1.1.9 and it works

**Comment by hershkoy** [comment]
I had this issue again on a new computer, fresh install of windows 10. nvm version 1.1.10 (latest)

```
ERROR open \settings.txt: The system cannot find the file specified
```

It happened on vscode terminal
I downgrade to 1.1.9, still happens. 
I downgrade to 1.1.8, still happens. 

I open command prompt (cmd) outside of vscode, and it started working. 
I checked `nvm version` inside vscode and in command line, both show version 1.1.8

![image](https://user-images.githubusercontent.com/13259380/202675913-92af7797-f0ef-4856-825c-86d62a20b9ed.png)

**Comment by majkilde** [comment]
I had the same problem. Added the NVM folder to the path - and now it works.
