### ISSUE TITLE
npm folder not installed!! and npm -v shows error

### ISSUE THREAD

**Issue by Abhishek-pandey-1998** [coreybutler/nvm-windows#534]
I have downloaded nvm and then run it after running it when input npm -v it shows error internal/modules/cjs/loader.js:589
npm install also shows same error.

**Comment by fx69005** [comment]
Hello I have same problem , npm is not found after install nodejs version, anyone have a solution ?

**Comment by TBAIKamine** [comment]
up!! up !! same here.

**Comment by opexu** [comment]
Hi. You need input:
1) nvm list available
(you'll see all versions)
2) nvm isnstall <version>
3) nvm use <version>
and then will be installed npm
