### ISSUE TITLE
NVM not properly parsing credentials used for proxy authentication

### ISSUE THREAD

**Issue by mikenap** [coreybutler/nvm-windows#535]
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

Run `nvm version` if you don't know.
1.1.7
### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [x] settings.txt
- [x] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

My company requires proxy authentication for all GitHub traffic. I've tried setting my credentials on the proxy using the following syntax:

`nvm proxy "http://myusername:mypassword5#6@proxy.com:8080"`

Proxy authentication will allow me to download the NPM CLI from  https://github.com/npm/cli/archive/v6.14.4.zip

Without proxy authentication, I get the following message:
Downloading npm version 6.14.4... Error while downloading https://github.com/npm/cli/archive/v6.14.4.zip - Get https://github.com/npm/cli/archive/v6.14.4.zip: Proxy Authentication Required

### Actual Behavior
When I set the proxy, with credentials like this:
`nvm proxy "http://myusername:mypassword5#6@proxy.com:8080"`

I get the following message when trying to install a version of Node:

`nvm install 12.16.2`

Could not retrieve https://nodejs.org/dist/latest/SHASUMS256.txt.

Get https://nodejs.org/dist/latest/SHASUMS256.txt: invalid proxy URL port "mypassword5"

**Comment by PracticalCode** [comment]
I have experienced this same issue...  it would appear the parser/regex used to parse proxy string for the port# takes the first word after the first colon...

**Comment by mikenap** [comment]
> I have experienced this same issue... it would appear the parser/regex used to parse proxy string for the port# takes the first word after the first colon...

I haven't tested it yet, because I normally work on a Mac and didn't have to deal with this issue, but I am thinking url encoding any special characters may fix the issue.

https://www.w3schools.com/tags/ref_urlencode.ASP#:~:text=URL%20Encoding%20(Percent%20Encoding)&text=URLs%20can%20only%20be%20sent,followed%20by%20two%20hexadecimal%20digits.

**Comment by coreybutler** [comment]
The proxy URL parsing is a native function of Go. [NVM 1.1.8](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8) has an upgraded version of Go, which supports port numbers. If anyone comes across this in 1.1.8+, please open a new issue.
