### ISSUE TITLE
Assisting with the automated build effort

### ISSUE THREAD

**Issue by FilBot3** [coreybutler/nvm-windows#536]
What kind of effort would it take to help you get your build for nvm-windows to be automated and also build on a regular basis? I've worked with NSIS a bit, and seen it and used it before. There a plethora of other tools that could be used to build this as well. 

Build Tools
* [Taskfile](https://taskfile.dev/)

**Comment by coreybutler** [comment]
First and foremost, thank you for offering to help.

Truth be told, my focus has been on a new version manager that won't use NSIS. I need to get 1.1.8 built/released manually, which I'm hoping will be the last release as "NVM for Windows" before announcing the new version later this year.

In other words, I'm not sure there is much point in automating the current process anymore. The new version will most likely be based on a simple Go installer (a separate OSS project), with an automatic update service. That decision doesn't have to be set in stone though.... I would love to hear more about other options. The keys are having easy-to-follow screens, a silent install option, permission checks, and code signing.

**For anyone else landing on this issue from Google/wherever:**

I know I've been pretty quiet and this project seems like it doesn't get much attention... but the reality is nothing could be further from the truth.

1. I've long been working on a new version manager (based on this one), currently called "rt" (short for "runtime", name subject to change). 
1. rt is currently Go-based, but I'm experimenting with Rust as well.
1. Cross-platform.
1. Technically it could support other runtimes like Python, JRE, etc... though I'm not committing to that yet (or perhaps ever).

The overwhelming majority of new feature requests have been for support in enterprise environments.... mostly from companies who don't support the project in any way. rt will remain open source and true to its intended goals, but I am pursuing commercial options as well.

My time this month is dedicated to finishing [metadoc.io](https://metadoc.io), which will be used to document both old and upcoming releases. In June I will be giving a talk at OpenJS World about CLI tooling (free virtual event) and a bunch of CLI-related libraries I've been working on. There is a collaborator's summit after the conference, where version management will be discussed. After that, I will focus on finishing rt.

**Comment by FilBot3** [comment]
To be honest, I was going to use it for personal use then transition that knowledge into the enterprise. I am excited to hear about your `rt` project though. I would have to learn more about Rust, and Go's advanced concepts are a bit beyond me, otherwise it's just reading other people's code that gets me. I'll close this Issue. Thank you for the update @coreybutler !
