### ISSUE TITLE
node_modules are not downloaded

### ISSUE THREAD

**Issue by silviuburceadev** [coreybutler/nvm-windows#540]
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:
1.1.7

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [x] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior
`npm install -g express` should install express globally

### Actual Behavior
runtime error, complaining about not finding module npm-cli.js(see below)

### Steps to reproduce the problem:
$ nvm install 14.2.0
Downloading node.js version 14.2.0 (64-bit)...
Complete
Creating C:\Users\sburcea\AppData\Roaming\nvm\temp

Downloading npm version 6.14.4... Complete
Installing npm v6.14.4...

Installation complete. If you want to use this version, type

nvm use 14.2.0

sburcea@SBURCEA-RO MINGW64 ~
$ nvm use 14.2.0
Now using node v14.2.0 (64-bit)

sburcea@SBURCEA-RO MINGW64 ~
$ node -v
v14.2.0

$ npm install -g express
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:1023
  throw err;
  ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Any npm command fails with the same error.  This is because node_modules folder is empty.

$ cd /c/Users/sburcea/AppData/Roaming/nvm/v14.2.0
$ du -a .
54172   ./node.exe
0       ./node_modules
4       ./npm
1       ./npm.cmd
4       ./npx
1       ./npx.cmd
54186   .

Downloading the binary archive from Node downlaods and extracting the node_modules to the right node_modules folder(e.g. /c/Users/sburcea/AppData/Roaming/nvm/v14.2.0/node_modules) fixes the issue.

**Comment by oobleck** [comment]
I'm getting this too. I installed on Win 10 using Chocolatey

**Comment by fedor-pavlov** [comment]
Same issue for me as well on Windows 10:
nvm install 10.21.0
npm -> results into the "cannot find module npm-cli.js" error

Folder "npm_modules" is empty.

C:\WINDOWS\system32>npm
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

C:\WINDOWS\system32>

**Comment by lauraBaakman** [comment]
This is a duplicate of [issue 302](https://github.com/coreybutler/nvm-windows/issues/302), which contains [a workaround](https://github.com/coreybutler/nvm-windows/issues/302#issuecomment-340249164).

**Comment by silviuburceadev** [comment]
@lauraBaakman sorry, I've missed that issue, perhaps #302 issue title could be replaced with this issue's title for clarity. Yes, there is a workaround, as I've mentioned in the first post, but I still consider it a nvm bug, as it is supposed to download anything that's needed for a proper node & npm usage. I'm closing this so we can track the progress in #302
