### ISSUE TITLE
Install NVM

### ISSUE THREAD

**Issue by Abdul2212** [coreybutler/nvm-windows#542]
can someone tell me the exact steps I need to install nvm 1.1.7
 and be able to use it with git

**Comment by goxr3plus** [comment]
https://github.com/coreybutler/nvm-windows/releases/download/1.1.7/nvm-setup.zip 

Extract double click installation file.

Then use like 
>nvm install 14.3.0 
>nvm use 14.3.0

And there you are node js 14.3.0 and npm 14.12

**Comment by coreybutler** [comment]
This is documented in the README. It can also be [manually installed](https://github.com/coreybutler/nvm-windows/wiki#manual-installation).
