### ISSUE TITLE
nvm use latest

### ISSUE THREAD

**Issue by TheJaredWilcurt** [coreybutler/nvm-windows#543]
### I'm using NVM4W version:

1.1.7

### My issue is related to:

* [x] API

### Feature request

You can do `nvm install latest` and it checks for the latest version, downloads and installs it.

There should be an `nvm use latest` that checks for the latest version then tries to use it. If it isn't installed it just reports that (just like it does now if you do `nvm use asdf`).

This would make instructions much easier in documentation on other projects.

1. Next download and install nvm-windows to control your Node and npm version.
1. Then run `nvm install latest && nvm use latest`

**Comment by coreybutler** [comment]
While slightly different, the work to achieve this is part of the alias effort in #478, so I'm closing this as being "already on the roadmap".
