### ISSUE TITLE
Feature Request: Package for Winget

### ISSUE THREAD

**Issue by polarspark** [coreybutler/nvm-windows#547]
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version: Current

Run `nvm version` if you don't know.

### I have already...

- [ Y] read the README to be aware of npm gotchas & antivirus issues.
- [ Y] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [ Y] verified I'm using an account with administrative privileges.
- [ Y] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ Y] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ X] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

winget install nvm-windows (Add Packaging to the nvm-windows project and submit for acceptance.)

I am willing to give this a first stab in a branch if you want. Or you can have a current project member do it.

### Actual Behavior

N/A

### Steps to reproduce the problem:

N/A

**Comment by alanlivio** [comment]
It is a must feature.

**Comment by AshMcConnell** [comment]
This would be great!

**Comment by sushruth** [comment]
This would help streamline developer machine setups for frontend devs, a lot.

**Comment by AnderssonPeter** [comment]
It seems there is a tool provided by Microsoft to make this easier, https://github.com/microsoft/winget-create

**Comment by shotlandec1980** [comment]
> 
> 
> It seems there is a tool provided by Microsoft to make this easier, https://github.com/microsoft/winget-create

It is necessary to put the release of NVM without an archive, for further addition to the Windows Package Manager (winget), since winget does not understand .zip archives.

**Comment by shinayser** [comment]
Very interested on this feature 👀

**Comment by HandyHat** [comment]
This has now been added under the id CoreyButler.NVMforWindows - see: https://github.com/coreybutler/nvm-windows/discussions/705#discussioncomment-2650131

**Comment by martinkunc** [comment]
Hi, it seems we already have a package, thanks Corey!.
```
 winget install CoreyButler.NVMforWindows
```

**Comment by fowl2** [comment]
Is there some way to make `winget install nvm` work?
