### ISSUE TITLE
nvm not working windows 10 64 bit

### ISSUE THREAD

**Issue by SufyanParkar** [coreybutler/nvm-windows#548]
Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I'm using NVM4W version:

Run `nvm version` if you don't know.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by SufyanParkar** [comment]
![image](https://user-images.githubusercontent.com/42181353/84594005-06faf600-ae6d-11ea-9fa0-7fd045cc4a5f.png)
so my laptop has the user name as "Sufyan Parkar"

i think that's causing the issue here 
cuz my name has space

**Comment by SufyanParkar** [comment]
![image](https://user-images.githubusercontent.com/42181353/84594147-d49dc880-ae6d-11ea-8a3d-c1bebd27a0e1.png)

**Comment by SufyanParkar** [comment]
![image](https://user-images.githubusercontent.com/42181353/84594191-35c59c00-ae6e-11ea-8c9d-ec832130002c.png)

**Comment by gcsepregi** [comment]
I had the same problem this morning. What I've done:

1. Created a folder to store nvm on a path without spaces and special characters
2. Copied over the contents of %USERHOME%/AppData/Roaming/nvm
3. In the environment variables settings of control panel change the NVM_HOME variable (both in your personal and the system settings)
4. Change the root path in the settings.txt on the new path

After these steps, it worked for me.

I know it's just a workaround but at least you can move on until it's fixed.

**Comment by michapixel** [comment]
Even dots '.' are evil ;) so i changed my setup too, since my username has a dot in it.

**Comment by aje0827** [comment]
I had the same issue **"C:\Users\User is not a recognized as an internal nor external command,.."** and was able to resolve it without having to create a new folder. My username also had a space in it... Here is hw I fixed my error below. 

1.  I followed this video to rename my username [(https://www.youtube.com/watch?v=w5N2aaiToiQ)]
2. After I checked to see if I had any node versions installed to uninstall them first (which I didn't in my case)
3. I then reran the setup file from the installation download zip file (https://github.com/coreybutler/nvm-windows/releases)
*IMPORTANT* when you rerun the installation, you may notice the installation path might still say your previous username, for example: C:\Users\<User Name>\AppData\Roaming\nvm
*Make sure you get rid of the space at this point: C:\Users\<UserName>\AppData\Roaming\nvm

Finish the installation. This worked for me.

**Comment by regnete** [comment]
The issue also pops up when installing in a folder below "C:\Program Files\".

**Comment by lukewis** [comment]
Another fix that worked for me was simply to add quotes around the values in NVM_HOME and NVM_SYMLINK variables.

**Comment by caobingsheng** [comment]
use powershell(administrator)

**Comment by MissakaI** [comment]
> 
> 
> Another fix that worked for me was simply to add quotes around the values in NVM_HOME and NVM_SYMLINK variables. Might be nice if the installer did this by default.

I tried but it didn't work. nvm then reads the string with the quotes. Did you use the quotes or ` character

**Comment by coreybutler** [comment]
Spaces are now supported in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
