### ISSUE TITLE
Use version information from .nvmrc

### ISSUE THREAD

**Issue by prl94** [coreybutler/nvm-windows#556]
Is there are any plans to support .nvmrc?

**Comment by coreybutler** [comment]
Not directly, since this is not a per-shell utility. I've long thought about a hook system though to give developers an option to support this if they like, but it has been pushed to the next edition (something I'll start working on in mid-late September).

**Comment by prl94** [comment]
Cool, thanks! Will be a very useful feature. Recently I migrated from Mac to Windows so looking for the ability to configure npm version on the project level.
