### ISSUE TITLE
yarn global

### ISSUE THREAD

**Issue by Andriy2** [coreybutler/nvm-windows#557]
Yarn global packages is not usable via nvm-windows.
Yes, I know, that I can use `npm i -g pm2` and etc. but my preferred packet manager is yarn and I like to manage all packets (including global) via yarn

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [ ] My Windows installation is non-English.

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [x] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [x] searched the issues (open and closed) to make sure this isn't a duplicate.
- [x] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [x] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

`'pm2' is not recognized as an internal or external command` because of global node/npm/yarn switching

### Actual Behavior

`pm2` runned successfully

### Steps to reproduce the problem:
```
npm install -g yarn
yarn globall add pm2
pm2 ls
nvm use <another version>
pm2 ls
```

**Comment by Andriy2** [comment]
My bad, didn't add yarn to PATH, but there is new problem.
when using yarn global - modules is not switching when swithing node version

**Comment by coreybutler** [comment]
Per an email update: 

```
My bad, didn't add yarn to PATH, but there is new problem.
when using yarn global - modules is not switching when swithing node version
```

NVM4W does not automatically transfer global modules. There are too many nuances with native libraries across different architectures, versions, and disks to keep track of. If you make a change to a global module in one version of Node (like a module update), then downgrade to test in another, failures can occur. Similarly, feature deprecations in newer versions of Node can fail with older versions of a global module.

This is not a feature I plan to add, at least not in this tool. I have an open issue for adding a hook system (think git hooks) to give developers an option to run scripts in response to actions like "install". For example, listening for an "install" hook would allow developers to reinstall the appropriate version of their global modules in the new version of the runtime.

**Comment by Andriy2** [comment]
I discovered, that global `npm` modules and global `yarn` modules have different behaviors.
npm modules are linked to node version (change node version = change set of global modules)
yarn modules are NOT linked to node version (change node version = same global modules)

And I found it usable for me (so, not bug but a feature)) modules that are not depended on node version I installed via yarn and have them on any version of node selected (also reinstalled `yarn global add yarn` and `npm uninstall -g yarn`, so can use it on different node versions without reinstalling it every time).

Anyway, as I said earlier I found it for myself as a feature, and also big thank to you for this beatyfull tool for Windows :)

**Comment by coreybutler** [comment]
@Andriy2 I only use yarn infrequently, so this is quite an interesting detail. Perhaps you could post this in the new [discussion](https://github.com/coreybutler/nvm-windows/discussions) section?

**Comment by Andriy2** [comment]
Ok, I'll prepare and post new discussion tomorrow
