### ISSUE TITLE
[Feature request] Tag version

### ISSUE THREAD

**Issue by Andriy2** [coreybutler/nvm-windows#558]
Any way to 'tag' installed versions like `install`

Usage behavior: 
```
nvm tag <version> [name]
```
```
nvm untag <version>
```
then any time to change version you don't have to remember version number but just type 
```
nvm use <name>
```

**Comment by Andriy2** [comment]
If you have two node versions - it's okay to just `nvm list` and find needed version, but if you have different projects, some on LTS, some on Latest, some on elder node versions - it would be comfortable to use use tags instead of versions

**Comment by coreybutler** [comment]
Duplicate of #478.
