### ISSUE TITLE
powershell miss npm's  arguments

### ISSUE THREAD

**Issue by walker27** [coreybutler/nvm-windows#559]
![305965F192767E0EAEAD562C293B0FA1](https://user-images.githubusercontent.com/6702568/89983909-1484fe80-dcab-11ea-972b-fc09e98c0d3d.png)

I'm not sure if it is nvm's problem, but it did happend after i  install nvm-windows.

Make sure you have reviewed the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues) and existing issues before submitting a new issue.

If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.

If this is an issue regarding antivirus, make sure you search the existing issues first.

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL - see wiki for details)
- [ ] Windows 8
- [ ] Windows 8.1
- [x] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [ ] Windows Server 2012 R2
- [ ] Windows Server 2016

- [x] My Windows installation is non-English.

### I'm using NVM4W version: 

Run `nvm version` if you don't know.

nvm version is 1.1.7

### I have already...

- [x] read the README to be aware of npm gotchas & antivirus issues.
- [ ] reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
- [x] verified I'm using an account with administrative privileges.
- [ ] searched the issues (open and closed) to make sure this isn't a duplicate.
- [ ] made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.

### My issue is related to (check only those which apply):

- [ ] settings.txt
- [ ] proxy support (Have you tried version 1.1.0+?)
- [ ] 32 or 64 bit support (Have you tried version 1.1.3+?)
- [ ] Character escaping (Have you tried version 1.1.6+?)
- [ ] A standard shell environment (terminal/powershell)
- [ ] A non-standard shell environment (Cmder, Hyper, Cygwin, git)

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

**Comment by coreybutler** [comment]
I'm not sure how this would be an NVM4W issue. NVM4W only sets up symlinks to node. In other words, you're running node scripts and npm directly against the node executable and its associated npm installation. NVM4W doesn't shim anything.

**Comment by coreybutler** [comment]
I just saw this again and looked closer at your arguments. The problem is the `"-p"`. That is being recognized as an argument of the `--app-provider` flag, not as its own flag. To fix, use `-p`.

**Comment by walker27** [comment]
it's ran right after restart my computer. I  guess it's related a *.ps1 file. but now i can't find that file.

**Comment by walker27** [comment]
the input command is the first line of the picture. ```-p```'s quotes added by npm.cmd (i guess)

**Comment by coreybutler** [comment]
@walker27 apologies, I see what you're talking about now. [This answer](https://stackoverflow.com/questions/11580961/sending-command-line-arguments-to-npm-script) or [this one](https://exceptionshub.com/passing-arguments-to-npm-script-in-package-json.html#:~:text=To%20pass%20arguments%20to%20npm%20script%2C%20you%20should,parse%20them%20and%20treat%20them%20as%20npm%E2%80%99s%20option.) _may_ help you, but this is definitely not an NVM4W bug. It has to do with how the npm script is processing the arguments.
