### ISSUE TITLE
Unable to use a specific node js version

### ISSUE THREAD

**Issue by AshutoshSajan** [coreybutler/nvm-windows#561]
I have installed the node js and when I am trying to use that specific version I am getting this error. How can I fix this?
![Screenshot (2)](https://user-images.githubusercontent.com/44765540/91155001-dc84af00-e6df-11ea-9bef-41d81dc32ce2.png)

**Comment by coreybutler** [comment]
Try using a standard terminal or powershell. The MINGx64 shell (and others) can affect the `PATH`.

**Comment by coreybutler** [comment]
Closing due to no response.
