### ISSUE TITLE
NVM not working with User that has space in it

### ISSUE THREAD

**Issue by empeje** [coreybutler/nvm-windows#576]
**NVM4W version:** 1.1.5

### My Environment

- Windows 10

### Expected Behavior

Able to install Node.js smoothly in the User folder that has a folder.

### Actual Behavior

Failed when installing Node.js using nvm that installed here `C:\Users\Puji at Majoe`.

### Steps to reproduce the problem:

I'm running the following command.

```
C:\Users\Puji at Majoe>nvm install 14.15.0
Version 14.15.0 is already installed.

C:\Users\Puji at Majoe>nvm use 14.15.0
exit status 1: 'C:\Users\Puji' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by coreybutler** [comment]
See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#spaces-in-pathnamesinstallation-root or refer to #519 for workarounds.

**Comment by empeje** [comment]
Thanks @coreybutler
