### ISSUE TITLE
No Install Instructions

### ISSUE THREAD

**Issue by awayshops** [coreybutler/nvm-windows#577]
There should be install instructions in this package (that is a pretty basic requirement - right?) What happened? Researching your issues, I found the text below. This would be fine IF IT WERE IN THE README.

"There is a no-install method you could use (see releases for the download, or https://github.com/coreybutler/nvm-windows/wiki#manual-installation for instructions). However; there is no executable script, primarily because on Windows you have to access the registry. So, you could use curl to download the manual installer, but you'd have to script the rest of it yourself.

Another option is there is a community maintained version on chocolatey, which might be easier.

**Comment by coreybutler** [comment]
You're referring to the lesser used manual installation method. There is an installer, linked directly in the README, right by the screenshot of it, with instructions. 

![image](https://user-images.githubusercontent.com/770982/98200357-08e45500-1ef3-11eb-9b8f-8f61e3c600c6.png)

That said, I've updated the instructions and added a link to the wiki for those who prefer the manual installation process.
