### ISSUE TITLE
[Improved user experience] avoid redundant permission requests

### ISSUE THREAD

**Issue by Vixb1122** [coreybutler/nvm-windows#583]
Because restricted user can execute some command to create symbolic link without permission elevated.
For example: "C:\A_folder"->"C:\B_folder", create symbolic links by the following logic：
1.  run `cmd /c rmdir "C:\A_folder"` to delete symbolic link
2.  if "C:\A_folder" exists, elevate permission and rerun step 1
3.  if "C:\A_folder" exists, throw error
4.  run `cmd /c mklink /j "C:\A_folder" "C:\B_folder"` to create symbolic link
5.  if "C:\A_folder" not exists, elevate permission and rerun step 4
6.  if "C:\A_folder" not exists, throw error

**Comment by coreybutler** [comment]
Step 4 is using a junction, which may not work in all environments, but the overall concept of a retry upon failure due to permissions seems like a useful enhancement. It would be nice to reduce/eliminate permission prompts.

**Comment by Vixb1122** [comment]
@coreybutler 
Yes, execute the command first, and if it fails, elevate permission and execute the command again.

**Comment by Vixb1122** [comment]
@coreybutler `mklink /j` can create symbolic link without admin permission, but 'mklink /d' need admin permission

**Comment by coreybutler** [comment]
@Vixb1122 - yes, I know what the junction does, but this can cause problems in some Windows environments, especially those where the junction is made with a directory on another system (NAS/SAN/mapped drive). This is relatively common in corporate environments where the user's home directory is part of a floating Windows profile or is mapped to a different storage system. I've considered making `/j` an option that can be configured in the settings. There are several old issues referring to this.

**Comment by Vixb1122** [comment]
> @Vixb1122 - yes, I know what the junction does, but this can cause problems in some Windows environments, especially those where the junction is made with a directory on another system (NAS/SAN/mapped drive). This is relatively common in corporate environments where the user's home directory is part of a floating Windows profile or is mapped to a different storage system. I've considered making `/j` an option that can be configured in the settings. There are several old issues referring to this.

Well, your answer was very helpful for me.

**Comment by Vixb1122** [comment]
>I've considered making `/j` an option that can be configured in the settings. There are several old issues referring to this.

make '/j' an default option is useful to reduce permission prompts.

**Comment by vieruuuu** [comment]
any progress on this?

**Comment by coreybutler** [comment]
@vieruuuu - this won't be coming to NVM4W due to the feature freeze, but it should be part of [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) (which will replace NVM4W when we're done with it).

**Comment by tbonifazi** [comment]
Having `/j` as an option that can be configured in the settings would be awsome for me too :)

**Comment by coreybutler** [comment]
NVM4W won't get junctions. See [Why Won't NVM for Windows Support Junctions?](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-won-nvm4w-support-junctions). Hint: there is a better alternative in the pipeline.

We've resolved this in Runtime now, so I am closing as `wontfix`. Hopefully we'll release Runtime in late August.
