### ISSUE TITLE
nvm install blocks my ip address!!!

### ISSUE THREAD

**Issue by T04435** [coreybutler/nvm-windows#584]
### My Environment

- Windows 10 - ES Version 1903
- Powershell version: 5.1.18362.1
- NVM4W version: 1.1.1

### Expected Behavior

`nvm install 12.14.0`
# expected to install the version

### Actual Behavior

`nvm install 12.14.0`
`Get https://nodejs.org/dist/latest/SHASUMS256.txt: read tcp 192.168.43.10:9393->104.20.22.46:443: wsarecv: Se ha forzado la interrupción de una conexión existente por el host remoto.`

### Steps to reproduce the problem:

I think the issue is related to my current location IP address. Also I'm connected via hostspot from my phone wifi.

**Comment by coreybutler** [comment]
Nothing in NVM4W blocks anything on the network. There is no code to prevent installs. However; your local computing environment may restrict access. Common issues include firewall restrictions, non-authenticated proxies, and possibly CORS issues (especially if you're trying to access and HTTPS resource from an HTTP proxy). In this case, your phone is proxying requests and your hotspot connection could potentially restrict access to certain kinds of files. The hotspot could also be cutting out mid-transmission. It's really hard to tell without a network trace, but I really doubt NVM4W is causing this.
