### ISSUE TITLE
Nvm use is not switching to desired version

### ISSUE THREAD

**Issue by bjquiocho** [coreybutler/nvm-windows#586]
**NVM4W version:** 1.1.7
### My Environment

Windows 10

### Expected Behavior

`nvm list`

>10.16.3
10.15.3

`nvm use 10.16.3 `

>Now using node v10.16.3 (64-bit)

`node -v`

>v10.16.3

### Actual Behavior

`nvm list`

>10.16.3
10.15.3

`nvm use 10.16.3 `

>Now using node v10.16.3 (64-bit)

`node -v`

>v14.15.0

### Steps to reproduce the problem:

![image](https://user-images.githubusercontent.com/14336202/99412604-ed018b80-28c2-11eb-890a-c1aa22ea04bc.png)

**Comment by coreybutler** [comment]
Did you install Node 14.5.0 before installing NVM4W? If so, and if you didn't uninstall it, you'll get this result.

Run `echo %PATH%` and `echo %NVM_SYMLINK%`. Look to see if there is a Node installation listed before the value of `NVM_SYMLINK`

_Here's why:_

`nvm use ...` updates the symlink, pointing it to the appropriate Node installation directory. When you run `node <whatever>`, Windows loops through the `PATH` values looking for the existence of `node.exe` in one of the directories. Once it finds it, it runs it. So, if you have more than one installation directory in your `PATH`, the first one will always be used while subsequent ones will always be ignored. This is why you have to uninstall old Node versions prior to using a version manager... the uninstall removes that value from the `PATH` and cleans up any potentially conflicting registry settings.
