### ISSUE TITLE
[Build Error]'.\build.bat' can't be executed in a path with spaces

### ISSUE THREAD

**Issue by Vixb1122** [coreybutler/nvm-windows#588]
### My Environment 

Windows 10

### Expected Behavior

built success.

### Actual Behavior

built failure.

### Steps to reproduce the problem:

```
Set-Location "E:\Git Dirs"
git clone https://github.com/coreybutler/nvm-windows
# go get...
.\build.bat
```

**Comment by contactsamie** [comment]
Having same issue on my side too

**Comment by buzitsl** [comment]
The same issue. Installed the NVM in C:\Program Files\nvm directory. During execution, the error message was 
"Can't find C:\Program directory"

**Comment by IvanBil** [comment]
+1

**Comment by coreybutler** [comment]
Resolved with https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
