### ISSUE TITLE
On Windows 7 64 bit, nvm forgets architecture

### ISSUE THREAD

**Issue by greenaj** [coreybutler/nvm-windows#59]
I basically set the NVM_HOME, NVM_SYMLINK and PATH in a batch file on the fly as instructed before running NVM. I did the manual install, unzipping to grandchild of %SYSTEMROOT% as opposed to %USERPROFILE%. I set up the settings.txt file as instructed. 

Initially, nvm install latest and nvm use all work resulting in a working node environment, but when you open a new command prompt, setting the proper environment variables, nvm cannot firgure out the architecture and reports the version you installed as 'not installed'. Running nvm arch shows:

Currently Configured: ?-bit

Since you reference node install using a symlink, you can get to a node prompt, and npm is in path, it's just that nvm seems to have forgotten everything.

**Comment by whitecolor** [comment]
Seems to be solved by uninstalling official version, installing NVM for windows in `C:\nvm` and setting node folder to `C:\nodejs` (instead of `Program Ffiles`), then nvm works as expected.

**Comment by espoelstra** [comment]
@greenaj @whitecolor In your batch file are you using `set` or `setx` to set your environment variables?

**Comment by coreybutler** [comment]
Stale issue. Win7 is not technically supported.
