### ISSUE TITLE
Can we know when will be the next release?

### ISSUE THREAD

**Issue by vajahath** [coreybutler/nvm-windows#590]
Sorry for reaching out like this.
First of all, this is such a serene, marvellous piece of work! 💯 
Can we know when will be the next release? Because the last release was on Aug 2018. and we are nearing 2021.
At the same time, I feel like this should be an active project [in demand](https://insights.stackoverflow.com/survey/2020#technology-developers-primary-operating-systems).

There is already a lot of PRs raised by the community.
~14300 stars, 1500 forks and 373 repository watchers! These are big numbers.

If you need help, it would be nice to put a "maintainer needed" clause on the top of the readme.
Thank you.

**Comment by coreybutler** [comment]
Closing, because I addressed this [here](https://github.com/coreybutler/nvm-windows/discussions/565).
