### ISSUE TITLE
NVM4W loses track of all nodes after NPM script

### ISSUE THREAD

**Issue by abmagil** [coreybutler/nvm-windows#591]
**NVM4W version:** 
1.1.7

### My Environment
Windows 10 Pro, OS Build 19041.630

### Expected Behavior

NVM4W maintains selected node

### Actual Behavior

I'm running a standard Create-React-App app, involving webpack etc. out of the box. After running NPM scripts, such as `start`, the process will be attempted but then die without an error in the console. NVM will then lose track of everything. i.e.

```
> npm start # console prints some output, clearly tries to start a dev server but then this process seems to die. The dev server never starts. Process Explorer shows no live node processes
> node -v # 'node' is not recognized as an internal or external command,....
> npm -v # 'node' is not recognized.... (this message prints out twice)
> nvm list # outputs correctly the installed nodes
> nvm use 14.15.1 # node v14.15.1 (64-bit) is not installed. (14.15.1 _is_ in the output from list)
> nvm arch # System Default: 64-bit. **Currently Configured: -bit.** (emphasis mine)
```

### Steps to reproduce the problem:

I'm not sure- I strongly suspect this is a my-computer problem but I cannot figure out how to fix it and it prevents all node development. I have repeatedly uninstalled and reinstalled NVM4W with the same symptoms. The problem occurs whether I use NPM or Yarn and does not vary with whatever Node version I install or use (have tested with v10-14)

**Comment by Effiongoto** [comment]
I am also having the same issue!

**Comment by coreybutler** [comment]
Are you running your shell with admin privileges? `nvm use` changes the `NVM_SYMLINK` to point to the appropriate node directory. If the account does not have sufficient privileges to update the symlink, it may render it blank, in which case it will say Node isn't installed (the default message when it cannot find the node executable).

If you're using something other than the standard shell or Powershell, it may be possible the shell is changing the paths. 

While I doubt the react CLI app is making changes, I cannot say with certainty that it isn't the cause. I don't use React and am simply unfamiliar with the internals of the tooling. Again, I doubt it's the CLI tool, but that's the only remaining place where paths could potentially be manipulated.

**Comment by Rob-Echlin-Solace** [comment]
Did you uninstall all Node.js versions before installing nvm4w?
When I re-read the instructions for installing nvm, that struck me as a point that many people could miss, and which could cause this kind of havoc.

**Comment by coreybutler** [comment]
closing as stale. Reopen if the issue persists.
