### ISSUE TITLE
.nvmrc file incompatibility between MacOS and Windows

### ISSUE THREAD

**Issue by lukemcd** [coreybutler/nvm-windows#593]
**NVM4W version:** 1.1.7

### My Environment

Windows 10

### Expected Behavior

When I run `nvm use` the .nvmrc file should trigger Node to switch versions or prompt me for the correct version to use.

The contents of the .nvmrc file are:
```sh
v10.16.3

```
(there is a blank line that follows)

### Actual Behavior

The following error appears:
```sh
.0.0
node v.0.0 (64-bit) is not installed.
```

### Steps to reproduce the problem:

Create the .nvmrc file on a Mac then try to run `nvm use` on a Windows environment.

The use of LF or CRLF line endings does not appear to make a difference.

There is similar issue in reverse and I created a ticket for that on the [NVM project](https://github.com/nvm-sh/nvm/issues/2380).

I understand NVM and NVM Windows are two separate projects but ideally a workflow can still be enabled for teams that need to switch between Mac and Windows development environments. That is why I am hoping for each project an .nvmrc file can be processed regardless of the system it was created on.

**Comment by coreybutler** [comment]
.nvmrc is not supported. As the README states, this project is not supposed to be a clone of nvm. For anyone arriving here via Google, please see the numerous other versions of this issue which have been closed.
