### ISSUE TITLE
Running multiple versions of node simultaneously.

### ISSUE THREAD

**Issue by enbermudas** [coreybutler/nvm-windows#600]
**NVM4W version:** 1.1.7

### My Environment

- Windows 10

### Explanation

I'm trying to run two versions of node simultaneously on my PC with windows 10. Why? Well, I have two different projects and each of those requires a different version. How can I get it to work by using `nvm-windows`? If I set the node version for my Project A by using:

`nvm use v11.10.1`

It will affect the version for my project B, which is `v12.18.4`.

Thanks in advance.

**Comment by bencun** [comment]
I would definitely suggest using Docker for that purpose. You can easily run one of those projects (or both) in simple Docker containers with minimum setup.
Try reading up on this to get the idea: https://blog.logrocket.com/node-js-docker-improve-dx/

Furthermore, I don't think this project has such goals in mind and this is not a valid issue.

**Comment by coreybutler** [comment]
@enbermudas - you're attempting to virtualize your environment, which (as @bencun mentioned) is not an objective for NVM4W. Tools like nvm (for linux) shim the node executable to imitate virtualization. The shim is basically a proxy to the node executable, so the node executable is never executed directly by the user. Instead, the shim is executed, which then attempts to reconstruct the original command and execute node (it's basically a proxy). NVM4W differs by using symlinks. When node is executed, it's actually running the Node executable directly, not through a "proxy executable".

Environment virtualization is outside the scope of this project. Docker is currently the most robust solution for this. However; if you really want to do this without Docker, you can run a different Node executable directly, by specifying the path to the `exe`.

For example, running `nvm use 15.0.0` and `node whatever.js` will run the script with **v15.0.0** (the NVM4W symlink handles this). To run a different node executable directly, specify the full path, such as:

```sh
C:\Users\coreybutler\AppData\Roaming\nvm\v15.3.0\node.exe whatever.js
```

You can find the directory where NVM stores different versions of Node by running `echo %NVM_HOME%`. The directory will look something like this:

![image](https://user-images.githubusercontent.com/770982/105370728-7b4b0400-5bc9-11eb-9789-a62f20d18564.png)
