### ISSUE TITLE
Download failed using nvm install command

### ISSUE THREAD

**Issue by mercale** [coreybutler/nvm-windows#609]
**NVM4W version:** 

### My Environment
Windows 10

currently only have one version of node installed
```
nvm list

  * 14.15.4 (Currently using 64-bit executable)
  
```

### Expected Behavior
should have installed using the following command

```nvm install 12.20.1```

### Actual Behavior
Failed

### Steps to reproduce the problem:
```
nvm install 12.20.1
Downloading node.js version 12.20.1 (64-bit)...
Download failed. Rolling Back.
Rollback failed. remove C:\Users\mercale\AppData\Roaming\nvm\v12.20.1\node64.exe: The process cannot access the file because it is being used by another process.
Could not download node.js v12.20.1 64-bit executable.
```

As shown above, there isn't enough info to suggest the reasons for download failure. Any idea how to solve this problem? I will greatly appreciate it.

**Comment by coreybutler** [comment]
Closing as resolved in new editions of NVM for Windows.
