### ISSUE TITLE
Using single request to get Node and NPM

### ISSUE THREAD

**Issue by rluvaton** [coreybutler/nvm-windows#618]
@coreybutler Thank you for the great project!

I read the code and saw that you do 2 requests:
1. Get the `node.exe`
2. Get the NPM zip file

Instead, I think we can do a single request to download the windows zip file and unzip to get the `node.exe` and npm inside the node_modules folder.

### Advantages:
- Single request
- Download smaller file size
  - `node.exe` is 58MB (for version _15.8.0_)
  - `npm.zip` is 5MB and when unzipped is 9.2MB (for version _7.5.4_)
  - `node.zip` is 26.8MB (for version _15.8.0_ and the NPM for that version) 
- Need to mirror only 1 website (Node.JS dist)
- no need to search the corresponding npm version for the requested node version.

### Disadvantage:
- Unzipping the node.zip will have the total size of 76MB (which can be solved by unzipping only what needed)

**Comment by coreybutler** [comment]
@rluvaton this isn't a bad idea. I may eventually implement it, pending how my attempts to use the msi files go. npm always had 
a goal of working with the msi files, which I believe may resolve some of the weird issues users experience with npm (specifically older versions). npm had a habit of hard coding certain paths (and ignoring symlinks) that are set by the msi files.

**Comment by coreybutler** [comment]
I've implemented this for version 16.9.0+. Older versions may benefit from this as well, but it will require checking every zip file to figure out which ones contain npm and which don't (earlier versions do not).

**Comment by rluvaton** [comment]
Is it available for download already? (I don't see any new release / tag)

**Comment by coreybutler** [comment]
@rluvaton - it will be released in v1.1.8 next week (likely Tuesday or Wednesday).

**Comment by rluvaton** [comment]
Great!, thanks!
