### ISSUE TITLE
Just merge the PR that allows installing latest based on requested version

### ISSUE THREAD

**Issue by Sieabah** [coreybutler/nvm-windows#623]
Hi, 

I made a PR nearly 2.5 years ago that solved the problem of installing the latest version based on the requested version but it was denied for "code quality" purposes which left it in purgatory with a stale request.

I have no intention of fixing this as I use WSL to get around this repo barely being maintained. I need a working NVM and I don't feel like googling the latest version to install.

Assume: Latest v12 -> 12.20.4
Expected Behavior:

nvm install 12 -> 12.20.4
nvm install 12.20 -> 12.20.4
nvm install 12.20.3 -> 12.20.3

Actual Behavior:

nvm install 12 -> 12.0.0

In no world is this the expected behavior as nearly every other program in existence installs the latest when only giving the the major or major.minor version.

The PR is [here](https://github.com/coreybutler/nvm-windows/pull/311), it worked when I last tried it. Anyone who wants to clone/merge my code or do whatever. It's the minimal amount of effort but I really don't care enough to baby it across the line for this repo. You can either modify it with dur's requested changes or keep it consistent with the rest of the codebase.

**Comment by MarthinusBosman** [comment]
Just got here, hay @coreybutler could we do this or can someone recommend an alternative to this repo?

**Comment by CodeDraken** [comment]
It's a minor inconvenience, but you could just run `nvm list available` to avoid having to Google.

```
nvm list available

|   CURRENT    |     LTS      |  OLD STABLE  | OLD UNSTABLE |
|--------------|--------------|--------------|--------------|
|   15.12.0    |   14.16.0    |   0.12.18    |   0.11.16    |
|   15.11.0    |   14.15.5    |   0.12.17    |   0.11.15    |
|   15.10.0    |   14.15.4    |   0.12.16    |   0.11.14    |
|    15.9.0    |   14.15.3    |   0.12.15    |   0.11.13    |
|    15.8.0    |   14.15.2    |   0.12.14    |   0.11.12    |
|    15.7.0    |   14.15.1    |   0.12.13    |   0.11.11    |
|    15.6.0    |   14.15.0    |   0.12.12    |   0.11.10    |
|    15.5.1    |   12.21.0    |   0.12.11    |    0.11.9    |
|    15.5.0    |   12.20.2    |   0.12.10    |    0.11.8    |
|    15.4.0    |   12.20.1    |    0.12.9    |    0.11.7    |
|    15.3.0    |   12.20.0    |    0.12.8    |    0.11.6    |
|    15.2.1    |   12.19.1    |    0.12.7    |    0.11.5    |
|    15.2.0    |   12.19.0    |    0.12.6    |    0.11.4    |
|    15.1.0    |   12.18.4    |    0.12.5    |    0.11.3    |
|    15.0.1    |   12.18.3    |    0.12.4    |    0.11.2    |
|    15.0.0    |   12.18.2    |    0.12.3    |    0.11.1    |
|   14.14.0    |   12.18.1    |    0.12.2    |    0.11.0    |
|   14.13.1    |   12.18.0    |    0.12.1    |    0.9.12    |
|   14.13.0    |   12.17.0    |    0.12.0    |    0.9.11    |
|   14.12.0    |   12.16.3    |   0.10.48    |    0.9.10    |
```

But I agree that support for this repo seems to be dead and we may need an alternative.

**Comment by MarthinusBosman** [comment]
That does actually make it more convenient.

**Comment by Sieabah** [comment]
@CodeDraken While valid, the PR brought this project in line with the expected behavior of what most people assume `nvm install 12` would do. 

It is also in line with what nvm does on linux and OSx.

**Comment by Sieabah** [comment]
Won't bother arguing it much further than this but your change isn't remotely equivalent @coreybutler. I know you're probably busy but I have use cases for maintaining multiple branches other than the LTS version. Namely 10, 12, & 14.

Your code change does not properly address installing latest historical versions outside of LTS.

**Comment by orokanasaru** [comment]
@Sieabah, have you tried it?

![image](https://user-images.githubusercontent.com/5751627/135191859-e2075257-8d24-4fdf-8c7d-bf806eb16564.png)

There were multiple commits around this area. I am not sure why they closed this issue with that one

Unfortunately, it is still worse than your PR

![image](https://user-images.githubusercontent.com/5751627/135192004-9c7dd367-0e5d-4a67-873a-a31d5b7db8b6.png)

**Comment by coreybutler** [comment]
@orokanasaru can you post your screenshots as a new issue? 12.22 should be expanding to the latest patch version.

@Siebah's PR was closed when I reviewed PR's, so another one was merged instead.

**Comment by Sieabah** [comment]
It was open for like **2 years**. It was opened in **2017**.

I closed it because I had no faith it would ever be addressed that assumption was valid up until I guess a recent version. As expressed by orokanasaru though almost 4 years later it still doesn't seem to properly handle major.minor versions. I honestly thought this project was abandoned.

Look, I understand there is always workarounds and it's been expressed "just `nvm list available, bro. just type the correct version, bro`. There is an expectation if you want to be "NVM" for windows, that you would mimic the same behavior and style as the linux/mac NVM. I don't think I've ever, in my life, wanted to install the absolute oldest version of anything when targeting a major version. If I wanted to I'd be explicit, because there would be a reason _to do that in the first place_. I don't go "apt-get install apache" and expect to get Apache 0.9, or any package for that matter.

In the end I don't _really_ care at this point, I switched to [nvs](https://github.com/jasongin/nvs) because I was tired of waiting and parsing a column for which version I want, when the CLI should just work like every other installer in existence. At one point I just compiled my branch but that stopped working with long path names.

If I sound salty it's because you're responding 4 year later "well it was closed.". You had _2 entire years before it was closed_. Then 2 years _after that_ (Feb 23) there was _still_ no solution.

**Comment by coreybutler** [comment]
@Sieabah - Clearly you're holding a lot of resentment, strong opinions, and assumptions about this project (you say you don't care, but your "salty" comments suggest otherwise). I'm not contesting your choice to close the PR, but I'm not going to spend time combing through closed PRs. I chose to merge an open one addressing the same situation that I thought was going to supply the desired functionality. It looks like there are issues with it, but the only way it will be on my radar is if a new issue is logged. That's what I asked for... I didn't ask why you closed your PR.
