### ISSUE TITLE
Switching between versions fails with 32-bit involved

### ISSUE THREAD

**Issue by AGBrown** [coreybutler/nvm-windows#63]
Switching from 32-bit node version A to node version B causes switching back to version A to fail with the message `node v#.##.## (32-bit) is not installed.`. It appears this is because the switch leaves the `node.exe` file named `node.exe` and not `node32.exe`

Repro steps (windows 8.1, cmd.exe run as Administrator):

```
>nvm arch
System Default: 64-bit.
Currently Configured: ?-bit.

D:\dev>nvm install 0.10.37
Downloading node.js version 0.10.37 (64-bit)... Complete
Downloading npm version 1.4.28... Complete
Installing npm v1.4.28...

Installation complete. If you want to use this version, type

nvm use 0.10.37

D:\dev>nvm use 0.10.37
Now using node v0.10.37 (64-bit)

D:\dev>nvm use 0.10.36 32
node v0.10.36 (32-bit) is not installed. <----------- expected - it isn't installed yet

D:\dev>nvm install 0.10.36 32
Downloading node.js version 0.10.36 (32-bit)... Complete
Downloading npm version 1.4.28... Complete
Installing npm v1.4.28...

Installation complete. If you want to use this version, type

nvm use 0.10.36

D:\dev>nvm use 0.10.36 32
Now using node v0.10.36 (32-bit)

D:\dev>nvm install 0.10.37 32
Downloading node.js version 0.10.37 (32-bit)... Complete

D:\dev>nvm use 0.10.37 32
Now using node v0.10.37 (32-bit)

D:\dev>nvm use 0.10.36 32
node v0.10.36 (32-bit) is not installed. <----------- failed - it is installed
```

**Comment by AGBrown** [comment]
It appears this happens when only the 32-bit version (and not the 64-bit version) of version A (in the example above that would be `0.10.36`) is installed - the workaround is to install both 32- and 64-bit versions of all node versions.

**Comment by coreybutler** [comment]
Yes, the code in the released version is missing support for this use case. The master branch has a temporary fix, but you have to build from source. The temporary fix is indeed to install both versions.

**Comment by coreybutler** [comment]
This was resolved and never closed. If it pops up again, please open a new issue.
