### ISSUE TITLE
.nvmrc does not install latest patch when left blank

### ISSUE THREAD

**Issue by ashblue** [coreybutler/nvm-windows#635]
**NVM4W version:** 1.1.7

### My Environment

Windows 10

### Expected Behavior

`.nvmrc` with the contents `14.16` should install the latest patch as NVM does on `nvm use`.

### Actual Behavior

Command instead returns the following.

```bash
.0.0
node v.0.0 (64-bit) is not installed.
```

### Steps to reproduce the problem:

* Create a `.nvmrc` file with the contents `14.16`
* Run `nvm use`
* Notice the output fails to install / use anything (should install 14.16.0 I believe).

**Comment by falconmick** [comment]
@ashblue what was the resolution?
