### ISSUE TITLE
can not support windows program files dir

### ISSUE THREAD

**Issue by bluemiaomiao** [coreybutler/nvm-windows#639]
System Info:
- Windows 10 20H2 x64

Error Details:

```
C:\Users\Administrator>nvm install v10.23.3
Downloading node.js version 10.23.3 (64-bit)...
Complete
Creating C:\Program Files\nvm\temp

Downloading npm version 6.14.11... Complete
Installing npm v6.14.11...

Installation complete. If you want to use this version, type

nvm use 10.23.3

C:\Users\Administrator>nvm use 10.23.3
exit status 1: 'C:\Program' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
```

**Comment by ameet-pradhan-au5** [comment]
hi, I had the same issue I followed the steps given in comments, this worked for me.
https://github.com/coreybutler/nvm-windows/issues/548#issuecomment-747538634

**Comment by rafaelbezerra195** [comment]
I had to install nvm in another path without any space. As this comment : https://github.com/coreybutler/nvm-windows/issues/548#issuecomment-645819540

**Comment by mwittmann** [comment]
Same issue here. I installed `nvm-windows` to `C:\Program files\nvm-windows`. Then, after `nvm install latest`, I tried `nvm use 16.2.0` and got:

    > nvm use 16.2.0
    exit status 1: 'C:\Program' is not recognized as an internal or external command, operable program or batch file.

Sigh.

**Comment by coreybutler** [comment]
Resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8
