### ISSUE TITLE
nodevars.bat file?

### ISSUE THREAD

**Issue by AGBrown** [coreybutler/nvm-windows#64]
Joyent seems to include a nodevars.bat file with their node installs (e.g. https://github.com/joyent/node/blob/v0.10.38/tools/msvs/nodevars.bat). Visual Studio 2015 RC expects this file to be present for some features.

However, that bat file does do some weird things, so this might not be a simple thing to do. I have included it, although I have also added symlinks for `%APPDATA%\npm` and `%ProgramFiles(x86)%\nodejs`, both pointing to `%ProgramFiles%\nodejs`, and I also commented out `set PATH=%APPDATA%\npm;%~dp0;%PATH%` just to be safe.

``` bat
@echo off

rem Ensure this Node.js and npm are first in the PATH
set PATH=%APPDATA%\npm;%~dp0;%PATH%

setlocal enabledelayedexpansion
pushd "%~dp0"

rem Figure out the node version.
set print_version=.\node.exe -p -e "process.versions.node + ' (' + process.arch + ')'"
for /F "usebackq delims=" %%v in (`%print_version%`) do set version=%%v

rem Print message.
if exist npm.cmd (
  echo Your environment has been set up for using Node.js !version! and npm.
) else (
  echo Your environment has been set up for using Node.js !version!.
)

popd
endlocal

rem If we're in the node.js directory, change to the user's home dir.
if "%CD%\"=="%~dp0" cd /d "%HOMEDRIVE%%HOMEPATH%"
```

**Comment by coreybutler** [comment]
Closing due to age.
