### ISSUE TITLE
No uninstaller?

### ISSUE THREAD

**Issue by palbrecht1** [coreybutler/nvm-windows#643]
The documentation specifies the installer .exe file comes with an uninstaller, however, running it after a previous installation doesn't offer you the option to uninstall it. I need to uninstall / reinstall because of #611 #617 et al.

**Comment by coreybutler** [comment]
You can uninstall it like you would any other Windows software, i.e. 
![image](https://user-images.githubusercontent.com/770982/121384424-de85ca80-c90d-11eb-9d9b-b126c5f65b69.png)

Alternatively, you can run the uninstaller manually. See https://github.com/coreybutler/nvm-windows/wiki#uninstall. You may need to update the path if you didn't use the default when NVM4W was installed.
