### ISSUE TITLE
nvm list not show "Currently using..." info and "npm: command not found"

### ISSUE THREAD

**Issue by IChocolateKapa** [coreybutler/nvm-windows#644]
today my nvm broke for the reason I have not got a clue  after it worked just fine for the past 2 years.
After I executed "nvm list" command, it just showed info below:
![微信截图_20210610180605](https://user-images.githubusercontent.com/8414714/121507055-e0878080-ca16-11eb-8aa4-6142c96a48fb.png)

And I uninstalled nvm, reboot, reinstall nvm,  install node verisons, without any error message showed during the process。it just showed the same info"npm: command not found"。
I‘ve did the actions above several times(nvm 1.1.7 and 1.1.6 both tried), it didn't make a change. 
Can anyone help me? thx

**Comment by israeljunior** [comment]
Same here. After some Windows update, NVM is not working anymore.

**Comment by coreybutler** [comment]
Have you updated mingw32? This could be an issue with the mingw32 shell (which isn't supported). Try using a supported shell, such as the standard terminal or powershell.

**Comment by coreybutler** [comment]
Closing due to age. If this occurs in the latest release (https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8), please open a new issue.
