### ISSUE TITLE
confusing error message

### ISSUE THREAD

**Issue by iongion** [coreybutler/nvm-windows#65]
maybe a minor issue, but a more proper error message would be nice(window 8.1- 64):
```
nvm install v0.12.4
```
Node.js vv0.12.4 is only available in 32-bit

but
```
nvm install 0.12.4
```
has no issue

**Comment by vkbansal** [comment]
Duplicate of #37

**Comment by kRITZCREEK** [comment]
:+1: just took me 10min to find this issue...

**Comment by rainabba** [comment]
VERY confusing since `nvm list` reports `v0.12.4`.

**Comment by coreybutler** [comment]
Fixed in 1.1.1
