### ISSUE TITLE
`latest` flag doesn't install the latest LTS

### ISSUE THREAD

**Issue by Ramadanko** [coreybutler/nvm-windows#653]
Adding `latest` flag doesn't install latest LTS version. Is it possible to fix that or leave it and create new flag `--lts` ? 
![Screenshot (182)](https://user-images.githubusercontent.com/62075159/126862811-779f3fd0-76c6-4ae6-b734-83c1eb3e7f61.png)
![Screenshot (183)](https://user-images.githubusercontent.com/62075159/126862816-2d195e1e-b1e9-4407-b35d-5efcc0878cdd.png)

**Comment by coreybutler** [comment]
The inline help is inaccurate. It should be the latest current version.
