### ISSUE TITLE
Corepack is skipped with Node 16.9.0. Unable to access it.

### ISSUE THREAD

**Issue by lockHrt** [coreybutler/nvm-windows#660]
**Issue:**

https://github.com/nodejs/corepack/issues/52

Node 16.9.0 includes a module called corepack. Corepack allows you to use yarn, pnpm without having to install them (just like how you can use npm right now). Terminal is unable to find the corepack. It seems that corepack isn't installed with the node 16.9.0 if we install node via `nvm-windows`

**How To Reproduce:**

1. `nvm install 16.9.0`
2. `nvm use 16.9.0`
3. `corepack enable` 
this one gives error saying it can't recognize/find corepack

[Node docs on Corepack](https://nodejs.org/dist/latest-v16.x/docs/api/corepack.html)

**Comment by 442283045** [comment]
I meet a seem problem

**Comment by coreybutler** [comment]
This was just released as an experimental feature and Node doesn't ship with it for Windows yet. The only bundled distributions released are available at https://github.com/nodejs/corepack/actions/runs/276463953. Until there is a stable download source for Node with corepack on Windows, there isn't much NVM4W can do.

Windows users can apparently install corepack manually though. See https://github.com/nodejs/corepack#manual-installs.

**Comment by merceyz** [comment]
> Node doesn't ship with it for Windows yet

Corepack is installed by default in the Windows installer and is present in the `zip` distributions so not sure what you mean by that.
https://nodejs.org/dist/v16.9.0/node-v16.9.0-win-x86.zip
https://nodejs.org/dist/v16.9.0/node-v16.9.0-win-x64.zip

**Comment by coreybutler** [comment]
Thanks @merceyz - I was unaware it was shipping as part of the distribution. We can work with that.

**Comment by coreybutler** [comment]
Resolved in https://github.com/coreybutler/nvm-windows/releases/tag/1.1.8

**Comment by perqin** [comment]
According to [Corepack's documentation](https://github.com/nodejs/corepack#default-installs):

> Corepack is distributed by default with Node.js 14.19.0 and 16.9.0, but is opt-in for the time being. Run `corepack enable` to install the required shims.

And `corepack` binary file is included in 14.19.0 distributed zip, so this issue also occurs when installing node 14.19.0.
