### ISSUE TITLE
nvm use <any version> - file explorer opens(!?)

### ISSUE THREAD

**Issue by MrCarlLister** [coreybutler/nvm-windows#661]
If this is a question about how to use NVM4W, please use [stackoverflow](http://stackoverflow.com/questions/tagged/nvm-windows) instead.
 
 If this is an issue regarding antivirus, make sure you search the existing issues first.
 
 ### My Environment
 * [ ]  Windows 7 or below (not truly supported due to EOL - see wiki for details)
 * [ ]  Windows 8
 * [ ]  Windows 8.1
 * [x]  Windows 10
 * [ ]  Windows 10 IoT Core
 * [ ]  Windows Server 2012
 * [ ]  Windows Server 2012 R2
 * [ ]  Windows Server 2016
 * [ ]  My Windows installation is non-English.
 
 ### I'm using NVM4W version:
 * [x]  1.1.7
 * [ ]  1.1.6
 * [ ]  1.1.5
 * [ ]  1.1.4
 * [x]  1.1.3 (tried this version also, same issue)
 * [ ]  1.1.2
 * [ ]  1.1.1
 * [ ]  Older
 * [ ]  OTHER (Please Specify)
 
 ### I have already...
 * [x]  read the README to be aware of npm gotchas & antivirus issues.
 * [x]  reviewed the [wiki](https://github.com/coreybutler/nvm-windows/wiki) to make sure my issue hasn't already been resolved.
 * [x]  verified I'm using an account with administrative privileges.
 * [x]  searched the issues (open and closed) to make sure this isn't a duplicate.
 * [x]  made sure this isn't a question about how to use NVM for Windows, since [gitter](https://gitter.im/coreybutler/nvm-windows?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) is used for questions and comments.
 
 ### My issue is related to (check only those which apply):
 * [ ]  settings.txt
 * [ ]  proxy support (Have you tried version 1.1.0+?)
 * [ ]  32 or 64 bit support (Have you tried version 1.1.3+?)
 * [ ]  Character escaping (Have you tried version 1.1.6+?)
 * [x]  A standard shell environment (terminal/powershell)
 * [x]  A non-standard shell environment (Cmder, Hyper, Cygwin, git)
 
 ### Expected Behavior
 Should activate Node v16.9.0
 
 ### Actual Behavior
After running `nvm use 16.9.0` the terminal crashes and file explorer opens(!?)

When running in powershell, it glitches and does say `Now using node 16.9.0` but checking `nvm ls` does not confirm this.
 
 ### Steps to reproduce the problem:
 1. Install using NVM MSI 1.1.7
 2. Open powershell/hyper and type in `nvm install 16.9.0` or `nvm install latest`
 3. Run `nvm use 16.9.0`
 
 I've tried variations on installation path in case it was a space issue. Not sure if related, but I also can't access Comand Prompt (window appears for a split second then closes).

**Comment by coreybutler** [comment]
Well - I've never heard of this happening before. It sounds like you're following the normal procedures, but it sounds like something is going on in your environment. I cannot recreate this in powershell.

Here's what you should consider:

1. There is no `.msi` file - make sure you're using an official version of NVM4W.
2. Hyper is not tested, see [special terminal shells](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#special-terminal-shells)

I have no idea why file explorer is opening, but I suspect there may be an issue with Hyper. When all else fails, use the basic terminal (not powershell) - remember to run as an administrator.

**Comment by MrCarlLister** [comment]
Solved. This was not related to NVM. Turns out it was a bitcoin trojan hijacking command prompt in the registry

[In case it helps anyone else](https://stackoverflow.com/questions/5373137/cmd-exe-closes-immediately-after-calling-win7-64).

**Comment by MrCarlLister** [comment]
Solved. This was not related to NVM. Turns out it was a bitcoin trojan hijacking command prompt in the registry

[In case it helps anyone else](https://stackoverflow.com/questions/5373137/cmd-exe-closes-immediately-after-calling-win7-64).
