### ISSUE TITLE
Install.cmd truncates %PATH% to 1024 variables

### ISSUE THREAD

**Issue by anmiles** [coreybutler/nvm-windows#662]
**Issue:**
`Install.cmd` doing this in 4th line:
`setx /M PATH "%PATH%;%NVM_HOME%;%NVM_SYMLINK%"`
This truncates `%PATH%` to first 1024 symbols and then appends `%NVM_HOME%` and `%NVM_SYMLINK%`.
I had to restore my `%PATH%` after this. Thanks to backups, I had a quick way to do it via loading registry hive and extracting old `%PATH%` from here. But this might be much more painful for other people who didn't have a backup of their `%PATH%` / registry / system drive.

**How To Reproduce:**
1. Have system `%PATH%` more than 1024 characters long
2. Execute `install.cmd`

**Desktop:**
 - OS: Windows 10 x64

**Comment by coreybutler** [comment]
Thanks for reporting and apologies for the inconvenience. This is now resolved in the master branch through the use of the `/M` argument, but I've also added a feature to backup the existing `PATH` before writing to it (not yet pushed). I am planning a release sometime next week. This issue will auto-close when that happens.
