### ISSUE TITLE
 exit status 1

### ISSUE THREAD

**Issue by WiiCoder** [coreybutler/nvm-windows#665]
My Environment:

1. windows10
2. nvm
    ``root: E:\Roaming\nvm ``
     ``path: E:\nodejs ``

Condition:
1. "Exit status 1" appears when using “nvm use” through CMD
2. But it is normal when using "nvm use" through PowerShell

**Comment by coreybutler** [comment]
Is this what you see?

![image](https://user-images.githubusercontent.com/770982/133709187-956ca4e1-f45a-41f7-868e-32301aa5bf30.png)

**Comment by thapecroth** [comment]
I also experience similar problems on window 11, but my isn't work on PowerShell without running as an administrator as well. 
My root: C:/nvm

**Comment by coreybutler** [comment]
The Windows operating system requires administrative privileges to create a symlink. It also requires administrative privileges to write to protected directories like `C:\Program Files`. It doesn't matter whether you use CMD or PowerShell... those requirements are operating-system-level. In other words, your user account must have privileges to create symlinks and write to the `NVM_HOME` directory.

**Comment by WiiCoder** [comment]
Thank you, it is indeed because of permissions.

**Comment by coreybutler** [comment]
Some users may need to right click on powershell/terminal and "run as admin". For users of Windows 10+, it may be desirable to enable developer mode: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development, which will provide more flexible permissions.

**Comment by liudonghua123** [comment]
I tried to execute `nvm use xxx` in an administrator shell, and it worked. However, I can confirm that it did not need an administrator shell to execute in the older versions.

**Comment by bopoh13** [comment]
@liudonghua123 I didn't create the symlink in `cmd` under Administrator for the first time. I had to download and install [Node.js] and then repeat the installation attempt. I didn't change the paths. The installator has several times once again proposed to transfer the established version of [Node.js] and created symlink.

@coreybutler Perhaps it is worth removing the section ":star: :star: Uninstall any pre-existing Node installations!! :star: :star:" in README.

[Node.js]: //nodejs.org/dist/latest-v14.x/
