### ISSUE TITLE
Windows Defender reports the new 1.1.8 version as Trojan

### ISSUE THREAD

**Issue by stevebeauge** [coreybutler/nvm-windows#666]
I'm on the latest W10 PRO build, and using the OOB Windows Defender.

the latest nvm-update.zip is reported as Trojan:

![image](https://user-images.githubusercontent.com/184604/133737490-40b62ade-c53f-4a45-929b-cd9e631f04a5.png)

The error message translation is something like `This program is dangerous and executes commands from an attacker`

Virus Total does not detect any issue : https://www.virustotal.com/gui/url/06807e4ff6982dc9e9bcabcd485bbcf84c822ef06a47d799e9aab71572a3f0e6/detection

I guess it's related to #496 and [others](https://github.com/coreybutler/nvm-windows/issues?q=is%3Aissue+trojan)

**Comment by coreybutler** [comment]
See https://github.com/coreybutler/nvm-windows/discussions/664
