### ISSUE TITLE
Shows up twice in Path and Environment variables

### ISSUE THREAD

**Issue by JesterDollar** [coreybutler/nvm-windows#667]
Not sure if this is a bug or was somehow required to overcome some issue??

The NVM_HOME and NVM_SYMLINK values show up TWO times in the path.  The values are placed in BOTH the user environment and system environment.  I assume it should just be one or the other.

Thanks.

**Comment by coreybutler** [comment]
It is supposed to show up in both. There are circumstances where only the user PATH is recognized and others where only the system PATH is recognized. The most notable use case is when a different user account runs a Node process (with a tool like [node-windows](https://github.com/coreybutler/node-windows)), whereas another user _could_ run NVM4W from a different location.

**Comment by JesterDollar** [comment]
Where would only​ the user path?? User and system are merged when a process is created.  No other app I've ever seen required duplicate entries in the path

________________________________

**Comment by coreybutler** [comment]
@JesterDollar - System & User PATH variables aren't always merged. Windows 2003 and Windows 7 will not merge these if one of them exceeds 1920 characters. In those cases, only one of them will be used. I haven't tested in Windows 8, but I believe it behaves the same way.

NVM4W doesn't "officially" support the older versions of Windows, but I don't want to intentionally do something I know will break existing user environments... at least not in NVM4W. In rt (the successor project I'm working on), using a single PATH should be fine.
