### ISSUE TITLE
exit status 5: Access is denied.

### ISSUE THREAD

**Issue by tymmesyde** [coreybutler/nvm-windows#668]
**Issue:**
When running `nvm use 10.19.0` with nvm v1.1.8 I get a `exit status 5: Access is denied.` error.
When running with Administrator rights I get `exit status 145: The directory is not empty.`

**How To Reproduce:**
1. Install nvm v1.1.7
2. Run `nvm install 10.19.0`
3. Install Node v16.9.1
4. Run `nvm install 16.9.1`
5. Install nvm v1.1.8
6. Run `nvm use 10.19.0`

**Expected Behavior:**
It should switch to version 10.19.0

**Screenshots:**
![image](https://user-images.githubusercontent.com/7889816/133832767-44f3e563-4b9e-40ac-ba50-c342e1373fa0.png)

**Desktop:**
 - OS: Windows 11

**Comment by coreybutler** [comment]
First, step #1 is "Install nvm 1.1.7" - did you mean 1.1.8?

If access is denied, your account doesn't have permission. The NVM4W code doesn't throw an exit status of `5`, meaning this message is passed through from the operating system. 

Was Node installed prior to the installation of NVM4W? **If you try to override an existing Node installation, the directory may not be empty.** The installer attempts to handle this circumstance, but the installer must use the same account used to install the original version of Node... and even then it isn't guaranteed to work on some editions of Windows. This is why the recommendation is to remove prior Node installations before installing NVM4W.

In a fresh environment, using an administrative account, I cannot recreate the issue:

![image](https://user-images.githubusercontent.com/770982/133836730-a0a39b57-766b-470f-869b-b71866d00fe8.png)

However; using a non-admin account, you can see the permissions issue:

![image](https://user-images.githubusercontent.com/770982/133837428-c6e67c80-83e3-4c94-b9d1-69a3557571ea.png)

**Comment by DalderupMaurice** [comment]
I get `exit status 1: Toegang geweigerd.` (It is in dutch but it says access denied) when upgrading to 1.18.
I am running on Windows 10 Pro 20H2

It only says that when I execute `nvm use <version>`

**Comment by tymmesyde** [comment]
> First, step #1 is "Install nvm 1.1.7" - did you mean 1.1.8?

No i meant `1.1.7`

> If access is denied, your account doesn't have permission. The NVM4W code doesn't throw an exit status of `5`, meaning this message is passed through from the operating system.

I didn't switch account and was working fine before installing 1.1.8

> Was Node installed prior to the installation of NVM4W? **If you try to override an existing Node installation, the directory may not be empty.** The installer attempts to handle this circumstance, but the installer must use the same account used to install the original version of Node...

Yes node was installed prior to the install. It was the same account. 

> and even then it isn't guaranteed to work on some editions of Windows. This is why the recommendation is to remove prior Node installations before installing NVM4W.

That must be the reason why it failed, i did not remove prior node install before installing the new version of NVM4M.

**Comment by xander-lw** [comment]
Another workaround is going to the nvm executable (to find it, open CMD and enter: where nvm) and giving it admin rights by going to the executable properties -> compatiblity tab -> enable "run this program as administrator".

**Comment by Liptom328** [comment]
for me worked running command line as administrator
