### ISSUE TITLE
why v1.1.7 is well, but v1.1.8 error status 1 or status 5

### ISSUE THREAD

**Issue by this-ren** [coreybutler/nvm-windows#669]
when Installed nvm v1.1.8, run nvm use xxx, error status1 or status 5.

v1.1.7 all is well.

**Comment by coreybutler** [comment]
This isn't enough information to actually diagnose a problem. My best guess is v1.1.7 was installed with admin permissions while 1.1.8 was not. Exit status 5 is an "Access Denied" from Windows itself. 

Closing as a duplicate of #665 and #665.

**Comment by liudonghua123** [comment]
I have the same issue, I double click `nvm-setup.exe` to install `nvm`, however it seemed not popped up an admin permissions request dialog.

**Comment by Yzzzed** [comment]
Same to me by using Git-Bash.I tried everything but got exit staus 1: You do not have sufficient privilege to perform this operation.

**Comment by r1si** [comment]
me too
