### ISSUE TITLE
After setting proxy, value is not used

### ISSUE THREAD

**Issue by jasperbosch** [coreybutler/nvm-windows#670]
**Issue:**

After setting the proxy `nvm proxy http://proxysomethingurl:8080` the value is saved in `settings.txt` but it is not used. 
Requiring the proxy by `nvm proxy` the proxy is not set.

On W10 in cmd.

Switched back to nvm 1.1.7

**Comment by agonzalezgaliana** [comment]
Same behavior here using NVM 1.1.8 installed via Scoop in a W7 machine. The proxy data is persisted in the settings.txt file however `nvm proxy` shows that the proxy is not set. Other settings part of the settings.txt as `root` are correctly shown in the console by typing `nvm root`.

I've already tried to set/consult the values with administrator rights, turned NVM off and on, and other solutions found on SO.

**Comment by H4M5TER** [comment]
Reproduced on 1.1.8

**Comment by VxRain** [comment]
Reproduced on Win11, nvm version is 1.1.8.

**Comment by mushroom11s** [comment]
Reproduced on Windows 11 Pro Insider Preview ,nvm version is 1.1.8.

**Comment by coreybutler** [comment]
This was a bug introduced in v1.1.8. It has been fixed in[1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9).
