### ISSUE TITLE
No elevation privileges request when nvm use in v1.1.8

### ISSUE THREAD

**Issue by Tester798** [coreybutler/nvm-windows#671]
**Issue:**
In v1.1.7 when running `nvm use` I was getting UAC request for elevated privileges, but in v1.1.8 I'm just getting `exit status 1: You do not have sufficient privilege to perform this operation.` error which reduced convenience of using nvm for me.

**How To Reproduce:**
1. Install v1.1.8
2. Install some nodejs version
3. Run command `nvm use <version>`

**Expected Behavior:**
Elevated request appears as it was in v1.1.7

**Screenshots:**
![image](https://user-images.githubusercontent.com/8844478/134778557-e3776c1e-294a-4e74-b390-c37f80c4fe7b.png)

**Desktop:**
 - OS: Win 10 x64

**Comment by coreybutler** [comment]
This "feature" was highly requested, i.e. eliminating UAC prompts for newer versions of Windows when the prompt wasn't necessary. You're seeing the byproduct of this.

I'm going to leave this open to see how many people upvote/thumbs-up this issue. I most likely won't revert these changes (unless there is overwhelming demand), but I do want to know how many people prefer the older approach. As I develop rt (successor, see https://github.com/coreybutler/nvm-windows/discussions/565), I want to take these kinds of things into consideration.

**Comment by Tester798** [comment]
Thanks for your reply!
Maybe some configurable setting can be added to `settings.txt` file so when it turned on nvm will keep showing UAC requests as before?

**Comment by coreybutler** [comment]
@Tester798 - That's what I was thinking - an attribute in the settings. However; I'm trying not to add new features to this project, so this will likely end up in rt (the successor project, as mentioned above).

**Comment by millimoose** [comment]
I just encountered this and as-is, the experience is jarring. I'm not "many people", I have no idea how they've set things up so that UAC elevation is unnecessary, what happens is NVM just fails to work on a clean install, doesn't really tell me why, nor how to rectify this. Near as I can tell I'm using the latest version of Windows that doesn't require Insider builds.

**Comment by coreybutler** [comment]
@millimoose See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied, specifically the part about enabling developer mode if you haven't already done this.

**Comment by cyxen** [comment]
Hi, run terminal like Administrator

**Comment by millimoose** [comment]
Yeah that's the weird thing, I do have developer mode enabled and I still got the error. Using an administrative terminal works though so at least there's a way around this.

**Comment by ShivamS136** [comment]
I am getting a different error, `Access is denied`. Is this the same issue and the only resolution is to downgrade?

![image](https://user-images.githubusercontent.com/32218762/142160124-70cce1bd-f4bc-4221-a948-46368705fde0.png)

**Comment by lorenzodallavecchia** [comment]
I prefer the old way.

The reason is that I usually realize that I need to switch Node version when in the middle of some task in the console.
Of course, I don't usually run elevated, so I need to open another console just for `nvm use`.

The real problem, as someone mentioned, is the lack of a `sudo` equivalent in Windows.

**Comment by jason-cannon** [comment]
Please revert this! It's so annoying having to open up an entirely different console just to switch versions.

**Comment by coreybutler** [comment]
NVM4W [1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9) will attempt to run under the current user. For administrators who have enabled developer mode, this should simply run. If an access denied error is detected, NVM4W will attempt to auto-rerun the command, triggering the UAC prompt. If the UAC prompt fails (cancelled) or the user doesn't actually have appropriate permissions, the access denied error will be displayed. Hopefully this behavior finds a viable compromise to make everyone happy.

**Comment by jason-cannon** [comment]
@coreybutler this behavior seems to still be occuring. Tested in git bash (my normal shell), powershell, and in command prompt.

<img width="242" alt="image" src="https://user-images.githubusercontent.com/55110049/145657502-3bdd8f79-6238-4ada-8c5f-b5aec31c377d.png">

**Comment by coreybutler** [comment]
@jason-cannon this will still happen if the account doesn't have admin privileges (i.e. access is _actually_ denied by user permissions). Can you verify you're running as an admin?

**Comment by jason-cannon** [comment]
Yup, administrator account. It works just fine if I set git bash to run as administrator. No UAC prompt appears.

**Comment by Fotiman** [comment]
I'm also having the problem still with v1.1.9, with a user that is a local Administrator, and with Developer Mode enabled.  I was trying to use v1.1.9 to get around this problem with 1.1.7, so now I'm completely stuck (can't use node 16.14.0).
https://github.com/npm/cli/issues/4234

**Comment by Fotiman** [comment]
I found a workaround.  I installed nvm to C:\nvm, and when the setup asked where I wanted Node, instead of picking C:\Program Files\nodejs, I picked C:\nodejs.  Now I'm able to "nvm use" without hitting the access denied.  It's not ideal, but better than the alternative.

**Comment by jason-cannon** [comment]
Thank you for that workaround @Fotiman this has been annoying me for awhile.

**Comment by ViliusS** [comment]
Please revert this change. Developer Mode which is suggested in documentation is for completely different purpose. It's when you develop Windows applications on Windows and want to test then. NVM should handle elevation tasks as needed, like it was in 1.1.7.

**Comment by unjello** [comment]
While I still cannot believe this was not resolved...

> The real problem, as someone mentioned, is the lack of a `sudo` equivalent in Windows.

as a workaround I suggest
1/ start using scoop.sh, as you should anyway if you're using Windows
2/ `scoop install  sudo`
3/ `sudo nvm use XX.YY`
4/ ...
5/ profit

**Comment by elbootio** [comment]
We have a Visual Studio solution with several npm projects in it, each one potentially on a different Node version.  We use NVM 4 Windows to switch between the versions, which we do via a PowerShell script which creates lock files to manage the different projects trying to compile all at the same time.  Our machines are tightly controlled by our employer (we make bank software and have extra security concerns), it is not reasonable for us to expect all of our devs to run Visual Studio in administrator mode just so that they can run a build.  While it is probably technically possible to achieve, it is not the desirable path for us. We are currently stuck on v1.1.7 and will likely be unable to upgrade until there is a solution.

**Comment by coreybutler** [comment]
@elbootio - there's no straightforward way to deal with this, but we're designing a solution for this exact scenario in rt (no ETA yet). We're working on several other enterprise challenges as well. I am maintaining a mailing list for those who wish to be notified of rt enterprise updates... happy to add you and/or a rep from your company if you like.

**Comment by ViliusS** [comment]
The equivalent of sudo on Windows is UAC. There is no reason why NVM for Windows could not support both per-user installs and global per-machine installs. Just make a switch in the installer and install to the PATH/env. variables/registry keys accordingly.

**Comment by WORMSS** [comment]
So, is this STILL broken? Sorry, not broken, feature **erroneously** removed.. 
This is such a pain.. I've been sticking with 1.1.7 because of this bug, and unfortunately today I have HAD to upgrade, and can't believe this is still a thing.. 

Can you at least show us where in the code this was removed, so we can hack it back in locally?

**Comment by unjello** [comment]
> Can you at least show us where in the code this was removed, so we can hack it back in locally?

The best hack I've found was `scoop install fnm`. Switched over couple months ago, didn't look back. A bit sad, but I just cannot understand how come this could be an issue for so long.

**Comment by WORMSS** [comment]
I'm actually trying a 'new' hack.. 

I am wondering if I can get NVM to update a symlink in a completely DIFFERENT place.. 
That way I can use
```
%ProgramFiles%\nodejs ----> %UserProfile%\nodejs
```
and then have NVM manage
```
%UserProfile/nodejs -----> %AppData%\nvm\v16.17.0
                    \----> %AppData%\nvm\v16.16.0
                    \----> %AppData%\nvm\v16.15.0
```
That way I don't need admin privileges to create symlinks in %ProgramFiles%
It can switch and swap all day long without admin.. 

The problem I have now is working out HOW to make it do it.

**Comment by coreybutler** [comment]
Folks - I know it can be a pain, but there is no pleasing everyone. Last year the complaints were "we don't want to have UAC prompts for everything". While it may seem like a "simple" change, the project is used in millions of different environments... with thousands of different variations. There is a ripple effect with every release.

This is not my full time job... in fact, it costs me money to keep this project going. I run about 40 OSS projects and I'm working on a more sustainable JS runtime management application (Runtime) to replace this project. If your company needs something faster, there are ways. We've provided paid support arrangements and custom builds for corporations in the past.

That said, Runtime works on a different architecture. It will support UAC prompting and developer mode, giving folks more flexibility in how they manage their Node environments. We're hoping to release Runtime sometime in January.

**Comment by WORMSS** [comment]
Is there a way to make change a different symlink that isn't c:\program files\nodejs?
I tried changing settings.txt but it still updates program files.

If I could get it to just change a symlink that exists in my userdirectory (where admin privledges are not required) I can point program files at that dir (once), and then that can redirect to the different node versions no UAC needed.

**Comment by coreybutler** [comment]
@WORMSS I believe you're referring to the `NVM_SYMLINK` environment variable, which is used to define the "target" directory where symlinks point to. You can change this in your environment variables. For more details, see https://github.com/coreybutler/nvm-windows/wiki#manual-installation.

**Comment by WORMSS** [comment]
AHH, perfect.. I have too many env vars, it got lost in the jungle of them all.. I will play with that now, thank you.

**Comment by WORMSS** [comment]
```shell
C:\WINDOWS\System32>echo %NVM_SYMLINK%
C:\Users\CRichardson\nodejs

C:\WINDOWS\System32>dir /a "c:\Program Files" | findstr nodejs
15/09/2022  08:03pm    <SYMLINKD>     nodejs [C:\Users\CRichardson\nodejs]

C:\WINDOWS\System32>dir /a %userprofile% | findstr nodejs
15/09/2022  08:07pm    <SYMLINKD>     nodejs [C:\Users\CRichardson\AppData\Roaming\nvm\v16.16.0]

C:\WINDOWS\System32>nvm use 16.17.0
Now using node v16.17.0 (64-bit)

C:\WINDOWS\System32>dir /a %userprofile% | findstr nodejs
15/09/2022  08:07pm    <SYMLINKD>     nodejs [C:\Users\CRichardson\AppData\Roaming\nvm\v16.17.0]

C:\WINDOWS\System32>nvm use 16.16.0
Now using node v16.16.0 (64-bit)

C:\WINDOWS\System32>dir /a %userprofile% | findstr nodejs
15/09/2022  08:07pm    <SYMLINKD>     nodejs [C:\Users\CRichardson\AppData\Roaming\nvm\v16.16.0]

C:\WINDOWS\System32>where node
C:\Program Files\nodejs\node.exe
C:\Users\CRichardson\nodejs\node.exe

C:\WINDOWS\System32>nvm root
Current Root: C:\Users\CRichardson\AppData\Roaming\nvm
```

@coreybutler  I couldn't be happier with this arrangement..
1. Everything still thinks node is at %programfiles% so 3rd party stuff works as intended.
2. I can now use `nvm use ***` without Access Denied
3. I don't even get the Double UAC popup from deleting the %programfiles% symlink and then making a new symlink. I don't get UAC at all.. 

This is like the best of ALL WORLDS.. (I obviously needed Admin to create the `mklink /D %programfiles%\nodejs %userprofile%\nodejs` but that is the last time I need to be an admin now.. Perfect Perfect PERFECT

**Comment by Gaspa79** [comment]
Just have an extra option for UAC and that's it. It's not good practice to run terminals as admin after all.
