### ISSUE TITLE
ERROR open \settings.txt: The system cannot find the file specified.

### ISSUE THREAD

**Issue by Uxspy** [coreybutler/nvm-windows#68]
nvmw: V1.0.6, windows 8(64bit), normal install, no errors during install, after install, click finish with "run cmd" by default.

![image](https://cloud.githubusercontent.com/assets/3072295/8594008/a564da58-266f-11e5-9071-6c647518890b.png)

**Comment by Uxspy** [comment]
As a workaround, I copy the "settings.txt" from c:\users\my-user\name\appdata\roaming\nvm to c:\ and it works.

**Comment by mnpenner** [comment]
I had this issue too. Moved settings.txt to C:/ but my install is still broken. Not sure if it's related.

**Comment by jrgleason** [comment]
No roaming file here this is a clean install what am I supposed to do?

**Comment by jrgleason** [comment]
looks like just creating the file with nothing in it works is this correct?

**Comment by reedog117** [comment]
I'm having the same problem with Windows Server 2012 R2. Completely clean Windows install. Downloaded v1.0.6 and have the same issue. Tried copying settings.txt to c:\ but same problem.

Also, attempting to start nvm from the Start Menu causes a window to flash for a split second and then disappear. This makes me think that there's something wrong with paths..

**Comment by tohagan** [comment]
Copied settings.txt to c:\ and it worked for me.

**Comment by reedog117** [comment]
I finally tried a reboot and it seems it worked.  Looks like an environment variable probably needs to be set that doesn't get setup until initial login. I wonder if there's any way to guarantee triggering it right after installation.

**Comment by mnpenner** [comment]
This happens after a fresh install of Windows 10 too, with no prior node or iojs installations.

**Comment by vkbansal** [comment]
I believe that the main culprit behind this error is `NVM_HOME` not being set.

**Comment by mnpenner** [comment]
Yeah, it worked fine for me after I opened a new command prompt and the environment vars were refreshed. I'm not sure if the cmd prompt that pops up at the end of setup opens a little bit too soon? Or does it carry the [lack of] environment vars from the parent process (the installer)? Just a bit annoying that it doesn't appear to install cleanly.

**Comment by rannday** [comment]
Had the same problem. Added nvm and nodejs (C:\Users\Me\WebDev\nvm - I altered default install directory for nvm - C:\Program Files\nodejs) directories to the PATH, restarted CMD, and it's working now. NVM_HOME and NVM_SYMLINK were set with install, but for whatever reason, it wasn't working. Using Windows 10.

**Comment by SandHilt** [comment]
nvmw: V1.0.6, windows 10(64bit) no-install; 
What is workaround if setting.txt no come in pack.

**Comment by tohagan** [comment]
Here's the contents of my `c:\settings.txt` file (replace `<user>` with your user name)

    root: C:\Users\<user>\AppData\Roaming\nvm 
    path: C:\Program Files\nodejs

**Comment by vnen** [comment]
Had this issue with v1.1.0 when I opened cmd.exe from the installer. It worked fine after closing the prompt and opening another.

**Comment by jazzzz** [comment]
Had this with 1.1.0 too, copying `%appdata%\nvm\settings.txt` to `C:\` worked.

**Comment by Tmarty** [comment]
I also had this issue with v1.1.0 when I opened cmd.exe from the installer. It worked fine after closing the prompt and opening another.

**Comment by fresheneesz** [comment]
I have this problem on the cmd prompt opened by the installer - this installer: https://github.com/coreybutler/nvm-windows/releases/download/1.1.0/nvm-setup.zip

If I open up a new command prompt, it works fine. Same as eeeeeverybody else.

**Comment by s100** [comment]
Seeing the same problem when using the "noinstall" version. If there's a particular environment variable which needs to be set before it'll work, that's fine, but the error message should say what needs setting.

**Comment by coreybutler** [comment]
The prompt to open a terminal window after installation has been removed. It may come back in a future version with a different installer. Bottom line: the installer launches the window prematurely on too many systems, in an unreliable patter.... so it's gone in 1.1.1.

**Comment by RicardoSouzaMoura** [comment]
In a noinstall vesion, just running the install.cmd script fix the problem to me

**Comment by toddalbers** [comment]
A suggestion for the nvm installer is maybe give a message to the user at beginning of install that the command window will close once install is complete. Then, just close the command window when the install finishes. Then the user is forced to open a new command window after installation.

**Comment by qaisjp** [comment]
If you come across this error and use Windows Terminal, try closing Windows Terminal completely and reopening it -- don't just open a new tab.

**Comment by bernardoadc** [comment]
Here I installed in a different drive, and it only worked in `a:\settings.txt`. But this is annoying, I wish I could control where this file is (a have a special folder with configs from all apps) or at least in the nvm folder

**Comment by projeffboy** [comment]
I followed what vkbansal did by setting NVM_HOME to where my nvm was and it worked

**Comment by zachbugay** [comment]
I ran into this issue as well. 

I installed nvm using scoop on the latest powershell version, 7.1.4

My NVM_HOME and NVM_SYMLINK environment variables were not set. I had to manually set them. After I manually set the environment variables it worked without creating a settings.txt file, and without any other issues.

**Comment by ryegrammer** [comment]
I ran into this problem doing the manual install. Wasted a ton of time trying most of these suggestions. Eventually, I just uninstalled and did the nvm-setup.zip and it ran without issue... another evening learning computer programming, thinking I'll get something done, but just installed NVM and node... Thanks to those of you that can stick with it and make good things.

**Comment by jones-Blackwell** [comment]
I tried most of the solutions that worked for other people here but still was facing the same issue so I just created a new file and save it as settings.txt inside the folder I extracted the nvm zip.... and manually add this folder to path because the installer.cmd did not work for me even after restart (on windows 10). Opened the new PowerShell (even cmd can work). You can download the settings.txt file on following link 
[settings.txt](https://github.com/coreybutler/nvm-windows/files/8108132/settings.txt) and modify it according to your pc specs.

**Comment by kid1412621** [comment]
for those who install via scoop, dir is: `C:\Users\Alex_Tan\scoop\persist\nvm`

**Comment by duaneking** [comment]
Just had this issue on a brand new install of Windows 11 on a brand new laptop using the latest bits of everything.

If you encounter this issue, close *all* terminals, all instances of Windows Terminal, All instances of console, then get coffee/tea/water, then reopen Windows Terminal as Admin and type 'nvm root' and it should work... it did for me.

**Comment by limbertin** [comment]
**settings.txt** needs to be copied to the root of drive where **nvm** is installed, in my case it was **G:\Program\nvm**, so coping settings.txt to **C:** didn't work, until I copied to **G:\\:settings.txt**

**Comment by PStoner3** [comment]
I just downloaded and used the nvm-setup.exe for version 1.1.9 and had the same issues. While it collected the install and symlink directories, it would seem the installer is not adding the necessary environment variables, %NVM_HOME% and %NVM_SYMLINK%. after following the manual install directions and adding those variables, everything worked perfectly. 

There was no need to move the settings.txt file from the root install directory.

**Comment by basickarl** [comment]
As with everything in Windows: RESTART YOUR MACHINE.

**Comment by Hrojas1997** [comment]
> Como con todo en Windows: REINICIA TU MÁQUINA.

REINICIANDO LA MAQUINA SE ARREGLA.

**Comment by Scyntrus** [comment]
So "noinstall" doesn't mean that you don't have to install, it means that it won't install for you and you have to install it yourself. Just use the setup version.

**Comment by gyohza** [comment]
Just expanding on [the comment by vkbansal](#issuecomment-125421503), which 8 years later still remains helpful:

1. Close every instance of your terminal;
2. Search for and open "Edit the system environment variables";
3. Click **New...** and fill out the prompt with:
  - **Variable name**: `NVM_HOME`;
  - **Variable value**: `%appdata%\nvm` (or whatever path NVM is in);
4. Start the terminal and test it with `nvm current` - no need to reboot. It should display the current version.

**Comment by eric-kelley** [comment]
I have 2 pertinent things to say about this.

1) if you did the manual install from the installation guide you will get this error. Delete the npm folder from your manual install and just run nvm-setup.zip

2) if you are using a company computer you may have to make AppData not hidden

**Comment by ktmn** [comment]
I ran CMD (_not_ PWS) as administrator and ran `mklink "C:\settings.txt" "%APPDATA%\nvm\settings.txt"` for the "workaround"

**Comment by sotoskprs** [comment]
Restarting my PC worked for me

**Comment by kentshenlim** [comment]
For me I named the file as settings.txt; show the extension then the actual name is settings.txt.txt. Remove the extra extension.

**Comment by wykopx** [comment]
SOLUTION FOR AUTOMATED INSTALLATION

I am installing vnvm and all other stuff using winget *.bat script.
In the script i temp set local variable `NVM_HOME` 
This works without any \settings.txt error 

```
winget install --wait --disable-interactivity --location "c:\nvm" -e --id CoreyButler.NVMforWindows
SET NVM_HOME=c:\nvm\
nvm install latest
```

**Comment by liuhe32** [comment]
my suggestion is reinstall by install.cmd    

> scoop 
> scoop  dir

**Comment by devmanx** [comment]
I resolve this issue by setting NVM_HOME environment variable (in system settings) to directory where my nvm.exe file exist

**Comment by JonathanRys** [comment]
I installed nvm on another drive, but kept my symlinks on C.  So I created a `.bash_profile` file in ~ and added this to it:
```
export NVM_HOME="/d/Users/<replace_with_your_user>/AppData/Local/nvm"
export PATH="$NVM_HOME:$PATH"
export NVM_SYMLINK="/c/nvm4w/nodejs"
```
You can find the symlink folder in your $NVM_HOME/settings.txt file
Then I opened a new bash shell and everything worked.

**Comment by Andrej730** [comment]
Got the same error unpacking `nvm-noinstall` and trying to run `nvm install 24`.
Setting `NVM_HOME` also resolved the issue for me.
