### ISSUE TITLE
nvm use command partially working

### ISSUE THREAD

**Issue by ohgasauraus** [coreybutler/nvm-windows#682]
**Issue:**

**How To Reproduce:**

1. nvm install lts  - this command works
2. nvm use lts - this command failed silently
3. nvm use 12.19.0 - this command works
4. nvm use 10.15.0 - this command works

**Expected Behavior:**

nvm should switch to lts version.

![image](https://user-images.githubusercontent.com/26083834/138193438-35c19745-f8ac-45ce-a5e1-91ef61451605.png)

**Desktop:**
 - OS: Window 7 Pro 64 bit

I can see the symbolic link changed in the folder, however npm or node command does not work at all

**Comment by coreybutler** [comment]
This may be an edge case with the use method. In order to synchronize functionality, I've update the use method in this commit: c4a157cad3d8f7df7463dad5886c7d122b60012a. This will have to wait until the 1.1.9 release (which is held up until our new code signing certificate arrives).

**Comment by coreybutler** [comment]
Resolved in 5751e53159feeb7248badbe4f3d36f24c6762a0a. v1.1.9 scheduled for release by or on Dec 10, 2021.

**Comment by coreybutler** [comment]
[v1.1.9](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9) is now available.
