### ISSUE TITLE
[27/10/21]: [install node from local network]

### ISSUE THREAD

**Issue by benayat** [coreybutler/nvm-windows#686]
**Is your feature request related to a problem? Please describe.**
My environment has no direct internet connection,and I'd like to set a local network place,or local folder as a download source for node installation. 

In node_mirror it won't accept a local location(without http/https).

**Describe the solution you'd like**
Add a property in settings to manually state download path,be it a remote or local path in windows.

**Describe alternatives you've considered**
Couldn't find any alternatives.

**Additional context**

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
See https://github.com/coreybutler/nvm-windows/discussions/695.
