### ISSUE TITLE
Proxy setting in settings.txt is not used

### ISSUE THREAD

**Issue by Siggi1981** [coreybutler/nvm-windows#687]
**Issue:**
NVM is not using the saved proxy setting in settings.txt
There is a small bug in nvm.go in line 851:

`res, err := url.Parse(val)
			if err != nil {
				web.SetProxy(res.String(), env.verifyssl)
			}
`
But it should be if err == nil probably. 

**How To Reproduce:**
1. call: nvm proxy http://test.com
2. call nvm proxy

**Expected Behavior:**
nvm should show the set proxy url

**Comment by sassman** [comment]
have the same issue running on `1.1.8` and manually installed (no administrator permissions)

**Comment by sassman** [comment]
a possible duplicate of 670

> by replacing the version 1.1.8 with the 1.1.7, the problem is solved

**Comment by cfranzen** [comment]
Seems to be a general issue reading the settings.txt. I configured the architecture there but `nvm arch` delivers:
```
System Default: 64-bit.
Currently Configured: -bit.
```

**Comment by coreybutler** [comment]
Closing as duplicate of #670.
