### ISSUE TITLE
Change from one version to another

### ISSUE THREAD

**Issue by cristian-smocot** [coreybutler/nvm-windows#69]
I have __nvm__ installed on my Windows 64bit.

I installed the 64 bit version of node 0.12.7
`nvm install 0.12.7 64`

Then I switched to 0.12.6.
`Now using node v0.12.6 (64-bit)`

Then I wanted to switch back to 0.12.7.
`node v0.12.7 (64-bit) is not installed.`
I had to download ``node.exe`` 64 bit version from nodejs official page, and rename the file to ``node64.exe`` and copy it in the folder of 0.12.7.
After that, I could switch back to version 0.12.7

**Comment by coreybutler** [comment]
This is related to issue #63. You happened to manually apply the fix (good job).
