### ISSUE TITLE
nvm-auto-run.cmd is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Nescabir** [coreybutler/nvm-windows#697]
**Issue:**
Cannot use `nvm use`, getting this error :
> 'C:\Users\abcd\AppData\Roaming\nvm\nvm-auto-run.cmd' is not recognized as an internal or external command,
operable program or batch file.

Clean install, clean windows install too, retried after cleaning PATH too

**How To Reproduce:**
- Install NVM via x64 installer
- `nvm install latest`
- `nvm use latest`

**Expected Behavior:**
Should switch to the desired node version, I guess ?

**Desktop:**
 - OS: Win 10 Pro 21H1 19043.1288 (fresh install)

**Comment by coreybutler** [comment]
That file does not exist in this project and it is not included in the installer. Where did you download the installer from?

**Comment by Nescabir** [comment]
From the release tab in GitHub, I also checked but couldn't find it either

**Comment by coreybutler** [comment]
Unfortunately, I'm not sure why you'd be seeing this error. I cannot recreate this on a fresh Windows 10 installation.

**Comment by Nescabir** [comment]
Thanks anyway, I'll find a way to get it working.

**Comment by tHe-AK** [comment]
> Thanks anyway, I'll find a way to get it working.

Hi @Nescabir, I am facing the same issue. Did you find any solution for this?

**Comment by Nescabir** [comment]
Hi, iirc I had to do a fresh install of windows to get it to work. I think I installed another node version manager prior to nvm and it messed up the installation of Corey's nvm.
Hope I could help !
