### ISSUE TITLE
Error when installer itself asks for admin rights

### ISSUE THREAD

**Issue by vkbansal** [coreybutler/nvm-windows#7]
Installer shows different error codes when it itself asks for admin rights
![screenshot 3](https://cloud.githubusercontent.com/assets/5930351/4424056/b2ee1ab0-459a-11e4-8530-f7c21800ebbc.jpg)
![61fec526-4533-11e4-8ca5-4aef968535a1](https://cloud.githubusercontent.com/assets/5930351/4424064/c90a408a-459a-11e4-9acb-2ff7c9059e26.jpg)

**Comment by coreybutler** [comment]
Closing this since a completely new installer is being built for the next version.
