### ISSUE TITLE
sermver calc with nvm 1.1.9

### ISSUE THREAD

**Issue by ShiJuuRoku** [coreybutler/nvm-windows#706]
**Issue:**

With nvm 1.1.9
I think there is a problem with the calculation of the semver when it is not complete

**How To Reproduce:**

```
node> nvm install 14
  No Major.Minor.Patch elements found
```

```
node> nvm install 14.18.2
node> nvm use 14
  node vv14.18.2 (64bit) is not installed or cannot be found.
  
```
  

**Expected Behavior:**

`node> nvm install 14`
Should install the latest node 14 (v14.18.2)

`node> nvm use 14`
Should use v14.18.2
Log display `vv14.18.2`, there are two 'v'

**Comment by coreybutler** [comment]
This should be auto-expanding the version. I've marked this as a bug.

**Comment by coreybutler** [comment]
This has been re-released in v1.1.9 with a note in the change log referencing this issue. https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9

**Comment by ShiJuuRoku** [comment]
The issue still exists for the command 'nvm use'

![image](https://user-images.githubusercontent.com/3122358/146445364-c830e855-7c0f-434c-a4a5-1b0adcf2cfd2.png)

**Comment by coreybutler** [comment]
Technically the `vv` is a different issue, which has been filed as #703.

**Comment by stefan-emakina** [comment]
In version 1.1.7 you can/could switch node versions from within Visual Studio Code.
In later versions (also this last 1.1.9) you will always receive a "exit status 5: Access is denied"
Its an older unsolved issue it seems
https://stackoverflow.com/questions/50563188/access-denied-issue-with-nvm-in-windows-10

Only switching in a separate elevated prompt works, also downgrading to 1.1.7 works

**Comment by chenxinyanc** [comment]
> Technically the `vv` is a different issue (from No Major.Minor.Patch elements found), which has been filed as #703.

I bump into similar issue on nvm v1.1.9.

I've tried to open #703 but GitHub says the page does not exist. Is there anything I can do locally for this? Version abbreviation is a very handy feature...

**Comment by VsevolodChumachenko** [comment]
I download the latest version and still have this problem
![image](https://user-images.githubusercontent.com/53918248/157902842-9d5bc8d8-0f1f-4398-a7b8-b1fc8b0f7cfb.png)

**Comment by karleinarb** [comment]
I am having the same issue as @VsevolodChumachenko 
Downloaded the latest version today
![image](https://user-images.githubusercontent.com/45044399/158160276-94b2196b-bc5b-4654-a81e-a01efa100caa.png)

**Comment by VsevolodChumachenko** [comment]
> I am having the same issue as @VsevolodChumachenko Downloaded the latest version today ![image](https://user-images.githubusercontent.com/45044399/158160276-94b2196b-bc5b-4654-a81e-a01efa100caa.png)

@karleinarb, I tried to install 1.1.7 version and it works for me

**Comment by Tanimpathan** [comment]
nvm use (select exact version downloaded like 14.19.0) did work for me

**Comment by steffy2110** [comment]
@coreybutler what do suggest I have been following on this #706 issue that says access denied issues, I tried several times using nvm version 1.1.9 

nvm use x.x.x command doesn't work in case of executing from VS code terminal when using 1.1.9 v of nvm,
it works on the admin terminal but I want to access it from vs code integrated terminal, and I don't want to change my system's setting to developer enable, is there any way that I can use node on nvm 1.1.9 on vs code?
I have tried downgrading y node versions installation but still, access is denied, the tag of latest suggests that this issue was for version before Dec 15, 2021, I think it still isn't solved, any advice you have, do share, thnx in advance!

<img width="938" alt="image" src="https://user-images.githubusercontent.com/38892411/183742345-5cd047ca-f1ad-4dc5-9488-ada566f0dc81.png">

**Comment by CraigMason** [comment]
I installed this from fresh today and have the issue described above. No previous versions of nvm-windows were on my system.

```
PS C:\Users\camason> nvm list

  * 10.16.2 (Currently using 64-bit executable)
PS C:\Users\camason> nvm install 16
Downloading node.js version 16.16.0 (64-bit)...
Extracting...
Complete


Installation complete. If you want to use this version, type

nvm use 16.16.0
PS C:\Users\camason> nvm use 16
node vv16.16.0 (64-bit) is not installed or cannot be found.
PS C:\Users\camason> nvm use 16.16.0
Now using node v16.16.0 (64-bit)
PS C:\Users\camason> nvm list

  * 16.16.0 (Currently using 64-bit executable)
    10.16.2
```

**Comment by coreybutler** [comment]
_Windows_ requires permissions to create symlinks if you don't have admin rights. See [Symlinks in Windows 10](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/#:~:text=Starting%20with%20Windows%2010%20Insiders%20build%2014972%2C%20symlinks,reliably%20as%20they%20do%20on%20Linux%20or%20OSX.).

If you still don't have access, you have to assure you're not accessing a Windows protected directory (like `C:\Program Files`). 

Finally, if you're on Windows 11, you may have to allow NVM4W in Windows Security.

For those using VS Code, Windows still requires the same permissions of the user that launched VS Code. The sledgehammer solution is to open VS Code as an admin. The more appropriate approach would be to grant your user account permissions to create symlinks and to assure the user account has access to modify the directory where the node root is defined. For an old but still relevant example, see [Permission to make symbolic links in Windows 7](https://superuser.com/questions/104845/permission-to-make-symbolic-links-in-windows-7#:~:text=Computer%20configuration%20%E2%86%92%20Windows%20Settings%20%E2%86%92%20Security%20Settings,in%20for%20the%20change%20to%20have%20an%20effect.).
