### ISSUE TITLE
Support iojs

### ISSUE THREAD

**Issue by calebthebrewer** [coreybutler/nvm-windows#71]
I see that you've dropped iojs support since it is merging with node. Any chance this could be turned back on since they haven't merged yet, and people may want to install legacy versions of iojs?

**Comment by coreybutler** [comment]
I didn't drop io.js support, it was never supported in the first place :-) I considered legacy support, but bottom line is I can't justify the time right now. I'm not opposed to working with someone else on this project. If someone put out a PR on both this project and the supporting [distribution service](https://github.com/coreybutler/nodedistro), and was willing & able to support it as I work on the new version... then I'd consider it.
