### ISSUE TITLE
16 DEC 2021: Remove dependency on VBScript

### ISSUE THREAD

**Issue by dipetersen** [coreybutler/nvm-windows#710]
Currently to switch versions, NVM uses the elevate.vbs script.  My employer prevents vbscript from executing on my development machine.  Is there a way to accomplish the same thing without using vbscript?  They have allowed PowerShell which boggles the mind.

**Comment by coreybutler** [comment]
At the moment, no. When this tool was first created, Go did not have the ability to run elevated commands. In v1.1.9, most operations do not require elevation for admins... which may or may not be a workaround for now.

Go now supports elevated commands, but I'm not going to introduce a potentially breaking change right now with so many users who could be impacted. I've already removed the need for the VBS script in the successor project ([rt](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112)) that already removes the need for this file.

I'm closing as `wontfix`, but I hope it is clear this use case is something that is being addressed.

**Comment by dipetersen** [comment]
Thanks.  I appreciate the answer.
