### ISSUE TITLE
error parsing flags: when -address isn't specified, you must include -stream-stats-catapult-json

### ISSUE THREAD

**Issue by zjh-nuc-AIOT** [coreybutler/nvm-windows#714]
**Issue:**

**How To Reproduce:**

**Expected Behavior:**

![image](https://user-images.githubusercontent.com/57065248/147403400-8d941ac5-aa38-4db6-836a-341077529fbd.png)

**Comment by coreybutler** [comment]
This has nothing to do with NVM4W. It's the Mingw64 shell. Try running commands in a supported shell (terminal or powershell).
