### ISSUE TITLE
node_modules may contain 32 or 64 bit binary builds

### ISSUE THREAD

**Issue by tohagan** [coreybutler/nvm-windows#72]
As I understand it, node_modules may contain 32 or 64 bit binary builds so I was a bit surprised to find that the node_modules directory appears to be shared for 32 and 64 bit versions. Is that right? Maybe it's only used for npm?

**Comment by coreybutler** [comment]
Yes, node_modules is only used for npm, but you still raise a good point. If a module has a native build, it's possible to wind up with mixed bitness in the directory.

**Comment by coreybutler** [comment]
Even though this was a prospective problem, it never generated any further issues. Closing since I (obviously) never got around to doing anything about this. This is already addressed in rt (the successor project).
