### ISSUE TITLE
Add "--reinstall-packages-from" perms to "nvm install" command

### ISSUE THREAD

**Issue by Kayxue** [coreybutler/nvm-windows#721]
**Is your feature request related to a problem? Please describe.**
When I switch to another new node version through this package, I need to install all global package I installed in old node version again.

**Describe the solution you'd like**
Add `--reinstall-packages-from` perms so that all global package in other version can be auto installed on new version.

**Describe alternatives you've considered**
Make a command that can install all global package from other node version to another node version

**Additional context**
No

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
Reopening because it is an enhancement request.

**Comment by SamuelGaona** [comment]
☠️

**Comment by lucas-labs** [comment]
This would be really useful

**Comment by Kayxue** [comment]
Yeah

**Comment by coreybutler** [comment]
See https://github.com/coreybutler/nvm-windows/wiki/New-Features
