### ISSUE TITLE
"nvm could not be found" when user name has umlaut or non-ascii character

### ISSUE THREAD

**Issue by heneds** [coreybutler/nvm-windows#726]
**Issue:**
After a fresh installation of nvm the application does not work but fails with the error message 
"C:\Users\_USERNAME_\AppData\Roaming\nvm could not be found or does not exist. Exiting."
This happens when _USERNAME_ contains a non-ascii character. In the error message these characters are replaced with �.

**How To Reproduce:**
1. Create or use an Windows account with umlauts or non-ascii characters in the user name (and more importantly in the name of the user folder)
2. Install nvm. 
3. If the installer asks to handle an existing node installation, answer yes
4. Run "nvm list" 

**Expected Behavior:**
Expecting to see a list of node versions.

**Workaround:**
It works properly if you correct the path in settings.txt (while keeping the UTF-8 encoding)

**Desktop:**
Windows 11

**Comment by heneds** [comment]
Regarding the workaround: it's the "root" setting that needs correcting.

**Comment by coreybutler** [comment]
Which version of NVM4W are you using? There appears to be an [issue in older versions of Go](https://github.com/golang/go/issues/16857) that misinterpret umlauts and other western European characters. I'm unclear whether these issues are fully resolved in more recent versions of Go.

**Comment by heneds** [comment]
I was using the latest version 1.1.9.

**Comment by heneds** [comment]
I can't find the installer version but it was created on December 15 at ‏‎20:11:50.

**Comment by coreybutler** [comment]
Thanks, v1.1.9 was created with Go 1.17, which is the latest stable release of Go. I'm unsure how to troubleshoot this at the moment since I do not have access to a German version of Windows. There is also a possibility this hasn't been fixed (or a reversion happened). I will look into this to the best of my ability, but I wouldn't count on an immediate resolution given the circumstance.

**Comment by JakeRG** [comment]
+1 from me - same issue seems to have occurred with a colleague with a Ç in his last name trying to install v1.1.9. We have not attempted older versions.

The version of Windows does not seem to be the issue (I _believe_ he too is running on an English install) - it seems to be merely the path to the install location, in this case the username part. If I understand correctly, this should be reproducable by creating a new user (either "online" / MS account, or offline) with one or more "special" characters like those mentioned in the username. But I could be mistaken =)

**Comment by heneds** [comment]
Not stale AFAIK. (Looks like #744 is a recent duplicate.)

**Comment by karl-sjogren** [comment]
I didn't have this problem until after I upgraded to Windows 11 and upgraded NVM. It worked fine before upgrading to 1.1.9 but downgrading now doesn't help.

I got around this by opening `C:\Users\Karl-JohanSjögren\AppData\Roaming\nvm\settings.txt` and resaving the file as UTF8, so I'm guessing that it could have something to do with how the installer writes this file on Windows 11?

**Comment by coreybutler** [comment]
@karl-sjogren thanks for sharing. It could be the installer, but it could also be Windows 11 not respecting the file encoding (which _should_ be UTF8 by default). It's a little difficult to tell while Windows 11 keeps receiving updates.

It sounds like encoding is the problem regardless of whether the content is read from the settings file or displayed as an error message.

Go 1.18 was just released and it looks like there _may_ be a fix. I'll try building the next maintenance release on this to see if it resolves @heneds original issue. As for the installer, it hasn't changed in years (and works on American English editions), so I suspect something is going on with the Windows 11 encoding. Regardless, I will look into this when I get a chance to build the next update.

**Comment by eugeniomiro** [comment]
Having this same issue on Windows 11 and NVM 1.1.9 installed from Winget

**Comment by coreybutler** [comment]
This wasn't supposed to be closed by the bot.

**Comment by senthamizh-selvan-sf3819** [comment]
Can't we add the `chcp 65001 > nul` line to the _nvm-windows/bin/install.cmd line 21_ for saving files in UTF-8 format? If this isn't useful, please accept my apologies for wasting your time.

https://stackoverflow.com/questions/16598785/save-text-file-in-utf-8-encoding-using-cmd-exe

**Comment by JakeRG** [comment]
I only realized after @noysom 's message that I never mentioned that, afaik, my colleague who has this issue is also running on Windows 10 instead of 11.

We eventually worked around it by installing NVM in a different location (read; not the user directory, and thus avoiding having the non-ascii character in his username in the install path), as mentioned before.

**Comment by Snailedlt** [comment]
Same issue on Windows 10 Pro with a non-ascii username (`Jørgen`)
![image](https://user-images.githubusercontent.com/43886029/179617810-f44c6de5-195d-465e-bc17-57a985d30271.png)

![image](https://user-images.githubusercontent.com/43886029/179617957-1a4f77a2-e086-49ad-8bf3-15b0f2c121e1.png)

```
PS C:\Users\Jørgen> nvm install lts
C:\Users\J�rgen\AppData\Roaming\nvm could not be found or does not exist. Exiting.
Downloading node.js version 16.16.0 (64-bit)...
Error while creating C:\Users\J�rgen\AppData\Roaming\nvm\v16.16.0\node.zip - open C:\Users\J�rgen\AppData\Roaming\nvm\v16.16.0\node.zip: The system cannot find the path specified.
Could not download node.js v16.16.0 64-bit executable.
PS C:\Users\Jørgen> nvm list
C:\Users\J�rgen\AppData\Roaming\nvm could not be found or does not exist. Exiting.

No installations recognized.
```

**Comment by DennisRosen** [comment]
Just ran into this as well and had to change the installation directory.

**Comment by LoboMetalurgico** [comment]
This issue also happens if the username contains a space, however the workaround does not work.

**Comment by GuillaumeNo** [comment]
It has also happened to me on Windows 11 Pro, my username contains a `ë` character. The workaround has worked.

Adding it to the Documentation would be nice. I can do it if you want

**Comment by tscislo** [comment]
Same for me Windows 11 with Polish non ascii signs workaround with changing settings.txt to urf-8 encoding helped https://github.com/coreybutler/nvm-windows/issues/726#issuecomment-1067088011

**Comment by snerte** [comment]
> I didn't have this problem until after I upgraded to Windows 11 and upgraded NVM. It worked fine before upgrading to 1.1.9 but downgrading now doesn't help.
> 
> I got around this by opening `C:\Users\Karl-JohanSjögren\AppData\Roaming\nvm\settings.txt` and resaving the file as UTF8, so I'm guessing that it could have something to do with how the installer writes this file on Windows 11?

Happened to me today. This workaround fixed it.

```
➜ nvm -v
1.1.11
```

**Comment by 62791755** [comment]
aio plugins:install @adobe/aio-cli-plugin-api-mesh

**Comment by klorfrosken** [comment]
Just encountered this issue on Windows 11 and fixed it with the workaround. Can confirm that the settings.txt was saved with ANSI encoding and not UTF-8

![image](https://github.com/coreybutler/nvm-windows/assets/49696315/eefa8450-18ff-43bf-b02c-e37bc1b3d575)

**Comment by numbworks** [comment]
Thank you for your work guys!

**OS**: `Windows 10`
**nvm**: `1.2.2`

I have a "è" in my username and I got this issue as well. 
Converting `%AppData%\Local\nvm\settings.txt` from ANSI to UTF8 fixes the issue.

Any plan to fix this issue permanently?

**Comment by sundaydivine146-hub** [comment]
> **Issue:** After a fresh installation of nvm the application does not work but fails with the error message "C:\Users_USERNAME_\AppData\Roaming\nvm could not be found or does not exist. Exiting." This happens when _USERNAME_ contains a non-ascii character. In the error message these characters are replaced with �.
> 
> **How To Reproduce:**
> 
> 1. Create or use an Windows account with umlauts or non-ascii characters in the user name (and more importantly in the name of the user folder)
> 2. Install nvm.
> 3. If the installer asks to handle an existing node installation, answer yes
> 4. Run "nvm list"
> 
> **Expected Behavior:** Expecting to see a list of node versions.
> 
> **Workaround:** It works properly if you correct the path in settings.txt (while keeping the UTF-8 encoding)
> 
> **Desktop:** Windows 11

https://github.com/coreybutler/nvm-windows/issues/726#issue-1103305408

**Comment by coreybutler** [comment]
Update: v2 uses native windows encoding. If you found your way to this issue through Google/AI, consider upgrading to v2.
