### ISSUE TITLE
Upgrade an existing node version

### ISSUE THREAD

**Issue by r1si** [coreybutler/nvm-windows#730]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when try to upgrade and existing version. For example i want to update LTS to 16.13.2 from 16.13.1

**Describe the solution you'd like**
nwm update [current version] [new version]

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
How would this be any different from switching to a more recent version?

**Comment by r1si** [comment]
If I can upgrade a version (even a minor one) I can not install all the global packages again. :)

**Comment by coreybutler** [comment]
Upgrading could also break global modules.

There are other enhancement requests open for managing global module upgrades in a manner that won't break. I'm closing this in favor of #721.
