### ISSUE TITLE
nvm alias default node command is not working

### ISSUE THREAD

**Issue by abhimanusharma** [coreybutler/nvm-windows#736]
I have recently installed windows 11 and then installed nvm. I have installed node version 16.1.0 for my project requirement and want to set it as default. 

`nvm alias default 16.1.0` command is not working and also not showing in commands list.

**Comment by coreybutler** [comment]
This is not a feature of NVM for Windows. This is not [nvm](https://github.com/nvm-sh/nvm). Please read the [README](https://github.com/coreybutler/nvm-windows).

**Comment by abhimanusharma** [comment]
Then how to set default version @coreybutler , instead of just closing the issue, either tell me the solution or include this in future release.

**Comment by coreybutler** [comment]
Again, this project doesn't have the concept of aliases. If you want them, one possible solution is to fork the project and create your own aliases.

Aliases are not on the roadmap for this project. The discussions contain more details about the roadmap and [the wiki](
https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported) describes why certain nvm features are not included in NVM for Windows.

[This thread](https://github.com/coreybutler/nvm-windows/issues/722) also provides some context.

**Comment by ashutosh887** [comment]
Why is this Feature not a part of nvm for windows?

**Comment by luisgv94** [comment]
I thought it was on previous version?

**Comment by prakash118** [comment]
The way I switched my default nodejs version to another version is by deleting the current version. _I understand it is not ideal for everyone._

1. First install the required node version (you should be using the newly installed version else use `nvm use <version>`)
2. Delete the current default nodejs version. (`nvm uninstall <version>`)

I recently ran into this issue when our project upgraded however in my case I don't need to switch back and forth the nodejs versions.

**Comment by anuraagtech** [comment]
Now nvm use 2x works globally !
Ok for me thanks !
