### ISSUE TITLE
nvm seems not identifies system architecture and node doesn't execute scripts for older version of node

### ISSUE THREAD

**Issue by silmerio** [coreybutler/nvm-windows#739]
**Issue:**
I've installed some version of node with nvm but for older version nvm arch retrieve:
System Default: 64-bit.
Currently Configured: Unknown-bit.

therefore node doesn't sxecute scripts and exit silently without messages

**How To Reproduce:**
nvm install 6.3.1
nvm arch 

> System Default: 64-bit.

> Currently Configured: Unknown-bit.

**Expected Behavior:**

> System Default: 64-bit.

> Currently Configured: 64-bit.
![image](https://user-images.githubusercontent.com/4418932/151144674-d7c33ab4-e96c-4098-884c-047b2a020b68.png)
![image](https://user-images.githubusercontent.com/4418932/151142601-d76937ad-a287-409f-aa0a-46f34acd67ee.png)
https://watch.screencastify.com/v/Qblmnmb94sQmL0qUW0c4

i'm running on Windows 10 Pro build 19043.1466

**Comment by coreybutler** [comment]
I cannot recreate this. Installing 6.3.1 works (and run scripts).

<img width="384" alt="image" src="https://user-images.githubusercontent.com/770982/151638196-da84868d-1294-44ec-9d2f-400512459fa9.png">

Have you tried explicitly setting the arch? ex: `nvm arch 64`

<img width="227" alt="image" src="https://user-images.githubusercontent.com/770982/151638660-6ad88f2d-c682-4478-a19c-f433d79072f3.png">

**Comment by silmerio** [comment]
Setting explicitly the arch has no effect
![image](https://user-images.githubusercontent.com/4418932/151771610-557fccad-a58e-4636-8cec-3077a3bd2fa7.png)
but 32 bit version allow me to run scripts on older versions.

https://watch.screencastify.com/v/Z0FQuRvT8VWgwK1maFYX

Thank you for the support.

**Comment by coreybutler** [comment]
In your screencast, you're just running `nvm use 5.1.0`. Does it work when you specify the architecture, i.e. `nvm use 5.1.0 32` or `nvm use 5.1.0 64`?

What does the `settings.txt` file show for the arch? This can be found under the NVM installation directory. For example:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/770982/151853104-fc88180b-ff4f-420f-b3a4-3bd3230b6749.png">

**Comment by silmerio** [comment]
Is not working even if i specify architecture.

https://watch.screencastify.com/v/T2mYxWOfXCIG6XS0MC9Y

Content of settings.txt
root: C:\Users\smeconi\AppData\Roaming\nvm
arch: 64
proxy: none
originalpath: .
originalversion: 
node_mirror: 
npm_mirror:

**Comment by coreybutler** [comment]
Again, I cannot recreate this.

<img width="346" alt="image" src="https://user-images.githubusercontent.com/770982/151982171-6a0b617e-4a05-472d-b042-d8b57236ba64.png">

While it is perplexing that the architecture isn't displaying correctly, it shouldn't prevent the node executable from running. It makes me think there may be something wrong with the executable or something is blocking it. Reinstalling the affected version may help (i.e. version 5.1.0), but I'm not sure that will really work. You can try executing the command directly, like this:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/770982/151983668-97c756a6-6fd9-43ea-9a50-66008f814f6b.png">

If that doesn't work, I'd reinstall that version of node to make sure there isn't a problem with the executable.

**Comment by lokeshselvam** [comment]
I too have same issue

I already have node installed v18.13.0

While installing it prompts to accept it 

Then I installed node 4.5.0 using nvm 

Now If I shift to node 4.5.0 and execute any scripts it's not returning me anything and as above the (unknown bit version ) in nvm arch

**Comment by silmerio** [comment]
A workaround was to install the 32bit version for me: 
nvm i 4.5.0 32
nvm use 4.5.0 32

**Comment by khadija-chennaoui** [comment]
> Une solution de contournement consistait à installer la version 32 bits pour moi : nvm i 4.5.0 32 nvm use 4.5.0 32

Merci bcq
