### ISSUE TITLE
NVM can't install node when user folder contains å, ä or ö character

### ISSUE THREAD

**Issue by fsjobeck** [coreybutler/nvm-windows#741]
My surname contains an Ö and when i use my AzureAD account and set up my W11 user profile my user folder contains this character. When trying to run nvm install via PowerShell it seems to be failing due to the character not being recognised and the path becomes invalid to the executable.

**Comment by coreybutler** [comment]
@fsjobeck Which version of NVM4W are you using? You may be experiencing the same issue causing #726.

**Comment by fsjobeck** [comment]
I was using the latest version of NVM available at the time on a freshly installed Windows 11 Pro machine.
