### ISSUE TITLE
nvm does not elevate and prompt for admin credentials

### ISSUE THREAD

**Issue by larsenqec** [coreybutler/nvm-windows#743]
**Issue:**
I was running nvm 1.1.7  on Windows 10. I could run "nvm use x.y.z" as a standard user and I would get UAC prompts to enter admin credentials. It worked.

Moving to a new Windows 11 machine, I installed nvm 1.1.9. But when I run "nvm use x.y.z" it just says "You do not have sufficient privileges to perform this operation". There is no prompt for elevation.

Is this on purpose? Did something change? 

If this new behavior is intended, the steps to run nvm as an administrator are quite a bit more clunky than just prompting for privilege elevation. I don't care for it.

**How To Reproduce:**
Unzip nvm-noinstall.zip to C:\dev\tools\nvm

settings.txt content:
root: C:\dev\tools\nvm
path: C:\dev\tools\nodejs

**Expected Behavior:**
"nvm use x.y.z" should ask for credentials

**Comment by larsenqec** [comment]
Running "nvm use" from an admin shell didn't work either -- Sorry I did not grab the error message because I've killed an our on this and I'm just angry now.

I dropped the 1.1.7 files into my nvm folder and it's working as it did in Windows 10.

**Comment by coreybutler** [comment]
Yes, things changed. See the [common issues](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145).
