### ISSUE TITLE
Occurs when I do the following "nvm install version"

### ISSUE THREAD

**Issue by ukyo717** [coreybutler/nvm-windows#744]
As a test, I type nvm install 16.13.2.
Similar error occurs in other versions.

`C:\Users\UserName>nvm install 16.13.2
C:\Users\�_�R�E��\AppData\Roaming\nvm could not be found or does not exist. Exiting.
Downloading node.js version 16.13.2 (64-bit)...
Error while creating C:\Users\�_�R�E��\AppData\Roaming\nvm\v16.13.2\node.zip - open C:\Users\�_�R�E� �\AppData\Roaming\nvm\v16.13.2\node.zip: The system cannot find the path specified.
Could not download node.js v16.13.2 64-bit executable.`

**Comment by coreybutler** [comment]
Which version of Windows are you using? Does it use western European characters?

**Comment by morneluckybeard** [comment]
I had a similar issue, using Windows 11, but I have a feeling it had to do with my name having an Acute accent "Morné" in the username.

I installed straight to c:/nvm instead, works just fine.

**Comment by coreybutler** [comment]
@morneluckybeard - I believe you're running into #741/#726.
