### ISSUE TITLE
nvm install lts - tries to install lts.0.0

### ISSUE THREAD

**Issue by philipmat** [coreybutler/nvm-windows#745]
**Issue:**
Trying to install "lts" version fails. `nvm` seems to try parsing "lts" as if it was a version

**How To Reproduce:**
```
> nvm install lts
lts.0.0
Node.js vlts.0.0 is only available in 32-bit.
[ C:\WINDOWS\system32 ]  Tue, 08 Feb 2022 19:34:43 GMT
> nvm install --lts
--lts.0.0
Node.js v--lts.0.0 is only available in 32-bit.
```

**Expected Behavior:**
Expected to work like it does with `nvm install latest`:

```
> nvm install latest -v
Downloading node.js version 17.4.0 (64-bit)...
Complete
Creating C:\ProgramData\nvm\temp

Downloading npm version 8.3.1... Complete
Installing npm v8.3.1...

Installation complete. If you want to use this version, type

nvm use 17.4.0
[ C:\WINDOWS\system32 ]  Tue, 08 Feb 2022 19:43:56 GMT
> nvm list

    17.4.0
```

**Desktop:**
 - OS Name:                   Microsoft Windows 10 Pro
 - OS Version:                10.0.19043 N/A Build 19043
 - nvm version 1.1.7; installed through Chocolate

**Additional context:**
Work around: `nvm install 16.14.0`.  Workaround found in:  https://github.com/ampproject/amphtml/issues/17538

**Comment by kamack38** [comment]
You need to update to the newest version (`1.19`).

**Comment by kamack38** [comment]
Installing/uninstalling versions via *aliases* was added in `1.18`.

**Comment by coreybutler** [comment]
@kamack38 is correct, named installations are only supported in 1.1.8 and above.
