### ISSUE TITLE
nvm 1.1.9 use still not working with Windows due to "access denied"

### ISSUE THREAD

**Issue by CreeTar** [coreybutler/nvm-windows#748]
**Issue:**
when trying to switch the NVM version, there are always error messages regarding access being denied.
The message is extremly vague and is not explaining to what access this applies.

ENVs:
```
NVM_HOME=D:\Tools\nvm
NVM_SYMLINK=C:\Program Files\nodejs
```

settings.txt:
```
root: D:\Tools\nvm
path: C:\Program Files\nodejs
```

running as normal user
```
D:\Tools\nvm>nvm use 14.19.0
exit status 1: Access denied
```

running same as admin
```
D:\Tools\nvm>nvm use 14.19.0
exit status 1: You do not have sufficient privilege to perform this operation.
```

**How To Reproduce:**
1. Install nvm for windows
2. nvm install 14.19.0
3. nvm use 14.19.0

**Expected Behavior:**
nodejs is set to 14.19.0

**Desktop:**
 - Windows 20H2 19042.1348

**Comment by lawweiliang** [comment]
Hi @CreeTar Brother, I am getting this error as well, how did you solved it?

**Comment by lawweiliang** [comment]
Arr, I found the solution ad. What you need to do is just open the command prompt in 'administrator mode`. 
Then, problem solved. 

![image](https://user-images.githubusercontent.com/34936929/158925659-b97331a4-5455-4825-ac34-9ce44e0b3a26.png)
