### ISSUE TITLE
nvm-setup checksum mismatch?

### ISSUE THREAD

**Issue by Endovic** [coreybutler/nvm-windows#752]
**Issue:**

1.1.9 install package checksum verification failed.

**How To Reproduce:**

On Windows 10 command line, run CertUtil on nvm-setup.exe after unzipping nvm-setup.zip

**Expected Behavior:**

Checksum should match that of nvm-setup.zip.checksum

**Screenshots:**
![nvm install checksum](https://user-images.githubusercontent.com/61358146/154472553-ad6b85d4-edbc-4088-b739-424543b34530.jpg)

**Comment by ProjectPort** [comment]
Same problem here.  I am using a Windows app to check for a match of the checksum for the .ZIP file and the text string in the nvm-update.zip.checksum.txt file. It would be nice if the nvm-update.zip.checksum.txt indicated what type of checksum it was meant to check against but it does not. Given the length, I am guessing it is MD5. The app I have, "MD5 and SHA Checksum Utility 2.1 Pro" from: https://raylin.wordpress.com/ displays its own checksums for any file you point it at...in this case: nvm-setup.zip. It shows everything from CRC-32 all the way up to SHA-512. The checksum in your update.zip.checksum.txt doesn't match any of them.

Going with my guess of MD5 (based on the length), the MD5 checksum of the ZIP file is a 32 character string of 63E2C735A2594CF6626B507C55464DF2 while the string in the update.zip.checksum.txt file (as of today) is showing a 32 character string of 9109BCD822DD1E8111410B189AB9AE26.

After a couple of virus checks on the ZIP file, I went ahead and unzipped it - producing nvm-setup.exe. I ran the checksum you provided against the .exe in case that was what it was meant for. It didn't match the .exe either.

The logical explanation for this is that the ZIP file, and the underlying .exe were updated and no one  updated the checksum text file. Could you at least quickly check that?

This mis-match has stopped my installation of NVM for security reasons. A quick fix would be much appreciated.

**Comment by rusenaltindag** [comment]
This what comes to my mind before installing

**Comment by Adr-hub** [comment]
Checksum verification failed as well.  I ran CertUtil on nvm-setup.exe for version 1.1.9 and on nvm-update for version 1.1.10.
