### ISSUE TITLE
Weird behaviour of nvm in git bash 

### ISSUE THREAD

**Issue by bl0cknumber** [coreybutler/nvm-windows#753]
![Capture](https://user-images.githubusercontent.com/50759463/154843564-b72533ef-f98e-4c89-adb5-3bff45c21aac.PNG)

**ignore the access denied error**

nvm install 16 works smoothly and goes directly to 16.14.0 but unfortunately nvm use is doesn't work the same way as nvm install.

The result was produce double v.

rel https://github.com/nvm-sh/nvm/issues/2751

**Comment by badmetevils** [comment]
@bl0cknumber 
Try to run the same using admin privilege that does the job for me.
