### ISSUE TITLE
NVM unable to install version listed as available

### ISSUE THREAD

**Issue by mhscott64** [coreybutler/nvm-windows#756]
This issue was logged a issue 50 and again as issue 503.  Those are closed, but I am experiencing it again.
As I write this, nvm list available reports the highest available LTS as 16.13.0, but an attempt to install it yields:
   Node.js v16.13.0 is not yet released or available.
This check is apparently hard to write, and, it strikes me, completely redundant.  If the version number is bad, there will be no content at the URL we build, and there is logic to check for this.
Can we just remove this test?

**Comment by coreybutler** [comment]
I'm not able to recreate these issues:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/770982/157332248-87320874-a768-4b4a-bb57-c1944a09937d.png">

<img width="371" alt="image" src="https://user-images.githubusercontent.com/770982/157332474-bc8d5cc7-2d76-4e12-a614-653ee3785dca.png">

There's a chance the node distribution list outpaces the availability of the download. The distribution file (JSON) is built quickly, but Node itself takes quite awhile to build. If I'm not mistaken, the Node release process updates the distribution file at the same time as the build, but the build takes substantially longer to publish. This could create a small gap where the distribution list shows a new LTS version before the download is completely ready.

Issue 503 has to do with custom aliases, which aren't supported. The only supported aliases are available to the install/use commands as described in the [usage](https://github.com/coreybutler/nvm-windows#usage) section. Custom aliases are on the roadmap for [rt](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112).

The check may be redundant, but it's also not changing the outcome. I'm not necessarily opposed to stripping it out, but it's not really a priority.

**Comment by mhscott64** [comment]
Corey:
Thank you for taking the time to take a look.  I don't dispute your
results, but let me share my experience.  We forked the project last week
and pulled it into our corporate repository and built the project.  I
executed *list available* and *install *and got these results:
[image: image.png]
As you can see, it is listed as available, and will not install.
I commented out the logic that produces that message, built it, ran the
same commands, and successfully installed the version.
And as you can see here, attempting to install a version new than the
latest LTS still gives a useful message:
[image: image.png]

I respect your decision if you don't want to include it.  I'll pull a fresh
code base, and see if some other change has fixed this.  If not, I'll
submit my PR.  We'll run with our fork if you don't accept it.
Thanks for your time!
Have a great day!
Mark

**Comment by mhscott64** [comment]
hmmm... I'll get you the text instead... here's the whole thing, but with
text:

Corey:
Thank you for taking the time to take a look.  I don't dispute your
results, but let me share my experience.  We forked the project last week
and pulled it into our corporate repository and built the project.  I
executed *list available* and *install *and got these results:
[image: image.png]
(base) PS C:\Users\mscott3\AppData\Roaming> nvm list

  * 14.18.1 (Currently using 64-bit executable)
(base) PS C:\Users\mscott3\AppData\Roaming> nvm list available

|   CURRENT    |     LTS      |  OLD STABLE  | OLD UNSTABLE |
|--------------|--------------|--------------|--------------|
|    17.1.0    |   *16.13.0*    |   0.12.18    |   0.11.16    |
|    17.0.1    |   14.18.1    |   0.12.17    |   0.11.15    |
|    17.0.0    |   14.18.0    |   0.12.16    |   0.11.14    |
|   16.12.0    |   14.17.6    |   0.12.15    |   0.11.13    |
|   16.11.1    |   14.17.5    |   0.12.14    |   0.11.12    |
|   16.11.0    |   14.17.4    |   0.12.13    |   0.11.11    |
|   16.10.0    |   14.17.3    |   0.12.12    |   0.11.10    |
|    16.9.1    |   14.17.2    |   0.12.11    |    0.11.9    |
|    16.9.0    |   14.17.1    |   0.12.10    |    0.11.8    |
|    16.8.0    |   14.17.0    |    0.12.9    |    0.11.7    |
|    16.7.0    |   14.16.1    |    0.12.8    |    0.11.6    |
|    16.6.2    |   14.16.0    |    0.12.7    |    0.11.5    |
|    16.6.1    |   14.15.5    |    0.12.6    |    0.11.4    |
|    16.6.0    |   14.15.4    |    0.12.5    |    0.11.3    |
|    16.5.0    |   14.15.3    |    0.12.4    |    0.11.2    |
|    16.4.2    |   14.15.2    |    0.12.3    |    0.11.1    |
|    16.4.1    |   14.15.1    |    0.12.2    |    0.11.0    |
|    16.4.0    |   14.15.0    |    0.12.1    |    0.9.12    |
|    16.3.0    |   12.22.7    |    0.12.0    |    0.9.11    |
|    16.2.0    |   12.22.6    |   0.10.48    |    0.9.10    |

This is a partial list. For a complete list, visit
https://nodejs.org/download/releases
(base) PS C:\Users\mscott3\AppData\Roaming> nvm install *16.13.0*
*Node.js v16.13.0 is not yet released or available.*

As you can see, it is listed as available, and will not install.
I commented out the logic that produces that message, built it, ran the
same commands, and successfully installed the version.

And as you can see here, attempting to install a version newer than the
latest LTS still gives a useful message:
[image: image.png]
(base) PS C:\Users\mscott3\AppData\Roaming> nvm install 16.14.0

Version 16.14.0 is not available.

The complete list of available versions can be found at https://a059225
***@***.***/artifactory/pgr-nodejs/index.json

I respect your decision if you don't want to include it.  I'll pull a fresh
code base, and see if some other change has fixed this.  If not, I'll
submit my PR.  We'll run with our fork if you don't accept it.
Thanks for your time!
Have a great day!
Mark
P.S. - I note that the password in the URL is not masked - time allowing,
I'll look at that too.

**Comment by jamiehumphries** [comment]
Ah, thanks @RomainJamet. Yes it is working again now for me as well. Seems to have been a transient issue.

**Comment by wang1212** [comment]
I had the same problem and couldn't install any version.

**Comment by coreybutler** [comment]
@wang1212 - interesting. Were you still able to install from the mirror?

**Comment by tchetwin** [comment]
For folks using their own internal/corporate/other mirror, I think this stems from the mirror treating ~all files as immutable, including the `/latest/SHASUMS256.txt` and `/index.json`.

Most files in the mirror _are_ immutable, with those notable exceptions. I imagine they need to be wiped on a regular basis to ensure freshness.

Similar issue reported by someone else here for `/index.json`: https://bytemeta.vip/repo/nvm-sh/nvm/issues/2836

---

Regarding "the check", I assume we're talking about this: https://github.com/coreybutler/nvm-windows/blob/c1a633745ccfcfaedff34fdc72d3ca368720f166/src/nvm.go#L325-L328

Ideally this seems like something that should either be a warning, or be attempted only when the version the user requested is failing to download (to hint as to why it is failing). In this case it is causing an install to fail that would likely otherwise succeed.

**Comment by xHergz** [comment]
I was running nvm 1.1.8 and was getting this error when trying to install node 20.3.1. I resolved it by upgrading to NVM 1.1.11

**Comment by itzAnish** [comment]
NVM 1.1.9 had issue with installing latest(20.3.1) Node, resolved it by upgrading to NVM 1.1.11, Thanks to @xHergz 🍻

**Comment by godwinnnnn** [comment]
1. I fiugured it out that it is because the nodejs and npm mirror site  was configed in the nvm settings.txt, the solution is by  setting these configuration to null ,use github api to download nodejs and npm ,and then set nvm proxy to boost up the download speed. 

2. or like the guy's solution ,go to the mirror site to download the version you like ,then the decompile the file to here "./nvm", use "nvm list" to check if it's success. [https://zhuanlan.zhihu.com/p/507201533](https://zhuanlan.zhihu.com/p/507201533)
