### ISSUE TITLE
`nvm on` requires admin but `nvm off` does not

### ISSUE THREAD

**Issue by yilmazdurmaz** [coreybutler/nvm-windows#761]
**Issue:**

`nvm off` does not ask for any admin privilege to turn off itself, thus causing havoc if used by accident because `nvm on` requires admin rights.

**How To Reproduce:**

1. install nvm and set a distribution of node
2. enable it with `nvm on` on an elevated command prompt, see it enabled by `nvm list`
3. use `nvm off` on a user terminal and see it disabled by `nvm list`
4. try re-enabling it get and privilege error (error also shows **false positive** of `nvm enabled`):
````
nvm enabled
exit status 1: You do not have sufficient privilege to perform this operation.
````

**Expected Behavior:**

Either disabling should not work without admin privileges, or enabling should not.

**Comment by yilmazdurmaz** [comment]
any opinions?

**Comment by coreybutler** [comment]
Disabling attempts to [auto-elevate](https://github.com/coreybutler/nvm-windows/blob/master/src/nvm.go#L733). If your system is configured to use developer mode, it would be the equivalent of automatically accepting the prompts. The enabling behavior doesn't do this in an attempt to force the prompt.

That said, the behavior is different and it would probably be easier to understand if the behavior were consistent. I'll mark this as an enhancement request.

**Comment by yilmazdurmaz** [comment]
@coreybutler 
Recently, I have found out that there is more to this issue.

If I use "nvm on" from a non-admin terminal while nvm is also active, it deactivates nvm system-wide as it removes the folder link defined in the path to node, despite saying the user does not have "privilege" to do a system-effective operation; `exit status 1: You do not have sufficient privilege to perform this operation.`.

And that is not all. If, again as non-admin, I try to "nvm use x.xx.xx" the same happens: nvm gets disabled system-wide.

Anything a non-admin user does seem to immediately disable nvm system-wide as it deletes that link to the selected node version folder.

This one should actually be marked as an "urgent to fix" issue.
