### ISSUE TITLE
Is CrowdStrike Falcon reporting nvm-windows as grayware with a 60% confidence?

### ISSUE THREAD

**Issue by aledeniz** [coreybutler/nvm-windows#769]
**Issue:**
there is a Chocolatey package in the public repo for nvm-windows.
During the approval process for new versions (1.1.9) Chocolatey scans the package with a number of antivirus, a service provided by Virus Total, and then publishes the report, and the Virus Total report for nvm-windows 1.1.9 is reporting 1 detection.
The report specifically lists CrowdStrike Falcon as reporting "Win/grayware_confidence_60% (D)".
My own understanding of that statement is that CrowdStrike Falcon may be reporting this packages as grayware with a 60% confidence.

Here is the report:
https://www.virustotal.com/gui/file/4b16e9289a41527f17eca80c745688c6af6d10a882294bf94b2ed71c80fa42ef/detection

Here is the Chocolatey package approval conversation:
https://community.chocolatey.org/packages/nvm/1.1.9

**Expected Behavior:**
The Virus Total service should not detect any vulnerability related to this product.

**Comment by coreybutler** [comment]
I've never even heard of CrowdStrike Falcon until now, and there aren't any details of why it was marked this way. My understanding (based on quick research) is it is based on an ML algorithm, designed to detect adware. I have no idea why NVM4W would be marked this way.

Additionally, the reviewer in the chocolatey package stated the following:

```
nvm has been flagged as part of automated virus scanning.
Package virus scanning found that at least 1 file within, or downloaded by, the package has between 1 and 5 VirusTotal detections associated with it
This is not enough detections to prevent the approval of this package version.
```

The key part is `This is not enough detections to prevent the approval of this package version.`

Finally, this project doesn't maintain the chocolately package. Obviously we don't want it to be reported as a virus - and I don't think the maintainer is modifying the app, but without more specific detail, there is no clear action we can take.
