### ISSUE TITLE
Can't run nvm use 14.19.0

### ISSUE THREAD

**Issue by IT-Prince** [coreybutler/nvm-windows#771]
I already installed node 16.13.2
and I newly install node 14.19.0 using nvm install 14

but when I try to switch nvm use 14.19.0
it has error
exit status 5: Access is denied.
![image](https://user-images.githubusercontent.com/75807736/157400701-ec4a08b5-25c3-476a-889e-47a6459d41cf.png)
Do you have an idea?

**Comment by subhanjanOps** [comment]
have you tried it with administrator privileges?

**Comment by ojintoad** [comment]
Per @subhanjanOps 's suggetion, see here:

https://github.com/coreybutler/nvm-windows/issues/767

**Comment by ojintoad** [comment]
Also see https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145
