### ISSUE TITLE
Reference a old error

### ISSUE THREAD

**Issue by belsouza** [coreybutler/nvm-windows#772]
It's a known issue - as per the link below:

https://github.com/coreybutler/nvm-windows/issues/334#issuecomment-1066032479

During installation, the program says "version 8" of node is installed - but actually it is not; if I install any version of node, like 13.9.0 that still runs on windows 7, it is not recognized in the list. And now, when I install the downloaded version, it cannot be used, as an error is generated, as shown in the images below. The path is the default; no changes were made. Do I need to use an older version?
![Capturar](https://user-images.githubusercontent.com/61118820/158047356-9b4c9440-c86c-4243-a853-1d7310f91a60.PNG)
![Capturare](https://user-images.githubusercontent.com/61118820/158047361-5ea5cb18-3c8d-4dff-b953-c2d5275afc2e.PNG)

**Comment by coreybutler** [comment]
Does https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145 help?
