### ISSUE TITLE
03/14: Checking OS

### ISSUE THREAD

**Issue by belsouza** [coreybutler/nvm-windows#773]
The current version does not distinguish between different operating systems. As a Windows 7 user, validations for hardware check are missing:
node for windows 7 only works up to version 13.9.0 and the corresponding npm is version 6.13.7;
for windows 10, it is from 14.0.0
Currently if you use nvm install latest, it installs version 17.7.1 which does not work on Windows 7. There are still a lot of people who use this system.
I don't know where I could put the validation without harming the source code, so I leave it up to the developers.

**Comment by coreybutler** [comment]
NVM4W isn't _technically_ supported on operating systems Micrsoft doesn't support (Windows 7 support ceased on Jan 14, 2020).

Regardless, I understand this to be a feature request to validate the availability of Node for the current operating system. This will not be included in NVM4W, but I will leave this issue open and mark it for consideration in [rt](https://github.com/coreybutler/nvm-windows/discussions/565#discussioncomment-58112) (the successor project).

**Comment by JeffJacobson** [comment]
I recently encountered this issue, too. I learned that you can add a system environment variable `NODE_SKIP_PLATFORM_CHECK` and set its value to `1` to work around it. (Source: https://stackoverflow.com/a/68969030)

After doing this I was able to use nvm to install v17.9.0 of node (the latest version available at this time).
