### ISSUE TITLE
npx not installed with npm?

### ISSUE THREAD

**Issue by C-odes** [coreybutler/nvm-windows#774]
**Issue:**

After installing node latest version and node 7.9.0  I was about to install  another library onto the 7.9.0 version with npm. 
But as their documentation read "make sure you have node, npm and npx installed." That is kinda a given but when I checked to be 120% sure, I noticed npx is not installed at all. Weird. It should be installed with npm should it not?

**How To Reproduce:**

Install nvm. install version 7.9.0. And write npx --version.  

**Expected Behavior:** I expect npx to be installed

**Comment by coreybutler** [comment]
This is expected. npx was first introduced in npm **v5.2.0**. Node v7.9.0 ships with npm **v4.2.0**.

If you want to use npx with Node 7.9.0, you'll need to update npm to at least v5.2.0. Off the top of my head, I do not know if npm 5.2.0 is compatible with Node 7.9.0 (i.e. this may not be possible).
