### ISSUE TITLE
Install error - Exit code

### ISSUE THREAD

**Issue by dwilkes** [coreybutler/nvm-windows#776]
**Issue:**
GetExitCodeProcess Failed; Code 5.
Access is Denied

**How To Reproduce:**
Click "Finish" after install completes

**Expected Behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/17746652/159585777-707de502-9c98-4997-9514-51b04e3a9978.png)

**Desktop:**
 - OS: Windows 10

**Comment by foodornt** [comment]
Same, have you solved it?

**Comment by coreybutler** [comment]
If this occurs during installation, you need to install with admin privileges. If you get this while running the tool, see https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145.

Marking as a duplicate (of many).
