### ISSUE TITLE
Installing 1.1.9 actually installs 1.1.7

### ISSUE THREAD

**Issue by slacker-king** [coreybutler/nvm-windows#777]
**Issue:**

I downloaded the 1.1.9 setup ZIP and ran the EXE, but it only seems to install 1.1.7.

Even tried running 1.1.9 update and it doesn't install 1.1.9.

**Expected Behavior:**

I expect 1.1.9 to be installed.

**Comment by yumetodo** [comment]
1. uninstall nvm
2. erase `C:\ProgramData`
3. install again

I tried this and successed.

**Comment by coreybutler** [comment]
The download files contain 1.1.9, but your system may not be recognizing the change.

Uninstalling an old version prior to installing a new version will work.

You can also download the no-install zip file. Copy the elevate.cmd, elevate.vbs, install.cmd, and nvm.exe to the old directory.

**Comment by coreybutler** [comment]
There have been 100,000+ downloads since this issue was opened (with no other indicators that the wrong version is packaged). I do not think this is an issue with the download.

**Comment by PatFawbertMills** [comment]
I just fresh installed nvm, used the `1.1.9` installer and when I ran `nvm --version` it has installed `0.33.2`. Clearly I've done something wrong here?
