### ISSUE TITLE
Silent uninstall not working

### ISSUE THREAD

**Issue by russoedu** [coreybutler/nvm-windows#778]
The silent installation options for nvm-setup work fine, they’re really well detailed and thought out, and make it easy to deploy NVM via SCCM.

I’ve spent all morning trying to do a silent uninstall, and keep failing.

I have tried using nvm-setup /uninstall and unins0000.exe, each with various switches. It doesn’t matter what combination of switches I use, I always get this message:

 
![image](https://user-images.githubusercontent.com/472146/160122553-f65c1206-50b3-46c5-8ca2-6081fe4a46d6.png)

Once I click OK, assuming I’ve used /verysilent, I don’t see any other messages, and everything is uninstalled as I expect. Without the /verysilent switch, I see this message:

![image](https://user-images.githubusercontent.com/472146/160122604-e9f299da-214f-4f0c-b5d5-85b8e306768b.png)

The problem is that running the uninstaller through SCCM means using a service account, so this message will not be visible to the user who’s trying to do the uninstallation, meaning it’ll never get accepted, and thus never uninstalled.

Please could you provide the necessary switch(es) to not show this message, and/or make the unins000.exe /? command show a list of switches, rather than run the uninstaller?

**Comment by coreybutler** [comment]
I won't have time to rework the uninstaller anytime soon, but I'll mark this as an enhancement request.

**Comment by ogoess** [comment]
Hey Team!

I was able to silent uninstall NVM by using the following cmdlet:
"C:\Users\<user>\AppData\Roaming\nvm\unins000.exe"  /VERYSILENT /SP- /SUPPRESSMSGBOXES
