### ISSUE TITLE
Install version from `.nvmrc` error

### ISSUE THREAD

**Issue by thany** [coreybutler/nvm-windows#787]
**Issue:**

Installing a version from a pre-existing `.nvmrc` file returns an error:

```
> type .nvmrc
v12.6.0

> nvm use
Invalid version.
```

**How To Reproduce:**

1. Go to any project that has a `.nvmrc` file.
    1. Alternatively, create a new directory, and add a `.nvmrc` file to it
    2. Fill it with **exactly** this: `v12.6.0`
2. Run `nvm use`
3. See error

**Expected Behavior:**
It should take the content of a `.nvmrc` file, and plug it into `install`, then `use`. In other words, when `nvm use` is executed without further arguments, a version contained within `.nvmrc` should be installed and used.

To put it technically, the following PSEUDO CODE should describe accurately what `nvm use` should do:

```
nvm install < .nvmrc
nvm use < .nvmrc
```

I hope that makes it clear as day.

**Desktop:**
 - OS: Windows 10

**Additional context:**
I don't know of this has ever worked, but this is still a bug. I feel this is absolutely essential for nvm to function the way it was intended.

**Comment by coreybutler** [comment]
This has been addressed **many** times in prior issues and posts.

See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported

**Comment by thany** [comment]
Yes, well then time to get it fixed, innit? I don't care about excuses in the documentation. It's just a file contain a version number. Couldn't be simpler.
