### ISSUE TITLE
Version is not installed

### ISSUE THREAD

**Issue by thany** [coreybutler/nvm-windows#788]
**Issue:**

A version that is not installed, cannot be `use`'d.

```
> nvm use 12.6.0
node v12.6.0 (64-bit) is not installed.
```

**How To Reproduce:**
1. Run `nvm use x.x.x` where `x.x.x` is any version that has not been installed.
2. See error

**Expected Behavior:**
When I tell it to use version X, I expect it to go and do that. I don't give a toss whether it is already installed or not. If nvm needs it installed, install it then?.. Automatically, that is. Don't make me tell nvm how to do its job.

**Desktop:**
 - OS: Windows 10

**Additional context:**
I'd love to know what the advantage is of not installing a requested version automatically and just dumping an error instead. Seriously, to whom exactly is this better than installing a version automatically as soon as it is requested for `use`? Or rather, what is the *disadvantage* of automatically installing?

**Comment by coreybutler** [comment]
This has been addressed and is on the roadmap. Please review prior issues before posting.

**Comment by thany** [comment]
Duplicate issues indicate urgency. I tried nvm-window a few years ago, and it didn't work then.

This seems so bloody simple to implement, that I cannot believe it hasn't been already.

On top of that, you completely ignored my questions that might have led to some kind of understanding.

**Comment by coreybutler** [comment]
Again, you're welcome to fork the project and implement whatever you like.

A search of the issues, discussions, and wiki will highlight the challenges around this. For those who can't bother themselves to look at these prior issues, here's the main point: this feature is on the roadmap.

Repeatedly filing duplicate issues shows a lack of respect for prior discussion/work. Flat out [stating you don't care](https://github.com/coreybutler/nvm-windows/issues/787) about the maintainers decisions or the project roadmap doesn't exactly inspire anyone who _volunteers their time_ to take what you say seriously.

You've expressed (more than once) that you feel the features are easy to implement. The beautiful thing about open source is you can fork the project and implement whatever you like.
