### ISSUE TITLE
nvm use throws exec: "cmd": executable file not found in %PATH%

### ISSUE THREAD

**Issue by srizzon** [coreybutler/nvm-windows#794]
**Issue:**
When I run "nvm use 16.13.1" I got this error:
`exec: "cmd": executable file not found in %PATH%`

![image](https://user-images.githubusercontent.com/10997903/165532146-267b9c81-28f1-45ad-8b4a-d6a79770739a.png)

**How To Reproduce:**
- Remove nodejs completly
- Restart computer
- Remove all folders from nodejs
- Install nvm with last version 1.1.9
- Open cmd as administrator
- run nvm install 16.13.1 (this works as expected)
- run nvm use 16.13.1 (and the error occurs)

**Expected Behavior:**
I expected can use the version that I already installed

**Desktop:**
- Windows 10

My environment variable:
![image](https://user-images.githubusercontent.com/10997903/165532650-4aaf0cbc-8c79-494d-9225-ad21f8ed8576.png)

My Path on enviroment variable:
![image](https://user-images.githubusercontent.com/10997903/165533129-b16fd9e7-a4cf-4c51-805c-76b207c6ffc6.png)

Another commands with result:

```
C:\Windows\system32>nvm list

    16.13.1

C:\Windows\system32>nvm on
nvm enabled
exec: "cmd": executable file not found in %PATH%:

C:\Windows\system32>nvm install 10.15.3
Downloading node.js version 10.15.3 (64-bit)...
Complete
Creating C:\Users\shrizzon\AppData\Roaming\nvm\temp

Downloading npm version 6.4.1... Complete
Installing npm v6.4.1...

Installation complete. If you want to use this version, type

nvm use 10.15.3
```

**Comment by coreybutler** [comment]
It sounds like `cmd.exe` is not recognized on Windows. Can you run `cmd` from your terminal or powershell?

For example:
<img width="342" alt="image" src="https://user-images.githubusercontent.com/770982/165581062-a99a8171-075c-450c-aa6e-1f4b38c13b0b.png">

**Comment by coreybutler** [comment]
I'd recommend replacing `%NVM_HOME%` and `%NVM_SYMLINK%` with their real values in your `PATH` environment variable. Windows normally auto-expands these (i.e. you shouldn't have to do this), but it would be worth trying.

**Comment by sharabiania** [comment]
I have the same issue

**Comment by sharabiania** [comment]
> I'd recommend replacing `%NVM_HOME%` and `%NVM_SYMLINK%` with their real values in your `PATH` environment variable. Windows normally auto-expands these (i.e. you shouldn't have to do this), but it would be worth trying.

What is the path for NVM_SYMLINK?

**Comment by tretyakvl** [comment]
As a workaround you can just run these commands in Command Prompt instead of PowerShell

**Comment by ekene9999** [comment]
run it as an admnistrator in command prompt

**Comment by chengqing97** [comment]
Adding `C:\windows\system32` to `PATH` environment variables solves my problem.
