### ISSUE TITLE
nvm cannot "use" other installed node versions. 

### ISSUE THREAD

**Issue by rhtaylor-effect** [coreybutler/nvm-windows#798]
nvm-windows command nvm use "node-v" does not work. 

**1**. nvm install 16.3.0
Downloading node.js version 16.3.0 (64-bit)...
Complete
Creating C:\Users\RandallTaylor\AppData\Roaming\nvm\temp

Downloading npm version 7.15.1... Complete
Installing npm v7.15.1...
**2**. nvm use 16.3.0
exit status 145: The directory is not empty.

exit status 145: The directory is not empty.

**Expected Behavior:**
nvm use 16.3.0 should result in using 16.3.0

windows 10 
commands are executed in Administrator PowerShell or command prompt

**Comment by coreybutler** [comment]
https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#exit-145-or-the-process-cannot-access-the-file-because-it-is-being-used-by-another-process

**Comment by Saibamen** [comment]
```
C:\Users\Adam>nvm version
1.1.9

C:\Users\Adam>nvm list

    16.15.0
    8.17.0

C:\Users\Adam>nvm use 8.17.0
exit status 1: Access denied.
```

I uninstalled NVM and NodeJS and deleted npm-cache folders.

**Comment by angelhdzmultimedia** [comment]
> ```
> C:\Users\Adam>nvm version
> 1.1.9
> 
> C:\Users\Adam>nvm list
> 
>     16.15.0
>     8.17.0
> 
> C:\Users\Adam>nvm use 8.17.0
> exit status 1: Access denied.
> ```
> 
> I uninstalled NVM and NodeJS and deleted npm-cache folders and I have this same issue.

I install nvm in C:\ to avoid permissions or "Access denied" issues.

**Comment by Saibamen** [comment]
I used default path from installer (also C, but in program files)

**Comment by angelhdzmultimedia** [comment]
> 14.19.3

I'm getting this error: 

![image](https://user-images.githubusercontent.com/10191085/169001009-e8ad2066-3a05-469f-9104-02383e12c2f5.png)

It's weird. I have a have one 14.*.* version installed, one 17.*.*, and the new 18.1.0. Didn't get this error with them.

Let me try the 14.19.2 one...

**Comment by coreybutler** [comment]
@Saibamen & @angelhdzmultimedia - see the link I posted above about permissions issues.

@marcoXbresciani and @Saibamen - there appears to be a problem with the download for npm 6.14.17. See https://github.com/coreybutler/nvm-windows/issues/766#issuecomment-1124923726.

I'm closing this issue because I believe the wiki provides a solution for the problems. @rhtaylor-effect - if these resources don't help resolve your issue, please reopen or post an update (particularly about which directory you're running nvm commands from).

**Comment by angelhdzmultimedia** [comment]
> @Saibamen & @angelhdzmultimedia - see the link I posted above about permissions issues.
> 
> @marcoXbresciani and @Saibamen - there appears to be a problem with the download for npm 6.14.17. See [#766 (comment)](https://github.com/coreybutler/nvm-windows/issues/766#issuecomment-1124923726).
> 
> I'm closing this issue because I believe the wiki provides a solution for the problems. @rhtaylor-effect - if these resources don't help resolve your issue, please reopen or post an update (particularly about which directory you're running nvm commands from).

Thank you. I forgot to mention I am not experiencing this issues myself (I always use latest versions of Node, currently 18.1.0). I was just preparing a video tutorial on YouTube on how to install `nvm-windows`, so I ended here in the issues sections and wanted to give support to this issue, by checking and confirming if I was getting the same errors as well, to find out if it was a per-case issue or a general issue.

Wishing you all health and success. Thanks for the good work.
