### ISSUE TITLE
Error installing NodeJS 14.19.2 with npm version 6.14.17

### ISSUE THREAD

**Issue by robi-wan** [coreybutler/nvm-windows#799]
**Issue:**
I do not know if this is an issue with nvm for Windows or NodeJS:
I cannot get NodeJS 14.19.2 (more specifically: npm v6.14.17) to install with nvm v1.1.9:

**How To Reproduce:**
```
C:\Users\user>nvm install 14.19.2
Downloading node.js version 14.19.2 (64-bit)...
Complete
Downloading npm version 6.14.17... Download failed. Rolling Back.
Rollback failed. remove C:\development\tools\nvm\temp\npm-v6.14.17.zip: The process cannot access the file because it is being used by another process.
Could not download npm for node v14.19.2.
Please visit https://github.com/npm/cli/releases/tag/v6.14.17 to download npm.
It should be extracted to C:\development\tools\nvm\v14.19.2

C:\Users\user>nvm version
1.1.9
```

NodeJs is downloaded to `c:\development\tools\nvm\v14.19.2\node64.exe`.

A file `c:\development\tools\nvm\temp\npm-v6.14.17.zip` is also created but it is not a ZIP archive - it is a text file with this content:
```
the given path has multiple possibilities: #<Git::Ref:0x00007fe7bd76da98>, #<Git::Ref:0x00007fe7bd6df518>
```

(If it matters: I am using this git version locally:
```
C:\Users\user>git version --build
git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
)

**Expected Behavior:**
NodeJS 14.19.2 - and it's bundled npm - should install without an error.

I tried with:
**Desktop:**
 - Windows 11 Enterprise 21H2 (OS build 22000.613) and Microsoft Terminal (with Admin privileges) with PowerShell and cmd
 - Windows 10 Home 21H2 (OS build 19043.1645) in PowerShell (with Admin privileges)

**Comment by eugenedrvnk** [comment]
Same

**Comment by ahmadbakhshi** [comment]
same

**Comment by diegomachado** [comment]
Got the same error and this worked for me as a temporary solution:
https://github.com/coreybutler/nvm-windows/issues/373#issuecomment-529991743

**Comment by coreybutler** [comment]
This appears to be an upstream issue specifically with npm 6.14.17. The remote server is providing a corrupt/incomplete file (as opposed to not providing a file at all), which is not something NVM4W has any control over. All other versions of npm are working properly.

I'm closing this because I don't think there is anything NVM4W can do to resolve this issue.

**Comment by jbalpert** [comment]
Also facing this problem

**Comment by carlirows** [comment]
I have the same issue :(

**Comment by gugulothsureshnaik** [comment]
Solutions : nvm use 14.19.0 its got installed successfully

**Comment by piyushgoswami015** [comment]
roll back to nvm 1.1.17

**Comment by piyushgoswami015** [comment]
roll back to nvm 1.1.7

**Comment by s100** [comment]
> This appears to be an upstream issue specifically with npm 6.14.17. The remote server is providing a corrupt/incomplete file (as opposed to not providing a file at all), which is not something NVM4W has any control over. All other versions of npm are working properly.
> 
> I'm closing this because I don't think there is anything NVM4W can do to resolve this issue.

Any chance of providing a link to the upstream issue?

**Comment by robi-wan** [comment]
@s100 This is the upstream issue: https://github.com/npm/cli/issues/4890

**Comment by MyDinnerIsReady** [comment]
Hi guys, I met the same issue now, but I got a solving way.
if you installed a newer node and want to install an older one with nvm, you maybe got a problem with installing npm like me. 
And you could try to uninstall those nodes, **install the older one first, then install a newer one**.
It works for me.
I think it's due to the older npm install package being out of date, but maybe the new one still works.
Hope it will help you.
Hello world~

**Comment by Yenganollarajesh** [comment]
error installing 14.21.3: open C:\Users\venu\AppData\Local\Temp\nvm-npm-730612686\npm-v6.14.18.zip: The system cannot find the file specified.

**Comment by puzan43382** [comment]
was working fine. after I downloaded new nvm I ran into this issue.

**Comment by Yenganollarajesh** [comment]
no i have tried but it not working can you please explain how to install

**Comment by ronaldjeremy** [comment]
Also having this issue. "nvm install 0.10.48" installs node fine, but then i get:

Downloading npm version 2.15.1... Complete
Installing npm v2.15.1...
error installing 0.10.48: open C:\Users\me\AppData\Local\Temp\nvm-npm-306168934\npm-v2.15.1.zip: The system cannot find the file specified.

**Comment by cosmokramer04** [comment]
I think this error occurs when using NVM4win with a version higher than 1.2.0. See [https://github.com/coreybutler/nvm-windows/wiki/Common-Issues] under "Can't Download Old Node.js Versions". I've downgraded to version 1.1.12 and nvm install 14.21.0 worked fine.

**Comment by Alex-byte256** [comment]
i just downloaded the older version of nvm 1.1.12 and that helped

https://github.com/coreybutler/nvm-windows/releases/tag/1.1.12

**Comment by StiveHere** [comment]
> i just downloaded the older version of nvm 1.1.12 and that helped
> 
> https://github.com/coreybutler/nvm-windows/releases/tag/1.1.12

Hello, I also had to use this tactic!

**Comment by wlll5** [comment]
> i just downloaded the older version of nvm 1.1.12 and that helped
> 
> https://github.com/coreybutler/nvm-windows/releases/tag/1.1.12

that do helped

**Comment by VaTzZz1** [comment]
it seems to be happening only on windows. I installed a AUR package for nvm and instaling old versions work properly.

**Comment by Jihedoueslatiii** [comment]
> roll back to nvm 1.1.7

it worked correctly , thank you
