### ISSUE TITLE
Missing releases newer than v1.1.1

### ISSUE THREAD

**Issue by gama410** [coreybutler/nvm-windows#800]
**Issue:**
I can't find any releases newer than 1.1.1 although I had previously installed v1.1.9

**How To Reproduce:**
Just check the following URL https://github.com/coreybutler/nvm-windows/releases
where the newest release is largely outdated

**Expected Behavior:**
I would like to be able to download recent releases
![image](https://user-images.githubusercontent.com/1763404/167659509-315b60db-587f-4a24-9ecc-b5ff771b963f.png)

**Comment by WhiteWolf82** [comment]
same problem here.

**Comment by aDudman** [comment]
More recent versions are visible if you click on "Tags", it seems something went wrong with the signing process. I'm not an expert, but my guess is it's related to the April 27 update.

Using the "Tags" tab I was able to find [the current version](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.9), and the updater still worked fine.

**Comment by coreybutler** [comment]
No idea why this happened... newer version were definitely released (that's how the download stats are calculated). I've re-published 1.1.7-1.1.9. I don't recommend using a version below 1.1.7, but they are available in the tags for historical purposes.

**Comment by gama410** [comment]
Perfect, thanks for the quick response! (and the great tool :) )
