### ISSUE TITLE
Developer Mode needs enabled

### ISSUE THREAD

**Issue by tomgcavanaugh** [coreybutler/nvm-windows#803]
**Issue:**

The documentation does not mention that "Developer Mode" needs to be enabled in order to use this product.  I am not sure when this feature was added to Windows, but without enabling this feature it is not possible to install npm.

**How To Reproduce:**

On a machine without Developer Mode enabled, attempt to install new versions of tools,  you will receive error indicating "The process cannot access the file because it is being used by another process".

See https://github.com/coreybutler/nvm-windows/issues/580

**Expected Behavior:**

**Comment by coreybutler** [comment]
Developer Mode is not strictly required. The app requires permissions to create symlinks and to write to directories. Historically, Windows required an account with administrative privileges to create symlinks. They introduced Developer Mode to increase permissions for developers. One of those permissions is the ability to create symlinks without having an administrative account.

Bottom line, you only need to enable Developer Mode if you **aren't** running with administrative privileges. By default, Windows users have administrative privileges. _Organizations_ may block this through group policies, but they can also enable Developer Mode the same way.

**Comment by pedroyan** [comment]
Hi @coreybutler,

Running NVM on a privileged CMD did not solve the problem for me

![image](https://user-images.githubusercontent.com/11574849/168310667-a969f35e-4ecf-4b9e-8c07-32e4ad815211.png)

**Comment by coreybutler** [comment]
@pedroyan - that's a different issue. See https://github.com/coreybutler/nvm-windows/issues/766#issuecomment-1124923726.
