### ISSUE TITLE
Can not install npm

### ISSUE THREAD

**Issue by yunnysunny** [coreybutler/nvm-windows#807]
**Issue:**
Can not install npm. After I run install command, it will show that the npm.zip is locked by another process. The I delete the  zip file and the folder of broken node version and retry, it will result with same error.

**How To Reproduce:**
```
PS C:\Users\lenovo> nvm install 14.19.2
Downloading node.js version 14.19.2 (64-bit)...
Complete
Downloading npm version 6.14.17... Download failed. Rolling Back.
Rollback failed. remove C:\Users\lenovo\AppData\Roaming\nvm\temp\npm-v6.14.17.zip: The process cannot access the file because it is being used by another process.
```

**Env:**
 - OS: win10 21h2
 - nvm 1.1.9
 - Setting.txt
```
root: C:\Users\lenovo\AppData\Roaming\nvm
arch: 64
proxy: none
originalpath: .
originalversion: 
node_mirror: https://npmmirror.com/mirrors/node/
npm_mirror: https://npmmirror.com/mirrors/npm/
```

**Comment by yunnysunny** [comment]
The npm mirror miss the npm version of 6.14.17.

**Comment by kewur** [comment]
> nvm install 14                                                                                                                                                                                                    
Version 14.19.3 is already installed.

> nvm use 14                                                                                                                                                                                                        
node vv14.19.3 (64-bit) is not installed or cannot be found.
