### ISSUE TITLE
npm download failure - Proxy Authentication Required

### ISSUE THREAD

**Issue by pnewhook** [coreybutler/nvm-windows#810]
**Issue:**

During `nvm install 16.15.0` downloading npm fails with the following error

```

Downloading npm version 8.5.5... Error while downloading https://github.com/npm/cli/archive/v8.5.5.zip - Get "https://github.com/npm/cli/archive/v8.5.5.zip": Proxy Authentication Required

```

I'm in a corporate environment, with a proxy set in my settings.txt. node.js download works, this problem appears specific to the npm download.

 

I'm using nvm-windows 1.1.9

 

**How To Reproduce:**

1. Install by following noinstall-nvm instructions

2. Set proxy to http://webproxy.mycompany.com:8080/

3. Run `nvm install 16.15.0`

 

**Output:**

```

C:\Users\pn65925>nvm-noinstall\nvm.exe install 16.15.0

Downloading node.js version 16.15.0 (64-bit)...

Extracting...

Complete

Downloading npm version 8.5.5... Error while downloading https://github.com/npm/cli/archive/v8.5.5.zip - Get "https://github.com/npm/cli/archive/v8.5.5.zip": Proxy Authentication Required

panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x20 pc=0xb19b27]

 

goroutine 1 [running]:

nvm/web.Download({0x138b2180, 0x2d}, {0x1380a240, 0x15}, {0x138a7cc0, 0x5})

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:81 +0x297

nvm/web.GetNpm({0x138a6b06, 0x1}, {0x138a7cc0, 0x5})

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:209 +0x379

main.install({0x138a6080, 0x7}, {0xb7fa65, 0x2})

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:356 +0xa8a

main.main()

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69

```

**Comment by coreybutler** [comment]
The log states `Proxy Authentication Required`. It seems like the proxy is blocking the download. Your proxy may allow nodejs.org but block github.com (or requires special permission for github). There's nothing NVM4W can really do if the proxy won't complete the request.

**Comment by pnewhook** [comment]
I was thinking the same thing, and github.com is blocked by default within the company network, but when I set the npm_mirror I still got the same error. I guess it's possible github.com and npmmirror.com are blocked, but nodejs.org isn't.

We're exploring mirroring the node and npm distributions internally using Artifactory, hopefully that'll work. I'm eager to see if rt can resolve some of these self-inflicted enterprise wounds.

```
C:\Users\pn65925>nvm-noinstall\nvm.exe install 16.15.0

Downloading node.js version 16.15.0 (64-bit)...

Extracting...

Complete

Downloading npm version 8.5.5... Error while downloading https://npmmirror.com/mirrors/npm/v8.5.5.zip - Get https://npmmirror.com/mirrors/npm/v8.5.5.zip: Proxy Authentication Required

panic: runtime error: invalid memory address or nil pointer dereference

[signal 0xc0000005 code=0x0 addr=0x20 pc=0x1009b27]

 

goroutine 1 [running]:

nvm/web.Download({0x1340c9c0, 0x2c}, {0x13582048, 0x15}, {0x13697c30, 0x5})

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:81 +0x297

nvm/web.GetNpm({0x1340ebb6, 0x1}, {0x13697c30, 0x5})

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/web/web.go:209 +0x379

main.install({0x1340e130, 0x7}, {0x106fa65, 0x2})

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:356 +0xa8a

main.main()

        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69
```

**Comment by coreybutler** [comment]
@pnewhook - We're currently designing the (high level) rt enterprise features. A mirroring/caching server is amongst them so enterprises can use pre-vetted versions of Node/npm (and maybe yarn... TBD). I'm setting up a mailing list for those who want to be notified as we make progress on this. I'd be happy to add a rep from your company if you'd like.

**Comment by pnewhook** [comment]
Please add peter.newhook@citi.com

**Comment by SamKamalesan** [comment]
any development or fix for this yet ?
