### ISSUE TITLE
win11环境下下载了node但是切换过去之后不生效

### ISSUE THREAD

**Issue by pie-dog** [coreybutler/nvm-windows#813]
![1a4b8163dfc6cf4a13835c951b03ca6](https://user-images.githubusercontent.com/96970011/171341023-6a06f36e-c654-4b20-a984-8087d17b821f.png)
我在下载nvm之前把node删除了, 之后下载了nvm并通过nvm下载了node指定版本. 但是node不生效

**Comment by pie-dog** [comment]
已解决, 是因为dayjs文件夹的关系. 没有关联上

**Comment by CodeInn1024** [comment]
出现同样的问题，大佬怎么解决的啊

**Comment by pie-dog** [comment]
> 出现同样的问题，大佬怎么解决的啊

![image](https://user-images.githubusercontent.com/96970011/175191970-780ae0c8-c9b3-4e52-8b0e-344ec2103be1.png)
你看一下你的nodejs文件夹有没有这个标识. 有没有关联上, 再看看环境变量配置好没有

**Comment by DaZiYuan** [comment]
删除这个目录`C:\Program Files\nodejs`，重新执行命令可行
