### ISSUE TITLE
NVM use <version major> doesn't work

### ISSUE THREAD

**Issue by timtong1982** [coreybutler/nvm-windows#815]
**Issue:**

seems like a duplicate 'v' was attached to the v<version>
<img width="508" alt="image" src="https://user-images.githubusercontent.com/25381018/172231956-e4289418-1cbd-4441-b758-8c4914886c63.png">

**How To Reproduce:**

**Expected Behavior:**

**Comment by stalker8610** [comment]
Hi! I have the same problem. Try to write whole version, like 'nvm use 16.15.1' or 'nvm use 16.15.1 32' and enjoy )

**Comment by coreybutler** [comment]
Duplicate #708.
