### ISSUE TITLE
No Elevation attempted at 'use x.x.x' on latest (1.1.9)

### ISSUE THREAD

**Issue by shtanma** [coreybutler/nvm-windows#820]
Hi,
have read a similar #767 , but I'm experiencing slightly different problem on 1.1.9:
 - the same "no elevation prompt is attempted" by NVM.exe, but it fails with other error "exit status 1: You do not have sufficient privilege to perform this operation."

Setup:
 - no "Developer" features on Windows 21H2 (19044.1706)
 - UAC - always notify
 - WINSTA/interactive logged-on user context - has working (green outlines on screenshot) Admin rights granted SID:S-1-5-32-544(BUILTIN\Administrators) machine wide
 - intention is to use normal/non-elevated cmd.exe context (yellow outlines on screenshot) SID:S-1-16-8192 (Mandatory Label\Medium Mandatory Level)
 - NVM 1.1.9 manual nvm-noinstall.zip (https://github.com/coreybutler/nvm-windows/releases/latest (https://github.com/coreybutler/nvm-windows/releases/download/1.1.9/nvm-noinstall.zip))
 - set NVM_HOME=Drive:\no-spaces-path (subfolder in logged-on %USERPROFILE%)
 - set NVM_SYMLINK=%NVM_HOME%\non-existing-sub-folder  ... or  ... set NVM_SYMLINK=%USERPROFILE%\non-existing-sub-folder
 - settings.txt ( ... path: %NVM_SYMLINK% ...)

Expected on ' use x.x.x' :
- to have elevation prompt attempts happen (... confirm in UAC, and continue working...)

Screenshot:
![image](https://user-images.githubusercontent.com/36885262/173899610-f62a7295-de7b-4e99-af93-84e8c901c012.png)

**Comment by shtanma** [comment]
Hi guys,
I think the exactly same thing have been experienced here:
 - https://github.com/coreybutler/nvm-windows/issues/671#issuecomment-1066880349

**Comment by shtanma** [comment]
... regardless if it'll ever make sense (e.g. considered for new ver)  in "nvm-windows", I would like to upvote the following comments (by @ViliusS), maybe even to be considered in "rt":
 - https://github.com/coreybutler/nvm-windows/issues/671#issuecomment-1067901527
 - https://github.com/coreybutler/nvm-windows/issues/671#issuecomment-1150992842

**Comment by rfrances-werfen** [comment]
Don't stale, this is still going.

**Comment by cCarlosCervantes** [comment]
I need a solution for this, I?m also uanble to nvm use anything

**Comment by coreybutler** [comment]
UAC prompts were removed by user request in v1.1.8. Community feedback since then has shown a strong demand for it (i.e. nobody spoke up until it was too late), but I do not have time to revert the changes without also removing several new features. Runtime (rt), the successor project, will have the option to use or suppress UAC prompts. Until that is released, I recommend using NVM 1.1.7 if UAC prompts are truly necessary in your environment.

**Comment by WORMSS** [comment]
Just to confirm, you are saying once you have wrote RT you will come back and fix NVM?

**Comment by coreybutler** [comment]
@WORMSS tldr; if time allows, perhaps... but that's not the intention. Time is thin and the intention is to deprecate NVM4W, replacing it with Runtime. 

_Detail:_
I won't deprecate NVM4W until there is a defined transition path to Runtime. I will strongly encourage transitioning when the time comes. Unlike NVM4W, Runtime will have a few commercial options (in addition to a free version). Backing will facilitate timely updates, new features, and better educational resources. Naturally, that will promote timely development cycles too. NVM4W won't be brought under this umbrella though. Runtime is supposed to be the "fresh start based on a decade of lessons learned".

**Comment by WORMSS** [comment]
Not stale, still a problem.

**Comment by jackalvrus** [comment]
> UAC prompts were removed by user request in v1.1.8. Community feedback since then has shown a strong demand for it (i.e. nobody spoke up until it was too late), but I do not have time to revert the changes without also removing several new features. Runtime (rt), the successor project, will have the option to use or suppress UAC prompts. Until that is released, I recommend using NVM 1.1.7 if UAC prompts are truly necessary in your environment.

Funny how user feedback works, isn't it? People don't usually show up until they have a problem to solve. In my case I almost always run NVM from a VSCode terminal so not having the UAC is a bit of a hassle. However, I'm happy to keep using 1.1.7 as it is working fine for me, and I'm looking forward to trying Runtime (rt) when it's available. Thanks for the good work.

**Comment by WORMSS** [comment]
Just to note @jackalvrus I do have a working 1.1.9 by a small workaround. 

admin cmd , point `c:\program files\nodejs` to `%userprofile%\nodejs`
then set the `NVM_HOME` variable to `%userprofile%\nodejs` because it's a system directory.

Then `nvm` can point `%userprofile%\nodejs` to any directory it likes without needing UAC... Since YOU own the directory.

**Comment by coreybutler** [comment]
Elevation was brought back in 1.1.10. I'm closing, but will re-open if anyone has these problems in 1.1.10+.
