### ISSUE TITLE
npm deprecated --global

### ISSUE THREAD

**Issue by tchari** [coreybutler/nvm-windows#824]
**Issue:**
This may not be the correct repository for this issue, however, after installing the latest nodejs LTS (16.15.1) I'm getting this warning:
```config global `--global`, `--local` are deprecated. Use `--location=global` instead```
when using _npm_.

Somewhere the `npm` and `npm.cmd` files that are created include stuff like:
```NPM_PREFIX=`"$NODE_EXE" "$NPM_CLI_JS" prefix -g```

I don't know how these files are created or who is responsible so this repo may not the right place.

**How To Reproduce:**
1. Install NVM
2. `nvm install 16.15.1`
3. `npm --version` (8.11.0)

**Expected Behavior:**
For no deprecation warnings to appear.

**Desktop:**
 - OS: Windows 11, PowerShell terminal

**Comment by ohiobobcat** [comment]
This is an npm issue not an nvm issue. You didn't show your version of NPM but i'd bet you're using `v8.11`.

Here's the link to the fix implemented in `v8.12`

**Comment by tchari** [comment]
Yes you are correct, it's 8.11.0. I figured it probably wasn't an nvm issue. Is this just the npm version that node 18.15.1 bundles?
