### ISSUE TITLE
[July 2022]: [Fix admin requirements]

### ISSUE THREAD

**Issue by BurtHarris** [coreybutler/nvm-windows#826]
**Is your feature request related to a problem? Please describe.**

NVM has required admin rights for too long.   

**Describe the solution you'd like**

A simple change in the installer can solve it now, because Windows fixed the admin required for symlinks thing several years back.  All that needs to happen is to have the default values for ENV variables NVM_SYMLINK be in the user profile, where special permissions are not needed to modify it in NVM use.

For example, the following values work fine for me, without requiring any sort of elevation: 

    NVM_HOME                       C:\Users\burt_\AppData\Local\nvm
    NVM_SYMLINK                   C:\Users\burt_\AppData\Local\nodejs

I'd submit a PR but I don't understand the Install scripting language features.

**Describe alternatives you've considered**

Other approaches have been made unnecessary because of the change in Windows regarding SymLink policy.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
Non-admin Windows users still do not have symlink permissions by default. To use symlinks as a non-admin, users have to enable developer mode or be explicitly granted symlink permissions. NVM4W 1.1.9 already supports this. In fact, if you read through the issues, you'll find a lot of users who have requested NVM4W return to the original approach of using the UAT prompt to enforce elevated admin privileges.

Users still need temporary admin privileges to enable developer mode, or it must be assigned by a group policy.

Keep in mind, admin privileges are also used to write to protected directories, such as `C:\Program Files`.

I do not intend to change this in NVM4W. Instead, it will be addressed in the successor project (Runtime/rt), which is in development right now. I've spent considerable time on this and the change is too big to fit into NVM4W.
