### ISSUE TITLE
exit status 5: Access denied

### ISSUE THREAD

**Issue by sa-ndeep** [coreybutler/nvm-windows#843]
i am getting error like this when i am executing nvm use 11.0.0
![image](https://user-images.githubusercontent.com/65162931/183990788-03a81c27-857c-44dc-afb4-19185b3e2d84.png)

**Comment by sa-ndeep** [comment]
i am getting error like this when i am executing nvm use 11.0.0
![image](https://user-images.githubusercontent.com/65162931/183991018-31e747db-d2a0-4e4d-a1ea-0336b2dc41e0.png)

**Comment by Ahmedelforjani** [comment]
@sa-ndeep you need to open cmd as administrator, this will fix the issue

**Comment by ziyi-joiede** [comment]
It doesn`t work

**Comment by coreybutler** [comment]
This is a permissions error coming from Windows. Please see https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145
