### ISSUE TITLE
nvm use - exit status 1:

### ISSUE THREAD

**Issue by jaroslawjanas** [coreybutler/nvm-windows#847]
**Issue:**
`nvm use [any version]` produces an "exist status 1:" message.
No clear description of the error but based on other issues it seems to be permissions based.
Could not resolve after trying multiple common solutions

**How To Reproduce:**
nvm version: `1.1.9`
Running in admin mode: `Yes`
Dev mode enabled: `Yes`
OS: `Windows 10 - Build 19044`

```
nvm install latest
nvm use [latest version]
```

**Expected Behavior:**
It should work.

**Screenshot**
![image](https://user-images.githubusercontent.com/28691446/186769365-71973197-b379-4917-88b2-9ef1429983e5.png)

**Comment by NoeReverse** [comment]
@jaroslawjanas You should try to open the command prompt with administrative privileges.

**Comment by jaroslawjanas** [comment]
I figured it out.
The issue was the **cmd** itself. As I use *PowerShell**, specifically the **Terminal** I rarely have the need to open the **cmd** itself.
Turns out my **cmd** was broken, and it would close immediately after opening. My guess is that the same was happening to whatever processes/commands **nvm** was trying to run behind the `nvm use *` command.

I managed to fix the issue by going to `HKEY_CURRENT_USER\Software\Microsoft\Command Processor` in the `regedit` and removing the `AutoRun` entry, as recommended by the internet. This fixed my `cmd` issue, and **nvm** seems to be working perfectly fine now.
