### ISSUE TITLE
Can't install nodejs v4

### ISSUE THREAD

**Issue by eperedo** [coreybutler/nvm-windows#85]
I got this error when I try to install the version 4.0.
![node_nvm_4](https://cloud.githubusercontent.com/assets/461124/9752143/9531aa7a-5672-11e5-8832-c7b49041d54c.png)

I have this problem on **windows 8 and 10**. Any suggestions? Thanks!

**Comment by umayr** [comment]
+1 same error on windows 7 too.

![nvm](https://cloud.githubusercontent.com/assets/3071948/9754096/eb8c672c-56de-11e5-8d52-25eab7c43a2f.PNG)

**Comment by alexbooker** [comment]
Yep, me too (on Windows 10 64bit).

**Comment by Bruce17** [comment]
+1 Same here on Windows 10 x64. Tried to install it as 23-bit, but still does not work.

![zwischenablage02](https://cloud.githubusercontent.com/assets/5036995/9757108/be494596-56de-11e5-8fd1-2a2e25f48193.jpg)

**Comment by alexbooker** [comment]
@Bruce17 *23 bit?!* 

But nah, I tried to install the 32bit version, too, and I encountered problems.

**Comment by vmeurisse** [comment]
The path of the distributed file changed
https://github.com/coreybutler/nvm-windows/blob/master/src/nvm/web/web.go#L64
They are now located in https://nodejs.org/dist/v4.0.0/win-x64/ and https://nodejs.org/dist/v4.0.0/win-x86/

**Comment by Bruce17** [comment]
@alexbooker sry typo, I mean **32-bit**

**Comment by coreybutler** [comment]
Yes, the path changed. I have to update several things and I won't be able to get back to my Windows machine to create the executable until the weekend..

**Comment by alexbooker** [comment]
@coreybutler Fair enough. I appreciate your efforts!

**Comment by GrouchyPanda** [comment]
@coreybutler Is there anything we can do in the mean time to begin working with 4.0.0 now? such as installing from the msi into the Roaming dir for nvm? I need to incorporate jsdom into my current application and it requires 4+ so the sooner I can get this version the better. Thank you

**Comment by coreybutler** [comment]
You can look through the code and follow the install/symlink process by hand.... it's not terribly complicated. Or copy an existing install, rename it, add the node binaries, then `nvm use 4.0.0`.

**Comment by thisismygithub** [comment]
I can download node 4.0.0
![_091015_013933_pm](https://cloud.githubusercontent.com/assets/4269720/9780936/5d0da3e2-57c1-11e5-91e1-dffa1f952c9f.jpg)

**Comment by umayr** [comment]
@thisismygithub Exactly. What you can do is to download `4.0.0` executable file from [here](https://nodejs.org/dist/v4.0.0/win-x64/node.exe) and then manually copy that binary to the `<user>\AppData\Roaming\nvm\v4.0.0` folder. After copying just select the version by `nvm use 4.0.0` then you'd be good to go.

**Comment by Bruce17** [comment]
@umayr Thx for the hint.
@coreybutler Thx for your efforts!

**Comment by thisismygithub** [comment]
@umayr It worked , but if I install other version ... I need do this again (use other version binary ) . Orz

**Comment by alexbooker** [comment]
@umayr That there's a nice work around - thanks!

**Comment by Bruce17** [comment]
@umayr It's working pretty well. The performance gain with node v4 is great :-)

**Comment by umayr** [comment]
@thisismygithub, Indeed. The paths to download node binaries have been changed after the merge as @vmeurisse mentioned. So, I don't think we'd be able to download any version via nvm unless its been patched.

**Comment by kobezzza** [comment]
+1

**Comment by pierr** [comment]
:+1:

**Comment by SandHilt** [comment]
+1 waiting patch for this.

**Comment by BoringDays** [comment]
@umayr could you tell me how to switch to a older version? I ran `nvm use 0.10.36 32`,but it STILL stays on 4.0.0

![image](https://cloud.githubusercontent.com/assets/4611387/9866232/a0b4dbae-5b92-11e5-870a-e4c2038f5f24.png)

How to fix it?

**Comment by mitchelldavis** [comment]
:+1:

**Comment by rainabba** [comment]
@umayr I created the `v4.0.0` folder, downloaded the linked node.exe, "unblocked" it, did `nvm use 4.0.0` and all looked good until I did `node -v` and saw v0.12.7 still. More to be done?

**Comment by eperedo** [comment]
@rainabba I did the same thing, it works for me but now npm is gone :speak_no_evil: 
![npm_error](https://cloud.githubusercontent.com/assets/461124/9920566/fd6ae68c-5c9a-11e5-9505-88a1f18e5b95.png)

**Comment by ZaLiTHkA** [comment]
@eperedo, I had the same issue the other day.. Are you trying to use Node from a custom directory by any chance? I managed to get around that by leaving the default NodeJS path (in your "Program Files" folder) from the NVM installer.

**Comment by rainabba** [comment]
After finally getting 4.0.0 selected and getting npm updated to 2.14.3, I'm having issues with heapdump installing because it throws a node-gyp error (see https://github.com/nodejs/node-gyp/issues/735) that I expect is the result of this method being incomplete. Strange thing though is that ONLY heapdump is failing (all other modules I'm using compile and work fine).

**Comment by rainabba** [comment]
I had to install node from MSI and now 4.1.0 is out and this tool isn't properly supporting 4.0.0.

I appreciate the tool, but if the dependencies can't be kept updated, it's not going to work for me. If there was a clear guide that allowed other devs like myself to help maintain things, then perhaps this wouldn't be an issue.

**Comment by coreybutler** [comment]
@rainabba - Actually, there has been a [guide to hacking NVM](https://github.com/coreybutler/nvm-windows/wiki/Hacking) since the day it was released. The wiki contains other instructions for alternative uses as well. There's also a gitter channel for updates about the project.

**Comment by rainabba** [comment]
Perhaps I need to read that guide and your code in detail before I'm able to contribute updated dependencies? If so, that would address my point about there being "a clear guide that allowed other devs like myself to help maintain things" and that was said in the context of updated dependencies (such as 4.0.0 x64 or 4.1.0) that aren't presently available. The app itself doesn't have to be rebuilt to provide those does it?

**Comment by Efreak** [comment]
Oddly, the stated reason at [nodedistro](https://github.com/coreybutler/nodedistro) for not using the *official* feeds is that the official feeds are out of date*. Indeed, the official feed linked to in that repo *were* out of date (that URL is now a redirect to another page) , and GitHub releases feed doesn't work. However, [the official nodejs feed](https://nodejs.org/download/release/index.json) (and [the official nightly feed](https://nodejs.org/download/nightly/index.json) as well) works perfectly. It's in JSON format, and contains versions for nodejs and npm and the filenames of the binaries (albeit without the extensions?). Alternatively, [the directory listing](https://nodejs.org/download/release/) itself is probably fairly simple to parse as well.

*From this, I assume that the sources are downloaded from the nodejs website and/or github.

**Comment by SteveALee** [comment]
Doesn't work for me

I couldn't see how to install node 4.1.0 without the msi so I used it and then reset the PATH

However I now get this
<pre>
C:\Users\Steve>nvm list

    4.1.0
  * 0.12.7 (Currently using ?-bit executable

C:\Users\Steve>nvm use 4.1.0
node v4.1.0 (64-bit) is not installed.
</pre>

I also tried specifying arch. Same if i try "use  0.12.7"

Unfortunately Explorer doesn't let you manually update the symlink target so I installed [Link Shell Extension](http://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html) and created a new symblink (renaming the nvm one first). 

Now I just need to modify the symblink 'till this is fixed

**Comment by SteveALee** [comment]
It's just been pointed out to me that the command line prog "mklink" has existed since Vista and can create hard or soft (symolic) links. So no need to install LSE to manage node versions.

**Comment by rainabba** [comment]
@coreybutler @Efreak So (this)[https://github.com/coreybutler/nodedistro/pull/8] PR should be all that's required (once merged) to get 4.1.0 to show? Also, given the tag format for the node repo (-rc for unstable), couldn't this feed be used for the MOST accurate list: https://api.github.com/repos/nodejs/node/tags ?

**Comment by rainabba** [comment]
@SteveALee Hmmm. So you're proposing to use junctions to manage the root of the node and npm installs? That could be scripted nicely, but I suspect there's a bit more to it than that given the apparent complexity of this tool. No?

**Comment by SteveALee** [comment]
@rainabba Dunno about junctions as I never really spent time looking at them. I suspect you could script fairly easily however by the time you'd covered everyhting this tool does you might as well have used it :)

i only suggested it as a temp fix a I could not get the manual install to work.

**Comment by coreybutler** [comment]
The official JSON feed suggested by @Efreak is the preferred source of releases... something that didn't exist before (this feed failed on the Joyent repos). However; it doesn't make a distinction between the stable/unstable releases, which effects the functionality of NVM for Windows in the sense that `nvm install latest` could mean two different things (stable vs unstable). The move to semantic versioning makes this possible, but it requires some new logic to replace the old. Not a big deal.

The tags list isn't used because a) it didn't work under the Joyent repo, b) scraping tags wasn't reliable before, and c) it doesn't list the older versions of node.

Junctions have been suggested in the past. The primary reason for not using them before were some challenges I ran into on older versions of windows, but I've built a cadence of only supporting what MS supports. I have been revisiting this. LSE or mklink is definitely a way to do this... NVM really just wraps around this concept anyway.

**Comment by rainabba** [comment]
Decided to look into the issue with 4.0.0 not working further and found that http://nodejs.org/dist/ has changed their format as of Node 4.0.0 and the changes braeak NVM entirely (regardless or arch). I've submitted a (PR)[https://github.com/coreybutler/nvm-windows/pull/92] to address those changes, but it's not tested because of GO. The build chain is far more work than I'm willing to deal with.

**Comment by sullivanpt** [comment]
OK, Not going to promise I did everything correctly, but rainabba's work has been edited, compiled and published here [https://github.com/sullivanpt/nvm-windows/releases/tag/1.1.0-beta].  It seems to be working for me.

**Comment by coreybutler** [comment]
Thanks for all the contributions... I've been ridiculously backlogged lately and you all have stepped up. I sincerely appreciate it! I'm currently pulling @sullivanpt's latest. Assuming everything passes in my own tests, I'll try to get this merged and released today.
