### ISSUE TITLE
9/26/2022: nvm -v

### ISSUE THREAD

**Issue by dylanh724** [coreybutler/nvm-windows#855]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
node -v should be a shortcut to version.

**Describe alternatives you've considered**
Remembering this is the only cmd applet that doesn't allow -v :)

**Additional context**
node -v
yarn -v
npm -v
`nvm version` << The black swan

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

^ EDIT: Seems like the poller is broken?

**Comment by Kochise** [comment]
I concur.
