### ISSUE TITLE
07-Oct-22: `nvm install nightly`

### ISSUE THREAD

**Issue by jhmaster2000** [coreybutler/nvm-windows#860]
**Is your feature request related to a problem? Please describe.**
Unable to use or install Node.js nightly releases with NVM4W, can't even manually install them on a system with NVM4W as it causes conflicts with NVM4W's setup and breaks everything.

**Describe the solution you'd like**
Running `nvm install nightly` should install the current latest Node.js nightly release.

**Describe alternatives you've considered**
Manually installing the nightly releases, which fails as described in the first topic.

**Additional context**
I've searched the issues on this repository for other mentions of this issue and only found #87, which is frustratingly closed as completed even though it was not actually implemented.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
This is a perfectly reasonable request, but I won't have time to add this in NVM4W. It is already on the roadmap for Runtime (rt - successor project) though.

**Comment by jhmaster2000** [comment]
ah I see, is there a repository for "Runtime"? I tried to look for one under that name on your profile but found none, where can I keep track of progress on it?
