### ISSUE TITLE
Add nightlies

### ISSUE THREAD

**Issue by Efreak** [coreybutler/nvm-windows#87]
The easiest way to do this would be to add the nightly folder to your scraper

The nightly downloads are located [here](https://nodejs.org/download/nightly/)

Also, it appears that while the github api might not return any results, there's a json file in [both](https://nodejs.org/download/nightly/index.json) [folders](https://nodejs.org/download/release/index.json) on the nodejs website that seems to be up to date. Perhaps you could use this instead of running a separate scraper, though there's no telling how long they'll update it for.

**Comment by coreybutler** [comment]
There is a new structure for downloads that the next version will be using.

**Comment by yonatanmn** [comment]
still not an option. Looks like an easy fix as @Efreak suggested

**Comment by ItsAleph** [comment]
Any updates?
