### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by bozdoz** [coreybutler/nvm-windows#872]
I'm curious if you could add a flag for `--verbose` so it can be clear, for example, what/where something is being downloaded, or what is happening under the hood

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
Yes, and it's a good idea, but it won't be coming to NVM4W. See [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) for "why".

**Comment by bozdoz** [comment]
Great to know.  Thanks!
