### ISSUE TITLE
Improve installer

### ISSUE THREAD

**Issue by tmtron** [coreybutler/nvm-windows#874]
**Issue:**

Just a minor report to improve ux:

* I had version 1.1.9 installed (on Windows 10)
* download [nvm-update.zip](https://github.com/coreybutler/nvm-windows/releases/download/1.1.10/nvm-update.zip) for version 1.1.10
* extract the zip
* execute the executable
* a cmd window shows up and a version input dialog:
![image](https://user-images.githubusercontent.com/20422904/199176695-9510978b-5722-43ae-819d-14237397f46d.png)
  * For some reason the version in the dialogue defaults to 1.1.9 (which is already installed)  
  * I think that the newest version 1.1.10 should be the default
  * At first I didn't read the text and thought this was 'upgrade from version'
    * when I then clicked okay, the updater just stopped without a message 
    * then Windows showed a confusing dialog `This program might not have run correctly`:
      * `Run the program using compatibility mode`
      * `This program ran correctly`
      ![image](https://user-images.githubusercontent.com/20422904/199177390-c3158981-d982-4a85-baf3-e5293364c3c2.png)
   * So I got the impression that the installation failed for some reason and wasted quite some time
   * Of course totally my fault for not reading the text :)

**Expected Behavior:**

* The updater should always have the newest version as default.
* When we choose the same version that is already installed we should get a clear info message or dialogue

OS: Windows 10 Pro, 21H1

**Comment by coreybutler** [comment]
Nice catch. The build process didn't update the version number in the updater. I've updated the 1.1.10 release assets with a corrected update installer.
