### ISSUE TITLE
2022-11-01: Bundle of support programs and windows patches for native module compilation

### ISSUE THREAD

**Issue by Vlasterx** [coreybutler/nvm-windows#875]
**Is your feature request related to a problem? Please describe.**
Since NodeJS no longer requires Python 2.7 to build native modules on Windows, it has become increasingly hard to set up everything on a clean installation of Windows for projects that compile modules from source, unless we use installer from NodeJS site (NodeJS 14.20.0 has it), which includes all of that. For example node module [ttf2woff2](https://github.com/coreybutler/nvm-windows) is one of those special modules which compiles from source during `npm install`.

**Describe the solution you'd like**
Create an option to install bundle of support programs and windows patches which will enable native module compilation. Something like `nvm install support-bundle`

**Describe alternatives you've considered**
I had to install NodeJS 14.20.0 as a standalone version, from official site, just to install that support bundle.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
I don't consider this within the scope of a version manager. This falls under environment management, and it fits the scope of [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) (the successor project I'm working on). This is something I can add to the Runtime roadmap.

**Comment by Vlasterx** [comment]
Workaround for this is to install NodeJS from the official website, because installer will download and install all required patches, then uninstall that node and install NVM. I haven't found an easier way to do this.
