### ISSUE TITLE
nvm use 0.12.7 error

### ISSUE THREAD

**Issue by luqin** [coreybutler/nvm-windows#88]
```
nvm use 0.12.7
exit status 1: 'd:\Program'                     ｅ
```

**Comment by coreybutler** [comment]
Please try the [new version](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.0)

**Comment by GrouchyPanda** [comment]
@coreybutler I'm still getting this error on version 1.1.0. None of the nvm use XX commands will process.

>exit status 1: 'C:\Program' is not recognized as an internal or external command,
>operable program or batch file.

**Comment by raoulus** [comment]
I am getting the same error with the latest version

`$ nvm use 4.2.2
exit status 1: 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by raoulus** [comment]
I solved it by installing it directly under `c:\`

There seems to be a problem with the path `c:\Program Files\`

**Comment by coreybutler** [comment]
@raoulus - `c:\Program Files` requires elevated administrative privileges for all operations (not just nvm - this is a Windows thing).

**Comment by kavun** [comment]
I get this error when I install `nvm` to a path that contains spaces (ie `C:\Users\Kevin Reed\AppData\Roaming\nvm\`), and then try to run `nvm use ...` I get the error:

    exit status 1: 'C:\Users\Kevin' is not recognized as an internal or external command, operable program or batch file.

When I install to `C:\nvm\` and then run `nvm use ...` I don't get the error.

**Comment by rubenhazelaar** [comment]
Get the same here, perhaps because of the space I have in username?

**Comment by mhamann** [comment]
This is still an issue on the latest versions.

**Comment by coreybutler** [comment]
This is open under a number other issues. I'm not re-opening this for that reason.

**Comment by pietrofxq** [comment]
Still an issue...

**Comment by maticicero** [comment]
It's been almost 2 years and this is still an issue

**Comment by coreybutler** [comment]
Two years with no pull requests for this too.

**Comment by carlosen14** [comment]
still an issue..
