### ISSUE TITLE
2022-11-09: Mimic POSIX 'nvm use' behavior when .nvmrc file exists

### ISSUE THREAD

**Issue by brunnobb** [coreybutler/nvm-windows#880]
**Is your feature request related to a problem? Please describe.**
On nvm-sh ([Package page](https://github.com/nvm-sh/nvm)) we can use the command `nvm use` in a running directory to automatically change the node version in case a .nvmrc file exists.
This enables extensions like [This](https://marketplace.visualstudio.com/items?itemName=henrynguyen5-vsc.vsc-nvm) from vscode to automatically change the node version when opening a repository.

**Describe the solution you'd like**
Check the running directory when executing `nvm use`, and in case a .nvmrc file exists, call nvm use with the version attached in the file. The file can contain a text value in the format `v18.12.1` or in the format `18.12.1` as examples.
With this file existing, the final command would be `nvm use v18.12.1` (or any other version.)

**Additional context**
Most probably linked to the reduction of permission prompts so there is no need to elevate every time we open a repo.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
Please see https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-isnt-nvmrc-supported-why-arent-some-nvm-for-macoslinux-features-supported and https://github.com/coreybutler/nvm-windows/wiki/Runtime
