### ISSUE TITLE
Win10 admin confirmation on every "nvm use"

### ISSUE THREAD

**Issue by robozb** [coreybutler/nvm-windows#890]
Dear All,

Can I skip on some way the Win10 admin confirmation of "nvm use"?

Thanks: Beci

**Comment by coreybutler** [comment]
Yes and no. You can enable developer mode to bypass the UAC prompt. The catch: you have to have admin rights to enable developer mode. See https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#permissions-exit-1-exit-5-access-denied-exit-145.

**Comment by robozb** [comment]
Daer @coreybutler,

Thank you so much for your advice, I'm checking now!

Regards: Bela
