### ISSUE TITLE
Fa-duotone messed up icon

### ISSUE THREAD

**Issue by lufo88ita** [coreybutler/nvm-windows#892]
Hi,

I include the file all.min.css (downloaded from here https://fontawesome.com/download ) of the pro version in my project.

I try to use fa.duotone family, but the icons are all messed up. See the screenshot.
![Immagine 2022-12-01 151532](https://user-images.githubusercontent.com/85335935/205075430-881c4797-310c-434d-9874-b9c434e47b0d.png)

In previous version (5.16) the fad family work without a problem.

**Comment by coreybutler** [comment]
This has absolutely nothing to do with NVM for Windows.

**Comment by lufo88ita** [comment]
Ops, I'm sorry wrong repository.
