### ISSUE TITLE
2022-12-07: File information, especially version number

### ISSUE THREAD

**Issue by lennybacon** [coreybutler/nvm-windows#897]
It would be really nice to have sole file information. Especially a version number.

This is how it looks at the moment:

![image](https://user-images.githubusercontent.com/272164/206153674-fdb0fd37-0f7b-4c4b-a192-e19e8217cd20.png)

**Comment by coreybutler** [comment]
I've added the details to the installer, but this won't be available until the next release.

**Comment by lennybacon** [comment]
Thank you very much!
