### ISSUE TITLE
nvm install leads to panic

### ISSUE THREAD

**Issue by c33s** [coreybutler/nvm-windows#898]
after updating from 1.1.7 to 1.1.10 i get a panic similar but not a duplicate of https://github.com/coreybutler/nvm-windows/issues/507 

**How To Reproduce:**
```
nvm install yarn
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
main.versionNumberFrom({0x13410158, 0x4})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:496 +0x116
main.getVersion({0x13410158, 0x4}, {0x6e9d26, 0x2}, {0x0, 0x0, 0x0})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:233 +0x367
main.install({0x13410158, 0x4}, {0x6e9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:273 +0xbb
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea
```

**Desktop:**
 - OS: windows

**Comment by coreybutler** [comment]
NVM4W is a Node installer. Yarn is an **npm** package. If you want to install yarn, run `npm install -g yarn`. For newer versions, you can use corepack. See the [yarn installation instructions](https://yarnpkg.com/getting-started/install).

**Comment by c33s** [comment]
sorry for my bad explanation and my misleading issue title. 

what i mean is, shouldn't there be an input validation and an error handling? i just mixed up npm and nvm by mistake and got a panic. wouldn't an error message like "yarn" is not a valid node version, try using "1.0.0" be more helpful?

**Comment by coreybutler** [comment]
@c33s yes, the error messages could be more helpful.

I'm going to keep this closed because context-aware error messages are already a core milestone in [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).
