### ISSUE TITLE
2022-DEC-08: List Latest/LTS, etc.

### ISSUE THREAD

**Issue by censys-git** [coreybutler/nvm-windows#899]
**Is your feature request related to a problem? Please describe.**
I run node scripts from my IDE that may need to use different versions of node, so I have a shell script to change the version.  The shell script gets a version to be changed to. I run the 'nvm current' to get the current version to compare to what has been passed in and only call for the change if the current version is different from the requested version. This works great if the requested version is an actual version (e.g. "11.5.0" or "6.11.5", etc.). However it is a problem if the requested version is "latest", "lts", etc.

**Describe the solution you'd like**
Can we have a command similar to 'nvm current' that returns what the 'latest' and 'lts', etc. are? I am constantly adding versions of node so knowing what the 'latest' or 'lts' is can be problematic when being called by an IDE tool that has the request "hard coded" to "lts" or "latest". Ideally a simple call like:
  "nvm latest" => returns "19.1.0"
  "nvm lts" => returns "18.12.1"

Then if the request is for "latest", I can run "nvm current" and compare it to "nvm latest" to see if that is what I am currently running to know not make the change. Etc.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
There is a feature freeze on NVM4W, so I've added this as a feature request for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).
