### ISSUE TITLE
does not list the installed nodejs versions

### ISSUE THREAD

**Issue by sdudnic** [coreybutler/nvm-windows#904]
**Issue:**

```
PS C:\proj> nvm list

    16.19.0
PS C:\proj> nvm install lts
Version 18.12.1 is already installed.
PS C:\proj> nvm list

    16.19.0
PS C:\proj>
```
??
**How To Reproduce:**

**Expected Behavior:**

**Screenshots:**
![image](https://user-images.githubusercontent.com/35489219/208157905-76eb3884-df54-4164-a6b2-f1719a8eff9e.png)

**Desktop:**
 - OS: Windows 10 Pro
- nvm running version 1.1.9.

**Comment by coreybutler** [comment]
This suggests the original installation did not complete properly.

Without a way to reproduce this, there isn't much I can do. I'm closing this, but if you can post a way to recreate it, I can reopen/look into it.
