### ISSUE TITLE
2023-01-13: Allow to execute individual node commands on specified node versions (nvm exec)

### ISSUE THREAD

**Issue by itsmedmd** [coreybutler/nvm-windows#914]
**Is your feature request related to a problem? Please describe.**
Yes. I have to run two different projects at the same time. One project must use node 14 and the other one must use node 18. Unless I'm mistaken, `nvm-windows` doesn't have the ability to run node commands on specific node versions so because of this I can't run both projects at the same time and I'm limited to running only one project. The original `nvm` package seems to have functionality for this - the `nvm exec` command.

**Describe the solution you'd like**
I propose to add `nvm exec` command which would work identical to the original `nvm` package - you could run node commands on specified node versions using `nvm-windows` without the need to switch the node version by using `nvm use` - this would allow to run things with different node versions at the same time. For example it could be used like this:
* `nvm exec 12 node --version` - checks node version by running node 12
* `nvm exec 14 npm run dev` - runs project by using node 14
* `nvm exec 18 npm run dev` - runs project by using node 18

**Describe alternatives you've considered**
WSL on windows and virtual machines but it seems very inconvenient.

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
This has been requested before (many times), but it requires an entirely different approach. This can only be achieved with a shim, which (unlike Linux) can cause many edge cases/problems on Windows. So, this will not be added to NVM4W, but it is on the roadmap for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime).
