### ISSUE TITLE
New NVM Installation from Scratch; Installed NPM & Node - 'npm' is not recognized... error

### ISSUE THREAD

**Issue by elthombre** [coreybutler/nvm-windows#916]
'npm' is not recognized as an internal or external command, operable program or batch file.

similar from within Visual Studio:

npm : The term 'npm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Need to get these up-n-running and need to update node modules for a project.

please advise.

Thanks

**Comment by elthombre** [comment]
OK, I just ran nvm list which shows 19.4.0

I have an admin acct. and ran the cmd as admin.

I uninstalled the pre-existing NVM, npm, and node before running a re-installation.

I used the Windows Developer CMD; not Cygwin.

When I try to run the following to see if I can reinstall npm:

nvm install-latest-npm

it just throws up the current version of nvm that I'm running.

**Comment by coreybutler** [comment]
`nvm-install-latest-npm` is not a valid command. That's the syntax used in nvm-sh, not nvm-windows.

If node is running, you need to run `npm i -g npm` to install the latest version of npm.

**Comment by vuhung3990** [comment]
run the following command:
```
echo %NVM_SYMLINK%

Directory of D:\Installs\nodejs
```
then 
```
dir D:\Installs\  <=== Parent folder
Directory of D:\Installs

03/07/2023  05:13 PM    <DIR>          .
03/07/2023  05:13 PM    <DIR>          ..
03/07/2023  05:13 PM    <SYMLINKD>     nodejs [D:\Installs\nvm\v16.14.2]  <<=======
```
final
```
nvm install 16.14.2
nvm use 16.14.2
```

hope this help

**Comment by anmatika** [comment]
Had the same problem and had to explicitly say
`nvm on`

https://stackoverflow.com/a/73525409/1498822
