### ISSUE TITLE
Request help. NODE has been configured in the environment variable_ OPTIONS, but nodes installed with nvm cannot use this variable

### ISSUE THREAD

**Issue by xiyuvi** [coreybutler/nvm-windows#923]
Request help. NODE has been configured in the environment variable_ OPTIONS, but nodes installed with nvm cannot use this variable
![image](https://user-images.githubusercontent.com/38217058/215384275-60b2f13c-3e5d-46a6-a097-b52251c914ac.png)
![image](https://user-images.githubusercontent.com/38217058/215384462-481b9cfd-5463-46c1-ad5f-2f19f6a62b59.png)

**Comment by coreybutler** [comment]
I think this flag is only supported in newer versions of Node. I was able to make it work using `nvm use 18`, but not with `nvm use 16`.

**Comment by WORMSS** [comment]
I see no difference between node installed directly into `/program files/nodejs` vs installed via `nvm` , legacy provider works in both places.

**Comment by coreybutler** [comment]
Closing since this does not appear to be a problem with NVM4W.
