### ISSUE TITLE
Why is this happening???

### ISSUE THREAD

**Issue by AgenciaGelattina** [coreybutler/nvm-windows#924]
![image](https://user-images.githubusercontent.com/83784889/216172990-6955f257-7afa-41ec-964e-62f537df1bb5.png)

**Comment by coreybutler** [comment]
You most likely have a prior installation of Node.js. See https://github.com/coreybutler/nvm-windows#installation--upgrades and https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#uninstall-existing-node-installation-before-installing-nvm4w.
