### ISSUE TITLE
[11-Feb-2023]: [Update NVM using the command line]

### ISSUE THREAD

**Issue by lawweiliang** [coreybutler/nvm-windows#927]
Problem
Each and every time, where  there is a new nvm version, I need to download the and install it. 
It is pretty time consuming. 

Suggestion
Would it be possible to update the nvm using command like `nvm update`?

**Comment by coreybutler** [comment]
An auto-update feature is on the roadmap for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). There is a [feature freeze](https://github.com/coreybutler/nvm-windows/wiki/New-Features) on NVM for Windows.

While it still needs to be downloaded, releases from v1.1.8 and up have an [update tool](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.10) so you don't have to reinstall everything:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/770982/218281863-12b6f840-23b1-4c63-b689-750826de40b0.png">
