### ISSUE TITLE
Spaces in installation path are properly handled by nvm install, but not by nvm use

### ISSUE THREAD

**Issue by janerjak** [coreybutler/nvm-windows#932]
**Issue:**
When installing nvm-windows using the nvm-setup.exe to a path with spaces, e.g. "C:\Programs X", the command `nvm install latest` successfully runs. `nvm use latest` will return a non-zero exit-code and produce the output
`exit status 1: 'C:\Programs' is not recognized as an internal or external command,
operable program or batch file.`

**How To Reproduce:**
1. Install nvm using nvm-setup.exe (version 1.1.1.0, launched with admin privileges) to a path containing spaces
2. Open a terminal window and type `nvm install latest` (this should work)
3. Type `nvm use latest`

**Expected Behavior:**
nvm selecting the correct version

**Screenshots:**
![image](https://user-images.githubusercontent.com/23585349/218708409-d5f575b2-77d6-414f-8dd1-d9769c602408.png)

*Notes*: The screenshot is taken from a terminal running MINGW64. The bug is also present in Command Line (Windows 11) and Power Shell.

**Desktop:**
 - OS: Windows 11 22H2

**Comment by dalfiannur** [comment]
Open and Edit file C:\Programs X\nvm\settings.txt

from
```
root: C:\Programs X\nvm
```
to
```
root: C:\Programs\ X\nvm
```

**Comment by iquanxin** [comment]
Check your environment PATH

**Comment by janerjak** [comment]
> Check your environment PATH

Sorry, what exactly should I check? Installing at a path without spaces works like a charm (which I ultimately did).

Nevertheless, this should be fixed at some point.

**Comment by Plagiatus** [comment]
Having the same issue on Win10 Pro Build 19044.

**Comment by lava-floor** [comment]
Hi, I've encountered the same issue; solved running cmd as Administrator

**Comment by nineninesevenfour** [comment]
I suggest to fix it by wrapping arguments with an `escape` function in nvm.go:
```go
func run(name string, arg ...string) (bool, error) {
	c := exec.Command(name, escape(arg)...)
	// ... rest of function
}

func escape(args []string) []string {
	for index, arg := range args {
		if strings.Contains(arg, " ") && !strings.HasPrefix(arg, "\"") {
			args[index] = "\"" + arg + "\""
		}
	}
	return args
}
```
As far as I have seen this should work with current usages, but I did not test it.

**Comment by nineninesevenfour** [comment]
It turned out, that spaces in the arguments was not the problem. The problem was that `exec.Command(...)` refuses to execute commands with spaces in it. Quoting the command did not work as well. But setting `Dir` in type [`Cmd`](https://pkg.go.dev/os/exec#Cmd) worked.
PR follows.
