### ISSUE TITLE
nvm shortcut at start menu - wrong icon path - no cmd runs

### ISSUE THREAD

**Issue by NJT145** [coreybutler/nvm-windows#937]
there is a problem about the shortcut that installer creates at start menu.
1. path of "nvm.lnk" is the installatio path of "nvm.exe". In order to run it on a cmd, it must be `%windir%\system32\cmd.exe "/K" <InstallDir>\nvm.exe` and not only `<InstallDir>\nvm.exe`.
2. shortcut icon is at `<InstallDir>\nodejs.ico`, not at `bin\nodejs.ico`.

**Comment by NJT145** [comment]
shortcut icon path must be `nodejs.ico`, not `bin\nodejs.ico`

**Comment by NJT145** [comment]
another point is that you can use %NVM_HOME% instead of the <InstallDir>

**Comment by NJT145** [comment]
For "nvm.lnk" shortcut:
Icon path must be `%NVM_HOME%\nodejs.ico`,
Target must be `%windir%\system32\cmd.exe "/K" %NVM_HOME%\nvm.exe`,
Starting location can be `%NVM_HOME%`.

For "Uninstall nvm.lnk":
Icon path can be `%NVM_HOME%\unins000.exe`,
Target can be `%NVM_HOME%\unins000.exe`,
Starting location can be `%NVM_HOME%`.

Here, you can better to use %NVM_HOME% instead of an absolute path, so that it can work on different situations, or you can use absolute path for that.
But FOR ICON PATH, DON'T FORGET TO USE %NVM_HOME% or its absolute path.

**Comment by NJT145** [comment]
still no fix for that. any fix in the future?

**Comment by coreybutler** [comment]
My understanding is this is just an issue with the display of an icon, not a functional problem. That's why it was tagged low priority. 

Truthfully, I've never heard of anyone using NVM4W from the start menu. I'm not even sure what use case would warrant that.

**Comment by NJT145** [comment]
this is more than an icon issue. it's just running nvm and closes itself, so unnecessary. You can either remove that icon from start or edit it to rum with a cmd prompt. I already telling you all you need, so you can put that fixing on your future program for NVM4W.

**Comment by coreybutler** [comment]
How did you install NVM4W? I'm asking because the official installer doesn't create a start menu option at all. It doesn't create an nvm.lnk file either.

The following screenshot shows the installation contents:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/770982/233430385-1cc47c9c-5e3a-457a-941a-2533b8edce4c.png">

The installer doesn't touch the start menu. So, I really don't know where this is coming from.

**Comment by NJT145** [comment]
I use winget. but it uses original installer. For example, latest version uses https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe .

**Comment by NJT145** [comment]
still waiting for a fix...

**Comment by coreybutler** [comment]
NVM4W does not add anything to the start menu. However; if you are using Windows search to search for "nvm", Windows may display the executable, like this:

<img width="588" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/68495dd9-7396-4261-9bb5-6c4ef320f878">

Is this what you're referring to?

**Comment by NJT145** [comment]
I installed NVM4W from https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe to the location `C:\ProgramData\nvm` , and it creates two shortcuts at `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\NVM for Windows`: "nvm.lnk" and "Uninstall nvm.lnk"
![image](https://github.com/coreybutler/nvm-windows/assets/17969940/e721f5ab-81f7-41cd-b5cd-fa2f2220335b)
As a result, it creates these shortcuts.
And this is what you are telling... So yes, this is what I am referring to.
