### ISSUE TITLE
[02/03/2023]: [Using multiple node versions simultaneously]

### ISSUE THREAD

**Issue by AlbertoDente3** [coreybutler/nvm-windows#938]
**Is your feature request related to a problem? Please describe.**
I am dealing with multiple repos and i need to use different node versions,
OS: Windows 10
NVM: 1.1.10

**Describe the solution you'd like**
I would like to run simultaneously in two different projects, two different node version.
I.E a node12  web server in repo 1, and node18 web server in repo 2 on same machine

<table>
  <tr>
    <td>Please use the reactions to cast a vote in favor of or against this feature suggestion &raquo;</td>
    <td><img src="https://github.com/metadoc/metadoc.io/raw/main/.github/ISSUE_TEMPLATE/vote.png" width="75"/></td>
  </tr>
</table>

**Comment by coreybutler** [comment]
https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#how-can-i-use-two-different-versions-of-nodejs-at-the-same-time
