### ISSUE TITLE
panic: runtime error: slice bounds out of range [:1] with length 0

### ISSUE THREAD

**Issue by jhcarlos8888** [coreybutler/nvm-windows#942]
**Issue:**

panic: runtime error: slice bounds out of range [:1] with length 0
goroutine 1 [running]:
main.versionNumberFrom({0x118140b8, 0x8})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:496 +0x116
main.getVersion({0x118140b8, 0x8}, {0x5b9d26, 0x2}, {0x0, 0x0, 0x0})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:233 +0x367
main.install({0x118140b8, 0x8}, {0x5b9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:273 +0xbb
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea

**How To Reproduce:**
when trying to install a version of nodejs on windows 10 it throws me an error

**Expected Behavior:**

**Comment by coreybutler** [comment]
How did you try to install a version? If you ran `nvm install release`, that's not a valid alias which has been known to trigger this error. That's an alias used in nvm-sh, not nvm-windows.

The next maintenance release (which will be published sometime soon), will catch invalid alias names (as shown below):

![image](https://user-images.githubusercontent.com/770982/224109868-c89f812a-9500-4a03-808c-de8df6dbd2f3.png)

**Comment by LmaxplayG** [comment]
```go 
PS C:\Users\lmaxp> nvm install *
panic: runtime error: slice bounds out of range [:1] with length 0

goroutine 1 [running]:
main.versionNumberFrom({0xa085d0, 0x1})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:496 +0x116
main.getVersion({0xa085d0, 0x1}, {0x819d26, 0x2}, {0x0, 0x0, 0x0})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:233 +0x367
main.install({0xa085d0, 0x1}, {0x819d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:273 +0xbb
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea
PS C:\Users\lmaxp>
```

**Comment by coreybutler** [comment]
@hungnh17 is it actually the same stack trace? Or is there more information. If the proxy fails, it would reference a different part of the code.

**Comment by zdrawku** [comment]
thanks @coreybutler, as you noted, this is nvm for windows and the alias like `nvm instlal --lts` are not valid.

This is how I've installed the latest node available:
![image](https://user-images.githubusercontent.com/11193764/228765817-d628c19e-7c67-4f13-8f50-ab38ac4ee043.png)

**Comment by ErazorWhite** [comment]
The same for me:
![image](https://user-images.githubusercontent.com/41112771/230286037-d687a18e-0c88-4a1b-aa46-451a8abed008.png)

**Comment by ErazorWhite** [comment]
nvm install lts worked well in my case
![image](https://user-images.githubusercontent.com/41112771/230286653-27332bcd-c631-4be8-982b-00703c9248c4.png)

**Comment by moekhalil** [comment]
hehe -- I don't think @coreybutler seen that this program was referencing *HIS VERY OWN ONEDRIVE* when he looked at this issue.

I am having the same issue. It is looking to `checkVersionExceedsLatest` and seems like the node path is checking is hard coded , hence might work for you @coreybutler .

```
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x11c0a0d0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:790 +0x220
main.install({0x11c0a0d0, 0x6}, {0x127fa65, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:302 +0x35d
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69
```

neither `latest`  or `19.9.0` work.

![image](https://user-images.githubusercontent.com/5835530/231152579-3392fdc6-beca-4da9-ac28-3b3e48709f19.png)

**Comment by coreybutler** [comment]
This should be resolve in 1.1.11.
