### ISSUE TITLE
Connection timeout with 18.x.x but working with 16.x.x

### ISSUE THREAD

**Issue by kovapatrik** [coreybutler/nvm-windows#946]
**Issue:**
When using node version 18.x.x yarn or any other package manager can't reach the network, but it's working with v16.x.x.

**How To Reproduce:**
1. nvm install 18
2. nvm use 18
3. corepack enable
4. yarn

![image](https://user-images.githubusercontent.com/44952801/225760102-2dd389eb-4b02-4ed2-bb8a-c36c13152ca4.png)

(in the end I've got another error, but it can be ignored)

I'm not using any proxy or VPN and my internet connection is great.

**Comment by kovapatrik** [comment]
Looks like it's not an nvm related issue, I've tried to install node with the official installer and I'm experiencing the same.

**Comment by coreybutler** [comment]
For anyone else who may have encountered this problem, there was an outage on the Node.js servers for a little while recently.

**Comment by kovapatrik** [comment]
Oh, good to know! Other issue was that Node.js 16 was used IPv4 as default, while v17<= is using IPv6 as default. For some reason, if I didn't disable that my computer can get an IPv6 address, Node can't reach the internet.
