### ISSUE TITLE
After connection failure, panic

### ISSUE THREAD

**Issue by qiulaidongfeng** [coreybutler/nvm-windows#948]
**How To Reproduce:**
nvm install 10.22.0，Downloading npm version 6.14.6 timeout

**Expected Behavior:**
Tell me it's timed out

**Actual behavior:**
Downloading node.js version 10.22.0 (64-bit)...
Complete
Creating D:\nodejs\temp

Downloading npm version 6.14.6... Error while downloading https://github.com/npm/cli/archive/v6.14.6.zip - Get "https://github.com/npm/cli/archive/v6.14.6.zip": read tcp 192.168.1.252:53924->140.82.114.4:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xc6b53d]

goroutine 1 [running]:
nvm/web.Download({0x120ac030, 0x2e}, {0x1200e540, 0x1e}, {0x122e6d90, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:90 +0x44d
nvm/web.GetNpm({0x12018da1, 0x9}, {0x122e6d90, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/web/web.go:257 +0x39d
main.install({0x120180e8, 0x7}, {0xcd9d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:364 +0x9d9
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea

**Comment by coreybutler** [comment]
> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Either the remote server was down (which has happened a few times lately) or there was a problem with your connection. I just tried this and the download succeeded.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/770982/226116972-1bde28b5-c22f-4876-aa7c-69236b3be1fa.png">

**Comment by qiulaidongfeng** [comment]
I also downloaded successfully later. I only felt that there was a bug when I saw the panic and stack information

**Comment by coreybutler** [comment]
Understandable. NVM4W could use a better error message than the go stack trace.

**Comment by qiulaidongfeng** [comment]
I submitted a PR that should avoid panic
