### ISSUE TITLE
cannot install nodejs 4.1.1 64 bit

### ISSUE THREAD

**Issue by reidlai** [coreybutler/nvm-windows#95]
Any idea how to install nodejs 4.1.1 using nvm for windows?

**Comment by HerveSeger** [comment]
Download and install the [latest release](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.0) and type `nvm install 4.1.1`

**Comment by lpaulger** [comment]
I think this can be closed

**Comment by estvmachine** [comment]
Great man!
