### ISSUE TITLE
Node not recognized in normal CMD

### ISSUE THREAD

**Issue by ZegeM** [coreybutler/nvm-windows#954]
I've followed the instructions:

Delete all previous versions of nodejs and clear Npm folders
Install NVM

open Admin CMD
nvm install 12.22.12
nvm use 12.22.12
I get the message that I'm now using 12.22.12

When i open a normal CMD it doesn't work, node -v returns no node installed

I am using windows 11, and latest version of the NVM

Earlier I got the issue when I installed 18.15.0, I could not switch away from it, although i had 12.22.12 installed with nvm, in admin it switched and normal it didnt.

**Comment by coreybutler** [comment]
You should be able to run `node -v` and get a response, but you cannot run `nvm use ___` without elevated/admin privileges. Windows requires these permissions to create or modify a symlink. The `nvm use` command just modifies the symlink, so it's important to have the appropriate permissions. If you cannot even run `node -v`, then you'll need to check the `PATH` of the specific user account. See [this](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-do-i-need-to-uninstall-nodejs-before-installing-nvm-for-windows) for details.

If you're using the latest version of NVM (1.1.10), you should see the UAC prompt requesting elevated permissions to run `nvm use`.

**Comment by coreybutler** [comment]
@konieckropka `NVM_HOME` and `NVM_SYMLINK` cannot be the same value. `NVM_HOME` is the installation root for NVM for Windows (i.e. where _nvm.exe_ is installed). `NVM_SYMLINK` is the location where Windows will look for _node.exe_. NVM4W manages the symlink for you, but you have to specify the location. This should have been done in the installation.

Here's an example (v1.1.11 is not released yet, but it shows how the highlighted values should be different).

<img width="536" alt="image" src="https://user-images.githubusercontent.com/770982/230253879-8cc1f448-8ef7-4672-8904-404ffab2a3f1.png">

**Comment by JacquesDoubell** [comment]
I'm getting the same now after using the updater app to upgrade from 1.1.9 to 1.1.11. nvm list still shows that I have 2 node versions installed.

**Comment by coreybutler** [comment]
@JacquesDoubell post the output of `nvm debug`.

**Comment by JacquesDoubell** [comment]
@coreybutler Already uninstalled and reinstalled nvm to fix it. Sorry.

**Comment by gadzbi123** [comment]
Uninstalling Node and leaving nvm installed solved the issue.
![image](https://github.com/coreybutler/nvm-windows/assets/56163675/3c223977-9b91-4d6a-a5b3-0f856a229b1c)

**Comment by coreybutler** [comment]
Closing since this appears to be resolved for folks.

**Comment by Sahil4883** [comment]
Facing the issue of node -v not getting recognized 
1. I ran the cmd as administrator 
2. It's showing me that I have node version installed through nvm
3. When I try to run node -v it is not recognized
4. When I try to run nvm debug the cmd abruptly closes

![Image](https://github.com/user-attachments/assets/de1ebc61-25d1-471f-8adf-195ffc1b5a0c)
I have the nvm folder in the D drive and how and where should I put the system variable in order to work things out

**Comment by coreybutler** [comment]
@Sahil4883 - which version are you running? Make sure you're on the latest, because you may be facing [this bug](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#nodejs-installation-fails-silently).

**Comment by Sahil4883** [comment]
If you're talking about the nvm version it is the latest version which I got from [here](https://github.com/coreybutler/nvm-windows/releases/download/1.2.2/nvm-setup.exe) and still there's huge complexity in installing the nvm and making it work

**Comment by coreybutler** [comment]
@Sahil4883 - first, did you run `nvm use 23.6.0`? Your screenshot looks like you didn't activate a version (you only turned nvm4w on). Second, run `nvm debug`. It may give you insight into issues on your specific system. Third, there are some issues with v1.2.2, but only with older versions of Node/npm. I've fixed most of the issues and will be releasing v1.2.3 as soon as I have more time. Hopefully that will be sometime in the next week.
