### ISSUE TITLE
Error installing 'latest' node version

### ISSUE THREAD

**Issue by oracleoftroy** [coreybutler/nvm-windows#955]
**Issue:**

I can't install the latest version of node, either via `latest` or via an explicit version number. On the surface it looks like #942 and might be the same or closely related, but the error message I'm getting is slightly different than what I see in that thread.

**How To Reproduce:**

Using a fresh install using nvm-setup.exe from releases (first time trying this program, so no previous installs). Node was previously manually installed, but I uninstalled it before installing nvm.

```
> nvm version
1.1.10


> nvm install latest
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x11da80e0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x11c1a0b0, 0x6}, {0x909d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea


> nvm list available

|   CURRENT    |     LTS      |  OLD STABLE  | OLD UNSTABLE |
|--------------|--------------|--------------|--------------|
|    19.9.0    |   18.15.0    |   0.12.18    |   0.11.16    |
|    19.8.1    |   18.14.2    |   0.12.17    |   0.11.15    |
|    19.8.0    |   18.14.1    |   0.12.16    |   0.11.14    |
|    19.7.0    |   18.14.0    |   0.12.15    |   0.11.13    |
|    19.6.1    |   18.13.0    |   0.12.14    |   0.11.12    |
|    19.6.0    |   18.12.1    |   0.12.13    |   0.11.11    |
|    19.5.0    |   18.12.0    |   0.12.12    |   0.11.10    |
|    19.4.0    |   16.20.0    |   0.12.11    |    0.11.9    |
|    19.3.0    |   16.19.1    |   0.12.10    |    0.11.8    |
|    19.2.0    |   16.19.0    |    0.12.9    |    0.11.7    |
|    19.1.0    |   16.18.1    |    0.12.8    |    0.11.6    |
|    19.0.1    |   16.18.0    |    0.12.7    |    0.11.5    |
|    19.0.0    |   16.17.1    |    0.12.6    |    0.11.4    |
|   18.11.0    |   16.17.0    |    0.12.5    |    0.11.3    |
|   18.10.0    |   16.16.0    |    0.12.4    |    0.11.2    |
|    18.9.1    |   16.15.1    |    0.12.3    |    0.11.1    |
|    18.9.0    |   16.15.0    |    0.12.2    |    0.11.0    |
|    18.8.0    |   16.14.2    |    0.12.1    |    0.9.12    |
|    18.7.0    |   16.14.1    |    0.12.0    |    0.9.11    |
|    18.6.0    |   16.14.0    |   0.10.48    |    0.9.10    |

This is a partial list. For a complete list, visit https://nodejs.org/en/download/releases


> nvm install 19.9.0
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x11c1a0b0, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:875 +0x220
main.install({0x11c1a0b0, 0x6}, {0x909d26, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:308 +0x337
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/libraries/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xaea


> nvm install 19.8.1
Downloading node.js version 19.8.1 (64-bit)...
Extracting node and npm...
Complete
npm v9.5.1 installed successfully.


Installation complete. If you want to use this version, type

nvm use 19.8.1
```

**Expected Behavior:**

`nvm install latest` or `nvm install 19.9.0` would install the current latest version reported by the app (19.9.0).

As shown above, the previous version (19.8.1) worked fine, as did `nvm install lts`. It seems to be an issue specific to the latest nodejs version. The version nvm reports matches what Nodejs's website claims is the latest. I did not try installing any other versions aside from `latest`, `lts` and the two explicit version numbers above.

**Comment by MeerMusik** [comment]
I hereby confirm the Error.

Same Version(s) of NVM and Node. Same Error Message with the same Steps as reported in the OT. Differences:

1.) Manual Installation of NVM
2.) I upgraded countless of times without any Error before from Version 18.x all throughout 19.8.1

**Comment by moekhalil** [comment]
Same. 

Commented here https://github.com/coreybutler/nvm-windows/issues/942#issuecomment-1503175012

**Comment by moekhalil** [comment]
https://github.com/coreybutler/nvm-windows/pull/956  --> I just submitted a pull request that fixes this issue 👍🏼

**Comment by coreybutler** [comment]
Fixed in master, will be released in v1.1.11

**Comment by coreybutler** [comment]
Version 1.1.11 has been released.

**Comment by oracleoftroy** [comment]
Updated to 1.1.11 and no more issue. I give this the official 'works on my machine' stamp of approval! Thanks for your quick work.

**Comment by holmesadrianh** [comment]
Just want to leave this here from someone. I had the same issue and it turned out to be OneDrive messing with the path somehow. I do not need OneDrive so I unlinked my device and quit the app.

**Comment by rolfen** [comment]
I'm having this error when I try to install the latest version (20.3.0).  
However the version before the latest `nvm install 20.2.0` and any preceding versions would successfully install.

**Comment by verikono** [comment]
I'm getting version 1.1.9 when installing via chocolately in win11 powershell7 and hit into this issue obviously. Just a heads up.

thanks for the effort on this project - its greatly appreciated :)

**Comment by gigabet** [comment]
> I'm getting version 1.1.9 when installing via chocolately in win11 powershell7 and hit into this issue obviously. Just a heads up.
> 
> thanks for the effort on this project - its greatly appreciated :)

Use `choco install nvm.install` for version 1.1.11

**Comment by verikono** [comment]
> > I'm getting version 1.1.9 when installing via chocolately in win11 powershell7 and hit into this issue obviously. Just a heads up.
> > thanks for the effort on this project - its greatly appreciated :)
> 
> Use `choco install nvm.install` for version 1.1.11

perfect.. thank you! :)

**Comment by WolfSoko** [comment]
> > I'm getting version 1.1.9 when installing via chocolately in win11 powershell7 and hit into this issue obviously. Just a heads up.
> > thanks for the effort on this project - its greatly appreciated :)
> 
> Use `choco install nvm.install` for version 1.1.11

Or use `choco upgrade nvm.install`

**Comment by nlucis** [comment]
Issue is still a problem with the latest version of nvm available via choco.

**Comment by coreybutler** [comment]
We do not maintain the choco/nuget installations. Make sure it's installing the latest version.

**Comment by coreybutler** [comment]
Update: v2 was rebuilt from scratch, including a new alias system. If you found your way to this issue through Google/AI, consider upgrading to v2.
