### ISSUE TITLE
Please support the other mirror

### ISSUE THREAD

**Issue by zce** [coreybutler/nvm-windows#97]
I'm chinese, In our country nodejs.org frequent connection failure

**Comment by Micua** [comment]
http://npm.taobao.org/mirrors/node for china

**Comment by coreybutler** [comment]
Support for custom mirrors is now available in the master branch.

**Comment by zce** [comment]
thanks

**Comment by xiegeo** [comment]
In case anyone else is digging through old issues to find out. the command to set a node download mirror is `nvm node_mirror https://npm.taobao.org/mirrors/node/`. The tailing `/` is important.
