### ISSUE TITLE
[Issue]: Unable to install node latest v20

### ISSUE THREAD

**Issue by manthanank** [coreybutler/nvm-windows#971]
### Contact Details

manthan.ank46@gmail.com

### What happened?

![image](https://user-images.githubusercontent.com/50883320/233758843-af7f4625-44aa-4702-954a-dea9b8403db3.png)

### What did you expect to happen?

Install latest version

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

Asian

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

I don't know (Default)

### Is Developer Mode enabled?

No (Default)

**Comment by Ph4nToM-74** [comment]
Facing the same issue!

**Comment by mertssmnoglu** [comment]
I tried `nvm install 20` and thats the result
```
Version 20.0.0-arm64.msi is not available.

The complete list of available versions can be found at https://nodejs.org/dist/index.json
```

**Comment by mertssmnoglu** [comment]
As the maintainer said that's the 9th(now is 10) duplicate of #955. This issue resolved vith version ` v1.1.11.`

Steps:

Install the latest version of nvm-windows from https://github.com/coreybutler/nvm-windows/releases/tag/1.1.11
Just run the installer and if you have currently installed nodejs select it to use it after installing new version
Run `nvm install latest` and `nvm use 20`

![resim](https://user-images.githubusercontent.com/61623638/233779767-db06558e-9340-47f6-b1e9-6a86a1b97200.png)

@manthanank @Ph4nToM-74 

That worked for me.

**Comment by coreybutler** [comment]
The original issue says this is happening in v1.1.11. @manthanank - please confirm the version you're using by running `nvm --version`. Everything listed in this issue existed in v1.1.10 and was fixed in v1.1.11.

**Comment by Ph4nToM-74** [comment]
Updated nvm to 1.11.0 and the issue is fixed. Thanks for pointing it out.

**Comment by manthanank** [comment]
Okay, thanks 👍
