### ISSUE TITLE
Node 20.x not supported?

### ISSUE THREAD

**Issue by cope** [coreybutler/nvm-windows#973]
### What happened?

Node v20.0.0 did not install - `main.checkVersionExceedsLatest` throws an error.

### What did you expect to happen?

I expected node v20.0.0 to be installed, as it is [the current version](https://github.com/nodejs/release#release-schedule).

### Version

1.1.9

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Relevant log/console output

```Shell
C:\>nvm install 20.0.0
panic: runtime error: index out of range [3] with length 3

goroutine 1 [running]:
main.checkVersionExceedsLatest({0x128160f8, 0x6})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:790 +0x220
main.install({0x128160f8, 0x6}, {0x11dfa65, 0x2})
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:302 +0x35d
main.main()
        C:/Users/corey/OneDrive/Documents/workspace/oss/coreybutler/nvm-windows/src/nvm.go:87 +0xa69
```

### Anything else?

https://github.com/nodejs/release#release-schedule

**Comment by RadoslavK** [comment]
You need the latest version 1.1.11

**Comment by cope** [comment]
Well, I would have updated, but there was not indication of v20 support in the [v1.1.11 release](https://github.com/coreybutler/nvm-windows/releases/tag/1.1.11).
