### ISSUE TITLE
[Issue]: winget upgrade does not work

### ISSUE THREAD

**Issue by niStee** [coreybutler/nvm-windows#976]
### What happened?

```
PS C:\Users> winget list CoreyButler.NVMforWindows
Name                   Id                        Version Available Source
-------------------------------------------------------------------------
NVM for Windows 1.1.10 CoreyButler.NVMforWindows 1.1.10  1.1.11    winget
PS C:\Users> winget update CoreyButler.NVMforWindows
No applicable upgrade found.
PS C:\Users> winget install CoreyButler.NVMforWindows
Found an existing package already installed. Trying to upgrade the installed package...
No applicable upgrade found.
```

### What did you expect to happen?

I was expecting to be able to update NVM using Winget.

### Version

1.1.10

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

**Comment by coreybutler** [comment]
We do not maintain the winget installer. I recommend reaching out to that project instead.
