### ISSUE TITLE
[Issue]: nvm list shows node version but nvm use claims its not installed

### ISSUE THREAD

**Issue by majkinetor** [coreybutler/nvm-windows#979]
### What happened?

This happened:

![image](https://github.com/coreybutler/nvm-windows/assets/85767/90947943-48bc-433f-90bc-08e98f754c8c)

I resolved it by using `nvm install 17.3` but how did it appear in the list of installed versions?

### What did you expect to happen?

Not to show versions that are not installed

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

**Comment by coreybutler** [comment]
Please provide the output of `nvm debug`. This looks like a path issue. The debug feature identifies most of these.

**Comment by majkinetor** [comment]
I am sorry, unfortunatelly I can't because now the state is lost. If I manage to replicate it again I will. I thought to create a ticket after the fact and just then saw a debug related question... 

nvm is installed via [chocolatey](https://community.chocolatey.org/packages/nvm.install)

<details><summary> Install procedure</summary>

![image](https://github.com/coreybutler/nvm-windows/assets/85767/f62c42e3-3ab6-4862-a4a1-cf316aa74726)

</details>

I run the same code on tens of machines on our CI runners and developer machines, this failed on 1 machine.

**Comment by coreybutler** [comment]
@majkinetor the chocolatey installer is maintained by a different group. I recommend reaching out to them.

I will close this for now since there isn't a way to troubleshoot. If you're able to recreate the error in the future, just open a new issue.

**Comment by majkinetor** [comment]
Its not MSI, I was hasty, its setup.exe from this repo github downloads. 

I did scan the wiki and made sure that I uninstall any existing nodejs before installing nvm. Apart from other things, with it, install is not really silent due to the popup about existing node management. So everything is by the book.

**Comment by majkinetor** [comment]
BTW @coreybutler, the other shown versions **did work**, I forgot to say that. This IMO makes it less likely its about path. Looks like there is possibility that maybe some previous installation was terminated in the middle of it, while I was testing CI.

**Comment by coreybutler** [comment]
@majkinetor - It does sound like perhaps there was an aborted/incomplete installation. I've already updated the `nvm debug` code (in master) to validate each version of node, so that will be in v1.1.12. I wouldn't want to run this check in the list command though, due to latency (this can be a problem for users who run with mapped drives), but it makes sense to verify each version during debugging.

**Comment by majkinetor** [comment]
Maybe you should add extra option to list, like `nvm list --check-node-validity`, so there is no latency involved unless you want it.
