### ISSUE TITLE
[Issue]: Cannot find node after install lts and use lts

### ISSUE THREAD

**Issue by TakanashiHitomi** [coreybutler/nvm-windows#981]
### What happened?

Cannot find `node` command.

I didn't install node before.
After I installed `nvm` and `nvm install lts`, there is still no `node` in my terminal.
I use `Terminal Application`, and run a `Powershell 7.2.0-preview.2` version
There is no error in `nvm list` and `nvm use lts`.

### What did you expect to happen?

I want use `node`

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 11+

### Which locale?

Asian

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

### Relevant log/console output

```Shell
PS C:\Users\sf235> node
node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: move, ndr, cd, md, popd, copy, del, gdr, nal, ni.
PS C:\Users\sf235> nvm list

    18.16.0
PS C:\Users\sf235> nvm use lts
Now using node v18.16.0 (64-bit)
PS C:\Users\sf235> node
node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: move, ndr, cd, md, popd, copy, del, gdr, nal, ni.
PS C:\Users\sf235> node -v
node: The term 'node' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: PowerShell
NVM4W Version:      1.1.11
NVM4W Path:         D:\Develop\nvm\nvm.exe
NVM4W Settings:     D:\Develop\nvm\settings.txt
NVM_HOME:           D:\Develop\nvm
NVM_SYMLINK:        D:\Develop\nvm
Node Installations: D:\Develop\nvm

Active Node.js Version: none
(run "nvm use <version>" to activate a version)

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by TakanashiHitomi** [comment]
The `NVM_SYMLINK` after install is `D:\Develop`. I change it to `D:\Develop\nvm` for test but nothing changes.

**Comment by coreybutler** [comment]
Typically the NVM_HOME and NVM_SYMLINK values are different. For example:

<img width="532" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/6a0414be-05bf-4590-b61b-1fcca15e2619">


What happens when you run `D:\Develop\nvm\v18.16.0\node.exe -v`?

**Comment by TakanashiHitomi** [comment]
> Typically the NVM_HOME and NVM_SYMLINK values are different. For example:
> 
> <img alt="image" width="532" src="https://user-images.githubusercontent.com/770982/239020751-6a0414be-05bf-4590-b61b-1fcca15e2619.png">
> What happens when you run `D:\Develop\nvm\v18.16.0\node.exe -v`?

Thank you for your reply. It shows node version `v18.16.0` correctly.

I change `NVM_LINK` to `D:\Develop` again and nothing changes.

BTW, I didn't see any symbol link in nvm folder or its parent folder. I mean `node.lnk`.
Maybe this is the point?
```
PS D:\Develop\nvm> ls

    Directory: D:\Develop\nvm

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----           2023/5/13    13:45                v18.16.0
-a---           2021/12/7    12:36            305 elevate.cmd
-a---           2021/12/7    12:36            335 elevate.vbs
-a---           2023/1/26    21:28            724 install.cmd
-a---           2021/12/7    12:36          15086 nodejs.ico
-a---           2023/4/12    22:30        8294304 nvm.exe
-a---           2023/5/13    12:10             40 settings.txt
-a---           2023/2/13    20:54            384 setuserenv.vbs
-a---           2023/5/13    12:10          18797 unins000.dat
-a---           2023/5/13    12:10        3048509 unins000.exe
-a---           2023/2/13    20:54            286 unsetuserenv.vbs
```

**Comment by coreybutler** [comment]
Did you mean `NVM_SYMLINK`? `NVM_LINK` is not recognized by NVM4W. There is never a `node.lnk` file. 

Again, run `D:\Develop\nvm\v18.16.0\node.exe -v`. It should output the version. If this works, then there is a different path problem.

Also, is your D drive a mapped directory on a network drive or does it reference a hard drive/partition?

**Comment by TakanashiHitomi** [comment]
> 

Q1: Yes, I mean `NVM_SYMLINK`. And `node.lnk` is just something I imagine. Sorry for the bother.

Q2: And yes, the `D:\Develop\nvm\v18.16.0\node.exe -v` print the node version correctly.

Q3: My D drive is just a HDD in my pc.

**Comment by coreybutler** [comment]
I must be tired lately, because I should have seen the problem straight away.

The `NVM_SYMLINK` cannot be an existing _real_ directory. Every time `nvm use` is run, it attempts to update the `NVM_SYMLINK`. Since this is a real directory in your environment, there is no symlink to change. As a result, Windows thinks `node.exe` exists directly under `D:\Develop\nvm` instead of `D:\Develop\nvm\v18.16.0`. Bottom line: `nvm use` isn't doing anything when `NVM_SYMLINK` already exists as a real directory.

You mentioned that `NVM_SYMLINK` was originally `D:\Develop`. Since this is a real directory too, the problem would be the same. Changing it to `D:\Develop\nvm` changed it from one real directory to another. If you want to keep everything isolated in the `D:\Develop\nvm` directory, then I'd recommend changing `NVM_SYMLINK` to `D:\Develop\nvm\installations`. The `installations` directory should **not** exist when you do this. NVM4W will create/manage the symlink here for you when you run `nvm use`, so you'll see the linked directory in Windows Explorer after you run `nvm use`.

**Comment by TakanashiHitomi** [comment]
> 

Thank you sir! It's all about that `NVM_SYMLINK` original value.
So why it was `D:\Develop` after my installation?
