### ISSUE TITLE
[Feature]: NVM version iteration

### ISSUE THREAD

**Issue by zonglin-hub** [coreybutler/nvm-windows#982]
### Description of the new feature / enhancement

Old version iteration trival, expected to increase the background command-line NVM to upgrade

### Scenario when this would be used?

NVM iteration the old version

**Comment by coreybutler** [comment]
I'm sorry, but I'm don't clearly understand what you're asking for. Are you wanting NVM4W to autoupdate Node.js when new versions are available?

**Comment by zonglin-hub** [comment]
Sorry, I didn't make it clear. nvm has a new version, no need to reinstall nvm. update nvm.

**Comment by coreybutler** [comment]
There is a manual update utility available in each release:

<img width="904" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/b0deb992-5ea8-468d-9435-b26afd1d875a">

Automatic updates are planned for [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime) (paid editions).
