### ISSUE TITLE
[Issue]: 'corepack' 不是内部或外部命令，也不是可运行的程序 或批处理文件。('corepack' is not an internal or external command, nor is it a executable program or batch file.)

### ISSUE THREAD

**Issue by sqlyr** [coreybutler/nvm-windows#986]
### What happened?

1、nvm install 14.20.0
2、nvm use 12.20.0
3、corepack enable
![image](https://github.com/coreybutler/nvm-windows/assets/64026664/8f40d310-b080-4e4d-b212-294e606aaacc)

如下图所示，node环境缺少corepack命令相关文件(As shown in the following figure, the node environment is missing files related to the corepack command)
![image](https://github.com/coreybutler/nvm-windows/assets/64026664/d93037eb-a47a-4cac-ae0d-cbeb80814391)

### What did you expect to happen?

corepack enable命令能够正常运行(The corepack enable command can run normally)

### Version

1.1.11 or newer (Default)

### Which locale?

None

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

None

**Comment by coreybutler** [comment]
I cannot read the entire issue, but I believe it is about corepack not being available. Corepack is not available in Node 14.12.0. Corepack didn't exist until Node v16.9.0.

I'm closing this, but will reopen if I'm misunderstanding/translating.

**Comment by sqlyr** [comment]
First, Sorry， my English is not very well

And this is the correct step description

What happened?
1、nvm install 14.20.0
2、nvm use 14.20.0
3、corepack enable

Corepack is available in Node 14.20.0

**Comment by coreybutler** [comment]
That's OK, I understood what you were saying.

I misread the version. You were trying to install 14.20.0, whereas I read 14.12.0. My mistake.

Corepack, which was first released in v14.19.0, is still considered experimental (as of v20.2.0). In v14.19.0+, you have to set `ENABLE_EXPERIMENTAL_COREPACK=1` for it to work.
