### ISSUE TITLE
[Feature]: Ability for limit versions of Node to be installed

### ISSUE THREAD

**Issue by tomaszwojciechowski** [coreybutler/nvm-windows#987]
### Description of the new feature / enhancement

I would like to config NVM for Windows installation to be able to install only upfront selected versions of Node.

### Scenario when this would be used?

E.g. if in dev team there is a limitation of versios of Node to be installed.

**Comment by coreybutler** [comment]
This is also a feature we are planning for a pro edition of [Runtime](https://github.com/coreybutler/nvm-windows/wiki/Runtime). However; this will be part of a commercial add-on.
