### ISSUE TITLE
NPM command completely hangs up with any parameter

### ISSUE THREAD

**Issue by ThatAnonyG** [coreybutler/nvm-windows#991]
### What happened?

Running the NPM command completely makes the shell unresponsive. Can't even quit the process.

### What did you expect to happen?

Command either runs normally or atleast throws an error giving some hint.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
Running NVM for Windows with administrator privileges.

Administrator: Windows PowerShell
NVM4W Version:      1.1.11
NVM4W Path:         C:\Users\thata\AppData\Roaming\nvm\nvm.exe
NVM4W Settings:     C:\Users\thata\AppData\Roaming\nvm\settings.txt
NVM_HOME:           C:\Users\thata\AppData\Roaming\nvm
NVM_SYMLINK:        C:\tools\nodejs
Node Installations: C:\Users\thata\AppData\Roaming\nvm

Active Node.js Version: v18.16.0

No problems detected.

Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

### Anything else?

![image](https://github.com/coreybutler/nvm-windows/assets/53178362/0b7f7fed-d9ff-422d-84bf-b338c3b3f051)

**Comment by coreybutler** [comment]
Do you have this problem with any other version of Node?

Once NVM4W has installed node and npm, it's entirely hands off. So, if npm isn't running, it means something else is the problem.

I'd suggest looking at in `C:\Users\thata\AppData\Roaming\nvm\v18.16.0` to make sure the `npm` and `npm.cmd` files exist.

I'd also recommend trying this in a plain/unenhanced terminal.

<img width="245" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/ba0c31ee-a6b5-43ba-aeee-cd14205c7f0d">

Some users have found that reinstalling a version resolves the problem. Some versions of Windows block parts of an install (a very annoying trait, though more common on Windows 11).

**Comment by RobbiePlata** [comment]
Tested this on a fresh VM, npm is not recognized. Then when uninstalling and reinstalling 18.16.0, this error message is given.
```
ERROR: npm v9.5.1 is known not to run on Node.js v18.16.0. You'll need to upgrade
to a newer Node.js version in order to use this version of npm. This version of
npm supports the following node versions: `^14.17.0 || ^16.13.0 || >=18.0.0`. You
can find the latest version at https://nodejs.org/.

ERROR:
C:\Users\User\AppData\Roaming\nvm\v18.16.0\node_modules\npm\node_modules\@npmcli\arborist:1
../../workspaces/arborist
^

SyntaxError: Unexpected token '.'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\User\AppData\Roaming\nvm\v18.16.0\node_modules\npm\lib\npm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    ```

**Comment by coreybutler** [comment]
@RobbiePlata Looks like you're using an outdated version of NVM4W. The `.0.0` issue happens because the `use` command expects a version (i.e. `nvm use 18.16.0`). Old versions didn't catch this. More recent releases do:

<img width="313" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/c0326fcf-ef55-4305-8ed2-63c8e3c5e865">

**Comment by RobbiePlata** [comment]
@coreybutler oops thanks for letting me know, everything worked properly after that point on

**Comment by andradei** [comment]
Same issue. Installed `nvm` via Scoop. No other methods of installing `node` succeeds in running `npm`. It always hangs...
