### ISSUE TITLE
[Issue]: PROBLEMS DETECTED (and not expected) with npm debug 

### ISSUE THREAD

**Issue by Issam-seghir** [coreybutler/nvm-windows#995]
### What happened?

this is the output of :  `npm debug`
```
PROBLEMS DETECTED
-----------------
Another Node.js installation is blocking NVM4W installations from running. Please uninstall the conflicting version or update the PATH environment variable to assure "E:\Apps\scoop\persist\nvm\nodejs\nodejs" precedes "E:\Apps\scoop\apps\nvm\current\nodejs\nodejs".

"pwsh in GAMING" is not an officially supported shell. Some features may not work as expected.


The NVM4W symlink (E:\Apps\scoop\persist\nvm\nodejs\nodejs) was not found in the PATH environment variable.


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

and this is the env variables path :

![image](https://github.com/coreybutler/nvm-windows/assets/74573675/58d04a98-0205-4876-b7f3-7e0812196fba)

### What did you expect to happen?

The debug message does not indicate any problem, as the environment variables are correctly set in the path.

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

Western European

### Which shell are you running NVM4W in?

PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

No (Default)

### Debug Output

```Shell
PROBLEMS DETECTED
-----------------
Another Node.js installation is blocking NVM4W installations from running. Please uninstall the conflicting version or update the PATH environment variable to assure "E:\Apps\scoop\persist\nvm\nodejs\nodejs" precedes "E:\Apps\scoop\apps\nvm\current\nodejs\nodejs".

"pwsh in GAMING" is not an officially supported shell. Some features may not work as expected.


The NVM4W symlink (E:\Apps\scoop\persist\nvm\nodejs\nodejs) was not found in the PATH environment variable.


Find help at https://github.com/coreybutler/nvm-windows/wiki/Common-Issues
```

**Comment by coreybutler** [comment]
Do you have NVM4W installed twice?

The debugger appears to be detecting node.exe more than once. See [this section](https://github.com/coreybutler/nvm-windows/wiki/Common-Issues#why-do-i-need-to-uninstall-nodejs-before-installing-nvm-for-windows) for details.

**Comment by Issam-seghir** [comment]
I have only one folder contient `nvm` in my system 
![image](https://github.com/coreybutler/nvm-windows/assets/74573675/47c5fbfd-1642-45c5-9cba-a387e10f6435)

![image](https://github.com/coreybutler/nvm-windows/assets/74573675/5ad05de3-dd5a-4c36-8b83-a6632b3c29ed)

But I had installed Node.js with Scoop before installing nvm. However, I uninstalled Node.js either before or after installing nvm with Scoop. Perhaps this is causing a conflict ?

**Comment by coreybutler** [comment]
Yes, this is causing the problem. Your system thinks you have another installation of Node.js at `E:\Apps\scoop\apps\nvm\current\nodejs\nodejs`. You need to uninstall that version _or_ move the highlighted line to a position _after_ `E:\Apps\scoop\persiste\nvm\nodejs\nodejs`.

**Comment by Issam-seghir** [comment]
Thanks, adding `E:\Apps\scoop\persist\nvm\nodejs\nodejs`  
before `E:\Apps\scoop\apps\nvm\current\nodejs\nodejs`  in the path 
fix the problem 


![SystemPropertiesProtection_Jogz0o2bed](https://github.com/coreybutler/nvm-windows/assets/74573675/236cc51d-8936-43e3-ae78-6cedd60ef8fe)
