### ISSUE TITLE
[Issue]: NVM install <version> doesn't seem to be linking npm

### ISSUE THREAD

**Issue by nomadslayer** [coreybutler/nvm-windows#998]
### What happened?

After installing the latest NVM on a clean machine, npm doesn't work

1. install windows 10
2. install latest v1.1.11
3. in console nvm install lts
4. npm is nor recognized

### What did you expect to happen?

NPM should work

### Version

1.1.11 or newer (Default)

### Which version of Windows?

Windows 10 (Default)

### Which locale?

English (Default)

### Which shell are you running NVM4W in?

Command Prompt, PowerShell

### User Permissions?

Administrative Privileges, Elevated

### Is Developer Mode enabled?

Yes

**Comment by coreybutler** [comment]
What is the output of `nvm debug`?

**Comment by HsinLiu** [comment]
I encountered a similar situation.😅

**Comment by coreybutler** [comment]
I can't troubleshoot without further information. Anyone who is encountering this should post the output of `nvm debug`. You can also look in the `NVM_SYMLINK` directory (which is displayed in the debug output) to see if npm is in the `node_modules` directory. A proper setup looks like this:

<img width="527" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/caeadc47-d27f-4d49-af4e-19e7d1a19a05">
<img width="523" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/cad883c5-9012-4502-beea-0a65b7a46cf1">

You can confirm the existence of npm by looking in the `NVM_SYMLINK` directory:

<img width="540" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/10c7f093-0145-4c02-bfe7-ab986cba971b">

Make sure the `bin` folder and the `index.js` file are available.

<img width="534" alt="image" src="https://github.com/coreybutler/nvm-windows/assets/770982/94f95f43-191b-444e-898e-3c9375ddd91a">

**Comment by khuezy** [comment]
Hi there seems to be something odd w/ Windows and nodejs for certain people. I removed all instances of prior nodejs and system environment variables but can't get nodejs to work anymore (via directly install and nvm).

![image](https://github.com/coreybutler/nvm-windows/assets/811298/3145c8ba-21b2-4c54-b494-1a8187f5f44a)

**Comment by coreybutler** [comment]
@khuezy What happens when you run `C:\Program Files\nodejs\node.exe -v`? I'm interested in knowing if you get an error or the version number?

Additionally, if you have an antivirus installed, or if your Windows installation is protecting the `C:\Program Files\nodejs` directory, it could be silently preventing the symlink update that `nvm use` performs.

**Comment by khuezy** [comment]
Sorry for late reply. It looks like it fails to create the symlink from `C:\Users\khuezy\AppData\Roaming\nvm\v18.16.1` => `C:\Program Files\nodejs`

**Comment by coreybutler** [comment]
I recommend deleting `C:\Program Files\nodejs`, then run `nvm use 18.16.1` again. This should reset the symlink.

**Comment by khuezy** [comment]
Was nvm suppose to create `C:\Program Files\nodejs`?

**Comment by nomadslayer** [comment]
I tried on another clean Windows 10 and also installing nvm again. 
In Command Prompt or Powershell, type
1. nvm install lts
2. nvm on
3. nvm use lts
4. npm --version
The nodejs in C:\Program Files\nodejs is just a shortcut to C:\Users\{user}\AppData\Roaming\nvm\{version}
npm is installed in  C:\Users\{user}\AppData\Roaming\npm

**Comment by coreybutler** [comment]
@khuezy NVM4W creates a _symlink_ at `C:\Program Files\nodejs` the first time you run `nvm use`. If there is already a physical folder in this location, it will fail.

I would suggest changing `NVM_SYMLINK` to `C:\nodejs`. `C:\Program Files` is a special/protected directory on Windows. Most users can still access it, but if you're in an organization that has locked it down, the OS may be preventing NVM4W from creating the symlink properly.

@nomadslayer run `nvm debug` and post the output here.

**Comment by khuezy** [comment]
I changed `NVM_SYMLINK` to `C:\nodejs` but it still doesn't create the symlink there. I did give all users ability to create symlinks on my personal PC but it's still not working. It must be something specific on my computer. I did have `nvm` installed in the Ubuntu WSL, could that have anything to do with it?

**Comment by coreybutler** [comment]
@khuezy At this point, I'm not sure what else could be causing the problem. You could try manually making the symlink sing `mklink`. If there is a permission problem, this would likely uncover it.

Having nvm-sh in WSL _shouldn't_ cause a conflict, but I haven't tested it to know with certainty. nvm-sh uses a shim approach, which is different and unrelated to NVM4W's symlink approach.

I wish I could offer more assistance, but I'm not sure where else to point you. `exit 1` is the generic error Windows throws... so it seems likely Windows is doing something to block the operation.

**Comment by ChrisDu17** [comment]
Hi there

From France, I have similar problem.

I just remove the environemental system PATH variable "C:\ProgramData\npm\npm".

And then I have the right npm version for my nodejs.

Hope this can help

**Comment by coreybutler** [comment]
@ChrisDu17 how did you get that path in the first place? `C:\ProgramData\npm\npm` is not a normal target directory for npm (it is typically installed within a node install directory). In your case, `C:\ProgramData\npm\npm` must have been before the node root in your `PATH`, which is why things work when removing that.

If another tool installed npm at `C:\ProgramData\npm\npm`, I'd be curious to know. I'd be able to add something to `nvm debug` to catch this/explain the fix if there is a chance other users would run into this.

**Comment by khuezy** [comment]
fwiw, I don't have that in my system or user vars and I'll having linking issues.

**Comment by matteusbarbosa** [comment]
For me, it only worked after 

 1.  reinstalling nvm through the [.exe package][1], and 
 2. reinstalling node version in a way that Windows is able to add everything properly to environment variables 
 - **nvm uninstall < *nodeversion* >** 
 - **nvm install < *nodeversion* >**
- **nvm use < *node version* >**
- **npm -v** *should display your npm version*

Remember to run everything in a prompt as administrator to avoid symlink permission issues.


  [1]: https://github.com/coreybutler/nvm-windows/releases/download/1.1.11/nvm-setup.exe

**Comment by ikluhsman** [comment]
> I recommend deleting `C:\Program Files\nodejs`, then run `nvm use 18.16.1` again. This should reset the symlink.

I originally did not run the use command as administrator, which seems to have silently failed to create the symlink. After removing the nodejs folder from Program Files, and running `nvm use 18.16.1` again, the symlink was created successfully and everything was good.

Perhaps a warning that the command must be run as administrator when running the nvm use command could be helpful.
